import {useRef} from 'react';
import type {ActiveMomentumState} from '../../../types/momentum';
import type {GameEngineAction} from '../../../engine/core/ActionTypes';
import {MATH_POWERS,POWER_ORDER,powerTargets} from '../../../engine/systems/MomentumPowers';
export function MomentumPowerCards(){return <div className="momentum-power-cards">{POWER_ORDER.map((role,i)=><article key={role}><span className="momentum-card-art" style={{backgroundPosition:`${i/3*100}% 0%`}}/><div><h3><b>{MATH_POWERS[role].symbol}</b> {MATH_POWERS[role].name}</h3><p>{MATH_POWERS[role].movement}</p><p>{MATH_POWERS[role].power}</p></div></article>)}</div>;}
export function MomentumPowerActions({state,dispatch}:{state:ActiveMomentumState;dispatch:(a:GameEngineAction)=>void}){
 const piece=state.pieces.find(p=>p.id===state.selectedPieceId);if(!piece?.mathPower)return <p className="momentum-power-tip">Choose a blue guardian. Its move and power will appear here.</p>;
 const data=MATH_POWERS[piece.mathPower],targets=powerTargets(state,piece),active=state.activeTeam==='player'&&['player_select','player_move'].includes(state.phase);
 return <div className="momentum-power-actions"><h3>{data.symbol} {data.name} <span>{piece.energy}/6 energy</span></h3><p>{data.movement}</p><p>{data.power}</p>{active&&targets.map(t=><button key={t.id} onClick={()=>dispatch({type:'MOMENTUM_TACTIC',pieceId:piece.id,targetId:t.id})}>{piece.mathPower==='add'?'Charge +2':piece.mathPower==='subtract'?'Drain −2':`Split ${piece.energy} ÷ 2`} → {t.mathPower?MATH_POWERS[t.mathPower].name:t.id} · row {t.position.y+1}, col {t.position.x+1}</button>)}{piece.mathPower!=='multiply'&&!targets.length&&<small>No eligible target in range right now.</small>}<p className="momentum-power-tip">{data.tip}</p></div>;
}
export function MomentumPowerVideo({onOpenChange}:{onOpenChange?:(open:boolean)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),video=useRef<HTMLVideoElement>(null);
 return <><button className="momentum-watch" onClick={()=>{dialog.current?.showModal();onOpenChange?.(true);}}>▶ Watch piece powers</button><dialog className="momentum-video" ref={dialog} aria-label="Momentum piece powers video" onClose={()=>{video.current?.pause();onOpenChange?.(false);}}><header><div><span>POWER CLASH FIELD GUIDE</span><h2>Meet your four guardians</h2></div><button aria-label="Close powers guide" onClick={()=>dialog.current?.close()}>×</button></header><video ref={video} controls playsInline preload="metadata" poster="/assets/momentum-v2/powers-poster.jpg" src="/assets/momentum-v2/powers-guide.mp4"><track kind="captions" src="/assets/momentum-v2/powers-guide.vtt" srcLang="en" label="English captions" default/></video><p>Math is the power system. There are no sums to type. Capture all four enemies before turn 60. Each move or power uses your turn; every piece recharges +1, up to 6, at the start of its team’s turn.</p><MomentumPowerCards/><a href="/assets/momentum-v2/powers-guide.mp4" download>Download the guide video</a></dialog></>;
}
