import {describe,it,expect} from 'vitest';
import {TRAILS,startPop,goal,evaluate,popChain,findChain,ensureChain,validPath,mixPop} from './game';
import {popCommand,parsePop,validPop} from './model';
import {createInitialEngineState} from '../../engine/state/createInitialEngineState';
describe('Math Pop',()=>{
 it('generates a real, playable chain for every grade, level type and seed',()=>{for(const t of TRAILS)for(let level=1;level<=6;level++)for(let seed=1;seed<=8;seed++){const r=startPop('t',t.id,level,seed);const path=findChain(r);expect(path.length,`${t.id}:${level}:${seed}`).toBeGreaterThan(1);expect(evaluate(r,path).correct).toBe(true);expect(popChain(r,path).solved).toBe(true);}});
 it('first level teaches both a pair and a longer chain; wrong math loses no move',()=>{const r=startPop('t','add',1,1);expect(evaluate(r,[0,1]).correct).toBe(true);expect(evaluate(r,[6,7,8]).correct).toBe(true);const wrong=popChain(r,[1,2]);expect(wrong.solved).toBe(false);expect(wrong.run.moves).toBe(r.moves);expect(wrong.run.board).toEqual(r.board);expect(wrong.run.chains).toBe(0);});
 it('rejects jumps, wraps, repeats, stars and overlong paths',()=>{const r=startPop('t','add',3,1);for(const p of [[0,2],[5,6],[0,1,0],[14,15],[0,1,2,8,9,10,11,17,16]])expect(validPath(r,p)).toBe(false);expect(()=>popChain(r,[0,2])).toThrow();});
 it('uses exact fractions and ordered subtraction and division',()=>{for(const id of ['fraction','decimal','subtract','divide'] as const){const r=startPop('t',id,1,1);expect(evaluate(r,goal(r).solution.map((_,i)=>i)).correct).toBe(true);}const d=startPop('t','divide',1,1);expect(evaluate(d,[2,1,0]).correct).toBe(false);});
 it('checks algebra, ratios and slope instead of accepting a matching numeric total',()=>{for(const id of ['factor','terms','ratio','slope','equation','functions','powers'] as const){const r=startPop('t',id,1,1);const p=goal(r).solution.map((_,i)=>i);expect(evaluate(r,p).correct).toBe(true);r.board[p[0]].n=99;expect(evaluate(r,p).correct).toBe(false);}});
 it('creates specials, triggers row blasts, cracks ice, and keeps unique tile ids after gravity',()=>{const r=startPop('t','add',2,1);r.board[0].n=6;r.board[1].n=6;r.board[0].power='rocket';const before=r.board[12].id,result=popChain(r,[0,1]).run;expect(result.burst).toEqual(expect.arrayContaining([0,1,2,3,4,5]));expect(result.ice).toBe(2);expect(new Set(result.board.map(t=>t.id)).size).toBe(36);expect(result.board[12].id).toBe(before);const long=startPop('t','add',1,1),after=popChain(long,[6,7,8]).run;expect(after.board.some(t=>t.power==='rocket')).toBe(true);});
 it('a star falls into cleared space and is collected at the bottom',()=>{const r=startPop('t','add',3,1);r.board[15].star=false;r.board[27].star=true;r.board[33].n=6;r.board[34].n=8;const after=popChain(r,[33,34]).run;expect(after.stars).toBe(1);expect(after.status).toBe('won');expect(after.board.some(t=>t.star)).toBe(false);});
 it('repairs a dead board without moving obstacles or losing stars',()=>{const r=startPop('t','add',3,1);r.board.forEach(t=>{t.n=9;});expect(findChain(r)).toEqual([]);const star=r.board[15].id;expect(ensureChain(r)).toBe(true);expect(findChain(r).length).toBeGreaterThan(1);expect(r.board[15].id).toBe(star);expect(r.board[15].star).toBe(true);});
 it('rewards correct chains once, preserves assignment and records hint support',()=>{let s=createInitialEngineState();const learning=structuredClone(s.learning);s=popCommand(s,{kind:'start',trail:'add',level:1});const mp=s.player.currencies.mp;s=popCommand(s,{kind:'hint',revision:0});expect(s.learningEvidence?.at(-1)?.answerRevealed).toBe(true);const c={kind:'chain' as const,revision:1,path:[0,1]};s=popCommand(s,c);expect(s.player.currencies.mp).toBe(mp+2);expect(s.learning).toEqual(learning);expect(()=>popCommand(s,c)).toThrow();expect(validPop(s.mathPop)).toBe(true);expect(()=>popCommand(s,{kind:'start',trail:'add',level:8})).toThrow();});
 it('keeps scoring after the daily reward cap and unlocks a won level',()=>{let s=popCommand(createInitialEngineState(),{kind:'start',trail:'add',level:1});s.mathPop!.rewardDay=new Date().toISOString().slice(0,10);s.mathPop!.rewardCount=20;const mp=s.player.currencies.mp;for(let i=0;i<3;i++){const r=s.mathPop!.run!;s=popCommand(s,{kind:'chain',revision:r.revision,path:findChain(r)});}expect(s.player.currencies.mp).toBe(mp);expect(s.mathPop!.run!.status).toBe('won');expect(s.mathPop!.unlocked.add).toBe(2);expect(validPop(s.mathPop)).toBe(true);});
 it('validates corrupt input and saved boards',()=>{for(const c of [null,{kind:'start',trail:'fake',level:1},{kind:'chain',revision:0,path:[0,100]},{kind:'hint',revision:-1}])expect(()=>parsePop(c)).toThrow();expect(validPop(undefined)).toBe(true);expect(validPop({version:1} as never)).toBe(false);});
});

it('introductory ice and star levels have a clear winning route in every trail',()=>{for(const t of TRAILS)for(const level of [2,3]){let r=startPop('intro',t.id,level,7);for(let turn=0;turn<3;turn++){const base=level===2?turn*6:33;const path=goal(r).solution.map((_,i)=>base+i);r=popChain(r,path).run;}expect(r.status,t.id+':'+level).toBe('won');}});
it('mixing keeps progress and obstacles, remains valid and costs no move',()=>{let s=popCommand(createInitialEngineState(),{kind:'start',trail:'add',level:1});for(let i=0;i<10;i++){const r=s.mathPop!.run!;s=popCommand(s,{kind:'mix',revision:r.revision});expect(s.mathPop!.run!.moves).toBe(6);expect(validPop(s.mathPop)).toBe(true);}const r=startPop('mix','add',3,1),mixed=mixPop(r);expect(mixed.board.map(t=>t.star)).toEqual(r.board.map(t=>t.star));});
