import {useLayoutEffect,useRef,useState,type CSSProperties} from 'react';
import type {EngineState} from '../../types/engine';
import type {GameEngineAction} from '../../engine/core/ActionTypes';
import {PetSprite} from '../../components/pet/PetSprite';
import {TRAILS,trail,goal,tileLabel,evaluate,adjacent,objective,needed,type Trail,type PopRun} from './game';
import type {PopCommand} from './model';
import './math-pop.css';
type Props={state:EngineState;dispatch:(a:GameEngineAction)=>void;execute?:(c:PopCommand)=>Promise<void>};
export default function MathPop({state,dispatch,execute}:Props){
 const r=state.mathPop?.run,pet=state.pet;
 const [skill,setSkill]=useState<Trail>(()=>r?.trail??TRAILS.find(t=>t.grade===Math.min(9,state.learning.grade))?.id??'add'),[menu,setMenu]=useState(!r),[busy,setBusy]=useState(false),[error,setError]=useState(''),[help,setHelp]=useState(false);
 const lock=useRef(false);
 async function send(c:PopCommand){if(lock.current)return false;lock.current=true;setBusy(true);setError('');try{if(execute)await execute(c);else dispatch({type:'MATH_POP_COMMAND',command:c});return true;}catch(e){setError(e instanceof Error?e.message:'Could not save your move.');return false;}finally{lock.current=false;setBusy(false);}}
 async function start(level:number){if(await send({kind:'start',trail:skill,level}))setMenu(false);}
 const max=state.mathPop?.unlocked[skill]??1;
 return <main className="math-pop" data-testid="math-pop"><header className="pop-header"><button onClick={()=>dispatch({type:'SET_SCREEN',screen:'play'})}>← Games</button><div><small>A LITTLE THINKING. A BIG POP.</small><h1>Math Pop<span>✦</span></h1></div><button onClick={()=>{setMenu(!menu);setSkill(r?.trail??skill);}}>Levels & math</button></header>
 {error&&<p className="pop-error" role="alert">{error}</p>}
 {menu||!r?<section className="pop-lobby"><div className="pop-hero"><div className="pop-demo-tiles" aria-hidden="true"><i>6</i><b>+</b><i>4</i><b>=</b><strong>10 ✦</strong></div><h2>Connect it. Pop it. Play again.</h2><p>Drag through neighboring tiles to make the target.<br/>Longer chains make rockets and bombs!</p></div><div className="pop-shortcuts"><button onClick={()=>setSkill('count')} aria-pressed={skill==='count'}>Kindergarten · count dots</button><button onClick={()=>setSkill('add')} aria-pressed={skill==='add'}>Grade 1 · make ten</button></div><label>Choose your math<select value={skill} onChange={e=>setSkill(e.target.value as Trail)}>{TRAILS.map(t=><option key={t.id} value={t.id}>{t.grade===0?'K':`Grade ${t.grade}`} · {t.name} · {t.skill}</option>)}</select></label><p className="pop-small">Choose any grade to practice. Your teacher’s assignment stays the same.</p><div className="pop-levels" aria-label="Puzzle levels">{Array.from({length:Math.min(99,Math.max(9,max+2))},(_,i)=>i+1).map(level=><button key={level} disabled={busy||level>max} onClick={()=>void start(level)}><b>{level>max?'🔒':level<max?'★':level}</b><span>{level%3===1?'Pop chains':level%3===2?'Crack ice':'Drop a star'}</span></button>)}</div><button className="pop-primary" disabled={busy} onClick={()=>void start(max)}>{max===1?'Play first puzzle →':`Play level ${max} →`}</button>{r&&<button onClick={()=>setMenu(false)}>Continue saved puzzle</button>}<p className="pop-small">No timer · Mouse, touch, or keyboard · Your pet comes with you</p></section>:<>
 <div className="pop-run-top"><div><small>{trail(r.trail).grade===0?'KINDERGARTEN':`GRADE ${trail(r.trail).grade}`} · LEVEL {r.level}</small><strong>{trail(r.trail).name}</strong></div><span><b>{r.score}</b> points</span><span><b>{r.moves}</b> moves</span></div>
 {r.status==='playing'?<PopBoard key={r.id} run={r} busy={busy} send={send}/>:<section className="pop-finish"><div className="pop-finish-stars">{r.status==='won'?'★ ★ ★':'↻'}</div><h2>{r.status==='won'?'Beautiful connections!':'One more try?'}</h2><p>{r.status==='won'?`Level ${r.level} cleared · ${r.score} points`:'Try a longer chain to create a rocket. Earned rewards are already saved.'}</p><p>{state.mathPop?.notice}</p><button className="pop-primary" disabled={busy} onClick={()=>void send({kind:'start',trail:r.trail,level:r.status==='won'?Math.min(99,r.level+1):r.level})}>{r.status==='won'?'Next puzzle →':'Try this level again'}</button><button onClick={()=>setMenu(true)}>Choose another trail</button></section>}
 <div className="pop-companion">{pet&&<PetSprite speciesId={pet.speciesId} stage={pet.stage} animationName={r.chains?'happy':'idle'} scale={.55} equippedCosmetics={state.cosmetics.equipped[pet.id]}/>}<div><small>{pet?.name??'YOUR PUZZLE BUDDY'}</small><p role="status">{busy?'Saving your pop…':r.message}</p><small>{state.mathPop?.notice}</small></div></div>
 <div className="pop-tools"><button disabled={busy||r.status!=='playing'} onClick={()=>void send({kind:'hint',revision:r.revision})}>Show a connection</button><button disabled={busy||r.status!=='playing'} onClick={()=>void send({kind:'mix',revision:r.revision})}>Mix numbers</button><button onClick={()=>setHelp(true)}>How to play</button><button disabled={busy} onClick={()=>void send({kind:'start',trail:r.trail,level:r.level})}>Restart level</button></div>
 </>}
 {help&&<Help close={()=>setHelp(false)}/>}
 </main>;
}
function PopBoard({run:r,busy,send}:{run:PopRun;busy:boolean;send:(c:PopCommand)=>Promise<boolean>}){
 const section=useRef<HTMLElement>(null);
 useLayoutEffect(()=>{section.current?.scrollIntoView({block:'start'});},[r.id]);
 const [path,setPath]=useState<number[]>([]),[announcement,setAnnouncement]=useState('');const current=useRef<number[]>([]),drag=useRef(false),moved=useRef(false),board=useRef<HTMLDivElement>(null),oldPositions=useRef(new Map<string,DOMRect>()),submitting=useRef(false);
 const calculation=path.length?evaluate(r,path):null,g=goal(r),type=objective(r),progress=type==='chains'?r.chains:type==='ice'?r.ice:r.stars;
 const update=(p:number[])=>{current.current=p;setPath(p);};
 const choose=(i:number,restart=false)=>{if(busy||r.board[i]?.star)return;const p=current.current;if(p.at(-1)===i)return;if(p.length>1&&p.at(-2)===i){update(p.slice(0,-1));return;}if(!p.length){update([i]);return;}if(p.length<8&&!p.includes(i)&&adjacent(p.at(-1)!,i))update([...p,i]);else if(restart)update([i]);};
 async function submit(){const chain=[...current.current];if(chain.length<2||busy||submitting.current)return;submitting.current=true;try{if(await send({kind:'chain',revision:r.revision,path:chain})){update([]);setAnnouncement(evaluate(r,chain).correct?'Pop!':'Try another connection.');}}finally{submitting.current=false;}}
 useLayoutEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,newPositions=new Map<string,DOMRect>();board.current?.querySelectorAll<HTMLElement>('[data-tile-id]').forEach(el=>{const id=el.dataset.tileId!,rect=el.getBoundingClientRect(),before=oldPositions.current.get(id);newPositions.set(id,rect);if(!reduced&&oldPositions.current.size){const dy=before?before.top-rect.top:-50;if(dy)el.animate([{transform:`translateY(${dy}px)`,opacity:before?1:0},{transform:'translateY(0)',opacity:1}],{duration:260,easing:'cubic-bezier(.2,.7,.3,1)'});}});oldPositions.current=newPositions;},[r.revision]);
 const indexAt=(x:number,y:number)=>{const cell=document.elementFromPoint(x,y)?.closest<HTMLElement>('[data-pop-index]');return cell&&board.current?.contains(cell)?Number(cell.dataset.popIndex):null;};
 return <section className="pop-puzzle" ref={section}><div className="pop-goal"><div><small>YOUR TARGET</small><h2>{g.title}</h2></div><div className="pop-objective"><b>{type==='chains'?'✦':type==='ice'?'❄':'★'} {progress}/{needed(r)}</b><span>{type==='chains'?'chains to pop':type==='ice'?'ice tiles cracked':'stars brought down'}</span></div></div>
 <p className="pop-instruction">{type==='stars'?'Clear tiles below ★ to bring it to the bottom.':type==='ice'?'Connect through frosty tiles to crack the ice.':r.trail==='add'&&r.level===1&&r.revision===0?'Connect numbers that make 10. Try 6 + 4!':g.rule}</p>
 <div className="pop-play-area"><aside className="pop-side"><div><b>3+ tiles</b><span>→ Rocket</span><p>Use it in a chain to clear its row. Also earned every 3 correct chains.</p></div><div><b>5+ tiles</b><span>✹ Bomb</span><p>Use it to burst a 3 × 3 area.</p></div><details><summary>Math rule</summary><p>{g.rule}</p></details></aside>
 <div className="pop-board" ref={board} role="group" aria-label="Math Pop puzzle board" aria-busy={busy}
 onPointerDown={e=>{if(busy||e.button!==0)return;const i=indexAt(e.clientX,e.clientY);if(i===null)return;drag.current=true;moved.current=false;e.currentTarget.setPointerCapture(e.pointerId);choose(i,true);}}
 onPointerMove={e=>{if(!drag.current||busy)return;const i=indexAt(e.clientX,e.clientY);if(i!==null&&i!==current.current.at(-1)){moved.current=true;choose(i);}}}
 onPointerUp={e=>{if(!drag.current)return;drag.current=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(moved.current)void submit();}}
 onPointerCancel={()=>{drag.current=false;update([]);}}
 onKeyDown={e=>{const i=Number((e.target as HTMLElement).dataset.popIndex);if(!Number.isInteger(i))return;const delta:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6};if(e.key in delta){e.preventDefault();const n=i+delta[e.key];if(n>=0&&n<36&&adjacent(i,n))board.current?.querySelector<HTMLElement>(`[data-pop-index="${n}"]`)?.focus();}if(e.key==='Escape')update([]);}}>
 <svg className="pop-connection" viewBox="0 0 600 600" aria-hidden="true"><polyline points={path.map(i=>`${(i%6)*100+50},${Math.floor(i/6)*100+50}`).join(' ')} fill="none" stroke="#fff6be" strokeWidth="14" strokeLinecap="round" strokeLinejoin="round"/></svg>
 {r.board.map((tile,i)=>{const selected=path.includes(i),hint=r.hint.includes(i);return <button key={tile.id} type="button" data-pop-index={i} data-tile-id={tile.id} disabled={busy||tile.star} aria-label={`Row ${Math.floor(i/6)+1}, column ${i%6+1}: ${tile.star?'star':tileLabel(r,tile.n)}${tile.ice?', ice':''}${tile.power?`, ${tile.power}`:''}`} aria-pressed={selected} onClick={e=>{if(e.detail===0)choose(i,true);}} className={`pop-tile ${selected?'selected':''} ${hint?'hint':''} ${tile.ice?'iced':''} ${tile.star?'star':''} ${tile.power??''} ${r.trail==='ratio'?(tile.n===1?'red':'blue'):''}`} style={{'--hue':(Math.abs(tile.n)*37+165)%360} as CSSProperties}>
 {tile.star?<span>★</span>:r.trail==='count'?<span className="pop-dots" aria-label={String(tile.n)}>{Array.from({length:tile.n},(_,d)=><i key={d}/>)}</span>:<span>{tileLabel(r,tile.n)}</span>}
 {tile.power&&<em>{tile.power==='rocket'?'➜':'✹'}</em>}{tile.ice&&<i className="pop-ice-mark">❄</i>}{(selected||hint)&&<small>{(selected?path:r.hint).indexOf(i)+1}</small>}
 </button>;})}
 {r.burst.length>0&&<div className="pop-burst" key={r.revision} aria-hidden="true">{r.burst.map(i=><span key={i} style={{left:`${i%6/6*100}%`,top:`${Math.floor(i/6)/6*100}%`}}>✦</span>)}</div>}
 </div><aside className="pop-side pop-tip"><b>Make your move</b><p>Drag across touching tiles. Release to pop.</p><p>You can also tap tiles, then press Pop chain.</p><p>Wrong total? Nothing disappears and no move is lost.</p></aside></div>
 <div className={`pop-calculation ${calculation?.correct?'ready':''}`} aria-live="polite"><strong>{calculation?.expression??'Your connection appears here'}</strong><span>{calculation?.correct?'✓ Ready to pop!':path.length===8?'Eight tiles selected. Adjust your chain.':path.length?'Keep connecting, or step back one tile.':'Connect up, down, left, or right.'}</span></div>
 <div className="pop-actions"><button disabled={!path.length||busy} onClick={()=>update([])}>Clear selection</button><button className="pop-primary" disabled={path.length<2||busy} onClick={()=>void submit()}>Pop chain ✦</button></div><span className="pop-sr" role="status">{announcement}</span>
 </section>;
}
function Help({close}:{close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useLayoutEffect(()=>{ref.current?.showModal();},[]);return <dialog className="pop-help-dialog" ref={ref} aria-label="How to play Math Pop" onCancel={e=>{e.preventDefault();close();}}><button autoFocus onClick={close}>Close</button><h2>One connection. A big pop.</h2><div className="pop-demo-tiles"><i>6</i><b>+</b><i>4</i><b>=</b><strong>10 ✦</strong></div><ol><li>Look at the target above the board.</li><li>Drag through neighboring tiles. The equation updates as you go.</li><li>Release to pop! Or tap tiles and press Pop chain.</li></ol><p>Three or more tiles create a rocket. You also earn one every three correct chains. Five or more create a bomb. Include that special tile in a later correct chain to activate it.</p><p>Frozen tiles crack when cleared. Stars fall as tiles below them disappear. Bring a star all the way to the bottom.</p><p>No timer. Wrong totals never cost a move. Arrow keys move focus; Enter or Space select tiles. Escape clears your selection.</p></dialog>;}
