import {describe,it,expect} from 'vitest';
import {actDuel,createDuel,duelView,fairPair,fighter,MOVES,beats,type Duel,type Fighter,type Move} from './model';
import {createInitialEngineState} from '../../engine/state/createInitialEngineState';
import {hatchEgg} from '../../services/game/evolutionEngine';
function pet(id:string,level=1):Fighter{const s=createInitialEngineState();s.pet=hatchEgg({id:'egg',type:'ember',state:'ready',progress:100,createdAt:new Date().toISOString()});s.pet!.progression.level=level;return fighter(id,id,s)!;}
function start(a=pet('a'),b=pet('b')){let r=createDuel(a,b);r=actDuel(r,{action:'ready',round:0,phase:'lobby'},'a');return actDuel(r,{action:'ready',round:0,phase:'lobby'},'b',false,()=>.4);}
function answer(r:Duel,id:string,move:Move){return actDuel(r,{action:'answer',questionId:r.questions[id].id,answer:String(r.questions[id].answer),move},id);}
describe('earned-strength classroom duels',()=>{
 it('uses capped earned progression and ignores currencies and purchased combat boosts',()=>{const s=createInitialEngineState();s.pet=hatchEgg({id:'egg',type:'ember',state:'ready',progress:100,createdAt:new Date().toISOString()});const first=fighter('a','a',s)!;s.player.currencies.tokens=999999;expect(fighter('a','a',s)).toEqual(first);s.pet!.progression.level=999;s.pet!.bond=99999;s.pet!.discipline=99999;s.player.lifetimeMathCorrect=99999;s.pet!.stage='adult';expect(fighter('a','a',s)!.bonuses).toEqual({levels:57,evolution:24,math:15,bond:8,training:8});expect(fighter('a','a',s)!.power).toBe(212);});
 it('blocks unhatched pets, sickness, self-pairing and large strength gaps',()=>{const s=createInitialEngineState();expect(fighter('a','a',s)).toBeNull();expect(fairPair(pet('a'),pet('a'))).toBe(false);expect(fairPair(pet('a'),pet('b',5))).toBe(false);expect(()=>createDuel(pet('a'),{...pet('b'),power:121})).toThrow();expect(fairPair(pet('a'),pet('b',4))).toBe(true);});
 it.each(MOVES)('%s has one counter and one victim at equal strength',move=>{let r=start();r=answer(r,'a',move);r=answer(r,'b',beats[move]);expect(r.health[0]).toBeGreaterThan(r.health[1]);let inverse=start();inverse=answer(inverse,'b',move);inverse=answer(inverse,'a',beats[move]);expect(inverse.health).toEqual([...r.health].reverse());});
 it('earned strength matters on equal moves, but correct counters beat stronger pets',()=>{let r=start(pet('a'),pet('b',4));r=answer(r,'a','strike');r=answer(r,'b','strike');expect(r.health[1]/r.fighters[1].maxHealth).toBeGreaterThan(r.health[0]/r.fighters[0].maxHealth);r=start(pet('a'),pet('b',4));r=answer(r,'a','guard');r=answer(r,'b','strike');expect(r.health[0]/r.fighters[0].maxHealth).toBeGreaterThan(r.health[1]/r.fighters[1].maxHealth);});
 it('keeps the other question, answer, hint and locked move private',()=>{let r=start();r=answer(r,'a','feint');const v=duelView(r,'b');expect(v.question).not.toHaveProperty('answer');expect(v).not.toHaveProperty('questions');expect(v.results).toEqual([]);expect(v.question!.move).toBeNull();expect(v.fighters[0]).not.toHaveProperty('learning');expect(duelView(r,'teacher').question).toBeNull();});
 it('wrong retries cost no strength and repeated correct submission cannot switch moves',()=>{let r=start();const original=r;const cmd={action:'answer',questionId:r.questions.a.id,answer:'99999',move:'strike' as const};r=actDuel(r,cmd,'a');expect(r.health).toEqual(original.health);expect(r.questions.a.attempts).toBe(1);r=answer(r,'a','guard');expect(answer(r,'a','feint')).toEqual(r);r=answer(r,'b','strike');expect(answer(r,'a','feint')).toEqual(r);});
 it('requires mutual consent, preserves pause, rejects stale ready and outsider actions',()=>{let r=createDuel(pet('a'),pet('b'));r=actDuel(r,{action:'ready',round:0,phase:'lobby'},'a');expect(r.phase).toBe('lobby');expect(()=>actDuel(r,{action:'ready',round:0,phase:'lobby'},'outsider')).toThrow();expect(()=>actDuel(r,{action:'pause',paused:true},'a')).toThrow();r=actDuel(r,{action:'pause',paused:true},'teacher',true);expect(()=>actDuel(r,{action:'ready',round:0,phase:'lobby'},'b')).toThrow();r=actDuel(r,{action:'pause',paused:false},'teacher',true);r=actDuel(r,{action:'ready',round:0,phase:'lobby'},'b');expect(()=>actDuel(r,{action:'ready',round:0,phase:'lobby'},'b')).toThrow();});
 it('finishes a symmetric five-round match as a draw and ends abandoned matches without a winner',()=>{let r=start();for(let i=1;i<=5;i++){r=answer(r,'a','strike');r=answer(r,'b','strike');if(i<5){r=actDuel(r,{action:'ready',round:i,phase:'result'},'a');r=actDuel(r,{action:'ready',round:i,phase:'result'},'b');}}expect(r.phase).toBe('finished');expect(r.winner).toBeNull();expect(r.results).toHaveLength(5);const abandoned=actDuel(start(),{action:'end'},'a');expect(abandoned.winner).toBeNull();expect(abandoned.cancelled).toContain('left');});
 it('answer order gives identical combat results for every move pairing',()=>{for(const a of MOVES)for(const b of MOVES){const r=start();expect(answer(answer(r,'a',a),'b',b).health).toEqual(answer(answer(r,'b',b),'a',a).health);}});
});
describe('duel reactions',()=>{
 it('players send preset emotes with a cooldown; the teacher and outsiders cannot',()=>{
  let d=createDuel(pet('a'),pet('b'));
  d=actDuel(d,{action:'emote',emote:'cheer'},'a',false,Math.random,5000);expect(duelView(d,'b').emotes).toEqual({a:{emote:'cheer',at:5000}});
  expect(()=>actDuel(d,{action:'emote',emote:'wave'},'a',false,Math.random,6000)).toThrow(/Wait a moment/);
  expect(()=>actDuel(d,{action:'emote',emote:'wave'},'t',true,Math.random,9000)).toThrow(/Only players/);
  expect(()=>actDuel(d,{action:'emote',emote:'hello'},'b',false,Math.random,9000)).toThrow(/Choose a reaction/);
 });
});
