import {useCallback,useEffect,useRef,useState} from 'react';
import {startPolling} from '../../pilot/polling';
import {pilotAPI} from '../../pilot/api';
import {PetSprite} from '../../components/pet/PetSprite';
import {MOVES,beats,fairPair,type DuelData,type DuelView,type Move} from './model';
import {EmoteBar,EmoteBubble} from '../pet-identity/Emotes';
import './pet-duel.css';
const titles={strike:'Strike',guard:'Guard',feint:'Feint'};
export function PetDuels({teacher=false}:{teacher?:boolean}){
 const [data,setData]=useState<DuelData>({rooms:[]}),[error,setError]=useState(''),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[second,setSecond]=useState('');
 const lock=useRef(false),sequence=useRef(0),accepted=useRef(0);
 const refresh=useCallback(async()=>{const n=++sequence.current;const next=await pilotAPI<DuelData>('pet-duels');if(n>=accepted.current){accepted.current=n;setData(next);setConnected(true);}return next;},[]);
 useEffect(()=>{let live=true;const stop=startPolling(async()=>{try{await refresh();}catch{if(live)setConnected(false);}},2500);return()=>{live=false;stop();};},[refresh]);
 const run=async(path:string,body:unknown)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await pilotAPI(`pet-duels/${path}`,'POST',body);await refresh();}catch(e){setError((e as Error).message);try{await refresh();}catch{setConnected(false);}}finally{setBusy(false);lock.current=false;}};
 const chosen=data.learners?.find(s=>s.id===data.you),available=data.learners?.filter(s=>s.fighter&&!s.busy&&s.entries>0)??[],opponents=available.filter(s=>s.id!==data.you&&chosen?.fighter&&s.fighter&&fairPair(chosen.fighter,s.fighter));
 return <section className="pet-duels" aria-label="One-on-one pet duels"><header><div><p className="duel-eyebrow">Classroom arena · real classmates</p><h2>One-on-one pet duels</h2></div><span role="status">{connected?'Connected':'Reconnecting…'}</span></header>
 <p>Train your pet. Pick your move. Outthink your rival.</p>
 <details><summary>How battles stay fair</summary><p>Levels, evolution, math practice, bond and training add capped power. Pets must be within 3 levels, one evolution stage and 20% power. You choose an available classmate, and they accept or decline. Every three correct practice answers open one duel. Accepting uses it for both players; declining is free.</p><p>Five untimed rounds. Solve your assigned math to lock a move. Both moves reveal together: Strike beats Feint, Feint beats Guard, Guard beats Strike. Matching moves trade smaller hits. Hints and retries never reduce power.</p><p>Remaining health percentage decides the winner after five rounds; equal percentages are a draw. Leaving ends the match without a winner. No tokens, items, pet health or progress are lost. Duels award no currency or mastery credit; train in Math Lab and pet activities to improve your next match. Purchased combat boosts do not stack into duels.</p></details>
 {error&&<p role="alert">{error}</p>}
 {teacher?<><p>Students open <strong>Together → One-on-one pet duels</strong> and choose their own opponent. You can pause or end any match below.</p><details><summary>Pet readiness</summary>{data.learners?.map(s=><p key={s.id}>{s.alias}: {s.busy?'in a duel or invitation':!s.fighter?'needs a healthy, hatched pet':s.entries<1?'needs 3 correct practice answers':`ready · power ${s.fighter.power} · ${s.entries} entries`}</p>)}</details>{!data.rooms.length&&<p>No active duels. Several pairs can play at once.</p>}</>:<div className="duel-pairing"><h3>Challenge a classmate</h3><p><strong>{(data.entries??0)>0?'You’re ready to duel.':'Solve 3 practice questions to open your next duel.'}</strong></p>{!chosen?.fighter?<p>Hatch your pet and keep it healthy to unlock duels.</p>:chosen.busy?<p>Finish or cancel your current invitation or duel before choosing another opponent.</p>:chosen.entries<1?<p>Solve 3 practice questions to open your next duel, then come back here.</p>:<><label>Choose your opponent<select value={second} onChange={e=>setSecond(e.target.value)}><option value="">Choose a close match</option>{opponents.map(s=><option key={s.id} value={s.id}>{s.alias} · Lv {s.fighter!.level} · Power {s.fighter!.power}</option>)}</select></label><button className="duel-primary" disabled={busy||!connected||!opponents.some(s=>s.id===second)} onClick={()=>void run('create',{second})}>Send duel invitation</button>{!opponents.length&&<p>No close match is available yet. Your classmates need a hatched pet, a few solved questions, and no other duel in progress.</p>}</>}</div>}

 {data.rooms.map(room=><DuelCard key={room.id} room={room} teacher={teacher} busy={busy||!connected} act={body=>run('act',{id:room.id,...body})}/>)}
 </section>;
}
function DuelCard({room,teacher,busy,act}:{room:DuelView;teacher:boolean;busy:boolean;act:(body:Record<string,unknown>)=>Promise<void>}){
 const [draft,setDraft]=useState({id:'',answer:''}),[move,setMove]=useState<Move>('strike');const q=room.question,answer=draft.id===q?.id?draft.answer:'';
 const latest=room.results.at(-1),winner=room.fighters.find(f=>f.id===room.winner),ready=room.ready.includes(room.you),finished=room.phase==='finished';
 return <article className="duel-match" aria-label={`${room.fighters[0].alias} versus ${room.fighters[1].alias}`}><h3>{room.fighters.map(f=>f.alias).join(' vs ')}</h3><p>{room.phase==='lobby'?'Invitation · both players must be ready':`Round ${room.round} of 5`}{room.paused?' · Paused by teacher':''}</p>
 <div className="duel-fighters">{room.fighters.map((f,i)=><section key={f.id}><div className="duel-portrait">{room.emotes[f.id]&&<EmoteBubble key={room.emotes[f.id].at} {...room.emotes[f.id]}/>}<PetSprite speciesId={f.species} animationName="idle" scale={.65}/></div><strong className="duel-pet-name">{f.pet?.name??f.alias}{f.pet?.title?<small> {f.pet.title}</small>:null}</strong><span>{f.alias}{f.id===room.you?' · You':''}</span><p>Level {f.level} · Power {f.power}</p><label>Battle health {room.health[i]}/{f.maxHealth}<progress value={room.health[i]} max={f.maxHealth}/></label><details><summary>Earned strength</summary><p>Base 100 · levels +{f.bonuses.levels} · evolution +{f.bonuses.evolution} · math +{f.bonuses.math} · bond +{f.bonuses.bond} · training +{f.bonuses.training}</p></details></section>)}</div>
 {room.paused&&<p role="status">Take a break. Your answers and moves are saved.</p>}
 {finished?<h4 role="status">{room.cancelled??(winner?`${winner.alias} wins!`:'A draw — evenly matched!')}</h4>:!teacher&&(room.phase==='lobby'||room.phase==='result')&&<button className="duel-primary" disabled={busy||room.paused||ready} onClick={()=>void act({action:'ready',round:room.round,phase:room.phase})}>{ready?'Ready — waiting for your opponent':room.phase==='lobby'?'Accept duel':'Ready for next round'}</button>}
 {!teacher&&room.phase==='question'&&q&&<section className="duel-question" aria-label="Your duel question"><h4>{q.text}</h4><details><summary>Show a hint</summary><p>{q.hint}</p></details>{q.move?<p role="status">Your {titles[q.move]} is locked. Waiting for your opponent. Answer speed earns no extra damage.</p>:<form onSubmit={e=>{e.preventDefault();void act({action:'answer',questionId:q.id,answer,move});}}><fieldset disabled={busy||room.paused}><legend>Choose your move</legend><div className="duel-moves">{MOVES.map(m=><button key={m} type="button" aria-pressed={move===m} onClick={()=>setMove(m)}><strong>{titles[m]}</strong><small>Beats {titles[beats[m]]}</small></button>)}</div><label>Your answer<input value={answer} maxLength={80} autoComplete="off" onChange={e=>setDraft({id:q.id,answer:e.target.value})}/></label>{q.attempts>0&&<p role="status">Not yet. Use the hint and try again — your power stays the same.</p>}<button className="duel-primary" disabled={!answer.trim()}>Answer & lock move</button></fieldset></form>}</section>}
 {latest&&<section className="duel-result" aria-label="Round result"><h4>Round {latest.round} result</h4>{room.fighters.map((f,i)=><p key={f.id}>{f.pet?.name??f.alias}: {latest.moves[i]==='strike'&&f.pet?.move?`${f.pet.move}!`:titles[latest.moves[i]]} · took {latest.damage[i]} damage</p>)}{q&&'explanation' in q&&<details><summary>Review my math</summary><p>{q.text} Answer: {q.answer}</p>{q.explanation?.map((line,i)=><p key={i}>{line}</p>)}</details>}</section>}
 {!finished&&!teacher&&room.fighters.some(f=>f.id===room.you)&&<EmoteBar disabled={busy} send={emote=>void act({action:'emote',emote})}/>}
 {!finished&&<div className="duel-controls">{teacher&&<><p>{room.charged.length}/2 moves locked · {room.ready.length}/2 ready</p><button disabled={busy} onClick={()=>void act({action:'pause',paused:!room.paused})}>{room.paused?'Resume duel':'Pause duel'}</button></>}<button disabled={busy} onClick={()=>{if(confirm(room.phase==='lobby'?'Cancel this invitation? Nothing is used.':'End this duel without a winner? It still counts as your duel; saved pet progress stays safe.'))void act({action:'end'});}}>{teacher?'End duel':room.phase==='lobby'?(ready?'Cancel invitation':'Decline invitation'):'Leave duel'}</button></div>}
 </article>;
}
