import { useState } from 'react';
import type { EngineState } from '../types/engine';
import type { GameEngineAction } from '../engine/core/ActionTypes';
import { ADVENTURE_STYLES, DISCOVERY_DAYS, DISCOVERY_QUIZ, STYLE_KEYS } from '../config/discoveryConfig';
import { COMPANIONS } from '../config/companionConfig';
import { ASSETS } from '../config/assetManifest';
import { discoveryDays, discoveryReady } from '../services/game/eggDiscovery';
import { careDate } from '../services/game/petGrowth';
import { LearningHelp } from '../components/math/LearningHelp';
import { gradeLabel } from '../services/game/curriculum';
import '../discovery.css';

export function DiscoveryScreen({ state, dispatch }: { state: EngineState; dispatch: (action: GameEngineAction) => void }) {
  const d = state.eggDiscovery;
  const [editQuestion, setEditQuestion] = useState<number | null>(null);
  const [answer, setAnswer] = useState('');
  const [greeted, setGreeted] = useState(false);
  const [dismissedHelp, setDismissedHelp] = useState(false);
  if (!d) return <main className="growth-screen"><div className="growth-container"><h1>Companion discovery</h1><p>Your existing companion and egg are safe.</p><button className="growth-button" onClick={() => dispatch({ type: 'START_EGG_DISCOVERY' })}>Start a discovery week</button><button className="growth-button" onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'home' })}>← Home</button></div></main>;
  const firstUnanswered = d.answers.findIndex(a => a < 0);
  const q = editQuestion ?? firstUnanswered;
  const today = careDate(), days = discoveryDays(d), doneToday = d.stamps.some(s => s.day === today);
  const ready = discoveryReady(d), matched = d.companion && COMPANIONS[d.companion];
  const mission = d.mission?.day === today ? d.mission : null;
  const problem = mission?.problems[mission.index];
  return <main className="growth-screen discovery-screen"><div className="growth-container">
    <section className="growth-panel" aria-label="How to hatch your pet"><h2>How to hatch your pet</h2><ol><li>Earn five activity-day credits. Today’s activity below shows your next step.</li><li>Press <strong>Reveal my companion</strong>, then <strong>Bring my egg to the nursery</strong>.</li><li>In the nursery, tap the egg to reach 100% warmth, then press <strong>Hatch my pet</strong>.</li></ol><p>Your pet will welcome you on Home after it hatches. The adventure quiz is optional.</p></section>
    <div className="discovery-next-step" aria-label="Your next egg step">{d.status === 'collecting' && <>
      {ready ? <section className="growth-panel discovery-ready"><h2>Your egg is ready!</h2><p>Ready to meet your new friend? Your match is saved, so refreshing won’t change it.</p><button className="growth-button primary" onClick={() => dispatch({ type: 'REVEAL_DISCOVERY_EGG' })}>Reveal my companion</button></section>
      : doneToday ? <section className="growth-panel" role="status"><h2>Today is complete!</h2><p><strong>{days} of {DISCOVERY_DAYS} days completed.</strong> Today’s stamp is in your passport!</p><p>Come back on another learning day for your next stamp. You can keep playing; another stamp becomes available on your next activity day.</p></section>
      : mission && problem ? <section className="growth-panel discovery-mission" aria-label="Daily discovery mission"><p className="eyebrow">Today’s egg activity · Question {mission.index + 1} of 3 · {gradeLabel(state.learning.grade)} · Untimed · Retry freely</p><h2>{ADVENTURE_STYLES[mission.style].mission}</h2><p>{ADVENTURE_STYLES[mission.style].story}</p><div className="discovery-pieces" aria-label={`${mission.index} of 3 pieces collected`}>{[0, 1, 2].map(i => <span className={i < mission.index ? 'lit' : ''} key={i}>{ADVENTURE_STYLES[mission.style].icon}</span>)}</div><form onSubmit={e => { e.preventDefault(); setDismissedHelp(false); dispatch({ type: 'ANSWER_DISCOVERY_MISSION', questionId: problem.id, answer }); setAnswer(''); }}><label htmlFor="discovery-answer" className="growth-question">{problem.question}</label><input id="discovery-answer" value={answer} onChange={e => setAnswer(e.target.value)} autoComplete="off" aria-label="Discovery answer" placeholder="Your answer"/><button className="growth-button primary">Add an adventure piece</button></form><p role="status">{mission.feedback}</p>{problem && mission.feedback.startsWith('Try again') && !dismissedHelp && <LearningHelp key={problem.id} problem={problem} onRetry={() => { setDismissedHelp(true); document.getElementById('discovery-answer')?.focus(); }} />}<p className="discovery-note">Need an offline or read-aloud activity? Your teacher can credit today in the dashboard.</p></section>
      : <section className="growth-panel" aria-label="Choose today's adventure"><p className="eyebrow">Your next step · Day {days + 1} of {DISCOVERY_DAYS}</p><h2>Help your egg grow today.</h2><p>Answer 3 questions to earn today’s egg stamp and 30 base tokens. Math growth is saved for your companion when it hatches. You can take your time and try again.</p><button className="growth-button primary discovery-start" onClick={() => dispatch({ type: 'START_DISCOVERY_MISSION', style: STYLE_KEYS[days % STYLE_KEYS.length] })}>Start today’s activity →</button><h3>Or choose an adventure</h3><p>Each mission has three math questions at your teacher’s chosen level. Different themes, equal credit. The quiz is optional; your activities also shape your match.</p><div className="discovery-missions">{STYLE_KEYS.map(style => <button key={style} onClick={() => dispatch({ type: 'START_DISCOVERY_MISSION', style })}><span aria-hidden="true">{ADVENTURE_STYLES[style].icon}</span><strong>{ADVENTURE_STYLES[style].mission}</strong><small>{ADVENTURE_STYLES[style].story}</small></button>)}</div></section>}
    </>}</div>
    {matched && d.companion && <section className="growth-panel discovery-match" aria-label="Your companion match"><p className="eyebrow">A new friendship begins</p><img src={ASSETS.petPortraits[d.companion]} alt={matched.name}/><h2>Meet {matched.name}!</h2><p>{matched.description}</p><p>{d.teacherChoice ? 'Your teacher picked this companion for your next adventure. Your discovery stamps still helped welcome your new friend!' : 'Your pretend-adventure choices and completed activities helped match this friend from the companions you haven’t adopted yet. A tie gets a saved surprise pick.'} This is a game match—not a label about you.</p><img className="discovery-match-egg" src={ASSETS.eggs[COMPANIONS[d.companion].egg].url} alt={`${matched.name}'s egg`}/><button className="growth-button primary" onClick={() => dispatch(d.status === 'matched' ? { type: 'CLAIM_DISCOVERY_EGG' } : { type: 'SET_SCREEN', screen: state.egg ? 'incubation' : 'home' })}>{d.status === 'matched' ? 'Bring my egg to the nursery' : state.egg ? 'Visit my egg' : 'Visit my companion'}</button><p className="discovery-note">Your egg-day activities carry into your companion’s first temperament. After hatching, your baby begins its separate week of care.</p></section>}
    <button className="growth-button primary" onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'arcade' })}>Woodland Arcade · Play three new games →</button>
    {state.pet && <button className="growth-button" onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'home' })}>← Home</button>}
    <header className="growth-heading"><p className="eyebrow">The woodland discovery club</p><h1>Your week. Your companion.</h1><p>{d.bonusDays ? "Your early-hatch pass saves one day: complete four activity days." : "Your mystery egg stays with you for five activity days before it can hatch."}</p></header>
    {!!(state.prizes?.earlyHatchPasses||d.bonusDays)&&<section className="growth-panel" aria-label="Early hatch pass"><h2>{d.bonusDays?'One day saved!':'Teacher egg pass'}</h2><p>{state.prizes?.earlyHatchPasses??0} passes saved. One pass replaces one activity day per egg; the quiz is optional.</p><button className="growth-button" disabled={!state.prizes?.earlyHatchPasses||d.status!=='collecting'||!!d.bonusDays||days>=5} onClick={()=>dispatch({type:'USE_EARLY_HATCH_PASS'})}>Use one-day-early pass</button></section>}
    <div className="discovery-intro"><button className="mystery-egg" aria-label="Greet your mystery egg" onClick={() => setGreeted(!greeted)}>{greeted ? "♥" : days >= 4 ? "✦" : "?"}</button><div><h2>Your egg is getting to know you</h2><p>Keep your egg company and earn five day credits, including at most one teacher pass. Try a learning question, finish a game, or join a teacher-guided activity on each activity day. Exploring, building, helping, and wondering shape the friend inside. Your activities influence both its companion match and its first temperament—not your grades or speed.</p><p aria-live="polite">{greeted ? "Your egg gives a happy little wobble. It remembers your completed adventures; extra taps do not rush hatching." : ["A quiet little egg. Your first shared adventure is waiting.", "A tiny glow: your egg remembers your first adventure.", "A gentle wiggle: two shared days are tucked inside.", "A warm heartbeat: your friendship is growing.", "A bright shimmer: one more activity day before the reveal.", "Five shared activity days! Your friend is ready to be revealed."][Math.min(days, 5)]}</p><p className="discovery-note">No right or wrong quiz answers. Not a personality test. Every companion is equally special!</p></div></div>
    {d.status === 'collecting' && <>
      {q >= 0 ? <section className="growth-panel" aria-label="Adventure style quiz"><p className="eyebrow">Adventure style · {q + 1} of {DISCOVERY_QUIZ.length}</p><h2>{DISCOVERY_QUIZ[q].question}</h2><p>Choose a pretend adventure, or let us surprise you. A teacher can read this aloud.</p><div className="discovery-choices">{[0, 1, 2, 3, 4].map((_, i) => i === 4 ? 4 : (i + q) % 4).map(choice => <button key={choice} className="growth-button" aria-pressed={d.answers[q] === choice} onClick={() => { dispatch({ type: 'ANSWER_DISCOVERY_QUIZ', question: q, choice }); if (editQuestion !== null) setEditQuestion(q < 3 ? q + 1 : null); }}>{choice === 4 ? 'Surprise me—any of these!' : DISCOVERY_QUIZ[q].choices[choice]}</button>)}</div><button className="discovery-link" onClick={() => { DISCOVERY_QUIZ.forEach((_, question) => dispatch({ type: 'ANSWER_DISCOVERY_QUIZ', question, choice: 4 })); setEditQuestion(null); }}>Skip quiz—use my activities instead</button></section>
      : <section className="growth-panel discovery-quiz-done"><div><h2>Your adventure choices are packed!</h2><p>You can like a bit of everything. Activities matter more than quiz choices.</p></div><button className="growth-button" onClick={() => setEditQuestion(0)}>Review quiz choices</button></section>}
      <section className="growth-panel" aria-label="Discovery passport"><p className="eyebrow">My adventure passport</p><h2>{days} / {DISCOVERY_DAYS} learning days</h2><div className="discovery-passport">{Array.from({ length: DISCOVERY_DAYS }, (_, i) => { const stamp = d.stamps[i]; const bonus=!!d.bonusDays&&i===4; return <div key={i} className={stamp||bonus ? 'stamped' : ''}><span aria-hidden="true">{stamp ? ADVENTURE_STYLES[stamp.style].icon : bonus?'🎟':'○'}</span><strong>Day {i + 1}</strong><small>{stamp ? ADVENTURE_STYLES[stamp.style].label : bonus?'Teacher pass':'An adventure awaits'}</small></div>; })}</div><p>One stamp per day, not five sessions in one day. Weekends aren’t required. Miss a day? Your stamps stay! Days reset at midnight UTC.</p></section>
      <section className="growth-panel"><button className="woodland-invite" onClick={() => dispatch({ type: 'OPEN_WOODLAND' })}><strong>Join the bridge adventure →</strong><span>Meet your club guide and help the woodland while your mystery egg waits.</span></button><h2>More to play while you wait</h2><p>These games count toward today’s stamp too. One stamp per day; no grinding needed.</p><div className="growth-care-actions"><button onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'math' })}>Math Practice</button><button onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'catch_math' })}>Catch Math</button><button onClick={() => dispatch({ type: 'SET_SCREEN', screen: 'number_merge' })}>Number Merge</button></div></section>
    </>}
    <footer className="discovery-footer">Your game saves your activity choices and day stamps. No names, personal stories, rankings or public personality profiles.</footer>
    {state.devPreview && <p className="growth-panel text-amber-200">DEV preview only. These stamps and matches do not change a student’s save.</p>}
  </div></main>;
}
