import { SchoolCare } from '../components/care/SchoolCare';
import { useEffect, useRef, useState } from 'react';
import type { EngineState } from '../types/engine';
import type { GameEngineAction } from '../engine/core/ActionTypes';
import { COMPANIONS, GROWING_PETS, GROWTH_STAGES, isGrowingPet, isCompanion, petVisualKey, stageIndex } from '../config/companionConfig';
import { ASSETS } from '../config/assetManifest';
import { checkEvolution } from '../services/game/evolutionEngine';
import { careDate, careProgress, getGrowth } from '../services/game/petGrowth';
import { PetSprite } from '../components/pet/PetSprite';
import { LearningHelp } from '../components/math/LearningHelp';
import { gradeLabel } from '../services/game/curriculum';
import { CARE_ACTIONS, FOOD_ITEMS } from '../config/gameConfig';

export function GrowthScreen({ state, dispatch }: { state: EngineState; dispatch: (a: GameEngineAction) => void }) {
  const pet = state.pet, trial = state.growthTrial;
  const [answer, setAnswer] = useState('');
  const [dismissedHelp, setDismissedHelp] = useState(false);
  const trialRef = useRef<HTMLElement>(null);
  const trialKey = trial ? `${trial.petId}-${trial.stage}-${trial.kind}` : '';
  useEffect(() => { if (trialKey) trialRef.current?.scrollIntoView({ block: 'center' }); }, [trialKey]);
  const roster = state.companionRoster ?? [], owned = [...roster, ...(pet ? [pet] : [])];
  const progress = pet ? careProgress(pet) : null, growth = pet ? getGrowth(pet) : null;
  const ready = pet ? checkEvolution(pet, state.player.lifetimeMathCorrect) : null;
  const rank = pet ? stageIndex(pet.stage) : 0;
  const config = pet && isGrowingPet(pet.speciesId) ? GROWING_PETS[pet.speciesId] : null;
  const problem = trial && !trial.complete ? trial.problems[trial.index] : null;
  const busy = state.battle.active || state.run.active || state.momentum.active;
  return <main className="growth-screen"><div className="growth-container">
    <button className="growth-button" onClick={() => dispatch({ type: 'SET_SCREEN', screen: pet ? 'home' : 'incubation' })}>← Home</button>
    <header className="growth-heading"><p className="eyebrow">Little companions. Big possibilities.</p><h1>Nursery & evolution</h1><p>Care, learn, grow. Every friendship has its own journey.</p></header>
    {pet && progress && growth && <>
      <section className="growth-hero" aria-label="Active companion growth"><div className="growth-pet"><PetSprite speciesId={pet.speciesId} stage={pet.stage} animationName={trial?.complete ? 'happy' : 'idle'} scale={1.6} /></div><div><p className="eyebrow">{pet.stage} · Level {pet.progression.level} · {rank}/2 evolutions</p><h2>{pet.name}</h2><p>{config?.description ?? 'Your original companion keeps its progress and identity.'}</p><p className="growth-care-count">{progress.days} complete care days · {Math.floor(progress.ageDays)} days old</p><p>Babies need at least 7 real days and 7 complete care days. Adults need 14 complete care days and a week as a juvenile. Missed days never erase progress. Days reset at midnight UTC.</p></div></section>
      <SchoolCare dispatch={dispatch}/>
      <section className="growth-panel" aria-label="Today's baby care"><h2>Today’s care checklist</h2><p>One feed, one clean, and one play session make a complete day.</p><div className="care-week">{Array.from({ length: rank === 0 ? 7 : 14 }, (_, i) => <span key={i} className={progress.days > i ? 'done' : ''} aria-label={`Care day ${i + 1}${progress.days > i ? ' complete' : ''}`}>{progress.days > i ? '♥' : i + 1}</span>)}</div><div className="growth-care-actions">
        <button disabled={pet.state === 'dead' || state.player.currencies.tokens < FOOD_ITEMS[0].cost} onClick={() => dispatch({ type: 'FEED_PET', food: FOOD_ITEMS[0] })}>{progress.today.includes('feed') ? '✓ ' : ''}Feed · {FOOD_ITEMS[0].cost} tokens</button>
        <button disabled={pet.state === 'dead' || state.player.currencies.tokens < CARE_ACTIONS.clean.cost} onClick={() => dispatch({ type: 'CLEAN_PET' })}>{progress.today.includes('clean') ? '✓ ' : ''}Clean · {CARE_ACTIONS.clean.cost} tokens</button>
        <button disabled={pet.state === 'dead' || state.player.currencies.tokens < CARE_ACTIONS.play.cost} onClick={() => dispatch({ type: 'PLAY_PET' })}>{progress.today.includes('play') ? '✓ ' : ''}Play · {CARE_ACTIONS.play.cost} tokens</button>
      </div><p className="text-xs mt-3">Care mini-games also count: wash/brush for cleaning; pet, comfort, train or play for play. Tokens: {state.player.currencies.tokens}. Earn more in the existing mini-games.</p></section>
      {config && <section className="growth-panel"><h2>Your evolution path</h2><div className="growth-path">{GROWTH_STAGES.map((stage, i) => <article key={stage} className={rank >= i ? 'unlocked' : ''}><img src={ASSETS.petPortraits[petVisualKey({ speciesId: pet.speciesId, stage })]} alt={`${config.name} ${stage}`} /><h3>{config.stages[i]}</h3><p>{stage}</p><strong>{i === 0 ? 'Care & all existing mini-games' : config.powers[i - 1]}</strong><p>{i === 1 ? '+ Daily Bond Bloom' : i === 2 ? '+ Daily Star Expedition' : 'A week of little moments'}</p></article>)}</div></section>}
      <section className="growth-panel"><h2>{rank === 2 ? 'Fully evolved' : 'Ready for the next chapter?'}</h2>{rank < 2 && <><p>Next: {rank === 0 ? 'juvenile' : 'adult'} · Level {ready?.requirement?.level} · Bond {Math.floor(pet.bond)}/{ready?.requirement?.bond} · Math {state.player.lifetimeMathCorrect}/{ready?.requirement?.lifetimeMathCorrect}</p><p>{ready?.canEvolve ? 'All requirements met! Light the growth lanterns to evolve.' : `Still growing: ${ready?.blocker === 'age' ? `${Math.max(0, Math.ceil(7 - (rank === 0 ? progress.ageDays : progress.stageDays)))} more real days` : ready?.blocker === 'care' ? `${Math.max(0, (rank === 0 ? 7 : 14) - progress.days)} more complete care days` : ready?.blocker}.`}</p><button className="growth-button primary" disabled={!ready?.canEvolve || busy} onClick={() => dispatch({ type: 'START_GROWTH_TRIAL', kind: 'evolution' })}>{rank === 0 ? 'Play Growth Lanterns' : 'Play Guardian Constellation'}</button></>}
        <div className="growth-care-actions"><button disabled={!config || rank < 1 || pet.state === 'dead' || busy || growth.lastGiftDay === careDate()} onClick={() => dispatch({ type: 'USE_COMPANION_GIFT' })}>{rank < 1 ? '🔒 ' : ''}Bond Bloom {growth.lastGiftDay === careDate() ? '✓ Used today' : '· +20 joy, +15 health, +25 XP'}</button><button disabled={rank < 2 || pet.state === 'dead' || busy || growth.lastExpeditionDay === careDate()} onClick={() => dispatch({ type: 'START_GROWTH_TRIAL', kind: 'expedition' })}>{rank < 2 ? '🔒 ' : ''}Star Expedition {growth.lastExpeditionDay === careDate() ? '✓ Done today' : '· 5 questions, +50 base tokens and math growth'}</button></div>
      </section>
    </>}
    {trial && pet && <section ref={trialRef} key={trialKey} className={`growth-panel growth-trial ${trial.complete ? 'growth-complete' : ''}`} aria-label="Evolution mini-game"><p className="eyebrow">{gradeLabel(state.learning.grade)} · Untimed · Retry freely</p><h2>{trial.kind === 'expedition' ? 'Star Expedition' : trial.stage === 'baby' ? 'Growth Lanterns' : 'Guardian Constellation'}</h2><div className="growth-lanterns" aria-label={`${trial.index} of ${trial.problems.length} lanterns lit`}>{trial.problems.map((p, i) => <span key={p.id} className={i < trial.index ? 'lit' : ''}>✦</span>)}</div>
      {problem && <form onSubmit={e => { e.preventDefault(); setDismissedHelp(false); dispatch({ type: 'ANSWER_GROWTH_TRIAL', questionId: problem.id, answer }); setAnswer(''); }}><label htmlFor="growth-answer" className="growth-question">{problem.question}</label><input id="growth-answer" aria-label="Evolution answer" autoComplete="off" value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Your answer" /><button className="growth-button primary" type="submit">Light the next star</button></form>}
      <p role="status" className="my-3">{trial.feedback}</p>{problem && trial.feedback.startsWith('Try again') && !dismissedHelp && <LearningHelp key={problem.id} problem={problem} onRetry={() => { setDismissedHelp(true); document.getElementById('growth-answer')?.focus(); }} />}{trial.complete && config && trial.kind === 'evolution' && <p>Unlocked: {config.powers[Math.max(0, rank - 1)]} in battle, plus {rank === 1 ? 'Bond Bloom' : 'Star Expedition'}.</p>}<button className="growth-button" onClick={() => dispatch({ type: 'CLOSE_GROWTH_TRIAL' })}>{trial.complete ? 'Celebrate & continue' : 'Close mini-game'}</button>
    </section>}
    <section className="growth-panel"><h2>Your companion family</h2><p>Adopt each species once. Other companions rest safely in the nursery; switching never resets them.</p>{!state.devPreview && Object.keys(COMPANIONS).some(id => !owned.some(p => p.speciesId === id)) && <div className="my-4"><p>New eggs come from a five-day discovery adventure, not a shopping choice.</p><button className="growth-button primary" disabled={!!state.egg || busy} onClick={() => dispatch({ type: 'START_EGG_DISCOVERY' })}>{state.eggDiscovery && state.eggDiscovery.status !== 'claimed' ? 'Continue discovery week' : 'Discover my next egg'}</button></div>}<div className="nursery-grid">{Object.entries(COMPANIONS).map(([id, info]) => { const saved = owned.find(p => p.speciesId === id), active = pet?.speciesId === id; return <article key={id}><img src={ASSETS.petPortraits[saved ? petVisualKey(saved) : id]} alt={info.name} /><h3>{info.name}</h3><p>{info.title}</p><p>{saved ? `${saved.stage} · ${careProgress(saved).days} care days` : info.description}</p><button className="growth-button" disabled={active || !!state.egg || busy || (!saved && !state.devPreview)} onClick={() => dispatch(saved ? { type: 'SWITCH_COMPANION', petId: saved.id } : { type: 'ADOPT_COMPANION', speciesId: id })}>{active ? 'With you now' : saved ? `Visit ${info.name}` : state.devPreview ? `Adopt ${info.name}'s egg` : 'Waiting to be discovered'}</button></article>; })}</div>{roster.filter(p => !isCompanion(p.speciesId)).map(p => <button key={p.id} className="growth-button" disabled={!!state.egg || busy} onClick={() => dispatch({ type: 'SWITCH_COMPANION', petId: p.id })}>Visit {p.name} (original companion)</button>)}</section>
    {state.devPreview && <p className="growth-panel text-amber-200">DEV preview: changes do not touch your real save. Use the species and stage selectors in Dev Mode to preview every evolution.</p>}
  </div></main>;
}
