import { DEMO_MODE } from '../demo/demoMode';
import { useState } from 'react';
import type { LearnerProfile } from '../services/persistence/learnerIndex';
import type { ProfileResult } from '../services/persistence/learnerProfiles';

export function TeacherLearnersPanel({ profiles, activeId, onSelect, onCreate, disabled }: { profiles: LearnerProfile[]; activeId: string; onSelect: (id: string) => void; onCreate: (label: string) => ProfileResult; disabled: boolean }) {
  const [label, setLabel] = useState(''), [search, setSearch] = useState(''), [error, setError] = useState('');
  return <div className="space-y-6"><section className="teacher-card"><h2>Learners on this browser</h2><p>Choose a learner before changing settings or rewards. Every learner has a separate save, companions, discovery week and math settings. These are not the game’s pretend classmates.</p><label className="block my-4">Find a learner<input className="teacher-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Nickname or class code"/></label><div className="teacher-learners">{profiles.filter(p => p.label.toLowerCase().includes(search.toLowerCase())).map(p => <button key={p.id} disabled={disabled || p.id === activeId} onClick={() => onSelect(p.id)}><span className="teacher-avatar" aria-hidden="true">{p.label.slice(0, 1).toUpperCase()}</span><span><strong>{p.label}</strong><small>{p.id === activeId ? 'Selected learner' : 'Open learner profile'}</small></span></button>)}</div></section>
    <section className="teacher-card"><h2>Add a learner</h2><p>Use a nickname or class code, such as “Blue Team 3”. No real name or email is required. {DEMO_MODE ? 'Demo learners start with a ready-to-play pet and stocked supplies.' : 'New learners start with their own discovery quiz.'}</p><form onSubmit={e => { e.preventDefault(); const result = onCreate(label); if (!result.ok) setError(result.error); }}><label className="block my-4">Learner nickname or class code<input className="teacher-input" value={label} onChange={e => setLabel(e.target.value)} maxLength={30} required autoComplete="off"/></label><button className="growth-button primary" disabled={disabled || !label.trim()}>Create learner profile</button></form>{error && <p role="alert" className="text-amber-200">{error}</p>}</section>
    <p className="text-xs text-slate-400">{DEMO_MODE ? 'Demo profiles last until reload. Use the classroom game for individual student logins and saved progress.' : 'Local profiles only—not a synced school roster. Keep this browser’s storage; clearing it removes these profiles. Anyone with access to this browser can use the teacher tools.'}</p>
  </div>;
}
