import { describe, it, expect } from 'vitest';
import { apply, advanceClock, captain, createRoom, DEFAULT_SETTINGS, view, type Room } from './model';
function lobby(teams=2):Room {const r=createRoom({...DEFAULT_SETTINGS,teams,rounds:1,questions:1});r.members=[0,1,2,3].map(i=>({id:`m${i}`,alias:`Learner ${i}`,team:i%teams,tokenHash:`secret${i}`}));return r;}
function board():Room {let r=apply(lobby(),{action:'next'},'teacher',1000,()=>.5);for(const m of r.members)r=apply(r,{action:'answer',questionId:r.question!.id,answer:String(r.question!.answer)},m.id,1001);for(let i=0;i<3;i++)r=apply(r,{action:'next'},'teacher',1002);return r;}
describe('Portal Party classroom rules',()=>{
 it('uses the session math level without changing source settings',()=>{const s={...DEFAULT_SETTINGS,learning:{...DEFAULT_SETTINGS.learning,grade:9,topic:'Slope'}};const r=createRoom(s);const q=apply({...r,members:lobby().members},{action:'next'},'teacher',1000,()=>.5);expect(q.question!.topic).toBe('Slope');expect(r.phase).toBe('lobby');expect(s.learning.grade).toBe(9);});
 it('keeps answers and token hashes private until teacher reveal',()=>{let r=apply(lobby(),{action:'next'},'teacher',1000,()=>.5);r=apply(r,{action:'answer',questionId:r.question!.id,answer:String(r.question!.answer)},'m0',1001);for(const who of ['projector','m1']){const json=JSON.stringify(view(r,who));expect(json).not.toContain('secret');expect(view(r,who).question?.answer).toBeUndefined();expect(view(r,who).question?.answers).toBeUndefined();expect(view(r,who).history).toEqual([]);}expect(view(r,'teacher').question?.answer).toBe(r.question?.answer);expect(view(r,'m0').question?.mine?.text).toBe(String(r.question?.answer));r=apply(r,{action:'next'},'teacher');expect(view(r,'projector').question?.answer).toBeUndefined();r=apply(r,{action:'next'},'teacher');expect(view(r,'projector').question?.answer).toBe(r.question?.answer);});
 it('awards once, rounds half up, and accepts equivalent fractions',()=>{let r=apply(lobby(),{action:'next'},'teacher',1000,()=>.5);r=apply(r,{action:'answer',questionId:r.question!.id,answer:`${r.question!.answer*2}/2`},'m0',1001);r=apply(r,{action:'next'},'teacher');r=apply(r,{action:'next'},'teacher');expect(r.teams.map(t=>t.earned)).toEqual([1,0]);expect(r.history).toHaveLength(4);r=apply(r,{action:'next'},'teacher');expect(r.teams[0].earned).toBe(1);});
 it('rejects duplicate, old, malformed and late submissions',()=>{let r=apply(lobby(),{action:'next'},'teacher',1000);r.question!.deadline=2000;expect(()=>apply(r,{action:'answer',questionId:'old',answer:'2'},'m0',1001)).toThrow();expect(()=>apply(r,{action:'answer',questionId:r.question!.id,answer:'2abc'},'m0',1001)).toThrow();expect(()=>apply(r,{action:'answer',questionId:r.question!.id,answer:'2'},'m0',2000)).toThrow();r=apply(r,{action:'answer',questionId:r.question!.id,answer:'2'},'m0',1001);expect(()=>apply(r,{action:'answer',questionId:r.question!.id,answer:'3'},'m0',1002)).toThrow();});
 it('restricts hosting and controls to teacher or rotating captain',()=>{let r=board();expect(()=>apply(r,{action:'finish'},'m0')).toThrow();expect(()=>apply(r,{action:'score',team:0,amount:100},'m0')).toThrow();expect(()=>apply(r,{action:'spin'},'m1')).toThrow();expect(captain(r)).toBe('m0');r=apply(r,{action:'spin'},'m0',1000);r=apply(r,{action:'stop'},'m0',1001,()=>0);expect(r.teams[0].score).toBe(100);expect(captain(r)).toBe('m2');expect(()=>apply(r,{action:'stop'},'teacher')).toThrow();});
 it('requires received charges to be played and converts them after a rift',()=>{let r=board();r.teams[0].earned=3;r=apply(r,{action:'pass',team:1},'teacher');expect(r.teams[1].passed).toBe(3);expect(()=>apply(r,{action:'pass',team:0},'teacher')).toThrow();r=apply(r,{action:'spin'},'teacher',1000);r=apply(r,{action:'stop'},'teacher',1001,()=>2/16);expect(r.teams[1].passed).toBe(0);expect(r.teams[1].earned).toBe(3);});
 it('bounds gentle penalties and resets classic session scores',()=>{for(const gentle of [true,false]){let r=board();r.settings.gentle=gentle;r.teams[0].score=500;r=apply(r,{action:'spin'},'teacher',1000);r=apply(r,{action:'stop'},'teacher',1001,()=>2/16);expect(r.teams[0].score).toBe(gentle?300:0);expect(r.phase).toBe('result');expect(r.members).toHaveLength(4);}});
 it('pauses clocks and recovers an abandoned spin',()=>{let r=board();r=apply(r,{action:'spin'},'teacher',1000);r=apply(r,{action:'pause'},'teacher',2000);expect(advanceClock(r,40000,()=>0)).toBe(r);r=apply(r,{action:'pause'},'teacher',42000);expect(r.spinAt).toBe(41000);expect(advanceClock(r,55999,()=>0).phase).toBe('spinning');expect(advanceClock(r,56000,()=>0).phase).toBe('result');});
 it('finishes only after the round charges are spent',()=>{let r=board();expect(()=>apply(r,{action:'next'},'teacher')).toThrow();for(let i=0;i<2;i++){r=apply(r,{action:'spin'},'teacher');r=apply(r,{action:'stop'},'teacher',Date.now(),()=>0);r=apply(r,{action:'next'},'teacher');}r=apply(r,{action:'next'},'teacher');expect(r.phase).toBe('finished');expect(()=>apply(r,{action:'spin'},'teacher')).toThrow();});
 it('stores teacher overrides separately from chance scores',()=>{let r=apply(lobby(),{action:'next'},'teacher');r=apply(r,{action:'next'},'teacher');r=apply(r,{action:'override',memberId:'m0',correct:true},'teacher');r=apply(r,{action:'next'},'teacher');expect(r.history.find(h=>h.member==='m0')).toMatchObject({correct:true,overridden:true});expect(r.teams[0].score).toBe(0);});
});
