import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { startPolling } from '../../pilot/polling';
import { pilotAPI } from '../../pilot/api';
import { generateLearningProblem, GRADE_TOPICS, gradeLabel, type Challenge } from '../../services/game/curriculum';
import { CREWS, DEFAULT_SETTINGS, MASCOTS, TILES, type Settings, type View } from './model';
import './portal.css';

type Payload={room:View|null;projectorToken?:string};
type Seat={id:string;token:string;code?:string};
type Mode='teacher'|'student'|'projector';
async function publicAPI<T>(op:string,seat?:Seat,body?:unknown):Promise<T>{
  const res=await fetch(`/api/pilot/portal-access?op=${op}${seat?`&id=${encodeURIComponent(seat.id)}`:''}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Pilot-Request':'1',...(seat?{'X-Portal-Token':seat.token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});
  const data=await res.json();if(!res.ok)throw new Error(data.error??'Could not reach the festival.');return data;
}
const art=(i:number)=>i===0?'/assets/woodland-v1/pip-portrait.png':`/assets/companions-v1/${MASCOTS[i]}-baby-portrait.png`;
function Banner(){return <header className="portal-banner"><img src="/assets/woodland-v1/pip-portrait.png" alt="Pip, your festival host"/><div><p className="portal-eyebrow">A woodland math festival</p><h1>Pip’s Portal Party</h1><p>Solve together. Charge the portal. Let the woodland sparkle.</p></div><span className="portal-emblem" aria-hidden="true">✦</span></header>;}
function useRoom(mode:Mode,seat?:Seat){
  const [payload,setPayload]=useState<Payload>({room:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[serverOffset,setServerOffset]=useState(0);
  const pending=useRef(false);
  const accept=useCallback((data:Payload)=>{setPayload(old=>old.room&&data.room&&old.room.id===data.room.id&&old.room.revision>data.room.revision?old:data);setConnected(true);if(data.room)setServerOffset(data.room.serverNow-Date.now());},[]);
  const refresh=useCallback(async()=>{try{accept(mode==='teacher'?await pilotAPI<Payload>('portal'):await publicAPI<Payload>(mode==='projector'?'projector':'state',seat));}catch(e){setConnected(false);setError(e instanceof Error?e.message:'Connection interrupted.');}},[mode,seat,accept]);
  useEffect(()=>startPolling(refresh,1500),[refresh]);
  const command=async(body:Record<string,unknown>)=>{
    if(pending.current)return;pending.current=true;setBusy(true);setError('');
    try{const data={phase:payload.room?.phase,questionId:payload.room?.question?.id,...body,revision:payload.room?.revision};accept(mode==='teacher'?await pilotAPI<Payload>(`portal/act?id=${payload.room?.id}`,'POST',data):await publicAPI<Payload>('act',seat,data));}
    catch(e){setError(e instanceof Error?e.message:'Could not save that action.');await refresh();}
    finally{pending.current=false;setBusy(false);}
  };
  return {payload,accept,error,setError,busy,connected,command,serverOffset};
}
function Setup({onCreate}:{onCreate:(settings:Settings)=>Promise<void>}){
  const [s,set]=useState(DEFAULT_SETTINGS),[busy,setBusy]=useState(false);
  const sample=useMemo(()=>generateLearningProblem(s.learning,()=>.43),[s.learning]);
  return <form className="portal-setup" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onCreate(s);}finally{setBusy(false);}}}>
    <div><p className="portal-eyebrow">Teacher’s festival desk</p><h2>Make this your math lesson.</h2><p>Choose the level for this session. Students’ regular assignments stay saved.</p>
    <div className="portal-fields"><label>Math level<select value={s.learning.grade} onChange={e=>set({...s,learning:{...s.learning,grade:Number(e.target.value),topic:'mixed'}})}>{GRADE_TOPICS.map((_,i)=><option key={i} value={i}>{gradeLabel(i)}</option>)}</select></label>
    <label>Math topic<select value={s.learning.topic} onChange={e=>set({...s,learning:{...s.learning,topic:e.target.value}})}><option value="mixed">Mixed practice</option>{GRADE_TOPICS[s.learning.grade].map(t=><option key={t}>{t}</option>)}</select></label>
    <label>Difficulty<select value={s.learning.challenge} onChange={e=>set({...s,learning:{...s.learning,challenge:e.target.value as Challenge}})}><option value="support">Support</option><option value="standard">Standard</option><option value="stretch">Stretch</option></select></label>
    <label>Teams<select value={s.teams} onChange={e=>set({...s,teams:Number(e.target.value)})}>{CREWS.map((_,i)=><option key={i} value={i+1}>{i+1} {i===0?'team':'teams'}</option>)}</select></label>
    <label>Rounds<select value={s.rounds} onChange={e=>set({...s,rounds:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>
    <label>Questions per round<select value={s.questions} onChange={e=>set({...s,questions:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>
    <label>Answer time<select value={s.seconds} onChange={e=>set({...s,seconds:Number(e.target.value)})}>{[0,30,60,90,120].map(n=><option key={n} value={n}>{n?`${n} seconds`:'Untimed'}</option>)}</select></label>
    <label>Rift surprises<select value={s.gentle?'gentle':'classic'} onChange={e=>set({...s,gentle:e.target.value==='gentle'})}><option value="gentle">Gentle · lose up to 200 points</option><option value="classic">Classic · reset festival score</option></select></label></div>
    <button className="portal-primary" disabled={busy}>{busy?'Opening the portal…':'Create festival & join code'}</button></div>
    <aside className="portal-sample"><span className="portal-orb" aria-hidden="true">✧</span><p className="portal-eyebrow">Sample question · {sample.topic}</p><h3>{sample.question}</h3><details><summary>Preview answer & explanation</summary><strong>{sample.answer}</strong><p>{sample.explanation?.join(' ')}</p></details><p>Supported practice skills, selected by you. Students can enter numbers, decimals, or fractions.</p><hr/><p><strong>Everyone stays in.</strong> At least half of each team, rounded up, must answer correctly to earn one charge per question. All students answer before the team takes the board.</p></aside>
  </form>;
}
export function PortalTeacher(){
  const [open,setOpen]=useState(false);
  return <section className="portal portal-teacher-entry"><div className="portal-entry"><img src="/assets/woodland-v1/pip-portrait.png" alt=""/><div><p className="portal-eyebrow">Host a classroom festival</p><h2>Pip’s Portal Party</h2><p>Set the math level, invite 1–8 teams, and project a glowing prize board.</p></div><button className="portal-primary" onClick={()=>setOpen(!open)}>{open?'Hide festival controls':'Host Portal Party'}</button></div>{open&&<Festival mode="teacher"/>}</section>;
}
function Board({room}:{room:View}){
  const [tick,setTick]=useState(0);
  useEffect(()=>{if(room.phase!=='spinning'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setTick(n=>n+1),100);return()=>clearInterval(timer);},[room.phase]);
  const selected=room.phase==='spinning'?tick%16:room.result?.tile;
  return <div className={`portal-board ${room.phase==='spinning'?'is-spinning':''}`} aria-label="Portal prize board">{TILES.map((value,i)=><div key={i} className={`portal-tile ${value===0?'rift':''} ${selected===i?'lit':''}`}><span aria-hidden="true">{value===0?'🌀':'✦'}</span><strong>{value===0?'RIFT':`+${value}`}</strong><small>{value===0?'A woodland surprise':'festival points'}</small></div>)}<div className="portal-board-core"><span className="portal-ring"/><img src="/assets/woodland-v1/pip-portrait.png" alt="Pip"/><strong>{room.phase==='spinning'?'Stop the portal!':room.phase==='result'?'Woodland magic!':'Charge your luck'}</strong><small>{room.teams[room.active].name}</small></div></div>;
}
function exportResults(room:View){
  const rows=[['Nickname','Skill','Question','Answer','Correct','Teacher override'],...room.history.map(h=>[h.alias,h.topic,h.question,h.answer,h.correct?'Yes':'No',h.overridden?'Yes':'No'])];
  const csv=rows.map(row=>row.map(v=>`"${(/^[=+\-@\t\r]/.test(v)?"'":'')+v.replaceAll('"','""')}"`).join(',')).join('\r\n');
  const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='portal-party-math-results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Festival({mode,seat,onLeave}:{mode:Mode;seat?:Seat;onLeave?:()=>void}){
  const {payload,accept,error,setError,busy,connected,command,serverOffset}=useRoom(mode,seat),room=payload.room;
  const [answer,setAnswer]=useState(''),[clock,setClock]=useState(Date.now()),[newGame,setNewGame]=useState(false),[copied,setCopied]=useState(false),[sound,setSound]=useState(false);
  const audioRef=useRef<AudioContext|null>(null),heard=useRef<number|null>(null);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!sound||!room?.result||heard.current===room.result.at)return;heard.current=room.result.at;const ctx=audioRef.current;if(!ctx)return;const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.connect(gain);gain.connect(ctx.destination);oscillator.frequency.setValueAtTime(room.result.delta>0?660:180,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(room.result.delta>0?990:70,ctx.currentTime+.3);gain.gain.setValueAtTime(.07,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);oscillator.start();oscillator.stop(ctx.currentTime+.45);},[room?.result,sound]);
  const host=mode==='teacher',projector=mode==='projector';
  const invoke=(action:string,extras:Record<string,unknown>={})=>{void command({action,...extras});};
  const me=room?.members.find(m=>m.id===room.you);
  const activeMembers=room?.members.filter(m=>m.team===room.active)??[];
  const leader=room?activeMembers[room.teams[room.active].turns%Math.max(1,activeMembers.length)]:undefined;
  const controls=host||leader?.id===room?.you;
  const emptyBoard=room&&!room.teams.some(t=>t.earned+t.passed>0);
  const unavailable=busy||!connected||room?.pausedAt!==null;
  const result=room?.result;
  const joinURL=room?`${location.origin}/?portal=${room.code}`:'';
  return <div className={`portal portal-phase-${room?.phase??'setup'} ${projector?'portal-projector':''}`}><Banner/>
    <div className="portal-top-tools">{!host&&<button onClick={()=>{void document.documentElement.requestFullscreen?.();}}>Full screen</button>}<button aria-pressed={sound} onClick={()=>{if(!sound){audioRef.current??=new AudioContext();void audioRef.current.resume();}setSound(!sound);}}>{sound?'Sound on':'Sound off'}</button>{onLeave&&<button onClick={onLeave}>Back to V-Pet</button>}<span role="status">{connected?'● Connected':'○ Connecting / reconnecting…'}</span></div>
    {error&&<p className="portal-error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></p>}
    {host&&(!room||newGame)&&<Setup onCreate={async s=>{try{accept(await pilotAPI<Payload>('portal/create','POST',{...s,...s.learning}));setNewGame(false);}catch(e){setError(e instanceof Error?e.message:'Could not open festival.');}}}/>}
    {!host&&!room&&<p className="portal-panel">Opening your festival seat… Your saved session will reconnect automatically.</p>}
    {room&&!newGame&&<>
      <div className="portal-ribbon"><span>{gradeLabel(room.settings.learning.grade)} · {room.settings.learning.topic} · {room.settings.learning.challenge}</span><strong>Round {room.round} / {room.settings.rounds}</strong><span>{room.settings.gentle?'Gentle rifts':'Classic rifts'}</span></div>
      {host&&<div className="portal-host-tools"><a className="portal-button" href={`/?portalProjector=1#${room.id}.${payload.projectorToken}`} target="_blank" rel="noreferrer">Open projector ↗</a><button onClick={async()=>{try{await navigator.clipboard.writeText(joinURL);setCopied(true);}catch{setError('Copy the student link displayed below.');}}}>{copied?'Student link copied':'Copy student join link'}</button>{room.phase!=='finished'&&<><button disabled={busy||!connected} onClick={()=>invoke('pause')}>{room.pausedAt!==null?'Resume festival':'Pause festival'}</button><button disabled={busy||!connected} onClick={()=>{if(confirm('End this festival and show the results?'))invoke('finish');}}>End festival</button></>}<button onClick={()=>exportResults(room)}>Download math results</button></div>}
      {room.pausedAt!==null&&<div className="portal-pause" role="status">☾ Pip is taking a breather. Your teacher will resume the festival.</div>}
      {room.phase==='lobby'&&<div className="portal-lobby"><section className="portal-invite"><p className="portal-eyebrow">Your teacher’s festival code</p><strong className="portal-code">{room.code}</strong><p>On your Chromebook, open:</p><a href={joinURL} target="_blank" rel="noreferrer">{joinURL}</a><p>{room.members.length} adventurers ready · automatic balanced teams</p>{host&&<button className="portal-primary" disabled={unavailable||!room.members.length} onClick={()=>invoke('next')}>Start first question</button>}{me&&<p className="portal-ready">You’re in, {me.alias}! You’re with {room.teams[me.team].name}.</p>}</section><aside className="portal-panel"><h2>The woodland needs your math.</h2><p>Answer on your own screen. Your team earns a portal charge when at least half answer correctly, rounded up.</p><p>Captains take turns spinning, stopping, or passing. A rift changes festival points. Everyone keeps playing!</p><p>Session points stay in this festival. Your pet progress stays safe.</p></aside></div>}
      <div className="portal-teams">{room.teams.map((team,i)=><section className={`portal-team ${['board','spinning','result'].includes(room.phase)&&room.active===i?'active':''} ${me?.team===i?'my-team':''}`} key={i}><img src={art(i)} alt={`${CREWS[i]} mascot`}/><div><h3>{team.name}</h3><strong>{team.score.toLocaleString()}<small> points</small></strong><p>✦ {team.earned+team.passed} charges{team.passed>0?` · ${team.passed} received`:''}</p></div>{room.phase==='lobby'&&<ul>{room.members.filter(m=>m.team===i).map(m=><li key={m.id}>{m.alias}{host&&<><select aria-label={`Team for ${m.alias}`} value={m.team} onChange={e=>invoke('move',{memberId:m.id,team:Number(e.target.value)})} disabled={unavailable}>{room.teams.map((t,j)=><option key={j} value={j}>{t.name}</option>)}</select><button aria-label={`Remove ${m.alias}`} onClick={()=>invoke('remove',{memberId:m.id})} disabled={unavailable}>×</button></>}</li>)}</ul>}</section>)}</div>
      {['question','review','reveal'].includes(room.phase)&&room.question&&<section className="portal-question portal-panel"><p className="portal-eyebrow">Question {room.questionNumber} / {room.settings.questions} · {room.question.topic}</p><h2>{room.question.text}</h2><p>{room.question.submitted} / {room.members.length} answers received{room.phase==='question'&&room.question.deadline&&` · ${Math.max(0,Math.ceil((room.question.deadline-(room.pausedAt??(clock+serverOffset)))/1000))}s remaining`}</p>
        {room.phase==='question'&&mode==='student'&&(room.question.mine?<p className="portal-ready">Answer saved: {room.question.mine.text}. Watch the projector!</p>:<form className="portal-answer" onSubmit={e=>{e.preventDefault();invoke('answer',{questionId:room.question!.id,answer});}}><label>Your answer<input key={room.question.id} autoComplete="off" name="answer" inputMode="text" placeholder="Number, decimal, or fraction" maxLength={100} required onChange={e=>setAnswer(e.target.value)}/></label><button className="portal-primary" disabled={unavailable}>Send answer</button></form>)}
        {room.phase==='question'&&host&&<button className="portal-primary" disabled={unavailable} onClick={()=>invoke('next')}>Close answers & review</button>}
        {room.phase==='review'&&!host&&<p>Your teacher is reviewing. Get ready to explore the answer together.</p>}
        {room.phase==='review'&&host&&<><h3>Answer: {room.question.answer}</h3><div className="portal-review">{room.members.map(m=>{const a=room.question?.answers?.[m.id];return <div key={m.id}><strong>{m.alias}</strong><span>{a?.text??'No answer'}</span><button disabled={unavailable} onClick={()=>invoke('override',{memberId:m.id,correct:!a?.correct})}>{a?.correct?'✓ Correct':'Mark correct'}{a?.overridden?' · adjusted':''}</button></div>;})}</div><button className="portal-primary" disabled={unavailable} onClick={()=>invoke('next')}>Reveal explanation & award charges</button></>}
        {room.phase==='reveal'&&<><strong className="portal-solution">{room.question.answer}</strong><ol className="portal-explanation">{room.question.explanation?.map((line,i)=><li key={i}>{line}</li>)}</ol><p>Charge earned when at least half the team answered correctly, rounded up.</p>{host&&<button className="portal-primary" disabled={unavailable} onClick={()=>invoke('next')}>{room.questionNumber<room.settings.questions?'Next math question':'Open the portal board'}</button>}</>}
      </section>}
      {['board','spinning','result'].includes(room.phase)&&<><div className="portal-turn"><h2>{emptyBoard?'The portal is recharging.':`${room.teams[room.active].name}, your portal awaits.`}</h2><p>{leader?`${leader.alias} is captain this turn. `:''}{room.phase==='spinning'?'Press STOP! Automatic stop after 15 seconds.':'Captains rotate after every spin.'}</p></div><Board room={room}/>
        {room.phase==='result'&&result&&<div key={result.at} className={`portal-result ${TILES[result.tile]===0?'portal-rift-event':'portal-win-event'}`} role="status"><span className="portal-event-icon" aria-hidden="true">{TILES[result.tile]===0?'🌀':'✦'}</span><h2>{TILES[result.tile]===0?['A portal sneeze!','The vines got curious!','A rift borrowed your sparkle!'][result.tile%3]:'A burst of festival magic!'}</h2><p>{room.teams[result.team].name}: {result.delta>0?'+':''}{result.delta} festival points</p><small>{TILES[result.tile]===0?'Shake it off. Your pet is safe, and you’re still in!':'Your math charged this moment.'}</small>{host&&<button className="portal-primary" disabled={unavailable} onClick={()=>invoke('next')}>Continue festival</button>}</div>}
        <div className="portal-spin-controls">{controls&&room.phase==='board'&&!emptyBoard&&<><button className="portal-primary" disabled={unavailable} onClick={()=>invoke('spin')}>Spin the portal ✦</button>{room.teams[room.active].passed===0&&room.teams[room.active].earned>0&&room.teams.map((t,i)=>i!==room.active&&room.members.some(m=>m.team===i)?<button key={i} disabled={unavailable} onClick={()=>invoke('pass',{team:i})}>Pass to {t.name}</button>:null)}</>}{controls&&room.phase==='spinning'&&<button className="portal-stop" disabled={unavailable} onClick={()=>invoke('stop')}>STOP!</button>}{host&&room.phase==='board'&&emptyBoard&&<button className="portal-primary" disabled={unavailable} onClick={()=>invoke('next')}>{room.round<room.settings.rounds?'Start next round':'Show festival results'}</button>}</div>
      </>}
      {room.phase==='finished'&&<section className="portal-finale portal-panel"><p className="portal-eyebrow">The woodland is glowing</p><h2>{room.teams.filter(t=>t.score===Math.max(...room.teams.map(t=>t.score))).map(t=>t.name).join(' & ')} {room.teams.filter(t=>t.score===Math.max(...room.teams.map(t=>t.score))).length>1?'share the festival crown!':'takes the festival crown!'}</h2><p>Every answer helped power the portal. Thanks for playing together.</p>{host&&<><p>{room.history.filter(h=>h.correct).length} correct / {room.history.length} recorded math responses. Festival points include chance; they are not math grades.</p><button className="portal-primary" onClick={()=>setNewGame(true)}>Set up another festival</button></>}</section>}
      {host&&room.phase!=='lobby'&&room.phase!=='finished'&&<details className="portal-adjust"><summary>Teacher score adjustments</summary>{room.teams.map((t,i)=><div key={i}><strong>{t.name} </strong><button disabled={unavailable} onClick={()=>invoke('score',{team:i,amount:-100})}>−100</button><button disabled={unavailable} onClick={()=>invoke('score',{team:i,amount:100})}>+100</button></div>)}</details>}
    </>}
    <footer className="portal-footer">Pip’s Portal Party · Powered by your thinking · Teacher-led classroom play{host&&<p>Festival rooms last 12 hours. Download math results before your session expires.</p>}</footer>
  </div>;
}
export function PortalEntry(){
  const projector=new URLSearchParams(location.search).has('portalProjector');
  const [seat,setSeat]=useState<Seat|undefined>(()=>{if(projector){const [id,token]=location.hash.slice(1).split('.');return id&&token?{id,token}:undefined;}try{const code=new URLSearchParams(location.search).get('portal')??'';const saved=JSON.parse(sessionStorage.getItem(`vpet-portal-seat:${code}`)??'null');return saved?.id&&saved?.token?saved:undefined;}catch{return undefined;}});
  const [code,setCode]=useState(new URLSearchParams(location.search).get('portal')??''),[alias,setAlias]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(projector&&!seat)return <main className="portal portal-public"><Banner/><p className="portal-error">Open the complete projector link from your teacher dashboard.</p></main>;
  if(seat)return <main className="portal-public"><Festival mode={projector?'projector':'student'} seat={seat} onLeave={projector?undefined:()=>{location.assign('/');}}/></main>;
  return <main className="portal portal-public"><Banner/><div className="portal-join-layout"><section className="portal-join portal-panel"><p className="portal-eyebrow">Your classroom adventure</p><h2>Step through the portal.</h2><p>Use the festival code on your teacher’s screen.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const next=await publicAPI<Seat>('join',undefined,{code,alias});try{sessionStorage.setItem(`vpet-portal-seat:${code}`,JSON.stringify(next));}catch{ /* Seat remains usable in this tab. */ }setSeat(next);}catch(e){setError(e instanceof Error?e.message:'Try joining again.');}finally{setBusy(false);}}}><label>Festival code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="off" required pattern="[0-9]{6}"/></label><label>Nickname<input value={alias} onChange={e=>setAlias(e.target.value)} autoComplete="off" required minLength={2} maxLength={20} placeholder="Use your classroom nickname"/></label><button className="portal-primary" disabled={busy}>{busy?'Opening your seat…':'Join the festival'}</button><p role="alert">{error}</p></form><p>Keep this tab open. Refreshing returns you to your seat. No pet login is needed for this session.</p></section><aside className="portal-welcome-art"><div className="portal-ring"/><img src="/assets/companions-v1/ember_fox-baby-portrait.png" alt="Ember welcomes your team"/><h2>Big thinking.<br/>Little companions.<br/>A little woodland luck.</h2></aside></div></main>;
}
