import { test, expect, type Page } from '@playwright/test';
import { createTestEngineState } from '../src/engine/state/createTestEngineState';
import { computeChecksum } from '../src/services/persistence/saveValidation';
import { FURNITURE } from '../src/features/home-base/catalog';
import { CURRENT_SAVE_VERSION } from '../src/services/persistence/saveMigrations';
async function seed(page: Page) {
  const state = createTestEngineState(); state.mode = 'normal'; state.test = { active: false, label: '' }; state.screen = 'home'; state.devPreview = false; state.egg = null;
  state.player.currencies.tokens = 200; state.player.hasOnboarded = true; state.showDailyRitual = false; state.showOnboarding = false; state.notifications = [];
  await page.addInitScript(value => { if (!localStorage.getItem('vpet_save_auto')) localStorage.setItem('vpet_save_auto', value); }, JSON.stringify({ state, version: CURRENT_SAVE_VERSION, timestamp: Date.now(), checksum: computeChecksum(state) }));
  await page.goto('/'); await page.getByRole('button', { name: 'Build home', exact: true }).click();
  await page.getByRole('button', {name:'Decorate',exact:true}).click();
  await expect(page.getByRole('main', { name: 'Home Base' })).toBeVisible();
  await page.getByRole('button', { name: '✎ Build', exact: true }).click();
}
const saved = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('vpet_save_auto')!).state);
test('full-size home: build, move by pointer and keyboard, turn, store, undo, decorate and reload', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await seed(page);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  expect((await page.getByRole('group', { name: 'Room floor' }).boundingBox())!.width).toBeGreaterThan(600);
  const chair = page.locator('.hb-catalog article').filter({ has: page.getByRole('heading', { name: 'Woodland chair', exact: true }) });
  await chair.getByRole('button', { name: 'Place', exact: true }).click();
  await page.getByRole('button', { name: 'Floor tile 1, 6', exact: true }).click();
  let placed = page.getByRole('button', { name: 'Woodland chair, placed at 1, 6', exact: true });
  await expect(placed).toBeVisible(); await placed.click(); await placed.press('ArrowRight');
  placed = page.getByRole('button', { name: 'Woodland chair, placed at 2, 6', exact: true });
  await expect(placed).toBeVisible();
  const box = (await placed.boundingBox())!, floor = (await page.getByRole('group', { name: 'Room floor' }).boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down();
  await page.mouse.move(floor.x + floor.width * 3.5 / 8, floor.y + floor.height * 5.5 / 6, { steps: 8 }); await page.mouse.up();
  await expect(page.getByRole('button', { name: 'Woodland chair, placed at 4, 6', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Turn', exact: true }).click();
  await page.getByRole('button', { name: 'Put away', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Woodland chair, placed at 4, 6', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '↶ Undo', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Woodland chair, placed at 4, 6', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Walls & floors', exact: true }).click();
  await page.getByRole('button', { name: 'Seaside stripes', exact: true }).click();
  await page.getByRole('button', { name: 'Pale birch', exact: true }).click();
  await page.getByRole('button', { name: '☾ Evening', exact: true }).click();
  await expect.poll(async () => (await saved(page)).homeBase.rooms.den.wall).toBe('blue');
  const before = (await saved(page)).homeBase;
  await page.reload(); await expect(page.getByRole('main', { name: 'Home Base' })).toBeVisible();
  expect((await saved(page)).homeBase).toEqual(before);
  await page.getByRole('button', { name: '☀ Daylight', exact: true }).click();
  await page.screenshot({ path: 'docs/verification/home-base-desktop.png' });
  expect(errors).toEqual([]);
});
test('room upgrades, furnishing ownership and live-in interactions persist independently', async ({ page }) => {
  await seed(page);
  const startingTokens = (await saved(page)).player.currencies.tokens;
  await page.getByRole('button', { name: 'My rooms', exact: true }).click();
  const dream = page.locator('.hb-rooms article').filter({ hasText: 'Dream room' });
  await dream.getByRole('button').click();
  await expect(page.locator('.hb-room-heading h2')).toHaveText('Dream room');
  await page.getByRole('button', { name: 'Expand · 40 tokens', exact: true }).click();
  await expect(page.locator('.hb-room-heading')).toContainText('10 × 7');
  await page.getByRole('button', { name: 'Furniture', exact: true }).click();
  const lamp = page.locator('.hb-catalog article').filter({ has: page.getByRole('heading', { name: 'Reading light', exact: true }) });
  await lamp.getByRole('button').click(); await lamp.getByRole('button', { name: 'Place', exact: true }).click();
  await page.getByRole('button', { name: 'Floor tile 1, 2', exact: true }).click();
  await page.getByRole('button', { name: '♡ Live here', exact: true }).click();
  const light = page.getByRole('button', { name: 'Reading light, placed at 1, 2', exact: true });
  await light.click(); await expect(light).not.toHaveClass(/is-lit/);
  await page.locator('.hb-room-links button').filter({ hasText: 'Cozy den' }).click();
  await page.getByRole('button', { name: 'Little nest cushion, placed at 1, 2', exact: true }).click();
  await expect(page.locator('.hb-pet-bubble')).toContainText('nap');
  await page.locator('.hb-room-links button').filter({ hasText: 'Dream room' }).click();
  expect((await saved(page)).player.currencies.tokens).toBe(startingTokens - 90);
  await expect(page.locator('.hb-room-heading h2')).toHaveText('Dream room', {timeout:15000});
  await page.reload(); await expect(page.locator('.hb-room-heading h2')).toHaveText('Dream room');
  expect((await saved(page)).homeBase.rooms.bedroom.items[0].on).toBe(false);
});
test('phone builder fits, offers touch placement, and every furniture sprite loads', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await seed(page);
  const chair = page.locator('.hb-catalog article').filter({ has: page.getByRole('heading', { name: 'Woodland chair', exact: true }) });
  await chair.getByRole('button', { name: 'Place', exact: true }).click();
  await page.getByRole('button', { name: 'Floor tile 1, 6', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Woodland chair, placed at 1, 6', exact: true })).toBeVisible();
  const images = page.locator('.hb-catalog-art img');
  await expect(images).toHaveCount(36);
  expect(await images.evaluateAll(nodes => nodes.every(n => (n as HTMLImageElement).complete && (n as HTMLImageElement).naturalWidth > 0))).toBe(true);
  expect(await page.locator('.home-base').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.locator('.home-base').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: 'docs/verification/home-base-phone.png' });
  await page.getByRole('button', { name: 'Walls & floors', exact: true }).click();
  await page.getByRole('button', { name: 'Rosebud', exact: true }).click();
  await page.reload(); await expect(page.locator('.hb-back-wall')).toHaveClass(/pattern-rose/);
});


test('242 furniture designs browse by collection; individual colors and touch nudges survive reload', async ({ page, request }) => {
  await seed(page);
  expect(FURNITURE).toHaveLength(242);
  for (let i=0;i<FURNITURE.length;i+=24) await Promise.all(FURNITURE.slice(i,i+24).map(async f=>expect((await request.get(f.art)).ok(),f.art).toBe(true)));
  await page.getByLabel('Collection', {exact:true}).selectOption('Starlight');
  await expect(page.locator('.hb-catalog article')).toHaveCount(24);
  const chair = page.locator('.hb-catalog article').filter({has:page.getByRole('heading',{name:'Starlight armchair',exact:true})});
  await chair.getByRole('button').click();
  await chair.getByRole('button',{name:'Place',exact:true}).click();
  await page.getByRole('button',{name:'Floor tile 1, 6',exact:true}).click();
  await page.getByRole('button',{name:'Starlight armchair, placed at 1, 6',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Rose finish',exact:true}).click();
  await page.getByRole('button',{name:'Move →',exact:true}).click();
  await expect(page.getByRole('button',{name:'Starlight armchair, placed at 2, 6',exact:true})).toBeVisible();
  await expect.poll(async () => (await saved(page)).homeBase.rooms.den.items.at(-1).finish).toBe('rose');
  expect(await page.locator('.home-base').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  await page.screenshot({path:'docs/verification/home-collections-phone.png'});
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('.home-base').evaluate(el=>{el.scrollTop=0;});
  await page.screenshot({path:'docs/verification/home-collections-desktop.png'});
  await page.reload();
  await expect(page.getByRole('button',{name:'Starlight armchair, placed at 2, 6',exact:true})).toBeVisible();
  expect((await saved(page)).homeBase.rooms.den.items.at(-1).finish).toBe('rose');
});

test('pet roams, dances, accepts cuddles, and fetches a thrown ball back to its starting spot', async ({ page }) => {
  await page.setViewportSize({width:1440,height:1100}); await seed(page);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.getByRole('button',{name:'♡ Live here',exact:true}).click();
  await expect(page.getByLabel('Design desk',{exact:true})).toHaveCount(0);
  const resident=page.locator('.hb-resident');
  const start=await resident.getAttribute('data-activity');
  await expect.poll(()=>resident.getAttribute('data-activity'),{timeout:12000}).not.toBe(start);
  await page.getByRole('button',{name:'Pause wandering',exact:true}).click();
  await page.getByRole('button',{name:/Dance Wiggle together/}).click();
  await expect(resident).toHaveClass(/is-dancing/);
  await page.locator('.hb-pet-touch').click();
  await expect(resident).toHaveAttribute('data-activity','Cuddle time');
  await expect(page.locator('.hb-hearts')).toBeVisible();
  const x=await resident.getAttribute('data-x'), y=await resident.getAttribute('data-y');
  await page.getByRole('button',{name:/Play fetch Throw a ball/}).click();
  await page.getByRole('button',{name:'Floor tile 8, 6',exact:true}).click();
  await expect(page.getByLabel('Fetch ball',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Fetch ball',{exact:true})).toHaveCount(0,{timeout:12000});
  await expect(resident).toHaveAttribute('data-x',x!,{timeout:12000});
  await expect(resident).toHaveAttribute('data-y',y!);
  await page.getByRole('button',{name:/Chat Say hello/}).click();
  await page.getByRole('button',{name:'A reading nook',exact:true}).click();
  await expect(page.locator('.hb-pet-bubble')).toContainText('reading nook');
  await page.locator('.home-base').evaluate(el=>{el.scrollTop=0;});
  await page.mouse.move(0,0);
  await page.screenshot({path:'docs/verification/home-life-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  expect(await page.locator('.home-base').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
  await page.locator('.home-base').evaluate(el=>{el.scrollTop=0;});
  await page.screenshot({path:'docs/verification/home-life-phone.png',fullPage:true});
  expect(errors).toEqual([]);
});


test('dashboard and builder share furniture, finishes, surfaces, rooms and reloads', async ({page}) => {
  await page.setViewportSize({width:1440,height:1000});await seed(page);
  await page.getByRole('button',{name:'Little nest cushion, placed at 1, 2',exact:true}).click();
  await page.getByRole('button',{name:'Ocean finish',exact:true}).click();
  await page.getByRole('button',{name:'Turn',exact:true}).click();
  await page.getByRole('button',{name:'Walls & floors',exact:true}).click();
  await page.getByRole('button',{name:'Rosebud',exact:true}).click();
  await page.getByRole('button',{name:'Pale birch',exact:true}).click();
  await page.getByRole('button',{name:'☾ Evening',exact:true}).click();
  const layout=()=>page.locator('.hb-room-floor [data-furniture-id]').evaluateAll(nodes=>nodes.map(n=>({id:n.getAttribute('data-furniture-id'),finish:n.getAttribute('data-finish'),flipped:n.getAttribute('data-flipped'),position:(n.parentElement as HTMLElement).style.cssText})));
  const expected=await layout();
  await page.getByRole('button',{name:'← Back to pet',exact:true}).click();
  const home=page.getByLabel('Your saved home');await expect(home).toBeVisible();
  await expect(home.locator('.hb-dollhouse')).toHaveAttribute('data-home-wall','rose');
  await expect(home.locator('.hb-dollhouse')).toHaveAttribute('data-home-floor','birch');
  await expect(home.locator('.hb-dollhouse')).toHaveClass(/is-evening/);
  expect(await layout()).toEqual(expected);
  await expect(page.locator('#vpet-scene img[src="/assets/woodland-v1/home.png"]')).toHaveCount(0);
  await page.screenshot({path:'docs/verification/shared-home-dashboard.png'});
  await page.reload();await expect(home).toBeVisible();expect(await layout()).toEqual(expected);
  await page.getByRole('navigation',{name:'Rooms'}).getByRole('button',{name:'Yard',exact:true}).click();
  await expect(home).toHaveCount(0);
  await page.getByRole('navigation',{name:'Rooms'}).getByRole('button',{name:'Home',exact:true}).click();
  expect(await layout()).toEqual(expected);
  await page.getByRole('button',{name:'Build home',exact:true}).click();
  await page.getByRole('button',{name:'✎ Build',exact:true}).click();
  await page.getByRole('button',{name:'My rooms',exact:true}).click();
  await page.locator('.hb-rooms article').filter({hasText:'Dream room'}).getByRole('button').click();
  await page.getByRole('button',{name:'← Back to pet',exact:true}).click();
  await expect(home).toHaveAttribute('data-home-room','bedroom');
  await expect(page.locator('.home-heading h1')).toHaveText('Dream room');
  await expect(home.locator('[data-furniture-id]')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  await expect(home).toBeVisible();
  await page.screenshot({path:'docs/verification/shared-home-phone.png'});
});

test('pet memories persist across home views and reload without granting rewards', async ({page}) => {
  await seed(page);
  const before=await saved(page);
  await page.getByRole('button',{name:'♡ Live here',exact:true}).click();
  await page.getByRole('button',{name:'Pause wandering',exact:true}).click();
  await page.getByRole('button',{name:/Dance Wiggle together/}).click();
  await expect.poll(async()=>(await saved(page)).pet.mind?.memories.some((m:{kind:string})=>m.kind==='dance')).toBe(true);
  await page.getByRole('button',{name:'Little nest cushion, placed at 1, 2',exact:true}).click();
  await expect.poll(async()=>(await saved(page)).pet.mind?.objects.length??0,{timeout:12000}).toBeGreaterThan(0);
  const mind=(await saved(page)).pet.mind;
  expect((await saved(page)).player.currencies).toEqual(before.player.currencies);
  await page.getByRole('button',{name:'✎ Build',exact:true}).click();
  const resident=page.locator('.hb-resident'),x=await resident.getAttribute('data-x'),y=await resident.getAttribute('data-y');
  await page.waitForTimeout(1800);
  await expect(resident).toHaveAttribute('data-x',x!);await expect(resident).toHaveAttribute('data-y',y!);
  await page.getByRole('button',{name:'← Back to pet',exact:true}).click();
  await expect(page.locator('.dashboard-pet-thought')).toBeVisible();
  expect((await saved(page)).pet.mind).toEqual(mind);
  await page.reload();await expect(page.getByLabel('Your saved home')).toBeVisible();
  expect((await saved(page)).pet.mind.memories).toEqual(mind.memories);
  await page.screenshot({path:'docs/verification/pet-mind-dashboard.png'});
});

test('completed care drives contextual home dialogue and the developer explanation', async ({page}) => {
  await page.setViewportSize({width:1440,height:1100});await seed(page);
  await page.getByRole('button',{name:'← Back to pet',exact:true}).click();
  await page.getByRole('button',{name:'Care',exact:true}).click();
  await page.getByRole('button',{name:'Start Play',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'Let’s begin'}).click();
  for(let i=0;i<8;i++)await dialog.getByRole('button',{name:'Catch the ball'}).click();
  await dialog.getByRole('button',{name:'Finish care'}).click();
  await expect.poll(async()=>(await saved(page)).pet.mind?.memories.some((m:{kind:string})=>m.kind==='play')).toBe(true);
  await page.getByRole('navigation',{name:'Rooms'}).getByRole('button',{name:'Home',exact:true}).click();
  await expect(page.locator('.dashboard-pet-thought')).toContainText('I enjoyed our playtime!',{timeout:15000});
  await page.locator('.pet-mind-inspector summary').click();
  await expect(page.locator('.pet-mind-inspector')).toContainText('completed play event');
  await page.getByRole('button',{name:'Build home',exact:true}).click();
  await expect(page.locator('.hb-pet-bubble')).toContainText('I enjoyed our playtime!',{timeout:15000});
});

test('pet helps decorate, then sits and lies on the actual furniture', async ({page})=>{
  await page.setViewportSize({width:1440,height:1100});await seed(page);
  const chair=page.locator('.hb-catalog article').filter({has:page.getByRole('heading',{name:'Woodland chair',exact:true})});
  await chair.getByRole('button',{name:'Place',exact:true}).click();
  await page.getByRole('button',{name:'Floor tile 1, 6',exact:true}).click();
  const resident=page.locator('.hb-resident');
  await expect(resident).toHaveAttribute('data-work-phase','approach');
  await expect(resident).toHaveAttribute('data-work-phase','carry',{timeout:12000});
  const delivery=page.locator('.hb-furniture-delivery');
  await expect(delivery).toBeVisible();
  const deliveryX=await delivery.getAttribute('data-delivery-x'),deliveryY=await delivery.getAttribute('data-delivery-y');
  await expect.poll(async()=>[await delivery.getAttribute('data-delivery-x'),await delivery.getAttribute('data-delivery-y')].join(',')).not.toBe(`${deliveryX},${deliveryY}`);
  await page.screenshot({path:'docs/verification/pet-carrying-delivery.png'});
  await expect(resident).toHaveAttribute('data-work-phase','push',{timeout:12000});
  await expect(page.locator('[data-pet-work="push"]')).toHaveCount(1);
  await page.waitForTimeout(700);
  await page.screenshot({path:'docs/verification/pet-pushing-furniture.png'});
  await expect(resident).toHaveAttribute('data-work-phase','celebrate');
  await expect(resident).not.toHaveAttribute('data-work-phase',/./,{timeout:6000});
  await page.getByRole('button',{name:'♡ Live here',exact:true}).click();
  await page.getByRole('button',{name:'Pause wandering',exact:true}).click();
  await page.getByRole('button',{name:'Woodland chair, placed at 1, 6',exact:true}).click();
  await expect(resident).toHaveAttribute('data-pose','sitting',{timeout:10000});
  await page.getByRole('button',{name:'Little nest cushion, placed at 1, 2',exact:true}).click();
  await expect(resident).toHaveAttribute('data-pose','lying',{timeout:10000});
  await page.waitForTimeout(500);
  await page.screenshot({path:'docs/verification/pet-resting-on-cushion.png'});
  const layout=(await saved(page)).homeBase;
  await page.reload();expect((await saved(page)).homeBase).toEqual(layout);
});

test('removing a helper item cancels work; reduced motion saves without a push',async({page})=>{
  await seed(page);
  const chair=page.locator('.hb-catalog article').filter({has:page.getByRole('heading',{name:'Woodland chair',exact:true})});
  await chair.getByRole('button',{name:'Place',exact:true}).click();
  await page.getByRole('button',{name:'Floor tile 1, 6',exact:true}).click();
  await expect(page.locator('.hb-resident')).toHaveAttribute('data-work-phase','approach');
  await page.getByRole('button',{name:'Woodland chair, placed at 1, 6',exact:true}).click();
  await page.getByRole('button',{name:'Put away',exact:true}).click();
  await expect(page.locator('.hb-resident')).not.toHaveAttribute('data-work-phase',/./);
  await page.emulateMedia({reducedMotion:'reduce'});
  await chair.getByRole('button',{name:'Place',exact:true}).click();
  await page.getByRole('button',{name:'Floor tile 1, 6',exact:true}).click();
  await page.waitForTimeout(1000);
  await expect(page.locator('.hb-resident')).not.toHaveAttribute('data-work-phase',/./);
  await expect(page.getByRole('button',{name:'Woodland chair, placed at 1, 6',exact:true})).toBeVisible();
});

test('pet takes a shelf book, turns pages and returns it; house overview opens rooms',async({page})=>{
  await page.setViewportSize({width:1440,height:1100});await seed(page);
  await expect(page.getByRole('region',{name:'Your two-story house'}).locator('.cottage-room')).toHaveCount(8);
  await page.getByPlaceholder('Search pieces or collections…').fill('Storykeeper shelf');
  const shelf=page.locator('.hb-catalog article');await shelf.getByRole('button').click();
  await shelf.getByRole('button',{name:'Place',exact:true}).click();
  await page.getByRole('button',{name:'Floor tile 6, 1',exact:true}).click();
  await page.getByRole('button',{name:'♡ Live here',exact:true}).click();
  await page.getByRole('button',{name:'Pause wandering',exact:true}).click();
  await page.getByRole('button',{name:'Storykeeper shelf, placed at 6, 1',exact:true}).click();
  await expect(page.locator('.hb-book-prop')).toHaveAttribute('data-book-phase','take',{timeout:12000});
  await expect(page.locator('.hb-book-prop')).toHaveAttribute('data-book-phase','read');
  await page.screenshot({path:'docs/verification/pet-reading-book.png'});
  await expect(page.locator('.hb-book-prop')).toHaveAttribute('data-book-phase','return',{timeout:10000});
  await expect(page.locator('.hb-book-prop')).toHaveCount(0);
  await page.getByRole('button',{name:'Add Dream room for 35 tokens',exact:true}).click();
  await expect(page.locator('.hb-room-heading h2')).toHaveText('Dream room');
  await page.getByRole('button',{name:'Visit Cozy den',exact:true}).click();
  await expect(page.getByRole('button',{name:'Storykeeper shelf, placed at 6, 1',exact:true})).toBeVisible({timeout:15000});
  await page.getByRole('button',{name:'Bigger room view',exact:true}).click();
  await expect(page.getByRole('complementary',{name:'At home'})).toBeHidden();
  await page.screenshot({path:'docs/verification/large-home-and-rooms.png'});
});

test('walking stays animated through the final step and turns without mirroring dialogue',async({page})=>{
 await page.setViewportSize({width:1440,height:1100});await seed(page);
 await page.getByRole('button',{name:'♡ Live here',exact:true}).click();
 await page.getByRole('button',{name:'Pause wandering',exact:true}).click();
 const pet=page.locator('.hb-resident');
 // Observe arrival in the browser: sequential polling can miss the brief final step.
 await pet.evaluate(el=>{
  const observer=new MutationObserver(()=>{
   if(el.getAttribute('data-x')==='7'&&el.getAttribute('data-y')==='5'){
    observer.disconnect();el.setAttribute('data-final-step-walking',String(el.classList.contains('is-walking')));
   }
  });
  observer.observe(el,{attributes:true,attributeFilter:['data-x','data-y','class']});
 });
 await page.getByRole('button',{name:'Floor tile 8, 6',exact:true}).click();
 await expect(pet).toHaveAttribute('data-final-step-walking','true',{timeout:10000});
 await expect(pet).not.toHaveClass(/is-walking/);
 await page.getByRole('button',{name:'Floor tile 1, 6',exact:true}).click();
 await expect(pet).toHaveAttribute('data-facing','left');
 await expect(pet.locator('.hb-facing-left')).toHaveCount(1);
 expect(await pet.locator('.hb-pet-bubble').evaluate(el=>getComputedStyle(el).scale)).not.toBe('-1 1');
 await expect(pet).toHaveAttribute('data-x','0',{timeout:10000});
 await expect(pet).not.toHaveClass(/is-walking/);
 await page.locator('.home-base').evaluate(el=>{el.scrollTop=0;});
 await page.screenshot({path:'docs/verification/premium-home-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.locator('.home-base').evaluate(el=>{el.scrollTop=0;});
 expect(await page.locator('.home-base').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);
 const bubble=await pet.locator('.hb-pet-bubble').boundingBox();
 expect(bubble).not.toBeNull();
 expect(bubble!.x).toBeGreaterThanOrEqual(0);
 expect(bubble!.x+bubble!.width).toBeLessThanOrEqual(390);
 await page.screenshot({path:'docs/verification/premium-home-phone.png'});
});
