import {test,expect} from '@playwright/test';
test('view and pet are independent; invitations take real paths, survive reload, and preserve the old layout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:960});await page.goto('/e2e/living-house-fixture.html');await expect(page.getByTestId('living-house')).toBeVisible();const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('house-test')!));
 const nav=page.getByRole('navigation',{name:'Look into a room'});await nav.getByRole('button',{name:/Kitchen/}).click();await expect(page.getByTestId('house-resident')).toHaveAttribute('data-room','den');await page.getByRole('button',{name:/Come here,/}).click();await expect(page.getByTestId('resident-status')).toContainText('Coming');await expect(page.getByTestId('resident-status')).toContainText('Keeping you company',{timeout:30000});await expect(page.getByTestId('house-resident')).toHaveAttribute('data-room','kitchen');
 await nav.getByRole('button',{name:/Upstairs nook/}).click();await page.getByRole('button',{name:/Come here,/}).click();await page.waitForTimeout(1200);await page.reload();await expect(page.getByTestId('resident-status')).toContainText('Keeping you company',{timeout:30000});await expect(page.getByTestId('house-resident')).toHaveAttribute('data-room','landing');const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('house-test')!));expect(after.homeBase.rooms.den).toEqual(before.homeBase.rooms.den);expect(after.player.currencies).toEqual(before.player.currencies);expect(errors).toEqual([]);
});
test('phone: inspect furniture, invite, feed, decorate and return without relocating the pet',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/e2e/living-house-fixture.html');const nav=page.getByRole('navigation',{name:'Look into a room'});await nav.getByRole('button',{name:/Kitchen/}).click();await page.locator('.lh-nearby summary').click();await page.locator('.lh-nearby').getByRole('button',{name:'Cottage kitchen counter'}).click();await page.getByRole('button',{name:/Ask .* to check it out/}).click();await expect(page.getByTestId('resident-status')).toContainText('Waiting by the kitchen counter',{timeout:30000});await page.getByRole('button',{name:'Prepare a snack',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Decorate',exact:true}).click();await expect(page.locator('.home-base')).toBeVisible();await page.getByRole('button',{name:/Return to the living house/}).click();await expect(page.getByTestId('house-resident')).toHaveAttribute('data-room','kitchen');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.lh-viewport')).toHaveAttribute('data-reduced-motion','true');
});
