import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const pics='/home/dre/Pictures/V-Pet-Math-Stack-2026-09-27';mkdirSync(pics,{recursive:true});
test('Grade 1 and Kindergarten are playable, save and award verified rows',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1366,height:1000});await page.goto('/e2e/math-stack-fixture.html');await page.getByRole('button',{name:'Start with Grade 1',exact:true}).click();await expect(page.getByLabel('Math trail')).toHaveValue('add');await page.getByRole('button',{name:'Start with Kindergarten',exact:true}).click();await page.getByRole('button',{name:'Advanced: row puzzles',exact:false}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();await page.getByRole('group',{name:'Block value'}).getByRole('button',{name:'1',exact:true}).click();await page.getByRole('button',{name:'Move left',exact:true}).click({clickCount:2});await page.getByRole('button',{name:'Drop ↓',exact:true}).click();await expect(page.locator('.ms-cell.locked')).toHaveCount(4);await page.reload();await page.getByRole('button',{name:'Return to saved board',exact:true}).click();await expect(page.locator('.ms-cell.locked')).toHaveCount(4);await page.getByRole('group',{name:'Block value'}).getByRole('button',{name:'1',exact:true}).click();await page.getByRole('button',{name:'Move right',exact:true}).click({clickCount:2});await page.getByRole('button',{name:'Drop ↓',exact:true}).click();await expect(page.locator('.ms-stats')).toContainText('1/5');const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('stack-fixture')!));expect(s.learningEvidence.at(-1).correct).toBe(true);expect(s.learningEvidence.at(-1).grade).toBe(0);await page.screenshot({path:`pics/kindergarten.png`.replace('pics/',pics+'/'),fullPage:true});expect(errors).toEqual([]);
});
test('Grade 9 example is playable and recorded as supported practice',async({page})=>{await page.setViewportSize({width:1366,height:1000});await page.goto('/e2e/math-stack-fixture.html');await page.getByLabel('Math trail').selectOption('factor');await page.getByRole('button',{name:'Advanced: row puzzles',exact:false}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();await page.screenshot({path:`${pics}/algebra.png`,fullPage:true});await page.getByRole('button',{name:'▶ Watch an example',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Pause example',exact:true}).click();for(let i=0;i<3;i++)await page.getByRole('button',{name:'Next step',exact:true}).click();await expect(page.locator('.ms-example-row')).toHaveClass(/solved/);await page.screenshot({path:`${pics}/worked-example.png`,fullPage:true});expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('stack-fixture')!).learningEvidence.at(-1).answerRevealed)).toBe(true);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('phone controls and reduced motion work without horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/e2e/math-stack-fixture.html');await page.getByLabel('Math trail').selectOption('fraction');await page.getByRole('button',{name:'Advanced: row puzzles',exact:false}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'↻ Rotate',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();await expect(page.getByRole('button',{name:'Drop ↓',exact:true})).toBeDisabled();await page.screenshot({path:`${pics}/phone.png`,fullPage:true});});
test('arcade gravity advances and pause stops it',async({page})=>{await page.clock.install();await page.goto('/e2e/math-stack-fixture.html');await page.getByRole('button',{name:/Advanced: timed row puzzles/}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();const before=await page.locator('.ms-cell.falling').first().getAttribute('aria-label');await page.clock.runFor(2000);const after=await page.locator('.ms-cell.falling').first().getAttribute('aria-label');expect(after).not.toBe(before);await page.getByRole('button',{name:'Pause',exact:true}).click();const paused=await page.locator('.ms-cell.falling').first().getAttribute('aria-label');await page.clock.runFor(10000);expect(await page.locator('.ms-cell.falling').first().getAttribute('aria-label')).toBe(paused);});
