import {test,expect,type Page} from '@playwright/test';
import {findChain} from '../src/features/math-pop/game';
import {mkdirSync} from 'node:fs';
const pics='/home/dre/Pictures/V-Pet-Math-Pop-2026-09-27';mkdirSync(pics,{recursive:true});
async function begin(page:Page,skill='add'){await page.goto('/e2e/math-pop-fixture.html');await page.getByLabel('Choose your math').selectOption(skill);await page.getByRole('button',{name:'Play first puzzle →',exact:true}).click();}
async function drag(page:Page,path:number[]){const cells=page.locator('[data-pop-index]');const a=await cells.nth(path[0]).boundingBox();await page.mouse.move(a!.x+a!.width/2,a!.y+a!.height/2);await page.mouse.down();for(const i of path.slice(1)){const b=await cells.nth(i).boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2,{steps:8});}await page.mouse.up();}
test('drag a pair, pop a longer chain, keep progress after reload and win a level',async({page})=>{await page.setViewportSize({width:1366,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await begin(page);await drag(page,[0,1]);await expect(page.locator('.pop-objective')).toContainText('1/3');await drag(page,[6,7,8]);await expect(page.locator('.pop-objective')).toContainText('2/3');await expect(page.locator('.pop-tile.rocket')).toHaveCount(1);await page.screenshot({path:`${pics}/grade-1.png`,fullPage:true});await page.reload();await expect(page.locator('.pop-objective')).toContainText('2/3');const run=await page.evaluate(()=>JSON.parse(localStorage.getItem('pop-fixture')!).mathPop.run);await drag(page,findChain(run));await expect(page.getByRole('heading',{name:'Beautiful connections!'})).toBeVisible();await page.getByRole('button',{name:'Next puzzle →',exact:true}).click();await expect(page.locator('.pop-tile.iced')).toHaveCount(6);await page.screenshot({path:`${pics}/ice-level.png`,fullPage:true});expect(errors).toEqual([]);});
test('wrong math is safe, keyboard selection works and hints are recorded',async({page})=>{await begin(page);const a=page.locator('[data-pop-index="1"]'),b=page.locator('[data-pop-index="2"]');await a.focus();await page.keyboard.press('Enter');await b.focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Pop chain ✦',exact:true}).click();await expect(page.locator('.pop-companion')).toContainText('No move lost');await expect(page.locator('.pop-run-top')).toContainText('6 moves');await page.getByRole('button',{name:'Show a connection',exact:true}).click();await expect(page.locator('.pop-tile.hint').first()).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('pop-fixture')!).learningEvidence.at(-1).answerRevealed)).toBe(true);});
test('phone tapping, counting dots and reduced motion work without overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await begin(page,'count');await expect(page.locator('.pop-dots').first()).toBeVisible();for(const i of [0,1,2])await page.locator(`[data-pop-index="${i}"]`).tap();await expect(page.locator('.pop-calculation')).toContainText('Ready to pop');await page.getByRole('button',{name:'Pop chain ✦',exact:true}).tap();await expect(page.locator('.pop-objective')).toContainText('1/3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${pics}/phone-counting.png`,fullPage:true});});
test('Grade 9 factor chains and help dialog are playable',async({page})=>{await begin(page,'factor');await drag(page,[0,1]);await expect(page.locator('.pop-objective')).toContainText('1/3');await page.getByRole('button',{name:'How to play',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.screenshot({path:`${pics}/grade-9.png`,fullPage:true});});
test('intro ice and star puzzles can be completed through the actual controls',async({page})=>{await page.setViewportSize({width:1366,height:900});await begin(page);for(let n=0;n<3;n++){const r=await page.evaluate(()=>JSON.parse(localStorage.getItem('pop-fixture')!).mathPop.run);await drag(page,findChain(r));await expect(page.locator('.pop-run-top')).toContainText(`${6-n-1} moves`);}await page.getByRole('button',{name:'Next puzzle →',exact:true}).click();for(const path of [[0,1,2],[6,7,8],[12,13,14]]){await drag(page,path);await page.waitForTimeout(300);}await expect(page.getByRole('heading',{name:'Beautiful connections!'})).toBeVisible();await page.getByRole('button',{name:'Next puzzle →',exact:true}).click();await expect(page.locator('.pop-tile.star')).toHaveCount(1);await page.screenshot({path:`pics/star-level.png`.replace('pics/',pics+'/'),fullPage:true});for(let n=0;n<3;n++){await drag(page,[33,34,35]);await page.waitForTimeout(300);}await expect(page.getByRole('heading',{name:'Beautiful connections!'})).toBeVisible();await page.screenshot({path:`${pics}/victory.png`,fullPage:true});});
