import {test,expect} from '@playwright/test';
import {answerChoices} from '../src/features/math-stack/game';
import {mkdirSync} from 'node:fs';
const pics='/home/dre/Pictures/V-Pet-Math-Stack-Upgrade-2026-09-27';mkdirSync(pics,{recursive:true});
test('simple mode teaches, rejects wrong answers, saves the stack and rewards correct answers',async({page})=>{
 await page.setViewportSize({width:1366,height:768});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/e2e/math-stack-fixture.html');await page.getByRole('button',{name:'Start with Grade 1',exact:true}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();await expect(page.getByTestId('flow-game')).toBeVisible();await expect(page.getByRole('button',{name:'Drop ↓',exact:true})).toBeDisabled();
 const run=await page.evaluate(()=>JSON.parse(localStorage.getItem('stack-fixture')!).mathStack.run),choices=answerChoices(run);
 await page.getByRole('group',{name:'Answer pieces'}).getByRole('button').nth(choices.findIndex(c=>!c.correct)).click();await page.getByRole('button',{name:'Drop ↓',exact:true}).click();await expect(page.locator('.flow-try')).toBeVisible();await expect(page.locator('.flow-cell.solid')).toHaveCount(0);
 await page.getByRole('group',{name:'Answer pieces'}).getByRole('button').nth(choices.findIndex(c=>c.correct)).click();await page.getByRole('button',{name:'Move left',exact:true}).click({clickCount:2});await page.getByRole('button',{name:'Drop ↓',exact:true}).click();await expect(page.locator('.flow-cell.solid')).toHaveCount(4);await expect(page.locator('.flow-progress .done')).toHaveCount(1);
 await page.reload();await expect(page.locator('.flow-cell.solid')).toHaveCount(4);await expect(page.locator('.flow-question')).toContainText('QUESTION 2 OF 12');await page.screenshot({path:`${pics}/grade-1.png`,fullPage:true});expect(errors).toEqual([]);
});
test('counting and mobile controls are clear and fit a small screen',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/e2e/math-stack-fixture.html');await page.getByRole('button',{name:'Start with Kindergarten',exact:true}).click();await page.getByRole('button',{name:'Start stacking →',exact:true}).click();await expect(page.locator('.flow-count')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('group',{name:'Answer pieces'}).getByRole('button').first().click();await page.getByRole('button',{name:'↻ Rotate',exact:true}).click();await expect(page.locator('.flow-cell.outline')).toHaveCount(4);await page.screenshot({path:`${pics}/phone.png`,fullPage:true});
});
test('Grade 9 answer pieces and how-to remain accessible',async({page})=>{await page.goto('/e2e/math-stack-fixture.html');await page.getByLabel('Math trail').selectOption('factor');await page.getByRole('button',{name:'Start stacking →',exact:true}).click();await expect(page.locator('.flow-question')).toContainText('Factor');await expect(page.locator('.flow-answers')).toContainText('(x +');await page.getByRole('button',{name:'How to play',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Three steps');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
