import {test,expect,request} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {signInLink} from '../src/pilot/signInLinks';
const base='http://127.0.0.1:8797';
test('classroom launcher, authoritative pops, duplicate receipts, reload and locked progress',async({page})=>{
 const teachers=JSON.parse(readFileSync('.pilot-private/test-teachers.json','utf8'));const teacher=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}}),student=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}});
 try{await teacher.post('/api/pilot/login',{data:{role:'teacher',code:teachers[0].code}});await teacher.post('/api/pilot/quick-checks/policy',{data:{cadence:'teacher'}});const cards=await(await teacher.post('/api/pilot/teacher/students',{data:{count:1}})).json();await student.post('/api/pilot/login',{data:{role:'student',code:cards.cards[0].code,classCode:cards.classCode}});
 const get=async()=>await(await student.get('/api/pilot/save')).json();async function command(c:unknown){const save=await get(),body={revision:save.revision,requestId:crypto.randomUUID(),command:c};const response=await student.post('/api/pilot/math-pop-command',{data:body});expect(response.status(),await response.text()).toBe(200);return body;}
 const before=(await get()).state.player.currencies.mp;await command({kind:'start',trail:'add',level:1});const receipt=await command({kind:'chain',revision:0,path:[0,1]});expect((await student.post('/api/pilot/math-pop-command',{data:receipt})).status()).toBe(200);expect((await get()).state.player.currencies.mp).toBe(before+2);
 let save=await get();const forged=structuredClone(save.state);forged.mathPop.run.score=99999;expect((await student.put('/api/pilot/save',{data:{revision:save.revision,requestId:crypto.randomUUID(),state:forged}})).status()).toBe(409);
 expect((await student.post('/api/pilot/math-pop-command',{data:{revision:save.revision,requestId:crypto.randomUUID(),command:{kind:'start',trail:'add',level:99}}})).status()).toBe(409);
 await page.goto(signInLink(base,{role:'student',code:cards.cards[0].code,classCode:cards.classCode}));await page.getByRole('button',{name:'Games',exact:true}).click();await page.locator('.student-card').filter({has:page.getByRole('heading',{name:'Math Pop',exact:true})}).getByRole('button',{name:'Start →',exact:true}).click();await expect(page.getByTestId('math-pop')).toBeVisible();await expect(page.locator('.pop-objective')).toContainText('1/3');
 for(const i of [6,7,8]){await page.locator(`[data-pop-index="${i}"]`).focus();await page.keyboard.press('Enter');}await page.getByRole('button',{name:'Pop chain ✦',exact:true}).click();await expect(page.locator('.pop-objective')).toContainText('2/3');await expect(page.getByTestId('cloud-save-status')).toHaveText('Saved online');await page.reload();await page.getByRole('button',{name:/Continue Math Pop/}).click();await expect(page.locator('.pop-objective')).toContainText('2/3');await page.getByRole('button',{name:'Show a connection',exact:true}).click();await expect(page.locator('.pop-tile.hint').first()).toBeVisible();save=await get();expect(save.state.learningEvidence.at(-1).answerRevealed).toBe(true);
 }finally{await teacher.dispose();await student.dispose();}
});
