import {answerChoices} from '../src/features/math-stack/game';
import {signInLink} from '../src/pilot/signInLinks';
import {test,expect,request} from '@playwright/test';
import {readFileSync} from 'node:fs';
const base='http://127.0.0.1:8797';
test('authoritative placements, exactly-once rewards, protected checkpoints and saved UI',async({page})=>{
 const teachers=JSON.parse(readFileSync('.pilot-private/test-teachers.json','utf8')),t=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await t.post('/api/pilot/login',{data:{role:'teacher',code:teachers[0].code}});await t.post('/api/pilot/quick-checks/policy',{data:{cadence:'teacher'}});const cards=await(await t.post('/api/pilot/teacher/students',{data:{count:1}})).json();const c=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}});try{await c.post('/api/pilot/login',{data:{role:'student',code:cards.cards[0].code,classCode:cards.classCode}});const get=async()=>await(await c.get('/api/pilot/save')).json();let save=await get();const original=save.state.player.currencies.mp;async function command(command:unknown){save=await get();const body={revision:save.revision,requestId:crypto.randomUUID(),command};const r=await c.post('/api/pilot/math-stack-command',{data:body});expect(r.status(),await r.text()).toBe(200);return body;}
 await command({kind:'start',track:'bonds',mode:'learn'});await command({kind:'drop',revision:0,tray:0,rotation:0,value:1,x:0});const receipt=await command({kind:'drop',revision:1,tray:0,rotation:0,value:1,x:4});expect((await c.post('/api/pilot/math-stack-command',{data:receipt})).status()).toBe(200);save=await get();expect(save.state.player.currencies.mp).toBe(original+2);expect(save.state.mathStack.run.round).toBe(1);const forged=structuredClone(save.state);forged.mathStack.run.score=999999;expect((await c.put('/api/pilot/save',{data:{revision:save.revision,requestId:crypto.randomUUID(),state:forged}})).status()).toBe(409);await command({kind:'start',track:'factor',mode:'learn'});await command({kind:'explain',revision:0});save=await get();expect(save.state.learningEvidence.at(-1).answerRevealed).toBe(true);expect(save.state.learningEvidence.at(-1).grade).toBe(9);
 // The normal app loads the saved board through its classroom session.
 await page.goto(signInLink(base,{role:'student',code:cards.cards[0].code,classCode:cards.classCode}));await page.getByRole('button',{name:'Games',exact:true}).click();await page.locator('.student-card').filter({has:page.getByRole('heading',{name:'Math Stack',exact:true})}).getByRole('button',{name:'Start →',exact:true}).click();await expect(page.getByTestId('math-stack')).toBeVisible();await page.getByRole('button',{name:'Return to saved board',exact:true}).click();await expect(page.locator('.ms-goal')).toContainText('Factor');await page.getByRole('button',{name:'▶ Watch an example',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByTestId('cloud-save-status')).toHaveText('Saved online');
 await page.getByRole('button',{name:'Skills & modes',exact:true}).click();await page.getByRole('button',{name:'Start with Grade 1',exact:true}).click();await page.getByRole('button',{name:/Start a new adventure/}).click();await expect(page.getByTestId('flow-game')).toBeVisible();save=await get();const mp=save.state.player.currencies.mp;const answer=answerChoices(save.state.mathStack.run).findIndex(v=>v.correct);await page.getByRole('group',{name:'Answer pieces'}).getByRole('button').nth(answer).click();await page.getByRole('button',{name:'Drop ↓',exact:true}).click();await expect(page.locator('.flow-cell.solid')).toHaveCount(4);await expect(page.getByTestId('cloud-save-status')).toHaveText('Saved online');expect((await get()).state.player.currencies.mp).toBe(mp+2);await page.reload();await page.getByRole('button',{name:/Continue Math Stack/}).click();await expect(page.locator('.flow-cell.solid')).toHaveCount(4);

 }finally{await c.dispose();await t.dispose();}
});
