import{test,expect}from'@playwright/test';
const pics='/home/dre/Pictures/V-Pet-Battle-2026-09-26';
test('earned pet, equipment, free talents and loadouts survive reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1366,height:768});await page.goto('/e2e/pet-arena-fixture.html');await expect(page.getByRole('heading',{name:/Captain Waffles/})).toBeVisible();await page.screenshot({path:`${pics}/battle-adventure.png`,fullPage:true});await page.getByRole('button',{name:/Talents ·/}).click();await page.locator('.guardian').getByRole('button',{name:'Use recommended build'}).click();await expect(page.locator('.guardian [data-learned=true]')).toHaveCount(4);await expect(page.locator('.tactician [data-learned=true]')).toHaveCount(2);await page.getByRole('button',{name:'Save build 1'}).click();await page.getByRole('button',{name:'Reset talents',exact:true}).click();await expect(page.locator('[data-learned=true]')).toHaveCount(0);await page.getByRole('button',{name:'Load 1',exact:true}).click();await page.screenshot({path:`${pics}/battle-talents.png`,fullPage:true});await page.reload();await page.getByRole('button',{name:/Talents ·/}).click();await expect(page.locator('[data-learned=true]')).toHaveCount(6);await page.getByRole('button',{name:'Equipment',exact:true}).click();await expect(page.locator('.arena-gear article')).toHaveCount(16);await page.screenshot({path:`${pics}/battle-equipment.png`,fullPage:true});expect(errors).toEqual([]);
});
test('battle completes, uses a real item, gives XP once and unlocks next encounter',async({page})=>{
 await page.goto('/e2e/pet-arena-fixture.html');await page.getByRole('button',{name:/Bramble Scout/}).click();await expect(page.locator('.arena-combat')).toBeVisible();await page.screenshot({path:`${pics}/battle-combat.png`,fullPage:true});await page.getByRole('button',{name:/Healing Snack/}).click();await expect(page.getByRole('button',{name:/Healing Snack/})).toBeDisabled();for(let i=0;i<15;i++){if(await page.getByRole('button',{name:'Back to my build'}).count())break;const sig=page.getByRole('button',{name:/^Signature/});await page.getByRole('button',{name:/^Strike/}).waitFor();await expect.poll(()=>page.getByRole('button',{name:/^Strike/}).isEnabled(),{timeout:15000}).toBe(true);if(await sig.isEnabled())await sig.click();else await page.getByRole('button',{name:/^Strike/}).click();await page.waitForTimeout(400);}await expect(page.getByRole('button',{name:'Back to my build'})).toBeVisible({timeout:15000});await expect(page.locator('.arena-results')).toContainText('pet XP');await page.screenshot({path:`${pics}/battle-result.png`,fullPage:true});await page.getByRole('button',{name:'Back to my build'}).click();await expect(page.getByRole('button',{name:/Moss Sentry/})).toBeEnabled();const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('arena-fixture')!).pet.progression.xp);await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('arena-fixture')!).pet.progression.xp)).toBe(before);
});
test('Chromebook 150% and phone layouts fit with keyboard controls',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('vpet-display-size','1.5'));await page.setViewportSize({width:1366,height:768});await page.goto('/e2e/pet-arena-fixture.html');await page.getByRole('button',{name:/Bramble Scout/}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${pics}/battle-chromebook-150.png`,fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${pics}/battle-phone-150.png`,fullPage:true});await page.getByRole('button',{name:'Leave battle',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Bramblewood',exact:true})).toBeVisible();
});
