import{test,expect,request,type APIRequestContext}from'@playwright/test';
import{readFileSync}from'node:fs';
import{hatchEgg}from'../src/services/game/evolutionEngine';
import{CURRENT_SAVE_VERSION}from'../src/services/persistence/saveMigrations';
import{preset}from'../src/features/pet-arena/combat';
import{signInLink}from'../src/pilot/signInLinks';
const base='http://127.0.0.1:8798';
async function setup(){const teachers=JSON.parse(readFileSync('.pilot-private/test-teachers.json','utf8'));const t=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await t.post('/api/pilot/login',{data:{role:'teacher',code:teachers[0].code}});await t.post('/api/pilot/quick-checks/policy',{data:{cadence:'teacher'}});await t.post('/api/pilot/play-time/policy',{data:{enabled:false}});const cards=await(await t.post('/api/pilot/teacher/students',{data:{count:2}})).json();const clients:APIRequestContext[]=[];for(const card of cards.cards){const s=await request.newContext({baseURL:base,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await s.post('/api/pilot/login',{data:{role:'student',code:card.code,classCode:cards.classCode}});const saved=await(await s.get('/api/pilot/save')).json();saved.state.pet=hatchEgg({id:'e',type:'koala',state:'ready',progress:100,createdAt:new Date().toISOString()});saved.state.pet.id=`pet-${card.id}`;saved.state.pet.progression.level=16;saved.state.egg=null;saved.state.eggDiscovery=null;saved.state.player.currencies.mp=100;saved.state.player.lifetimeMathCorrect=100;saved.state.screen='pet_arena';const restore=await t.post(`/api/pilot/teacher/students/${card.id}/restore`,{data:{revision:saved.revision,confirm:'RESTORE',backup:{studentId:card.id,saveVersion:CURRENT_SAVE_VERSION,state:saved.state}}});expect(restore.status(),await restore.text()).toBe(200);clients.push(s);}return {t,clients,cards};}
async function post(s:APIRequestContext,body:Record<string,unknown>){const r=await s.post('/api/pilot/arena-rooms',{data:body});expect(r.status(),await r.text()).toBe(200);}
async function room(s:APIRequestContext,id:string){return (await(await s.get('/api/pilot/arena-rooms')).json()).rooms.find((r:{id:string})=>r.id===id);}
test('online rewards, receipts, reload and Chromebook UI',async({page})=>{const {t,clients,cards}=await setup(),s=clients[0];try{let save=await(await s.get('/api/pilot/save')).json();const body={revision:save.revision,requestId:crypto.randomUUID(),command:{kind:'buy',id:'mirror'}};for(let i=0;i<2;i++){const r=await s.post('/api/pilot/arena-command',{data:body});expect(r.status(),await r.text()).toBe(200);}save=await(await s.get('/api/pilot/save')).json();expect(save.state.player.currencies.mp).toBe(90);const forged=structuredClone(save.state);forged.petArena.owned.push('spark');expect((await s.put('/api/pilot/save',{data:{revision:save.revision,requestId:crypto.randomUUID(),state:forged}})).status()).toBe(409);await page.goto(signInLink(base,{role:'student',code:cards.cards[0].code,classCode:cards.classCode}));await expect(page.getByRole('navigation',{name:'Student menus'})).toBeVisible();await page.getByRole('button',{name:/Continue Pet battle/}).click();await expect(page.getByRole('heading',{name:'Pet Battle',exact:true})).toBeVisible();await page.getByRole('button',{name:'Equipment',exact:true}).click();const mirror=page.locator('.arena-card').filter({has:page.getByRole('heading',{name:'Mirror Charm',exact:true})});await mirror.getByRole('button',{name:'Equip',exact:true}).click();await expect(mirror.getByRole('button',{name:'Equipped',exact:true})).toBeVisible();await expect(page.getByTestId('cloud-save-status')).toHaveText('Saved online');await page.getByRole('button',{name:'Adventure',exact:true}).click();await page.getByRole('button',{name:/Bramble Scout/}).click();await page.getByRole('button',{name:/^Strike/}).click();await expect(page.locator('.arena-combat-top')).toContainText('Turn 2');await page.reload();await page.getByRole('button',{name:/Continue Pet battle/}).click();await expect(page.locator('.arena-combat-top')).toContainText('Turn 2');await page.getByRole('button',{name:'Leave battle',exact:true}).click();await expect(page.getByRole('heading',{name:'Bramblewood',exact:true})).toBeVisible();}finally{await t.dispose();for(const c of clients)await c.dispose();}});
test('fair classmate duel locks moves and prevents duplicate turns',async()=>{const {t,clients,cards}=await setup(),[a,b]=clients;try{await post(a,{kind:'create',mode:'duel',opponent:cards.cards[1].id});const data=await(await a.get('/api/pilot/arena-rooms')).json(),id=data.rooms[0].id;for(const [i,c]of clients.entries()){const r=await room(c,id);await post(c,{id,revision:r.revision,kind:'ready',build:preset(i?'striker':'guardian')});}let r=await room(a,id);await post(a,{id,revision:r.revision,kind:'start'});r=await room(a,id);await post(a,{id,revision:r.revision,kind:'move',round:1,move:'guard'});r=await room(b,id);expect(r.choices[cards.cards[0].id]).toBe('locked');await post(b,{id,revision:r.revision,kind:'move',round:1,move:'strike'});r=await room(a,id);expect(r.round).toBe(2);expect((await a.post('/api/pilot/arena-rooms',{data:{id,revision:r.revision,kind:'move',round:1,move:'strike'}})).status()).toBe(409);await post(a,{id,revision:r.revision,kind:'end'});}finally{await t.dispose();for(const c of clients)await c.dispose();}});
test('teacher team challenge joins, pauses and resolves actual item effects',async()=>{const {t,clients}=await setup();try{await post(t,{kind:'create',mode:'raid'});const id=(await(await t.get('/api/pilot/arena-rooms')).json()).rooms[0].id;for(const s of clients){let r=await room(s,id);await post(s,{id,revision:r.revision,kind:'join'});r=await room(s,id);await post(s,{id,revision:r.revision,kind:'ready',build:preset('guardian')});}let r=await room(t,id);await post(t,{id,revision:r.revision,kind:'start'});r=await room(t,id);await post(t,{id,revision:r.revision,kind:'pause'});r=await room(clients[0],id);expect((await clients[0].post('/api/pilot/arena-rooms',{data:{id,revision:r.revision,kind:'move',move:'item',round:1}})).status()).toBe(409);await post(t,{id,revision:r.revision,kind:'pause'});r=await room(clients[0],id);await post(clients[0],{id,revision:r.revision,kind:'move',move:'item',round:1});r=await room(t,id);await post(t,{id,revision:r.revision,kind:'resolve'});r=await room(t,id);expect(r.round).toBe(2);expect(r.members[0].fighter.used).toContain('tool');await post(t,{id,revision:r.revision,kind:'end'});}finally{await t.dispose();for(const c of clients)await c.dispose();}});
