import {test,expect} from '@playwright/test';
const pics='/home/dre/Pictures/V-Pet-Rooms-2026-09-26';
test('room framing, saved room zoom, overview, pet independence and phone fit',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1000});await page.goto('/e2e/living-house-fixture.html');const scene=page.locator('.lh-viewport');await expect(scene).toHaveAttribute('data-view','room');await page.waitForTimeout(800);await page.screenshot({path:`${pics}/room-after.png`});
 const nav=page.getByRole('navigation',{name:'Look into a room'});const petRoom=await page.getByTestId('house-resident').getAttribute('data-room');await nav.getByRole('button',{name:/Kitchen/}).click();await expect(scene).toHaveAttribute('data-room','kitchen');await expect(page.getByTestId('house-resident')).toHaveAttribute('data-room',petRoom!);
 await page.getByLabel('Room zoom',{exact:true}).fill('1.3');await page.reload();await expect(scene).toHaveAttribute('data-room','kitchen');await expect(page.getByLabel('Room zoom',{exact:true})).toHaveValue('1.3');await page.getByRole('button',{name:'Whole house',exact:true}).click();await expect(scene).toHaveAttribute('data-view','house');await nav.getByRole('button',{name:/Cozy den/}).click();await expect(scene).toHaveAttribute('data-view','room');await page.getByRole('button',{name:'Find my pet',exact:true}).click();await expect(scene).toHaveAttribute('data-room',petRoom!);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${pics}/room-phone.png`,fullPage:true});expect(errors).toEqual([]);
});
test('feeding meter uses actual gains, repeats once, and exits without cancelling care',async({page})=>{
 await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:'Feed pet',exact:true}).click();const meter=page.getByRole('progressbar',{name:'Pet fullness'});await expect(meter).toHaveAttribute('aria-valuenow','35');await page.getByRole('button',{name:'Feed Apple for 5 tokens'}).click();await expect(meter).toHaveAttribute('aria-valuenow','35');await expect(page.getByRole('button',{name:'Choose another snack'})).toBeEnabled({timeout:10000});await expect(meter).toHaveAttribute('aria-valuenow','50');await expect(page.getByRole('dialog')).toContainText('Fullness: 35 → 50 / 100');await page.screenshot({path:`${pics}/feeding-result.png`});
 await page.getByRole('button',{name:'Choose another snack'}).click();await page.getByRole('button',{name:'Feed Apple for 5 tokens'}).click();await expect(page.getByRole('button',{name:'Choose another snack'})).toBeEnabled({timeout:10000});await expect(meter).toHaveAttribute('aria-valuenow','65');await page.getByRole('button',{name:'Done — back to my pet'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('care-feedback-test')!));expect(state.pet.needs.hunger).toBe(65);expect(state.events.filter((e:{type:string})=>e.type==='pet_fed')).toHaveLength(2);
});
test('completed play auto-applies care and shows real changes; escape after completion keeps them',async({page})=>{
 await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:'Start play',exact:true}).click();await page.getByRole('button',{name:'Let’s begin'}).click();for(let i=0;i<8;i++)await page.getByRole('button',{name:'Catch the ball'}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Pet care complete'})).toBeVisible();await expect(page.getByRole('dialog')).toContainText('Happiness');await page.screenshot({path:`${pics}/care-result.png`});const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('care-feedback-test')!));expect(before.pet.needs.happiness).toBeGreaterThan(40);await page.getByRole('button',{name:'Done — back to my pet'}).click();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('care-feedback-test')!));expect(after.player.currencies).toEqual(before.player.currencies);expect(after.events.filter((e:{type:string})=>e.type==='care_game_complete')).toHaveLength(1);
});

for(const [mode,target,count] of [['pet','Pet the heart',5],['train','Touch the star',6],['brush','Brush ',5],['play','Catch the ball',8]] as const)test(`${mode} completes automatically with one care receipt`,async({page})=>{
 await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:`Start ${mode}`,exact:true}).click();await page.getByRole('button',{name:'Let’s begin'}).click();for(let i=0;i<count;i++)await page.getByRole('button',{name:mode==='brush'?/^Brush /:target,exact:mode!=='brush'}).click();await expect(page.getByRole('dialog',{name:'Pet care complete'})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('care-feedback-test')!));expect(state.events.filter((e:{type:string})=>e.type==='care_game_complete')).toHaveLength(1);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('app-wide sizing enlarges buttons, persists across screens and keeps Hunt full-screen',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1366,height:657});await page.goto('/');const launcher=page.getByRole('button',{name:'Adjust interface size'});const small=(await launcher.boundingBox())!.width;await launcher.click();await page.getByRole('button',{name:'Larger interface'}).focus();for(let i=0;i<3;i++)await page.keyboard.press('Enter');await expect(page.locator('.display-size-popover output')).toHaveText('150%');await page.getByRole('button',{name:'Done',exact:true}).click();expect((await launcher.boundingBox())!.width).toBeCloseTo(small*1.5,0);await page.getByRole('button',{name:/Explore my house/}).click();await expect(page.locator('.lh-viewport')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${pics}/house-large-ui.png`});await page.goto('/?petHunt=1');await page.getByRole('button',{name:/Play as a runner/}).click();const arena=page.locator('.hunt-game');await expect.poll(async()=>(await arena.boundingBox())!.height).toBeCloseTo(657,0);await page.getByRole('button',{name:'Open game menu'}).click();await expect(page.locator('.hunt-menu output')).toHaveText('150%');expect(await page.locator('.hunt-menu').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await page.screenshot({path:`${pics}/hunt-chromebook-large-ui.png`});await page.getByRole('button',{name:'Fullscreen',exact:true}).click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await page.getByRole('button',{name:'Back to game',exact:true}).click();await launcher.click();await page.getByRole('button',{name:'Reset',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.evaluate(()=>document.exitFullscreen());expect(errors).toEqual([]);
});
test('large interface feeding fits a phone and care rewards are capped honestly',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('vpet-display-size','1.5'));await page.setViewportSize({width:390,height:844});await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:'Feed pet',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Feed Pet'});expect(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await page.getByRole('button',{name:'Feed Apple for 5 tokens'}).click();await expect(page.getByRole('button',{name:'Choose another snack'})).toBeEnabled({timeout:10000});await page.screenshot({path:`${pics}/feeding-phone-large-ui.png`,fullPage:true});await page.getByRole('button',{name:'Done — back to my pet'}).click();await expect(dialog).toHaveCount(0);
});
for(const mode of ['wash','comfort'] as const)test(`${mode} applies care automatically`,async({page})=>{
 await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:`Start ${mode}`,exact:true}).click();await page.getByRole('button',{name:'Let’s begin'}).click();if(mode==='wash'){for(let n=1;n<=4;n++)for(let i=0;i<4;i++)await page.getByRole('button',{name:`Wash patch ${n}`,exact:true}).click();}else{const button=page.getByRole('button',{name:/Hold to comfort/});await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(3300);await page.keyboard.up('Space');}await expect(page.getByRole('dialog',{name:'Pet care complete'})).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('care-feedback-test')!));expect(state.events.filter((e:{type:string})=>e.type==='care_game_complete')).toHaveLength(1);
});
test('medicine reports capped health gain rather than the advertised maximum',async({page})=>{
 await page.goto('/e2e/care-feedback-fixture.html');await page.getByRole('button',{name:'Feed pet',exact:true}).click();await page.getByRole('button',{name:'Medicine',exact:true}).click();await page.getByRole('button',{name:'Feed Potion for 50 tokens'}).click();await expect(page.getByRole('button',{name:'Choose another snack'})).toBeEnabled({timeout:10000});await expect(page.getByRole('progressbar',{name:'Pet health'})).toHaveAttribute('aria-valuenow','100');await expect(page.getByRole('dialog')).toContainText('Health: 50 → 100 / 100');await expect(page.getByRole('progressbar',{name:'Pet fullness'})).toHaveAttribute('aria-valuenow','35');
});
