import {test,expect,request as newRequest,type APIRequestContext} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const baseURL='http://127.0.0.1:8811';
const teachers=()=>JSON.parse(readFileSync('.pilot-private/test-teachers.json','utf8')) as {code:string}[];
async function teacher(index=0){const api=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});expect((await api.post('/api/pilot/login',{data:{role:'teacher',code:teachers()[index].code}})).status()).toBe(200);return api;}
async function get(api:APIRequestContext,path='skill-challenges'){const r=await api.get(`/api/pilot/${path}`);expect(r.status(),await r.text()).toBe(200);return r.json();}
async function post(api:APIRequestContext,path:string,data:unknown){const r=await api.post(`/api/pilot/${path}`,{data});expect(r.status(),await r.text()).toBe(200);return r.json();}
function fixture(challengeId:string,studentId:string,fastForward:boolean|'week'=false){
 // Read answers / advance the follow-up clock ONLY in the isolated local test DB.
 const script=`import sqlite3,glob,json,sys,time\nfor path in glob.glob('.wrangler/pilot-test-state/v3/d1/**/*.sqlite',recursive=True):\n c=sqlite3.connect(path)\n if not c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='skill_challenge_learners'").fetchone(): continue\n row=c.execute('SELECT progress_json FROM skill_challenge_learners WHERE challenge_id=? AND student_id=?',(sys.argv[1],sys.argv[2])).fetchone()\n if not row: continue\n p=json.loads(row[0])\n if sys.argv[3] in ('1','2'):\n  for t in p['targets']:\n   if t['passedAt']: t['passedAt']=int(time.time()*1000)-86401000\n   if t.get('transferAt'): t['transferAt']=int(time.time()*1000)-86401000\n   if sys.argv[3]=='2' and t.get('confirmedAt'): t['confirmedAt']=int(time.time()*1000)-7*86400000-1000\n  c.execute('UPDATE skill_challenge_learners SET progress_json=?,revision=revision+1 WHERE challenge_id=? AND student_id=?',(json.dumps(p),sys.argv[1],sys.argv[2]));c.commit()\n print(json.dumps(p));break\nelse: raise Exception('Isolated fixture was not found')`;
 return JSON.parse(execFileSync('python3',['-c',script,challengeId,studentId,fastForward==='week'?'2':fastForward?'1':'0'],{encoding:'utf8'}));
}
test('teacher picks exact per-grade targets; student evidence, delay, approval and work-based winner',async({page,browser})=>{
 const host=await teacher();const cards=(await (await host.post('/api/pilot/teacher/students',{data:{count:2}})).json());const roster=await get(host,'teacher/classroom');
 for(const [i,card]of cards.cards.entries()){const s=roster.students.find((s:{id:string})=>s.id===card.id);await post(host,`teacher/students/${card.id}/grade-recovery`,{grade:i===0?3:8,topic:'mixed',settingsVersion:s.settingsVersion});}
 await page.goto('/');await page.getByRole('button',{name:'Teacher sign in',exact:true}).click();await page.getByLabel('Private teacher key').fill(teachers()[0].code);await page.getByRole('button',{name:'Open teacher classroom',exact:true}).click();await page.getByRole('button',{name:'Skill challenges Growth & mastery'}).click();await page.getByRole('button',{name:'Plan a skill challenge'}).click();await page.getByLabel('Learning path',{exact:true}).selectOption('1');await expect(page.getByRole('combobox',{name:'Skills to master'})).toHaveValue('3');
 const plans=page.locator('.skill-plan');await expect(plans).toHaveCount(2);await plans.first().locator('summary').click();const checkboxes=plans.first().locator('.skill-option input');await checkboxes.nth(0).uncheck();await checkboxes.nth(4).check();await expect(checkboxes.nth(4)).toBeChecked();
 const middlePlan=plans.nth(1);await middlePlan.locator('summary').click();
 const topics=middlePlan.getByRole('combobox',{name:/Filter topics for/});
 await expect(middlePlan.locator('.skill-option')).toHaveCount(24);
 await topics.selectOption('Transformations');await expect(middlePlan.locator('.skill-option')).toHaveCount(3);
 await expect(middlePlan.locator('.skill-option').first()).toContainText('Translate a coordinate');
 mkdirSync('docs/verification/middle-school',{recursive:true});
 await middlePlan.screenshot({path:'docs/verification/middle-school/teacher-topic-filter.png'});
 await topics.selectOption('');await expect(middlePlan.locator('.skill-option')).toHaveCount(24);
 await expect(middlePlan.locator('.skill-option input:checked')).toHaveCount(3);
 mkdirSync('docs/verification/skill-challenge',{recursive:true});await page.locator('.skill-challenge').screenshot({path:'docs/verification/skill-challenge/teacher-selection.png'});
 await page.getByRole('button',{name:'Issue 3-skill challenge to 2 learners'}).click();await expect(page.getByRole('button',{name:'Close challenge for judging'})).toBeVisible();let data=await get(host);const challengeId=data.challenge.id;expect(data.learners[0].progress.targets.map((t:{id:string})=>t.id)).toEqual(['g3-s1','g3-s2','g3-s4']);expect(data.learners[1].progress.targets.every((t:{id:string})=>t.id.startsWith('g8-'))).toBe(true);
 const other=await teacher(1);expect((await other.get(`/api/pilot/skill-challenges?id=${challengeId}`)).status()).toBe(200);expect((await get(other,`skill-challenges?id=${challengeId}`)).challenge).toBeNull();
 const student=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await post(student,'login',{role:'student',code:cards.cards[0].code,classCode:cards.classCode});
 expect((await student.get('/api/pilot/skill-challenges/preview')).status()).toBe(403);expect((await student.post('/api/pilot/skill-challenges/issue',{data:{}})).status()).toBe(403);let mine=await get(student);expect(mine).not.toHaveProperty('learners');expect(mine.assignment.progress.learning.grade).toBe(3);
 const studentPage=await browser.newPage({viewport:{width:1366,height:768}});await studentPage.goto('/');await studentPage.getByLabel('Class code',{exact:true}).fill(cards.classCode);await studentPage.getByLabel('My secret pet code').fill(cards.cards[0].code);await studentPage.getByRole('button',{name:'Visit my pet',exact:true}).click();await expect(studentPage.getByTestId('cloud-save-status')).toHaveText('Saved online');await studentPage.getByRole('button',{name:'My skill challenge · 0/3'}).click();await expect(studentPage.locator('.skill-dialog')).toBeVisible();await expect(studentPage.getByText('Master these 3 skills to qualify. Your own progress matters.')).toBeVisible();await studentPage.getByRole('button',{name:'Starting check · 0/3'}).first().click();await expect(studentPage.getByLabel('Your answer',{exact:true})).toBeVisible();await studentPage.locator('.skill-dialog').screenshot({path:'docs/verification/skill-challenge/student-checklist.png'});await studentPage.getByRole('button',{name:'Back to my pet'}).click();
 mine=await get(student);expect(mine.assignment.progress.current).not.toHaveProperty('answer');expect(mine.assignment.progress.current).not.toHaveProperty('hint');
 const id=cards.cards[0].id;const targets=mine.assignment.progress.targets.map((t:{id:string})=>t.id);
 async function solve(skillId:string,stage:string,correct=true){mine=await get(student);if(!mine.assignment.progress.current||mine.assignment.progress.current.answered)mine=await post(student,`skill-challenges/begin?id=${challengeId}`,{skillId,stage,revision:mine.assignment.revision});const current=fixture(challengeId,id).current;const before=mine.assignment.revision;mine=await post(student,`skill-challenges/answer?id=${challengeId}`,{questionId:current.id,answer:String(correct?current.answer:current.answer+999),revision:before});return {current,before};}
 for(const skillId of targets){for(let i=0;i<3;i++)await solve(skillId,'baseline',i!==0);for(let i=0;i<3;i++)await solve(skillId,'practice');for(let i=0;i<5;i++)await solve(skillId,'check',i!==0);}
 const early=await student.post(`/api/pilot/skill-challenges/begin?id=${challengeId}`,{data:{skillId:targets[0],stage:'follow',revision:mine.assignment.revision}});expect(early.status()).toBe(409);
 data=await get(host);const s=data.learners.find((s:{id:string})=>s.id===id);expect((await host.post(`/api/pilot/skill-challenges/confirm?id=${challengeId}`,{data:{studentId:id,skillId:targets[0],revision:s.revision,note:'Premature confirmation'}})).status()).toBe(409);
 fixture(challengeId,id,true);
 for(const skillId of targets){await solve(skillId,'follow');const {current,before}=await solve(skillId,'follow');const repeated=await post(student,`skill-challenges/answer?id=${challengeId}`,{questionId:current.id,answer:'999',revision:before});expect(repeated.assignment.progress.events.filter((e:{id:string})=>e.id===current.id)).toHaveLength(1);}
 data=await get(host);expect(data.learners.find((s:{id:string})=>s.id===id).confirmed).toBe(0);await post(host,`skill-challenges/close?id=${challengeId}`,{challengeId});
 for(const skillId of targets){data=await get(host);const row=data.learners.find((s:{id:string})=>s.id===id);expect((await student.post(`/api/pilot/skill-challenges/confirm?id=${challengeId}`,{data:{studentId:id,skillId,revision:row.revision,note:'Self approval forbidden'}})).status()).toBe(403);if(skillId===targets[0]){await page.getByRole('button',{name:'Refresh progress',exact:true}).click();const target=page.locator('.skill-learner').first().locator('.skill-target').first();await target.locator(':scope > summary').click();await expect(target.locator('.skill-review-next')).toContainText('Review the evidence below');await target.getByText('View question-by-question proof',{exact:true}).click();await expect(target.locator('.skill-proof li').first()).toBeVisible();await expect(target.getByRole('button',{name:'Confirm mastery',exact:true})).toBeDisabled();await target.getByRole('textbox',{name:/Observation for/}).fill('Explained the method and improved after practice.');await target.screenshot({path:'docs/verification/skill-challenge/teacher-review.png'});await target.getByRole('button',{name:'Confirm mastery',exact:true}).click();await expect(page.locator('.skill-count').first()).toContainText('1 / 3');}else await post(host,`skill-challenges/confirm?id=${challengeId}`,{studentId:id,skillId,revision:row.revision,note:'Explained the method and improved after practice.'});}
 await page.getByRole('button',{name:'Refresh progress',exact:true}).click();await expect(page.locator('.skill-count').first()).toContainText('3 / 3');await page.locator('.skill-learner').first().screenshot({path:'docs/verification/skill-challenge/teacher-confirmed.png'});
 const beforeSave=await get(student,'save');await post(host,`skill-challenges/close?id=${challengeId}`,{challengeId});expect((await host.post(`/api/pilot/skill-challenges/winner?id=${challengeId}`,{data:{challengeId,studentId:cards.cards[1].id,reason:'Cannot reward unfinished targets'}})).status()).toBe(409);
 data=await post(host,`skill-challenges/winner?id=${challengeId}`,{challengeId,studentId:id,reason:'Returned to difficult skills, used practice, and demonstrated improvement on fresh checks.'});expect(data.challenge.winnerId).toBe(id);const peer=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await post(peer,'login',{role:'student',code:cards.cards[1].code,classCode:cards.classCode});const peerView=await get(peer);expect(peerView.challenge.winnerId).toBeNull();expect(peerView.challenge.winnerReason).toBe('');await peer.dispose();const afterSave=await get(student,'save');expect(afterSave.state.player).toEqual(beforeSave.state.player);expect(afterSave.state.pet).toEqual(beforeSave.state.pet);
 mine=await get(student);expect(mine.challenge.closedAt).toBeTruthy();expect(mine.assignment.progress.targets.every((t:{confirmedAt:number})=>!!t.confirmedAt)).toBe(true);
 await studentPage.setViewportSize({width:390,height:844});await studentPage.getByRole('button',{name:/My skill challenge/}).click();await expect(studentPage.locator('.skill-dialog')).toBeVisible();expect(await studentPage.locator('.skill-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await studentPage.locator('.skill-dialog').screenshot({path:'docs/verification/skill-challenge/student-phone.png'});
 await studentPage.close();await host.dispose();await other.dispose();await student.dispose();
});
test('assignment validation, replacement audit, grade changes and manual target count',async()=>{
 const host=await teacher(2);const cards=await (await host.post('/api/pilot/teacher/students',{data:{count:1}})).json();const id=cards.cards[0].id,preview=await get(host,'skill-challenges/preview'),learner=preview.learners[0];
 const config={name:'Two focused targets',target:2,delayHours:24,assignments:[{studentId:id,settingsVersion:learner.settingsVersion,skills:['g2-s0','g2-s1']}]};
 expect((await host.post('/api/pilot/skill-challenges/issue',{data:{...config,assignments:[{...config.assignments[0],skills:['g2-s0','g7-s1']}]}})).status()).toBe(400);
 let data=await post(host,'skill-challenges/issue',config);const challengeId=data.challenge.id;expect(data.challenge.policy.target).toBe(2);
 data=await post(host,`skill-challenges/replace?id=${challengeId}`,{studentId:id,skillId:'g2-s0',newSkillId:'g2-s4',revision:data.learners[0].revision,note:'Needs subtraction regrouping instead.'});expect(data.learners[0].progress.targets[0].id).toBe('g2-s4');expect(data.learners[0].progress.archived).toHaveLength(1);
 const roster=await get(host,'teacher/classroom');await post(host,`teacher/students/${id}/grade-recovery`,{grade:4,topic:'mixed',settingsVersion:roster.students[0].settingsVersion});
 const student=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await post(student,'login',{role:'student',classCode:cards.classCode,code:cards.cards[0].code});const mine=await get(student);expect(mine.assignment.gradeChanged).toBe(true);expect((await student.post(`/api/pilot/skill-challenges/begin?id=${challengeId}`,{data:{skillId:'g2-s4',stage:'baseline',revision:mine.assignment.revision}})).status()).toBe(409);
 await host.dispose();await student.dispose();
});

test('K–12 upgrade: focused Home, preserved work, hints, transfer, explanation and teacher review queue',async({page,browser})=>{
 const host=await teacher(1),cards=await (await host.post('/api/pilot/teacher/students',{data:{count:1}})).json(),studentId=cards.cards[0].id;
 const roster=await get(host,'teacher/classroom'),profile=roster.students.find((s:{id:string})=>s.id===studentId);
 await post(host,`teacher/students/${studentId}/grade-recovery`,{grade:8,topic:'mixed',settingsVersion:profile.settingsVersion});
 const preview=await get(host,'skill-challenges/preview'),plan=preview.learners.find((s:{id:string})=>s.id===studentId);
 let teacherData=await post(host,'skill-challenges/issue',{name:'Learn and use it elsewhere',version:2,target:1,delayHours:24,assignments:[{studentId,settingsVersion:plan.settingsVersion,skills:['g8-s0']}]});const challengeId=teacherData.challenge.id;
 const student=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await post(student,'login',{role:'student',code:cards.cards[0].code,classCode:cards.classCode});
 const child=await browser.newPage({viewport:{width:1024,height:600}}),errors:string[]=[];child.on('pageerror',e=>errors.push(e.message));page.on('pageerror',e=>errors.push(e.message));
 await child.goto('/');await child.getByLabel('Class code',{exact:true}).fill(cards.classCode);await child.getByLabel('My secret pet code').fill(cards.cards[0].code);await child.getByRole('button',{name:'Visit my pet',exact:true}).click();
 await expect(child.getByRole('heading',{name:'Solve a two-step linear equation',exact:true})).toBeVisible();await expect(child.getByRole('button',{name:'Open my learning target →'})).toBeVisible();
 await page.goto('/');await page.getByRole('button',{name:'Teacher sign in',exact:true}).click();await page.getByLabel('Private teacher key').fill(teachers()[1].code);await page.getByRole('button',{name:'Open teacher classroom',exact:true}).click();await page.getByRole('button',{name:'Skill challenges Growth & mastery'}).click();
 await expect(page.getByRole('region',{name:'Teacher review queue'})).toBeVisible();await page.getByRole('button',{name:/Start focused session for/}).click();
 await expect(child.getByRole('main',{name:'Focused classroom session'})).toBeVisible({timeout:15000});await expect(child.getByRole('navigation',{name:'Student menus'})).toHaveCount(0);
 await child.reload();await expect(child.getByRole('main',{name:'Focused classroom session'})).toBeVisible();const action=child.getByRole('button',{name:'Open my learning target →'});expect((await action.boundingBox())!.y+(await action.boundingBox())!.height).toBeLessThan(600);
 await child.getByRole('button',{name:'Take an approved pet break'}).click();await expect(child.getByRole('heading',{name:'A quiet moment with your companion'})).toBeVisible();let mine=await get(student);
 expect((await student.post(`/api/pilot/skill-challenges/begin?id=${challengeId}`,{data:{skillId:'g8-s0',stage:'baseline',revision:mine.assignment.revision}})).status()).toBe(409);
 await child.reload();await expect(child.getByRole('heading',{name:'A quiet moment with your companion'})).toBeVisible();await child.getByRole('button',{name:'Return to my target'}).click();await action.click();const before=(await get(student,'save')).state;await child.getByRole('button',{name:'Starting check · 0/3'}).click();
 async function solve(stage:string,correct=true){mine=await get(student);if(!mine.assignment.progress.current||mine.assignment.progress.current.answered)mine=await post(student,`skill-challenges/begin?id=${challengeId}`,{skillId:'g8-s0',stage,revision:mine.assignment.revision});const q=fixture(challengeId,studentId).current;expect(mine.assignment.progress.current).not.toHaveProperty('answer');expect(mine.assignment.progress.current).not.toHaveProperty('hints');mine=await post(student,`skill-challenges/answer?id=${challengeId}`,{questionId:q.id,answer:String(q.answer+(correct?0:1000)),reasoning:'I removed the fixed amount, then divided into equal groups.',revision:mine.assignment.revision});}
 await solve('baseline',false);await solve('baseline');await solve('baseline');
 await expect(child.getByText('Learn this skill · example and model')).toBeVisible({timeout:15000});if(await child.locator('.skill-example').getAttribute('open')===null)await child.getByText('Learn this skill · example and model').click();await child.getByRole('button',{name:'I read the example · ready to practice'}).click();await child.getByRole('button',{name:'Practice with hints'}).click();
 await child.getByRole('button',{name:'Give me a hint',exact:true}).click();await child.getByRole('button',{name:'Strategy hint',exact:true}).click();await child.getByRole('button',{name:'Show worked solution · supported',exact:true}).click();await expect(child.locator('.skill-hint')).toContainText('Worked example');
 mkdirSync('docs/verification/combined-upgrade',{recursive:true});await child.locator('.skill-dialog').screenshot({path:'docs/verification/combined-upgrade/guided-learning.png'});
 await solve('practice');expect(mine.assignment.progress.events.at(-1)).toMatchObject({supported:true,answerRevealed:true});await solve('practice');await solve('practice');
 for(let i=0;i<5;i++)await solve('check');
 expect((await student.post(`/api/pilot/skill-challenges/begin?id=${challengeId}`,{data:{skillId:'g8-s0',stage:'follow',revision:mine.assignment.revision}})).status()).toBe(409);
 await solve('transfer');await solve('transfer');fixture(challengeId,studentId,true);await solve('follow');await solve('follow');
 teacherData=await get(host);const learner=teacherData.learners[0];expect((await host.post(`/api/pilot/skill-challenges/confirm?id=${challengeId}`,{data:{studentId,skillId:'g8-s0',revision:learner.revision,note:'Missing explanation must block this'}})).status()).toBe(409);
 await post(student,`skill-challenges/reflect?id=${challengeId}`,{skillId:'g8-s0',reflection:'Subtract the entry fee first so the remaining money pays for equal-price tickets.',revision:mine.assignment.revision});
 await page.getByRole('button',{name:'Refresh progress',exact:true}).click();const queue=page.getByRole('region',{name:'Teacher review queue'});await expect(queue).toContainText('Auto-confirmed (1)');await queue.getByRole('button').click();const evidence=page.locator('.skill-target').first();await expect(evidence).toHaveAttribute('open','');await expect(page.locator('.skill-count').first()).toContainText('1 / 1');await expect(evidence).toContainText('30-second check:');
 // A clean run confirmed itself once the learner explained it; undo keeps the teacher in charge.
 await evidence.getByRole('button',{name:'Undo auto-confirm',exact:true}).click();await expect(page.locator('.skill-count').first()).toContainText('0 / 1');await expect(evidence).toContainText('Subtract the entry fee first');await evidence.getByRole('textbox',{name:/Observation for/}).fill('Explained the fixed fee, connected the new ticket context, and checked the result.');await evidence.getByRole('button',{name:'Confirm mastery',exact:true}).click();await expect(page.locator('.skill-count').first()).toContainText('1 / 1');await queue.screenshot({path:'docs/verification/combined-upgrade/review-queue.png'});
 await page.getByRole('button',{name:/End focused session for/}).click();await child.getByRole('button',{name:'Back to my pet',exact:true}).click();await expect(child.getByRole('navigation',{name:'Student menus'})).toBeVisible({timeout:15000});
 await child.setViewportSize({width:390,height:844});await child.getByRole('button',{name:/My skill challenge/}).click();await expect(child.locator('.skill-dialog')).toBeVisible();expect(await child.locator('.skill-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await child.locator('.skill-dialog').screenshot({path:'docs/verification/combined-upgrade/learning-phone.png'});
 const after=(await get(student,'save')).state;expect(after.player.currencies).toEqual(before.player.currencies);expect(after.pet).toEqual(before.pet);expect(errors).toEqual([]);
 await post(host,`skill-challenges/close?id=${challengeId}`,{challengeId});fixture(challengeId,studentId,'week');
 const latestPlan=(await get(host,'skill-challenges/preview')).learners.find((s:{id:string})=>s.id===studentId);
 await post(host,'skill-challenges/issue',{name:'Next classroom target',version:2,target:1,delayHours:24,assignments:[{studentId,settingsVersion:latestPlan.settingsVersion,skills:['g8-s1']}]});
 await child.goto(`/?skillChallenge=${challengeId}`);await child.getByRole('button',{name:/My skill challenge/}).click();await expect(child.getByRole('heading',{name:'Learn and use it elsewhere',exact:true})).toBeVisible();await child.getByRole('button',{name:'Optional one-week check'}).click();await expect(child.getByLabel('Your answer',{exact:true})).toBeVisible();
 const week=fixture(challengeId,studentId).current;await child.getByLabel('Your answer',{exact:true}).fill(String(week.answer));await child.getByRole('button',{name:'Submit answer',exact:true}).click();await expect(child.locator('.skill-feedback')).toContainText('You got it');
 const archived=(await get(student,`skill-challenges?id=${challengeId}`)).assignment.progress;expect(archived.events.at(-1).stage).toBe('retention');expect(archived.targets[0].confirmedAt).toBeTruthy();await page.goto(`/?skillChallenge=${challengeId}`);await expect(page.getByRole('heading',{name:'Learn and use it elsewhere',exact:true})).toBeVisible();await expect(page.locator('.skill-count').first()).toContainText('1 / 1');

 await child.close();await student.dispose();await host.dispose();
});

test('grade 7 transfer uses a new structure and game world; a miss shows its in-game cost and flags the teacher with a 30-second question',async()=>{
 const host=await teacher(2);const open=(await get(host)).challenge;if(open&&!open.closedAt)await post(host,`skill-challenges/close?id=${open.id}`,{challengeId:open.id});
 const cards=await (await host.post('/api/pilot/teacher/students',{data:{count:1}})).json(),studentId=cards.cards[0].id;
 const roster=await get(host,'teacher/classroom'),profile=roster.students.find((s:{id:string})=>s.id===studentId);
 await post(host,`teacher/students/${studentId}/grade-recovery`,{grade:7,topic:'mixed',settingsVersion:profile.settingsVersion});
 const plan=(await get(host,'skill-challenges/preview')).learners.find((s:{id:string})=>s.id===studentId);
 const challengeId=(await post(host,'skill-challenges/issue',{name:'Percents in new places',version:2,target:1,delayHours:24,assignments:[{studentId,settingsVersion:plan.settingsVersion,skills:['g7-s1']}]})).challenge.id;
 const student=await newRequest.newContext({baseURL,extraHTTPHeaders:{'X-Pilot-Request':'1'}});await post(student,'login',{role:'student',code:cards.cards[0].code,classCode:cards.classCode});
 let mine=await get(student,`skill-challenges?id=${challengeId}`);
 async function solve(stage:string,correct=true){mine=await get(student,`skill-challenges?id=${challengeId}`);if(!mine.assignment.progress.current||mine.assignment.progress.current.answered)mine=await post(student,`skill-challenges/begin?id=${challengeId}`,{skillId:'g7-s1',stage,revision:mine.assignment.revision});const q=fixture(challengeId,studentId).current;mine=await post(student,`skill-challenges/answer?id=${challengeId}`,{questionId:q.id,answer:String(q.answer+(correct?0:-3)),reasoning:'Found 5%, then scaled to 100%.',revision:mine.assignment.revision});return q;}
 await solve('baseline',false);await solve('baseline');await solve('baseline');
 mine=await post(student,`skill-challenges/lesson?id=${challengeId}`,{skillId:'g7-s1',revision:mine.assignment.revision});
 for(let i=0;i<3;i++)await solve('practice');for(let i=0;i<5;i++)await solve('check');
 const missed=await solve('transfer',false);
 expect(missed.templateId).toMatch(/^g7-s1:structural-v1:/);
 const answered=mine.assignment.progress.current;
 expect(answered.stakes?.unit).toBeTruthy();expect(answered.text).not.toMatch(/^\d+% of a number is/);
 const view=(await get(host,`skill-challenges?id=${challengeId}`)).learners.find((s:{id:string})=>s.id===studentId);
 const tri=view.summary.find((t:{id:string})=>t.id==='g7-s1').triage;
 expect(tri.reasons.join(' ')).toContain('different-use');
 expect(tri.prompt).toContain(missed.text);
 expect(tri.prompt).toContain(`the answer is ${missed.answer}`);
 await student.dispose();await host.dispose();
});
