import type { EngineState } from '../core/EngineTypes';

export const createInitialEngineState = (): EngineState => ({
  initialized: false,
  mode: 'normal',
  screen: 'incubation',
  elapsedMs: 0,
  tickCount: 0,
  engineTime: 0,
  pet: null,
  egg: {
    id: `egg_${Date.now()}`,
    type: 'basic',
    state: 'incubating',
    progress: 0,
    createdAt: new Date().toISOString(),
  },
  player: {
    id: 'player_1',
    displayName: 'Player',
    activePetId: null,
    mathMastery: { arithmetic: 0, geometry: 0, fractions: 0 },
    streaks: { login: 0, correctAnswers: 0 },
    currencies: { tokens: 100, coins: 0, mp: 0, mpLifetime: 0 },
    unlockedRoomItems: [],
    quizOutcome: null,
  },
  session: {
    currentQuestion: null,
    rewardPopup: null,
    activeModal: null,
    eggInteractionState: null,
  },
  inventory: {
    items: [],
    maxSlots: 20,
  },
  room: {
    backgroundId: 'default',
    items: [],
    moodBonus: 0,
  },
  currentRoom: 'inside',
  battle: { active: false },
  run: { active: false },
  momentum: { active: false },
  events: [],
  achievements: [],
  notifications: [],
  animation: {
    animationName: 'idle',
    frameIndex: 0,
    frameCount: 4,
    frameDurationMs: 250,
    elapsedMs: 0,
    autoplay: true,
    isFinished: false,
  },
  test: {
    active: false,
    label: 'Test Mode',
  },
  lastUpdate: null,
  dailyGoals: {
    date: '',
    mathSolved: 0,
    battlesWon: 0,
    rewardClaimed: false,
  },
  classroom: {
    classroom: null,
    classmates: [],
    selectedOpponentId: null,
    lastRosterRefresh: '',
  },
  battleTickets: {
    tickets: [],
    maxTickets: 5,
    todayEarned: 0,
    todayUsed: 0,
    mathForNextTicket: 0,
    careActionsToday: { fed: false, cleaned: false, played: false },
  },
  matchHistory: [],
  matchupTrackers: [],
  trophyCase: {
    trophies: [],
    displayedInRoom: [],
    maxDisplay: 5,
  },
  mailbox: {
    lastClaimedDate: '',
    totalClaimed: 0,
  },
  help: {
    completedTutorials: [],
    encounteredFeatures: [],
    hintCounts: {},
    hintTimestamps: {},
  },
});
