import {describe,it,expect} from 'vitest';
import {createRoom,joinRoom,apply,roomView,type Room,type Member,type Move} from './model';
import {normalizeLearning} from '../../services/game/curriculum';
const learning=normalizeLearning({grade:0,topic:'Addition within 10'});
function member(id:string,side:'teachers'|'students'):Member{return {id,alias:id,side,pet:side==='teachers'?'chalkstone_griffin':'ember_fox',learning,tokenHash:'PRIVATE',...(side==='teachers'?{guardian:{name:'Chalkstone',color:'midnight' as const}}:{})};}
function room(teachers=1,students=2):Room{let r=createRoom(member('host','teachers'),3,learning);for(let i=1;i<teachers;i++)r=joinRoom(r,member(`t${i}`,'teachers'));for(let i=0;i<students;i++)r=joinRoom(r,member(`s${i}`,'students'));return r;}
function solve(r:Room,id:string,move:Move='strike'):Room{return apply(r,{action:'answer',questionId:r.questions[id].id,answer:String(r.questions[id].answer),move},id);}
describe('teacher battle',()=>{
 it.each([1,2,3])('normalizes %i teachers to the same power as thirty students',teachers=>{let r=apply(room(teachers,30),{action:'next'},'host',()=>.4);for(const m of r.members)r=solve(r,m.id);r=apply(r,{action:'next'},'host');expect(r.health).toEqual({teachers:70,students:70});expect(r.results[0].charged).toEqual({teachers,students:30});});
 it('caps adults at lead plus two co-teachers',()=>{expect(()=>joinRoom(room(3),member('t3','teachers'))).toThrow(/three adults/);});
 it('a hint and wrong attempts do not reduce a successful contribution',()=>{let r=apply(room(),{action:'next'},'host',()=>.2);r=apply(r,{action:'answer',questionId:r.questions.s0.id,answer:'999',move:'strike'},'s0');expect(r.questions.s0.solved).toBe(false);r=solve(r,'s0');r=apply(r,{action:'next'},'host');expect(r.health.teachers).toBe(85);});
 it('cannot score twice or switch moves by replaying an answer',()=>{let r=apply(room(),{action:'next'},'host');r=solve(r,'s0');r=solve(r,'s0','rally');expect(r.questions.s0.move).toBe('strike');r=apply(r,{action:'next'},'host');expect(r.health.teachers).toBe(85);expect(()=>solve(r,'s0')).toThrow();});
 it('keeps questions private even from the opposing teacher and projector',()=>{const r=apply(room(),{action:'next'},'host');for(const actor of ['host','s0','projector']){const v=roomView(r,actor);expect(JSON.stringify(v)).not.toContain('PRIVATE');if(v.question)expect(v.question).not.toHaveProperty('answer');expect(v).not.toHaveProperty('questions');if(actor==='projector')expect(v.question).toBeNull();}expect(roomView(r,'s0').members[0]).not.toHaveProperty('learning');});
 it('applies shielding and healing without permanently changing a pet',()=>{let r=apply(room(1,1),{action:'next'},'host');r=solve(r,'host');r=solve(r,'s0','guard');r=apply(r,{action:'next'},'host');expect(r.health.students).toBe(100);r=apply(r,{action:'next'},'host');r.health.students=50;r=solve(r,'s0','rally');r=apply(r,{action:'next'},'host');expect(r.health.students).toBe(68);});
 it('allows co-teacher pause but restricts progression, removal and ending',()=>{let r=apply(room(2),{action:'next'},'host');r=apply(r,{action:'pause'},'t1');expect(()=>solve(r,'s0')).toThrow(/paused/);r=apply(r,{action:'pause'},'host');expect(()=>apply(r,{action:'next'},'t1')).toThrow();expect(()=>apply(r,{action:'finish'},'s0')).toThrow();expect(()=>apply(r,{action:'pause'},'s0')).toThrow();expect(()=>apply(r,{action:'remove',memberId:'s0'},'host')).toThrow();});
 it('supports individual learning levels without different energy awards',()=>{let r=room();r=apply(r,{action:'learning',memberId:'s0',grade:8,topic:'mixed',challenge:'support'},'host');r=apply(r,{action:'next'},'host');expect(r.members.find(m=>m.id==='s0')?.learning.grade).toBe(8);for(const id of ['s0','s1'])r=solve(r,id);r=apply(r,{action:'next'},'host');expect(r.health.teachers).toBe(70);});
 it('rejects stale questions, spectator actions and late joining',()=>{let r=apply(room(),{action:'next'},'host');expect(()=>apply(r,{action:'answer',questionId:'old',answer:'1',move:'strike'},'s0')).toThrow();expect(()=>apply(r,{action:'answer'},'outsider')).toThrow();expect(()=>joinRoom(r,member('late','students'))).toThrow();r=apply(r,{action:'finish'},'host');expect(()=>apply(r,{action:'next'},'host')).toThrow();});
 it('requires a student and finishes after the chosen number of rounds',()=>{expect(()=>apply(room(1,0),{action:'next'},'host')).toThrow();let r=room();r.rounds=1;r=apply(r,{action:'next'},'host');r=apply(r,{action:'next'},'host');r=apply(r,{action:'next'},'host');expect(r.phase).toBe('finished');});
});
