import { useCallback, useEffect, useRef, useState } from 'react';
import { startPolling } from '../../pilot/polling';
import { pilotAPI } from '../../pilot/api';
import { GRADE_TOPICS, gradeLabel, normalizeLearning, type LearningSettings } from '../../services/game/curriculum';
import { GROWING_PETS } from '../../config/companionConfig';
import { COLORS, type Guardian, type Move, type View } from './model';
import { FRAME_MS, GUARDIAN_FRAMES, GUARDIAN_STILL, guardianPlan, guardianSheet, type GuardianPlan } from './guardianSprite';
import { EmoteBar, EmoteBubble } from '../pet-identity/Emotes';
import './teacher-battle.css';
type Payload={room:View|null;token?:string;projectorToken?:string};
type Seat={id:string;token:string};
type Mode='teacher'|'student'|'projector';
const petArt=(id:string)=>id==='koala_sprite'?'/assets/woodland-v1/pip-portrait.png':`/assets/companions-v1/${id}-baby-portrait.png`;
const SEAT='auralith-teacher-battle-seat-v1',HOST='auralith-teacher-battle-host-v1';
function saved<T>(key:string):T|null {try{return JSON.parse(sessionStorage.getItem(key)??'null') as T|null;}catch{return null;}}
async function publicAPI(op:string,seat:Seat|null,body?:unknown):Promise<Payload>{
  const response=await fetch(`/api/pilot/teacher-battle-access?op=${op}${seat?`&id=${encodeURIComponent(seat.id)}`:''}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Pilot-Request':'1',...(seat?{'X-Battle-Token':seat.token}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000),cache:'no-store'});
  const data=await response.json();if(!response.ok)throw Error(data.error??'Could not reach the match.');return data;
}
function Level({value,onChange,label='Math'}:{value:LearningSettings;onChange:(v:LearningSettings)=>void;label?:string}){return <div className="tb-fields"><label>{label} level<select aria-label={`${label} level`} value={value.grade} onChange={e=>onChange(normalizeLearning({...value,grade:Number(e.target.value),topic:'mixed'}))}>{GRADE_TOPICS.map((_,i)=><option key={i} value={i}>{gradeLabel(i)}</option>)}</select></label><label>{label} topic<select aria-label={`${label} topic`} value={value.topic} onChange={e=>onChange({...value,topic:e.target.value})}><option value="mixed">Mixed practice</option>{GRADE_TOPICS[value.grade].map(t=><option key={t}>{t}</option>)}</select></label><label>{label} difficulty<select aria-label={`${label} difficulty`} value={value.challenge} onChange={e=>onChange(normalizeLearning({...value,challenge:e.target.value as LearningSettings['challenge']}))}><option value="support">Support</option><option value="standard">Standard</option><option value="stretch">Stretch</option></select></label></div>;}
const IDLE:GuardianPlan={once:[],rest:'idle',holdLast:false};
function GuardianSprite({plan}:{plan:GuardianPlan}){
  const key=JSON.stringify(plan),[state,setState]=useState({key,step:0,frame:0});
  const current=state.key===key?state:{key,step:0,frame:0};
  const queue=[...plan.once,plan.rest],anim=queue[Math.min(current.step,queue.length-1)],resting=current.step>=queue.length-1;
  const still=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
  const {step,frame:at}=current;
  useEffect(()=>{
    if(still||(resting&&plan.holdLast&&at===GUARDIAN_FRAMES-1))return;
    const t=setTimeout(()=>setState(
      at<GUARDIAN_FRAMES-1?{key,step,frame:at+1}:!resting?{key,step:step+1,frame:0}:{key,step,frame:plan.holdLast?at:0},
    ),FRAME_MS[anim]);
    return ()=>clearTimeout(t);
  },[key,step,at,anim,resting,plan.holdLast,still]);
  const frame=still?(plan.holdLast?GUARDIAN_FRAMES-1:0):at;
  return <div className={`tb-guardian-sprite tb-anim-${anim}`} data-anim={anim} style={{backgroundImage:`url(${guardianSheet(anim)})`,backgroundPosition:`${frame/(GUARDIAN_FRAMES-1)*100}% 0`}}/>;
}
function GuardianPicture({guardian,large=false,plan=IDLE}:{guardian?:Guardian;large?:boolean;plan?:GuardianPlan}){return <figure className={`tb-guardian ${large?'tb-guardian-large':''} tb-${guardian?.color??'midnight'}`} role="img" aria-label={`${guardian?.name??'Chalkstone'}, a scholarly griffin with golden armor and a floating spellbook`}><GuardianSprite plan={plan}/><figcaption>{guardian?.name??'Chalkstone'}<small>Chalkstone Griffin · teacher guardian</small></figcaption></figure>;}
export function TeacherBattleLauncher(){const [open,setOpen]=useState(false);return <section className="tb tb-launcher"><img className="tb-pixel" src={GUARDIAN_STILL} alt="Chalkstone Griffin"/><div><p className="tb-eyebrow">The academy challenge</p><h2>Beat the Teacher</h2><p>Student pets challenge 1–3 teacher guardians. Solve math. Choose a move. Make it count.</p><button onClick={()=>setOpen(v=>!v)}>{open?'Hide match':'Open Beat the Teacher'}</button></div>{open&&<Battle mode="teacher"/>}</section>;}
export function TeacherBattleEntry(){const projector=new URLSearchParams(location.search).get('teacherBattle')==='projector';return <main className="tb tb-page"><a href="/">← Back to Auralith</a><Battle mode={projector?'projector':'student'}/></main>;}
function Battle({mode}:{mode:Mode}){
  const teacher=mode==='teacher',projector=mode==='projector';
  const [seat,setSeat]=useState<Seat|null>(()=>{if(projector){const p=new URLSearchParams(location.hash.slice(1));return {id:p.get('id')??'',token:p.get('token')??''};}return saved(SEAT);});
  const [roomId,setRoomId]=useState<string|null>(()=>saved(HOST));
  const [payload,setPayload]=useState<Payload>({room:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false);
  const [guardian,setGuardian]=useState<Guardian>({name:'Chalkstone',color:'midnight'}),[alias,setAlias]=useState(''),[code,setCode]=useState(''),[invite,setInvite]=useState(''),[pet,setPet]=useState(()=>{const p=new URLSearchParams(location.search).get('pet')??'';return Object.hasOwn(GROWING_PETS,p)?p:'ember_fox';});
  const [learning,setLearning]=useState(()=>normalizeLearning({grade:3,topic:'mixed'})),[rounds,setRounds]=useState(5),[draft,setDraft]=useState({id:'',text:''}),[move,setMove]=useState<Move>('strike'),[board,setBoard]=useState(false);
  const pending=useRef(false),scope=useRef(0),liveRoom=useRef(false),field=useRef<HTMLInputElement>(null);const room=payload.room;const answer=draft.id===room?.question?.id?draft.text:'';
  const accept=useCallback((data:Payload)=>{liveRoom.current=!!data.room&&data.room.phase!=='finished';setPayload(old=>old.room&&data.room&&old.room.id===data.room.id&&old.room.revision>data.room.revision?old:data);setConnected(true);},[]);
  useEffect(()=>{if(!teacher)return;let active=true;void pilotAPI<{guardian:Guardian}>('teacher-battle/guardian').then(data=>{if(active)setGuardian(data.guardian);}).catch(()=>{});return()=>{active=false;};},[teacher]);
  useEffect(()=>{const current=++scope.current;let stopped=false;
    const poll=async()=>{if(!teacher&&!seat)return;try{const data=teacher?await pilotAPI<Payload>(`teacher-battle${roomId?`?id=${roomId}`:''}`):await publicAPI(projector?'projector':'state',seat);if(!stopped&&scope.current===current)accept(teacher&&!roomId&&data.room?.phase==='finished'?{room:null}:data);}catch(e){if(!stopped){setConnected(false);setError((e as Error).message);}}};
    // A projector is untouched on purpose: keep it live while a match is running, then let it rest.
    const stop=startPolling(poll,1500,{awake:()=>projector&&!!liveRoom.current});return()=>{stopped=true;stop();};
  },[teacher,projector,seat,roomId,accept]);
  async function run(task:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await task();}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}}
  async function command(data:Record<string,unknown>){if(!room)return;await run(async()=>{const body={...data,revision:room.revision,phase:room.phase,round:room.round,paused:room.paused,questionId:room.question?.id};const next=teacher?await pilotAPI<Payload>(`teacher-battle/act?id=${room.id}`,'POST',body):await publicAPI('act',seat,body);accept(next);if(data.action==='answer'&&next.room?.question?.solved)setDraft({id:'',text:''});});}
  function leave(){scope.current++;setSeat(null);setRoomId(null);setPayload({room:null});setError('');sessionStorage.removeItem(SEAT);sessionStorage.removeItem(HOST);}
  const host=room?.host===room?.you,mine=room?.members.find(m=>m.id===room.you),result=room?.results.at(-1);
  return <div className="tb-game">
    <header className="tb-heading"><div><p className="tb-eyebrow">Class pets vs. academy guardians</p><h1>Beat the Teacher</h1><p>Every solved problem powers your team.</p></div>{room&&<span className="tb-connection">{connected?'● Connected':'Reconnecting…'}</span>}</header>
    {error&&<p role="alert" className="tb-error">{error} <button onClick={leave}>Return to setup</button></p>}
    {!room&&!projector&&<div className="tb-setup"><GuardianPicture guardian={guardian} large/>
      {teacher?<div><h2>Your teacher guardian</h2><p>A detailed academy griffin, reserved for the teacher team.</p><fieldset disabled={busy}><label>Guardian name<input maxLength={24} value={guardian.name} onChange={e=>setGuardian({...guardian,name:e.target.value})}/></label><label>Guardian colors<select value={guardian.color} onChange={e=>setGuardian({...guardian,color:e.target.value as Guardian['color']})}>{COLORS.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>void run(async()=>{await pilotAPI('teacher-battle/guardian','POST',guardian);})}>Save my guardian</button><label>Your teacher nickname<input maxLength={24} value={alias} onChange={e=>setAlias(e.target.value)} placeholder="Captain Chalk"/></label><Level value={learning} onChange={setLearning}/><label>Rounds<select aria-label="Rounds" value={rounds} onChange={e=>setRounds(Number(e.target.value))}>{[1,3,5,7,10].map(n=><option key={n}>{n}</option>)}</select></label><button className="tb-primary" onClick={()=>void run(async()=>{const data=await pilotAPI<Payload>('teacher-battle/create','POST',{...guardian,alias,...learning,rounds});sessionStorage.setItem(HOST,JSON.stringify(data.room!.id));setRoomId(data.room!.id);accept(data);})}>Create teacher challenge</button><details><summary>Join as a co-teacher</summary><p>Sign in with your own teacher account. Ask the lead teacher for their private invitation.</p><label>Co-teacher invitation<input value={invite} onChange={e=>setInvite(e.target.value)}/></label><button onClick={()=>void run(async()=>{const data=await pilotAPI<Payload>('teacher-battle/join','POST',{...guardian,alias,invite});sessionStorage.setItem(HOST,JSON.stringify(data.room!.id));setRoomId(data.room!.id);accept(data);})}>Join teacher team</button></details></fieldset></div>
      :<form onSubmit={e=>{e.preventDefault();void run(async()=>{const data=await publicAPI('join',null,{code,alias,pet});const next={id:data.room!.id,token:data.token!};sessionStorage.setItem(SEAT,JSON.stringify(next));setSeat(next);accept(data);});}}><h2>Bring your pet to the challenge</h2><p>Use the match code from your teacher and a classroom nickname.</p><label>Match code<input value={code} onChange={e=>setCode(e.target.value)} maxLength={6} required/></label><label>Your nickname<input value={alias} onChange={e=>setAlias(e.target.value)} minLength={2} maxLength={24} required/></label><label>Battle avatar<select value={pet} onChange={e=>setPet(e.target.value)}>{Object.entries(GROWING_PETS).map(([id,p])=><option key={id} value={id}>{p.name} · {p.title}</option>)}</select></label><img className="tb-avatar-preview" src={petArt(pet)} alt="Chosen student companion"/><p>Your saved pet and progress stay unchanged.</p><button className="tb-primary" disabled={busy||!!seat}>Join the student team</button>{seat&&<button type="button" onClick={leave}>Clear saved seat</button>}</form>}
    </div>}
    {room&&<>
      <div className="tb-toolbar"><strong>{room.phase==='lobby'?'Gather your teams':`Round ${room.round} of ${room.rounds}`}</strong><span>Match code: <b className="tb-code">{room.code}</b></span>{teacher&&<button onClick={()=>setBoard(v=>!v)}>{board?'Show my controls':'Projector view on this screen'}</button>}{host&&payload.projectorToken&&<a target="_blank" rel="noreferrer" href={`/?teacherBattle=projector#id=${room.id}&token=${payload.projectorToken}`}>Open private projector</a>}</div>
      <Battlefield room={room}/>
      {!projector&&room.phase!=='finished'&&room.members.some(m=>m.id===room.you)&&<EmoteBar disabled={busy} send={emote=>void command({action:'emote',emote})}/>}
      {!board&&!projector&&room.phase==='lobby'&&<section className="tb-panel"><h2>Ready the class</h2><p>Students join at <a href="/?teacherBattle=join" target="_blank" rel="noreferrer">{location.origin}/?teacherBattle=join</a>. Each team gets up to 30 power per round. Extra adults share that power.</p>{host&&<details><summary>Invite up to two co-teachers</summary><p>Give this private invitation only to signed-in teachers: <strong>{room.invite}</strong></p></details>}
        <div className="tb-roster">{room.members.map(m=><div key={m.id}><strong>{m.alias} · {m.side==='teachers'?m.guardian?.name:'student pet'}</strong>{host&&m.learning&&<Level label={`${m.alias}'s math`} value={m.learning} onChange={v=>void command({action:'learning',memberId:m.id,...v})}/>} {host&&m.id!==room.host&&<button disabled={busy} onClick={()=>void command({action:'remove',memberId:m.id})}>Remove {m.alias}</button>}</div>)}</div>
        {host?<button className="tb-primary" disabled={busy||!room.members.some(m=>m.side==='students')} onClick={()=>void command({action:'next'})}>Start the challenge</button>:<p>Waiting for the lead teacher to start.</p>}
      </section>}
      {room.paused&&<p className="tb-pause" role="status">Time out. Take a breath—your place is saved.</p>}
      {!board&&!projector&&room.phase==='question'&&room.question&&<section className="tb-panel tb-question" key={room.question.id}>
        <p className="tb-eyebrow">{mine?.side==='teachers'?`${mine.guardian?.name} is ready`:'Your pet is ready'} · your private question</p><h2>{room.question.text}</h2>
        {room.question.solved?<p role="status" className="tb-success">Your {room.question.move} is charged! You helped your team. Wait for the reveal.</p>:<form onSubmit={e=>{e.preventDefault();void command({action:'answer',answer,move});}}><fieldset disabled={busy||room.paused}><div className="tb-moves">{([['strike','Strike','Send a chalk-light attack'],['guard','Guard','Block an incoming attack'],['rally','Rally','Restore your team’s castle']] as const).map(([id,label,help])=><label className={move===id?'selected':''} key={id}><input type="radio" name="move" value={id} checked={move===id} onChange={()=>setMove(id)}/><strong>{label}</strong><small>{help}</small></label>)}</div><label>Your answer<input ref={field} value={answer} onChange={e=>setDraft({id:room.question!.id,text:e.target.value})} autoComplete="off" inputMode="text" maxLength={60} required/></label><button className="tb-primary">Power my pet</button></fieldset>{room.question.attempts>0&&<p role="status">Not quite yet. Use the hint and try again—your power stays the same.</p>}<details><summary>Give me a hint</summary><p>{room.question.hint}</p></details></form>}
      </section>}
      {room.phase==='result'&&result&&<section className="tb-panel tb-result" key={result.round}><p className="tb-eyebrow">Round {result.round} · the pets spring into action</p><h2>{result.charged.students} student pets + {result.charged.teachers} teacher guardians powered up</h2><div className="tb-result-grid">{(['students','teachers'] as const).map(side=><div key={side}><h3>{side==='students'?'Student team':'Teacher team'}</h3><p>Blocked {Math.round(result.shield[side])} · restored {Math.round(result.healing[side])} · took {Math.round(result.damage[side])} damage</p></div>)}</div>{!board&&!projector&&room.question&&<details><summary>Review my math</summary><p>{room.question.text} = {room.question.answer}</p><p>{room.question.explanation?.join(' ')}</p></details>}</section>}
      {room.phase==='finished'&&<section className="tb-panel tb-finale"><p className="tb-eyebrow">Challenge complete</p><h2>{room.results.length===0?'Match ended before the first reveal':room.health.students===room.health.teachers?'A shared victory!':room.health.students>room.health.teachers?'The students win!':'The teacher guardians win!'}</h2><p>{room.results.reduce((n,r)=>n+r.charged.students+r.charged.teachers,0)} solved problems powered the battle. Everyone stayed in the action.</p>{!projector&&<button onClick={leave}>{teacher?'Set up another challenge':'Leave match'}</button>}</section>}
      {teacher&&!projector&&room.phase!=='finished'&&<div className="tb-host-controls"><button disabled={busy} onClick={()=>void command({action:'pause'})}>{room.paused?'Resume match':'Pause match'}</button>{host&&room.phase==='question'&&<button disabled={busy||room.paused} onClick={()=>{const unfinished=room.charged.teachers+room.charged.students<room.members.length;if(!unfinished||confirm('Some players are still working. Reveal this round now?'))void command({action:'next'});}}>Reveal team moves</button>}{host&&room.phase==='result'&&<button className="tb-primary" disabled={busy||room.paused} onClick={()=>void command({action:'next'})}>{room.round>=room.rounds||room.health.teachers<=0||room.health.students<=0?'Show match result':'Next round'}</button>}{host&&<button disabled={busy} onClick={()=>{if(confirm('End this match now?'))void command({action:'finish'});}}>End match</button>}</div>}
    </>}
  </div>;
}
function Battlefield({room}:{room:View}){const plan=guardianPlan(room.phase,room.health,room.results.at(-1));return <div className={`tb-battlefield ${room.phase==='result'?'tb-impact':''}`} key={`${room.round}-${room.phase}`} aria-label="Classroom battlefield"><div className="tb-stars" aria-hidden="true">✧ · ✦ · ✧</div>{(['students','teachers'] as const).map(side=><section className={`tb-side tb-side-${side}`} key={side}><h2>{side==='students'?'The student alliance':'The academy guardians'}</h2><div className="tb-health"><label>{side==='students'?'Student':'Teacher'} castle · {Math.ceil(room.health[side])}/100<progress max={100} value={room.health[side]}/></label></div><div className="tb-pets">{room.members.filter(m=>m.side===side).map(m=>{const e=room.emotes[m.id];const bubble=e&&<EmoteBubble key={e.at} {...e}/>;return side==='teachers'?<div className="tb-member" key={m.id}>{bubble}<GuardianPicture guardian={m.guardian} plan={plan}/><small>{m.alias}</small></div>:<figure className="tb-member" key={m.id}>{bubble}<img src={petArt(m.pet)} alt={`${m.alias}'s pet`}/><figcaption>{m.alias}</figcaption></figure>;})}</div><p>{room.charged[side]} / {room.members.filter(m=>m.side===side).length} pets charged</p></section>)}<span className="tb-versus" aria-hidden="true">VS</span>{room.phase==='result'&&<div className="tb-energy-wave" aria-hidden="true"/>}</div>;}
