import type { Achievement } from '../types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_feed',
    name: 'First Feeding',
    description: 'Feed your pet for the first time.',
    icon: '/assets/generated/final/item_apple.png',
    condition: { type: 'event_count', target: 1, eventType: 'pet_fed' },
    reward: { tokens: 10 },
  },
  {
    id: 'feed_10',
    name: 'Caretaker',
    description: 'Feed your pet 10 times.',
    icon: '/assets/generated/final/icon_hunger.png',
    condition: { type: 'event_count', target: 10, eventType: 'pet_fed' },
    reward: { tokens: 30 },
  },
  {
    id: 'clean_10',
    name: 'Clean Machine',
    description: 'Clean your pet 10 times.',
    icon: '/assets/generated/final/icon_clean.png',
    condition: { type: 'event_count', target: 10, eventType: 'pet_cleaned' },
    reward: { tokens: 30 },
  },
  {
    id: 'math_1',
    name: 'Math Starter',
    description: 'Solve your first math problem.',
    icon: '/assets/generated/final/math_number.png',
    condition: { type: 'event_count', target: 1, eventType: 'math_solved' },
    reward: { tokens: 10 },
  },
  {
    id: 'math_50',
    name: 'Math Whiz',
    description: 'Solve 50 math problems.',
    icon: '/assets/generated/final/math_number.png',
    condition: { type: 'event_count', target: 50, eventType: 'math_solved' },
    reward: { tokens: 100, coins: 2 },
  },
  {
    id: 'streak_5',
    name: 'On a Roll',
    description: 'Get a 5-answer streak.',
    icon: '/assets/generated/final/icon_streak_flame.png',
    condition: { type: 'streak', target: 5 },
    reward: { tokens: 25 },
  },
  {
    id: 'streak_10',
    name: 'Streak Master',
    description: 'Get a 10-answer streak.',
    icon: '/assets/generated/final/icon_token.png',
    condition: { type: 'streak', target: 10 },
    reward: { tokens: 50, coins: 1 },
  },
  {
    id: 'level_5',
    name: 'Growing Up',
    description: 'Reach level 5.',
    icon: '/assets/generated/final/effect_level_up.png',
    condition: { type: 'level_reached', target: 5 },
    reward: { tokens: 50 },
  },
  {
    id: 'level_15',
    name: 'Veteran',
    description: 'Reach level 15.',
    icon: '/assets/generated/final/icon_star.png',
    condition: { type: 'level_reached', target: 15 },
    reward: { tokens: 150, coins: 3 },
  },
  {
    id: 'hatched',
    name: 'Welcome to the World',
    description: 'Hatch your first egg.',
    icon: '🥚',
    condition: { type: 'event_count', target: 1, eventType: 'pet_hatched' },
    reward: { tokens: 20 },
  },
  {
    id: 'evolved',
    name: 'Evolution!',
    description: 'Evolve your pet.',
    icon: '/assets/generated/final/effect_sparkle.png',
    condition: { type: 'event_count', target: 1, eventType: 'pet_evolved' },
    reward: { tokens: 100, coins: 2 },
  },
  {
    id: 'rich',
    name: 'Loaded',
    description: 'Accumulate 1000 tokens.',
    icon: '/assets/generated/final/reward_coin_stack.png',
    condition: { type: 'need_threshold', target: 1000, needKey: 'hunger' },
    reward: { coins: 5 },
  },
  {
    id: 'battle_win',
    name: 'First Victory',
    description: 'Win your first battle.',
    icon: '/assets/generated/final/reward_trophy_gold.png',
    condition: { type: 'event_count', target: 1, eventType: 'battle_won' },
    reward: { tokens: 50 },
  },
];
