import type { SpriteSheetConfig } from '../engine/animation/types';

export interface BaseAssetConfig {
  url: string;
  alt: string;
}

export type PetAssetConfig = SpriteSheetConfig;

export interface CombatSheetConfig {
  url: string;
  frameCount: number;
  frameWidth: number;
  frameHeight: number;
  frameDuration: number;
}

export interface AssetManifest {
  eggs: Record<string, BaseAssetConfig>;
  pets: Record<string, PetAssetConfig>;
  petPortraits: Record<string, string>;
  /** Per-species combat animation sheets: { speciesId: { attack, special } } */
  combatAnims: Record<string, Record<string, CombatSheetConfig>>;
  backgrounds: Record<string, string>;
  icons: Record<string, string>;
  effects: Record<string, string>;
  scenes: Record<string, string>;
}

export const ASSETS: AssetManifest = {
  eggs: {
    basic: {
      url: '/assets/generated/final/egg_default.png',
      alt: 'Basic Egg',
    },
    mech: {
      url: '/assets/generated/final/egg_cracking.png',
      alt: 'Mech Egg',
    },
    magic: {
      url: '/assets/generated/final/egg_glowing.png',
      alt: 'Magic Egg',
    },
  },
  pets: {
    slime_baby: {
      url: '/assets/koala_sprite.png',
      alt: 'Slime Baby',
      spriteSheet: true,
      cols: 5,
      rows: 4,
      frameWidth: 128,
      frameHeight: 128,
      frames: 20,
      groundOffsetY: 13,
      animations: {
        idle: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        hungry: { startFrame: 5, endFrame: 9, frameDuration: 160 },
        happy: { startFrame: 10, endFrame: 14, frameDuration: 140 },
        sleeping: { startFrame: 15, endFrame: 19, frameDuration: 240 },
        sick: { startFrame: 5, endFrame: 9, frameDuration: 300 },
        dead: { startFrame: 15, endFrame: 15, frameDuration: 1000 },
      },
    },
    mech_bot: {
      url: '/assets/koala_sprite.png',
      alt: 'Mech Bot',
      spriteSheet: true,
      cols: 5,
      rows: 4,
      frameWidth: 128,
      frameHeight: 128,
      frames: 20,
      groundOffsetY: 13,
      animations: {
        idle: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        hungry: { startFrame: 5, endFrame: 9, frameDuration: 160 },
        happy: { startFrame: 10, endFrame: 14, frameDuration: 140 },
        sleeping: { startFrame: 15, endFrame: 19, frameDuration: 240 },
        sick: { startFrame: 5, endFrame: 9, frameDuration: 300 },
        dead: { startFrame: 15, endFrame: 15, frameDuration: 1000 },
      },
    },
    koala_sprite: {
      url: '/assets/koala_sprite.png',
      alt: 'Blue Koala',
      spriteSheet: true,
      cols: 5,
      rows: 4,
      frameWidth: 128,
      frameHeight: 128,
      frames: 20,
      groundOffsetY: 13,
      animations: {
        idle: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        hungry: { startFrame: 5, endFrame: 9, frameDuration: 160 },
        happy: { startFrame: 10, endFrame: 14, frameDuration: 140 },
        sleeping: { startFrame: 15, endFrame: 19, frameDuration: 240 },
        sick: { startFrame: 5, endFrame: 9, frameDuration: 300 },
        dead: { startFrame: 15, endFrame: 15, frameDuration: 1000 },
      },
    },
    // Mood-specific override sheets for koala_sprite (16 frames each, single-row)
    koala_sprite__idle: {
      url: '/assets/pets/blue-koala/mood/idle-sheet.png',
      alt: 'Blue Koala Idle',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__hungry: {
      url: '/assets/pets/blue-koala/mood/hungry-sheet.png',
      alt: 'Blue Koala Hungry',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__happy: {
      url: '/assets/pets/blue-koala/mood/idle-sheet.png',
      alt: 'Blue Koala Happy',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 150 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    // ── Blue Koala care interaction sprites (16-frame sheets) ──────
    koala_sprite__being_petted: {
      url: '/assets/pets/blue-koala/care/petted.png',
      alt: 'Blue Koala Being Petted',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_petted: { startFrame: 0, endFrame: 15, frameDuration: 150 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 150 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__being_washed: {
      url: '/assets/pets/blue-koala/care/washed.png',
      alt: 'Blue Koala Being Washed',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_washed: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__being_brushed: {
      url: '/assets/pets/blue-koala/care/brushing.png',
      alt: 'Blue Koala Being Brushed',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_brushed: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__being_comforted: {
      url: '/assets/pets/blue-koala/care/comfort.png',
      alt: 'Blue Koala Being Comforted',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_comforted: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__being_trained: {
      url: '/assets/pets/blue-koala/care/training.png',
      alt: 'Blue Koala Being Trained',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_trained: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__playing_with_hand: {
      url: '/assets/pets/blue-koala/care/play.png',
      alt: 'Blue Koala Playing',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        playing_with_hand: { startFrame: 0, endFrame: 15, frameDuration: 130 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 130 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__eating: {
      url: '/assets/pets/blue-koala/eating/sheet.png',
      alt: 'Blue Koala Eating',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        eating: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    koala_sprite__walking: {
      url: '/assets/pets/blue-koala/walking/sheet.png',
      alt: 'Blue Koala Walking',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        walking: { startFrame: 0, endFrame: 15, frameDuration: 90 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 120 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    blue_koala_adult_walk: {
      url: '/assets/pets/blue-koala/adult-walk/koala_sprite.png',
      alt: 'Blue Koala Adult Walk',
      spriteSheet: true,
      cols: 5,
      rows: 4,
      frameWidth: 128,
      frameHeight: 128,
      frames: 20,
      groundOffsetY: 13,
      animations: {
        idle: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        hungry: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 4, frameDuration: 180 },
        dead: { startFrame: 0, endFrame: 4, frameDuration: 1000 },
      },
    },
    blue_koala_hatching: {
      url: '/assets/pets/blue-koala/hatching/blue-koala-hatching.png',
      alt: 'Blue Koala Hatching',
      spriteSheet: true,
      cols: 17,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 17,
      groundOffsetY: 26,
      animations: {
        idle: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        hungry: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        dead: { startFrame: 16, endFrame: 16, frameDuration: 1000 },
      },
    },
    blue_koala_dancing: {
      url: '/assets/pets/blue-koala/dancing/blue-koala-dancing.png',
      alt: 'Blue Koala Dancing',
      spriteSheet: true,
      cols: 36,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 36,
      groundOffsetY: 16,
      animations: {
        idle: { startFrame: 0, endFrame: 35, frameDuration: 150 },
        hungry: { startFrame: 0, endFrame: 35, frameDuration: 150 },
        happy: { startFrame: 0, endFrame: 35, frameDuration: 150 },
        sleeping: { startFrame: 0, endFrame: 35, frameDuration: 150 },
        sick: { startFrame: 0, endFrame: 35, frameDuration: 150 },
        dead: { startFrame: 35, endFrame: 35, frameDuration: 1000 },
      },
    },
    blue_koala_cleaning: {
      url: '/assets/pets/blue-koala/cleaning/blue-koala-cleaning.png',
      alt: 'Blue Koala Cleaning',
      spriteSheet: true,
      cols: 20,
      rows: 1,
      frameWidth: 115,
      frameHeight: 85,
      frames: 20,
      groundOffsetY: 13,
      animations: {
        idle: { startFrame: 0, endFrame: 19, frameDuration: 180 },
        hungry: { startFrame: 0, endFrame: 19, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 19, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 19, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 19, frameDuration: 180 },
        dead: { startFrame: 19, endFrame: 19, frameDuration: 1000 },
      },
    },
    // ─── Subtrak ─────────────────────────────────────────────────────
    subtrak: {
      url: '/assets/pets/subtrak/idle/sheet.png',
      alt: 'Subtrak',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__idle: {
      url: '/assets/pets/subtrak/idle/sheet.png',
      alt: 'Subtrak Idle',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 200 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 320 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 200 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 200 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 320 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__sleeping: {
      url: '/assets/pets/subtrak/idle_variant/sheet.png',
      alt: 'Subtrak Sleeping',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 280 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 320 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 280 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 280 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 320 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__hungry: {
      url: '/assets/pets/subtrak/hungry/sheet.png',
      alt: 'Subtrak Hungry',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__happy: {
      url: '/assets/pets/subtrak/walk/sheet.png',
      alt: 'Subtrak Happy',
      spriteSheet: true,
      cols: 17,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 17,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 16, frameDuration: 150 },
        sleeping: { startFrame: 0, endFrame: 16, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 16, frameDuration: 150 },
        happy: { startFrame: 0, endFrame: 16, frameDuration: 150 },
        sick: { startFrame: 0, endFrame: 16, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__sick: {
      url: '/assets/pets/subtrak/sad/sheet.png',
      alt: 'Subtrak Sick',
      spriteSheet: true,
      cols: 15,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 15,
      groundOffsetY: 40,
      animations: {
        idle: { startFrame: 0, endFrame: 14, frameDuration: 250 },
        sleeping: { startFrame: 0, endFrame: 14, frameDuration: 350 },
        hungry: { startFrame: 0, endFrame: 14, frameDuration: 250 },
        happy: { startFrame: 0, endFrame: 14, frameDuration: 250 },
        sick: { startFrame: 0, endFrame: 14, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    // ── Subtrak care interaction sprites (16-frame sheets) ──────────
    subtrak__being_petted: {
      url: '/assets/pets/subtrak/care/petting.png',
      alt: 'Subtrak Being Petted',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_petted: { startFrame: 0, endFrame: 15, frameDuration: 150 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 150 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__being_washed: {
      url: '/assets/pets/subtrak/care/washed.png',
      alt: 'Subtrak Being Washed',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_washed: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__being_brushed: {
      url: '/assets/pets/subtrak/care/brushed.png',
      alt: 'Subtrak Being Brushed',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_brushed: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 160 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__being_comforted: {
      url: '/assets/pets/subtrak/care/comfort.png',
      alt: 'Subtrak Being Comforted',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_comforted: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__being_trained: {
      url: '/assets/pets/subtrak/care/training.png',
      alt: 'Subtrak Being Trained',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        being_trained: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__playing_with_hand: {
      url: '/assets/pets/subtrak/care/play.png',
      alt: 'Subtrak Playing',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        playing_with_hand: { startFrame: 0, endFrame: 15, frameDuration: 130 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 130 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__eating: {
      url: '/assets/pets/subtrak/eating/sheet.png',
      alt: 'Subtrak Eating',
      spriteSheet: true,
      cols: 16,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 16,
      groundOffsetY: 40,
      animations: {
        eating: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        idle: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 15, frameDuration: 140 },
        hungry: { startFrame: 0, endFrame: 15, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        sick: { startFrame: 0, endFrame: 15, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
    subtrak__walking: {
      url: '/assets/pets/subtrak/walk/sheet.png',
      alt: 'Subtrak Walking',
      spriteSheet: true,
      cols: 17,
      rows: 1,
      frameWidth: 128,
      frameHeight: 128,
      frames: 17,
      groundOffsetY: 40,
      animations: {
        walking: { startFrame: 0, endFrame: 16, frameDuration: 90 },
        idle: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        happy: { startFrame: 0, endFrame: 16, frameDuration: 120 },
        hungry: { startFrame: 0, endFrame: 16, frameDuration: 180 },
        sleeping: { startFrame: 0, endFrame: 16, frameDuration: 300 },
        sick: { startFrame: 0, endFrame: 16, frameDuration: 300 },
        dead: { startFrame: 0, endFrame: 0, frameDuration: 1000 },
      },
    },
  },
  backgrounds: {
    incubator: 'linear-gradient(180deg, #1e293b 0%, #0f172a 100%)',
    chamber: 'radial-gradient(circle at center, #334155 0%, #0f172a 100%)',
  },
  petPortraits: {
    slime_baby: '/assets/generated/final/pet_slime_baby.png',
    mech_bot: '/assets/generated/final/pet_mech_bot.png',
    koala_sprite: '/assets/pets/blue-koala/portrait.png',
    subtrak: '/assets/pets/subtrak/portrait.png',
  },
  combatAnims: {
    koala_sprite: {
      attack: {
        url: '/assets/pets/blue-koala/fighting/attack-sheet.png',
        frameCount: 15,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 60,
      },
      special: {
        url: '/assets/pets/blue-koala/fighting/special-sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 60,
      },
      defend: {
        url: '/assets/pets/blue-koala/fighting/defend-sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 70,
      },
      hurt: {
        url: '/assets/pets/blue-koala/fighting/hurt-sheet.png',
        frameCount: 9,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 80,
      },
      heal: {
        url: '/assets/pets/blue-koala/fighting/heal-sheet.png',
        frameCount: 18,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 70,
      },
      math: {
        url: '/assets/pets/blue-koala/fighting/math-sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 65,
      },
    },
    subtrak: {
      attack: {
        url: '/assets/pets/subtrak/attack_special/sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 60,
      },
      special: {
        url: '/assets/pets/subtrak/power_up/sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 60,
      },
      defend: {
        url: '/assets/pets/subtrak/defend/sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 70,
      },
      hurt: {
        url: '/assets/pets/subtrak/hurt/sheet.png',
        frameCount: 18,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 80,
      },
      heal: {
        url: '/assets/pets/subtrak/heal/sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 70,
      },
      math: {
        url: '/assets/pets/subtrak/power_up/sheet.png',
        frameCount: 16,
        frameWidth: 128,
        frameHeight: 128,
        frameDuration: 65,
      },
    },
  },
  icons: {
    heart: '/assets/generated/final/icon_heart.png',
    food: '/assets/generated/final/icon_hunger.png',
    energy: '/assets/generated/final/icon_token.png',
    clean: '/assets/generated/final/icon_clean.png',
    train: '/assets/generated/final/icon_energy.png',
    shield: '/assets/generated/final/icon_shield.png',
    sword: '/assets/generated/final/icon_sword.png',
    pvp: '/assets/generated/final/icon_pvp_swords.png',
    settings: '/assets/generated/final/icon_settings.png',
    speed: '/assets/generated/final/icon_speed_boot.png',
    armor: '/assets/generated/final/icon_armor.png',
    play: '/assets/generated/final/icon_play_button.png',
  },
  effects: {
    shieldBubble: '/assets/generated/final/effect_shield_bubble.png',
    runeGlyph: '/assets/generated/final/effect_rune_glyph.png',
    tracePerfect: '/assets/generated/final/effect_trace_perfect.png',
    traceFail: '/assets/generated/final/effect_trace_fail.png',
    // Combat effects
    slash: '/assets/generated/final/effect_slash.png',
    slam: '/assets/generated/final/effect_slam.png',
    lightning: '/assets/generated/final/effect_lightning.png',
    overcharge: '/assets/generated/final/effect_overcharge.png',
    slime: '/assets/generated/final/effect_slime.png',
    acid: '/assets/generated/final/effect_acid.png',
    shieldFlash: '/assets/generated/final/effect_shield_flash.png',
    absorb: '/assets/generated/final/effect_absorb.png',
    tackle: '/assets/generated/final/effect_tackle.png',
    repair: '/assets/generated/final/effect_repair.png',
    energyNova: '/assets/generated/final/effect_energy_nova.png',
    critical: '/assets/generated/final/effect_critical.png',
  },
  scenes: {
    battleArena: '/assets/generated/final/scene_battle_arena.png',
    mathTraining: '/assets/generated/final/scene_math_training.png',
    strategyChamber: '/assets/generated/final/scene_strategy_chamber.png',
    shopInterior: '/assets/generated/final/scene_shop_interior.png',
  },
};

// ── Hand cursor sprite sheets ────────────────────────────────────────

export interface HandSpriteConfig {
  url: string;
  cols: number;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  frameDuration: number;
}

export const HAND_ASSETS: Record<string, HandSpriteConfig> = {
  idle: {
    url: '/assets/hand/hand_idle.png',
    cols: 9,
    frameWidth: 256,
    frameHeight: 256,
    frames: 9,
    frameDuration: 120,
  },
  rub: {
    url: '/assets/hand/hand_rub.png',
    cols: 4,
    frameWidth: 256,
    frameHeight: 256,
    frames: 4,
    frameDuration: 140,
  },
};

/** Maps HandAnimState → HAND_ASSETS key. Missing = falls back to 'idle'. */
export const HAND_ANIM_TO_ASSET: Record<string, string> = {
  HAND_IDLE:  'idle',
  HAND_RUB:   'rub',
  HAND_TAP:   'rub',
  HAND_SCRUB: 'rub',    // TODO: dedicated scrub sheet
  HAND_HOLD:  'idle',   // TODO: dedicated hold sheet
  HAND_DRAG:  'rub',    // TODO: dedicated drag sheet
};

export type AssetType = typeof ASSETS;
export type EggType = keyof typeof ASSETS.eggs;
export type PetType = keyof typeof ASSETS.pets;
