import type { QuestTemplate } from '../types/quest';

/**
 * Quest templates. The QuestSystem rolls a subset of these at the start of
 * each day/week. Keep targets modest — these must be completable in a
 * single play session so kids always finish what they start.
 */

export const DAILY_QUESTS: QuestTemplate[] = [
  // --- Care ----------------------------------------------------------
  {
    id: 'daily_feed_3',
    cadence: 'daily',
    title: 'Breakfast, Lunch & Dinner',
    blurb: 'Feed your pet 3 times today.',
    icon: '/assets/generated/final/item_apple.png',
    target: 3,
    goal: { kind: 'event_count', eventType: 'pet_fed' },
    reward: { tokens: 25, seasonPoints: 20 },
    weight: 3,
  },
  {
    id: 'daily_clean_2',
    cadence: 'daily',
    title: 'Scrub-a-dub',
    blurb: 'Clean your pet 2 times.',
    icon: '/assets/generated/final/icon_clean.png',
    target: 2,
    goal: { kind: 'event_count', eventType: 'pet_cleaned' },
    reward: { tokens: 20, seasonPoints: 15 },
    weight: 3,
  },
  {
    id: 'daily_play_3',
    cadence: 'daily',
    title: 'Play Together',
    blurb: 'Play with your pet 3 times.',
    icon: '/assets/generated/final/item_ball.png',
    target: 3,
    goal: { kind: 'event_count', eventType: 'pet_played_with' },
    reward: { tokens: 20, seasonPoints: 15 },
    weight: 3,
  },
  {
    id: 'daily_foodie',
    cadence: 'daily',
    title: 'Foodie',
    blurb: 'Feed 3 different foods today.',
    icon: '/assets/generated/final/item_cake.png',
    target: 3,
    goal: { kind: 'distinct_foods_fed' },
    reward: { tokens: 30, seasonPoints: 20, shards: 1 },
    weight: 2,
  },
  {
    id: 'daily_all_rounder',
    cadence: 'daily',
    title: 'All Rounder',
    blurb: 'Do 3 different care interactions.',
    icon: '/assets/generated/final/item_brush.png',
    target: 3,
    goal: { kind: 'distinct_interactions' },
    reward: { tokens: 35, seasonPoints: 25 },
    weight: 2,
  },

  // --- Math ---------------------------------------------------------
  {
    id: 'daily_math_10',
    cadence: 'daily',
    title: 'Brain Warm-Up',
    blurb: 'Solve 10 math problems.',
    icon: '/assets/generated/final/math_number.png',
    target: 10,
    goal: { kind: 'event_count', eventType: 'math_solved' },
    reward: { tokens: 30, seasonPoints: 25 },
    weight: 4,
  },
  {
    id: 'daily_math_20',
    cadence: 'daily',
    title: 'Power Brain',
    blurb: 'Solve 20 math problems.',
    icon: '/assets/generated/final/math_number.png',
    target: 20,
    goal: { kind: 'event_count', eventType: 'math_solved' },
    reward: { tokens: 50, seasonPoints: 40 },
    weight: 2,
  },
  {
    id: 'daily_streak_5',
    cadence: 'daily',
    title: 'On Fire',
    blurb: 'Get a math streak of 5.',
    icon: '/assets/generated/final/icon_streak_flame.png',
    target: 5,
    goal: { kind: 'math_streak_at_least' },
    reward: { tokens: 25, seasonPoints: 20 },
    weight: 3,
  },
  {
    id: 'daily_streak_10',
    cadence: 'daily',
    title: 'Unstoppable',
    blurb: 'Reach a math streak of 10.',
    icon: '/assets/generated/final/icon_streak_flame.png',
    target: 10,
    goal: { kind: 'math_streak_at_least' },
    reward: { tokens: 50, seasonPoints: 35, shards: 1 },
    weight: 2,
  },

  // --- Battle -------------------------------------------------------
  {
    id: 'daily_battle_win_1',
    cadence: 'daily',
    title: 'Victory!',
    blurb: 'Win 1 battle.',
    icon: '/assets/generated/final/reward_trophy_gold.png',
    target: 1,
    goal: { kind: 'event_count', eventType: 'battle_won' },
    reward: { tokens: 25, seasonPoints: 20 },
    weight: 4,
  },
  {
    id: 'daily_battle_win_3',
    cadence: 'daily',
    title: 'Triple Threat',
    blurb: 'Win 3 battles.',
    icon: '/assets/generated/final/reward_trophy_gold.png',
    target: 3,
    goal: { kind: 'event_count', eventType: 'battle_won' },
    reward: { tokens: 60, seasonPoints: 45 },
    weight: 2,
  },
  {
    id: 'daily_pvp_win',
    cadence: 'daily',
    title: 'Classmate Showdown',
    blurb: 'Win a PvP battle.',
    icon: '/assets/generated/final/icon_star.png',
    target: 1,
    goal: { kind: 'event_count', eventType: 'pvp_battle_won' },
    reward: { tokens: 40, seasonPoints: 30 },
    weight: 3,
  },

  // --- Progression --------------------------------------------------
  {
    id: 'daily_earn_ticket',
    cadence: 'daily',
    title: 'Earn Your Ticket',
    blurb: 'Earn a battle ticket today.',
    icon: '/assets/generated/final/icon_token.png',
    target: 1,
    goal: { kind: 'event_count', eventType: 'ticket_earned' },
    reward: { tokens: 20, seasonPoints: 15 },
    weight: 3,
  },
  {
    id: 'daily_shop',
    cadence: 'daily',
    title: 'Shopping Spree',
    blurb: 'Purchase an item from the shop.',
    icon: '/assets/generated/final/reward_coin_stack.png',
    target: 1,
    goal: { kind: 'event_count', eventType: 'item_purchased' },
    reward: { tokens: 15, seasonPoints: 15 },
    weight: 2,
  },
];

export const WEEKLY_QUESTS: QuestTemplate[] = [
  {
    id: 'weekly_math_100',
    cadence: 'weekly',
    title: 'Math Marathon',
    blurb: 'Solve 100 math problems this week.',
    icon: '/assets/generated/final/math_number.png',
    target: 100,
    goal: { kind: 'event_count', eventType: 'math_solved' },
    reward: { tokens: 200, seasonPoints: 150, shards: 3 },
  },
  {
    id: 'weekly_battles_10',
    cadence: 'weekly',
    title: 'Battle Veteran',
    blurb: 'Win 10 battles this week.',
    icon: '/assets/generated/final/reward_trophy_gold.png',
    target: 10,
    goal: { kind: 'event_count', eventType: 'battle_won' },
    reward: { tokens: 180, seasonPoints: 140, shards: 2 },
  },
  {
    id: 'weekly_care_30',
    cadence: 'weekly',
    title: 'Devoted Caretaker',
    blurb: 'Feed + clean + play 30 times combined.',
    icon: '/assets/generated/final/icon_hunger.png',
    target: 30,
    goal: { kind: 'event_count', eventType: 'pet_fed' }, // system also counts clean/play
    reward: { tokens: 150, seasonPoints: 120, shards: 2 },
  },
  {
    id: 'weekly_bond_25',
    cadence: 'weekly',
    title: 'Best Friends',
    blurb: "Reach bond level 25 with your pet.",
    icon: '/assets/generated/final/icon_star.png',
    target: 25,
    goal: { kind: 'bond_reach' },
    reward: { tokens: 150, seasonPoints: 130 },
  },
  {
    id: 'weekly_level',
    cadence: 'weekly',
    title: 'Level Up!',
    blurb: 'Reach level 5.',
    icon: '/assets/generated/final/effect_level_up.png',
    target: 5,
    goal: { kind: 'level_reach' },
    reward: { tokens: 250, seasonPoints: 200, shards: 5 },
  },
];
