import {describe,it,expect} from 'vitest';
import {TRACKS} from './catalog';
import {startRun,question,piece,correct,drop,landing,emptyBoard} from './game';
import {stackCommand,parseStack,validStack} from './model';
import {createInitialEngineState} from '../../engine/state/createInitialEngineState';
function solution(r:ReturnType<typeof startRun>){const q=question(r);for(let a=0;a<q.palette.length;a++)for(let b=0;b<q.palette.length;b++){if(correct([...piece(r,0,0,a).map(p=>p.v),...piece(r,0,0,b).map(p=>p.v)],q))return[a,b];}throw new Error('Unsolvable '+r.track);}
describe('Math Stack',()=>{
 it('all K–9 tracks generate solvable puzzles with real row validation',()=>{for(const t of TRACKS)for(let seed=1;seed<=40;seed++){let r=startRun('test',t.id,'learn',1,seed);for(let i=0;i<5;i++){const [a,b]=solution(r);const first=drop(r,{tray:0,rotation:0,value:a,x:0});expect(first.solved).toBe(false);const second=drop(first.run,{tray:0,rotation:0,value:b,x:4});expect(second.solved,`${t.id}:${seed}:${i}`).toBe(true);r=second.run;}expect(r.status).toBe('won');expect(r.round).toBe(5);}});
 it('rejects incorrect rows without erasing existing blocks',()=>{const r=startRun('t','bonds','learn',1,1);const a=drop(r,{tray:0,rotation:0,value:0,x:0}).run;const b=drop(a,{tray:0,rotation:0,value:0,x:4});expect(b.wrong).toBe(true);expect(b.run.board).toEqual(a.board);expect(b.run.mistakes).toBe(1);expect(b.run.round).toBe(0);});
 it('handles rotation, edges, gravity and top-out',()=>{const r=startRun('t','add','learn',1,1);expect(landing(r,0,1,1,7)).toBe(8);expect(landing(r,0,0,1,7)).toBe(-1);r.board[0][2]={n:1,x:0,color:0};expect(drop(r,{tray:0,rotation:0,value:1,x:2}).run.status).toBe('blocked');});
 it('earns one receipt, keeps classroom settings and cannot replay a solved move',()=>{let s=createInitialEngineState();const settings=structuredClone(s.learning);s=stackCommand(s,{kind:'start',track:'add',mode:'learn'});const r=s.mathStack!.run!,[a,b]=solution(r),mp=s.player.currencies.mp;s=stackCommand(s,{kind:'drop',revision:0,tray:0,rotation:0,value:a,x:0});const c={kind:'drop' as const,revision:1,tray:0,rotation:0,value:b,x:4};s=stackCommand(s,c);expect(s.player.currencies.mp-mp).toBe(2);expect(s.learningEvidence?.at(-1)?.source).toBe('math-stack');expect(s.learning).toEqual(settings);expect(()=>stackCommand(s,c)).toThrow();expect(s.mathStack!.run!.previous).toBeNull();expect(validStack(s.mathStack)).toBe(true);});
 it('undoes only an unsolved move and records examples as supported practice',()=>{let s=createInitialEngineState();s=stackCommand(s,{kind:'start',track:'factor',mode:'learn'});s=stackCommand(s,{kind:'explain',revision:0});expect(s.learningEvidence?.at(-1)?.answerRevealed).toBe(true);s=stackCommand(s,{kind:'drop',revision:1,tray:0,rotation:0,value:0,x:0});s=stackCommand(s,{kind:'undo',revision:2});expect(s.mathStack!.run!.board).toEqual(emptyBoard());expect(()=>stackCommand(s,{kind:'undo',revision:3})).toThrow();});
 it('validates corrupt saves and untrusted commands',()=>{expect(validStack(undefined)).toBe(true);expect(validStack({version:1} as never)).toBe(false);for(const value of [null,{kind:'drop',revision:0,tray:0,rotation:800,value:0,x:0},{kind:'start',track:'fake',mode:'learn'}])expect(()=>parseStack(value)).toThrow();});
 it('caps daily rewards while continuing practice and scores',()=>{let s=createInitialEngineState();s=stackCommand(s,{kind:'start',track:'bonds',mode:'learn'});s.mathStack!.rewardDay=new Date().toISOString().slice(0,10);s.mathStack!.rewardCount=20;const [a,b]=solution(s.mathStack!.run!),mp=s.player.currencies.mp;s=stackCommand(s,{kind:'drop',revision:0,tray:0,rotation:0,value:a,x:0});s=stackCommand(s,{kind:'drop',revision:1,tray:0,rotation:0,value:b,x:4});expect(s.player.currencies.mp).toBe(mp);expect(s.mathStack!.run!.round).toBe(1);expect(s.learningEvidence?.at(-1)?.correct).toBe(true);});
});
