import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type {EngineState} from '../../types/engine';
import type {GameEngineAction} from '../../engine/core/ActionTypes';
import {PetSprite} from '../../components/pet/PetSprite';
import {TRACKS,track,HEIGHT,SHAPE_NAMES,type Track} from './catalog';
import {question,piece,shape,landing,fits,label,describe,correct,type Run,type Cell,type Drop} from './game';
import type {StackCommand} from './model';
import './math-stack.css';
type Props={state:EngineState;dispatch:(a:GameEngineAction)=>void;execute?:(c:StackCommand)=>Promise<void>};
export default function MathStack({state,dispatch,execute}:Props){
 const [skill,setSkill]=useState<Track>(()=>TRACKS.find(t=>t.grade===Math.min(9,state.learning.grade))?.id??'bonds'),[mode,setMode]=useState<'learn'|'arcade'>('learn'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[menu,setMenu]=useState(false),[demo,setDemo]=useState(false);
 const lock=useRef(false),run=state.mathStack?.run,pet=state.pet;
 async function send(c:StackCommand){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(execute)await execute(c);else dispatch({type:'MATH_STACK_COMMAND',command:c});}catch(e){setError(e instanceof Error?e.message:'Could not save this move.');}finally{lock.current=false;setBusy(false);}}
 const start=async()=>{await send({kind:'start',track:skill,mode});setMenu(false);};
 return <main className="math-stack" data-testid="math-stack"><header className="ms-header"><button onClick={()=>dispatch({type:'SET_SCREEN',screen:'play'})}>← Games</button><div><small>THE BLOCKWORK GARDEN</small><h1>Math Stack</h1><p>Build the answer. Clear the sky.</p></div><button aria-pressed={menu} onClick={()=>setMenu(!menu)}>Skills & modes</button></header>
 {error&&<p className="ms-error" role="alert">{error}</p>}
 {(!run||menu)&&<section className="ms-lobby"><div><span className="ms-eyebrow">YOUR NEXT ADVENTURE</span><h2>Think it. Stack it. Clear it.</h2><p>Move and rotate falling shapes. A full row clears only when its blocks solve the math. Every block counts!</p><p className="ms-small">Suggested from your assigned grade: {state.learning.grade===0?'Kindergarten':`Grade ${state.learning.grade}`}. Pick a skill to practice; your school assignment stays unchanged.</p></div><div className="ms-tools"><button onClick={()=>setSkill('bonds')}>Start with Kindergarten</button><button onClick={()=>setSkill('add')}>Start with Grade 1</button></div><label>Math trail<select value={skill} onChange={e=>setSkill(e.target.value as Track)}>{TRACKS.map(t=><option key={t.id} value={t.id}>{t.grade===0?'K':`Grade ${t.grade}`} · {t.name} · {t.skill}</option>)}</select></label><div className="ms-modes"><button aria-pressed={mode==='learn'} onClick={()=>setMode('learn')}><strong>Learn & build</strong><span>No falling timer. Think, rotate, and drop when ready.</span></button><button aria-pressed={mode==='arcade'} onClick={()=>setMode('arcade')}><strong>Falling challenge</strong><span>Pieces descend. Pause whenever you need thinking time.</span></button></div><p>{track(skill).detail} · Five puzzles per adventure.</p><button className="ms-primary" disabled={busy} onClick={()=>void start()}>{run?.status==='playing'?'Start a new adventure (replaces this board)':'Start stacking →'}</button>{run&&<button onClick={()=>setMenu(false)}>Return to saved board</button>}</section>}
 {run&&!menu&&<div className="ms-layout"><aside className="ms-side"><div className="ms-pet-card">{pet?<PetSprite speciesId={pet.speciesId} stage={pet.stage} animationName={run.lastClear?'happy':'idle'} scale={.6} equippedCosmetics={state.cosmetics.equipped[pet.id]}/>:<span className="ms-egg" aria-hidden="true">◈</span>}<div><small>YOUR STACKING BUDDY</small><strong>{pet?.name??'Your future companion'}</strong><p>{run.status==='won'?'We built that together!':run.mistakes?'Let’s try another way. You can do this!':'A little thinking. A brilliant landing.'}</p></div></div><div className="ms-stats"><span><b>{run.score}</b>score</span><span><b>{run.round}/5</b>puzzles</span><span><b>{state.mathStack?.best[run.track]??0}</b>best</span></div><div className="ms-goal"><small>{track(run.track).skill.toUpperCase()} · LEVEL {run.level}</small><h2>{question(run).prompt}</h2><p>{track(run.track).detail}</p>{question(run).kind==='factor'&&<strong>Left half: (x + a)<br/>Right half: (x + b)</strong>}<button disabled={busy||run.status==='won'} onClick={()=>void send({kind:'hint',revision:run.revision})}>Give me a hint</button><button disabled={busy} onClick={()=>{setDemo(true);if(run.status!=='won')void send({kind:'explain',revision:run.revision});}}>▶ Watch an example</button></div><details className="ms-instructions"><summary>How to play & controls</summary><ol><li>Choose one of three shapes, then the value on its blocks.</li><li>Move left/right and rotate. The outline shows the landing spot.</li><li>Drop. All eight spaces in a row must be filled and solve the goal.</li><li>A correct row clears the puzzle. Solve five to finish an adventure.</li></ol><p>← → move · ↑ rotate · ↓ lower · Space drop · P pause. Buttons work on touchscreens. Wrong totals return your piece, with a hint about what went wrong. Undo only affects the latest unsolved placement.</p></details><p className="ms-rewards">{state.mathStack?.notice}</p></aside>
 <section className="ms-play"><div className="ms-board-heading"><span>{track(run.track).name}</span><strong>{run.mode==='learn'?'No timer':'Falling challenge'}</strong></div>{run.status==='won'?<div className="ms-victory"><div aria-hidden="true">✦</div><h2>Brilliant building!</h2><p>Five real math puzzles solved.</p><b>{run.score} points · {run.cleared} rows</b><p>{state.mathStack?.notice}</p><button className="ms-primary" disabled={busy} onClick={()=>void send({kind:'start',track:run.track,mode:run.mode})}>Next adventure →</button><button onClick={()=>setMenu(true)}>Explore another math trail</button></div>:<Board key={`${run.id}:${run.revision}`} run={run} blocked={busy||demo} onDrop={m=>void send({kind:'drop',revision:run.revision,...m})} undo={()=>void send({kind:'undo',revision:run.revision})} retry={()=>void send({kind:'retry',revision:run.revision})}/>}<div className={`ms-feedback ${run.message.startsWith('That row')?'ms-mistake':''}`} key={run.revision} role="status">{busy?'Saving your move…':run.message}</div>{run.lastClear&&<details className="ms-proof"><summary>Why the last puzzle worked</summary><p>{run.lastClear}</p></details>}</section></div>}
 {demo&&run&&<ExampleDialog run={run} close={()=>setDemo(false)}/>}
 </main>;
}
function Board({run:r,blocked,onDrop,undo,retry}:{run:Run;blocked:boolean;onDrop:(m:Drop)=>void;undo:()=>void;retry:()=>void}){
 const [tray,setTray]=useState(0),[value,setValue]=useState(0),[rotation,setRotation]=useState(0),[x,setX]=useState(2),[y,setY]=useState(0),[paused,setPaused]=useState(false),[visible,setVisible]=useState(()=>!document.hidden);
 const q=question(r),ps=piece(r,tray,rotation,value),ghost=landing(r,tray,rotation,value,x),height=Math.max(...ps.map(p=>p.y))+1;
 const send=()=>{if(!blocked&&!paused&&visible)onDrop({tray,rotation,value,x});};
 const rotate=()=>{const next=(rotation+1)%4;const newPiece=piece(r,tray,next,value);for(const delta of [0,-1,1,-2,2])if(fits(r,newPiece,x+delta,y)){setRotation(next);setX(x+delta);return;}};
 const move=(delta:number)=>{if(fits(r,ps,x+delta,y))setX(x+delta);};
 const lower=()=>{if(fits(r,ps,x,y+1))setY(y+1);else send();};
 useEffect(()=>{const change=()=>setVisible(!document.hidden),blur=()=>setPaused(true);document.addEventListener('visibilitychange',change);window.addEventListener('blur',blur);return()=>{document.removeEventListener('visibilitychange',change);window.removeEventListener('blur',blur);};},[]);
 const tick=useRef(lower);useEffect(()=>{tick.current=lower;});
 useEffect(()=>{if(r.mode!=='arcade'||paused||blocked||!visible||r.status!=='playing')return;const id=setInterval(()=>tick.current(),Math.max(550,1700-r.round*130-Math.min(10,r.level)*45));return()=>clearInterval(id);},[r.mode,r.round,r.level,r.status,paused,blocked,visible]);
 const show=r.board.map(row=>row.map(c=>c));if(ghost>=0)for(const p of ps)show[ghost+p.y][x+p.x]=p.v;
 const previewRow=Math.min(HEIGHT-1,Math.max(0,ghost+height-1));
 const choose=(t:number)=>{setTray(t);setRotation(0);setX(2);setY(0);};
 return <><div className="ms-tray" role="group" aria-label="Choose shape">{[0,1,2].map(t=><button key={t} disabled={blocked} aria-pressed={tray===t} onClick={()=>choose(t)}><span>{SHAPE_NAMES[shape(r,t)]} piece</span><Mini points={piece(r,t,0,value)} q={q}/></button>)}</div><div className="ms-palette" role="group" aria-label="Block value">{q.palette.map((v,i)=><button key={i} aria-pressed={value===i} disabled={blocked} onClick={()=>setValue(i)}>{q.kind==='ratio'?`${v.n} R · ${4-v.n} B`:label(v,q)}</button>)}</div>
 <div className="ms-board-wrap"><div className="ms-board" role="grid" aria-label="Math Stack eight-column board. Use arrow keys to move, up to rotate, and Space to drop." tabIndex={0} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','p','P'].includes(e.key))return;e.preventDefault();if(e.key.toLowerCase()==='p'){setPaused(!paused);return;}if(blocked||paused)return;if(e.key==='ArrowLeft')move(-1);else if(e.key==='ArrowRight')move(1);else if(e.key==='ArrowUp')rotate();else if(e.key==='ArrowDown')lower();else send();}}>
 {r.board.flatMap((row,ry)=>row.map((cell,cx)=>{const active=ps.find(p=>p.x+x===cx&&p.y+y===ry),landingCell=ghost>=0?ps.find(p=>p.x+x===cx&&p.y+ghost===ry):undefined,c=cell??active?.v??landingCell?.v;return <div role="gridcell" key={`${cx}:${ry}`} aria-label={`Row ${ry+1}, column ${cx+1}${c?`, ${label(c,q)}`:', empty'}`} className={`ms-cell ${cell?'locked':active?'falling':landingCell?'ghost':''} ${c?.color===1?'red':c?.color===2?'blue':c?.x?'algebra':c&&c.n<0?'negative':''} ${q.kind==='factor'&&cx===4?'factor-divider':''}`} style={{'--tile-hue':(r.round*43+track(r.track).grade*27)%360} as CSSProperties}>{c&&<span>{label(c,q)}</span>}</div>;}))}
 {(paused||!visible||blocked||r.status==='blocked')&&<div className="ms-paused">{r.status==='blocked'?<><h3>Room to rethink</h3><button onClick={undo} disabled={!r.previous||blocked}>Undo last placement</button><button onClick={retry} disabled={blocked}>Clear space · same question</button></>:<><h3>{blocked?'Taking a moment…':'Paused'}</h3>{!blocked&&<button onClick={()=>setPaused(false)}>Resume stacking</button>}</>}</div>}
 </div><div className="ms-row-readout"><small>LANDING ROW · INCLUDING YOUR OUTLINE</small><strong>{describe(show[previewRow],q)}</strong>{q.kind==='slope'&&<Slope row={show[previewRow]}/>}</div></div>
 <div className="ms-controls" role="group" aria-label="Piece controls"><button disabled={blocked||paused} onClick={()=>move(-1)} aria-label="Move left">←</button><button disabled={blocked||paused} onClick={rotate}>↻ Rotate</button><button disabled={blocked||paused} onClick={()=>move(1)} aria-label="Move right">→</button><button disabled={blocked||paused} onClick={lower}>↓</button><button className="ms-primary" disabled={blocked||paused||r.status!=='playing'} onClick={send}>Drop ↓</button></div><div className="ms-tools"><button disabled={blocked||!r.previous} onClick={undo}>Undo placement</button><button disabled={blocked} onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button></div>
 </>;
}
function Mini({points,q}:{points:ReturnType<typeof piece>;q:ReturnType<typeof question>}){return <span className="ms-mini" aria-hidden="true">{points.map((p,i)=><i key={i} style={{left:p.x*19,top:p.y*19}} className={p.v.color===1?'red':p.v.color===2?'blue':''}>{label(p.v,q)}</i>)}</span>;}
function Slope({row}:{row:(Cell|null)[]}){let rise=0;const points=['0,45'];for(let i=0;i<row.length;i++){rise+=row[i]?.n??0;points.push(`${(i+1)*18},${45-rise*2}`);}return <svg className="ms-slope" viewBox="0 0 150 90" role="img" aria-label="A path showing the total rise and run"><path d="M0 45H150M2 0V90" stroke="#8ba5ba"/><polyline points={points.join(' ')} fill="none" stroke="#89edd2" strokeWidth="3"/></svg>;}
function example(run:Run){const r={...run,mode:'learn' as const};const q=question(r);for(let a=0;a<q.palette.length;a++)for(let b=0;b<q.palette.length;b++){const row=[...piece(r,0,0,a).map(p=>p.v),...piece(r,0,0,b).map(p=>p.v)];if(correct(row,q))return {a,b,row};}return null;}
function Example({run}:{run:Run}){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(true);const q=question(run),solution=example(run);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(s=>{if(s>=3)return 3;return s+1;}),2200);return()=>clearInterval(id);},[playing]);
 if(!solution)return <p>{q.hint}</p>;
 const captions=[q.prompt,'Choose an I piece. Move it to the left four columns and drop.','Choose the second value. Fill the right four columns.','A full row satisfies the math. Puzzle clear!'];
 return <><small>WORKED EXAMPLE · YOUR CURRENT SKILL</small><h2>Watch the answer take shape</h2><p>{captions[step]}</p><div className={`ms-example-row ${step===3?'solved':''}`}>{solution.row.map((c,i)=><span key={i} className={c.color===1?'red':c.color===2?'blue':''}>{step>=2||step===1&&i<4?label(c,q):'·'}</span>)}</div><p>{step===3?q.explanation:q.hint}</p><div className="ms-tools"><button onClick={()=>setPlaying(!playing)}>{playing?'Pause example':'Play example'}</button><button onClick={()=>setStep(s=>(s+1)%4)}>Next step</button><button onClick={()=>{setStep(0);setPlaying(true);}}>Replay</button></div><small>This demonstration spends nothing. Your board waits for you. Worked examples are recorded as supported practice.</small></>;
}

function ExampleDialog({run,close}:{run:Run;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="ms-demo" aria-label="Math Stack worked example" onCancel={e=>{e.preventDefault();close();}}><button autoFocus onClick={close}>Close example</button><Example run={run}/></dialog>;}
