import { middleSkills, middleSkill } from '../middle-school/catalog';
import { middleProblem } from '../middle-school/content';
import { GRADE_TOPICS, withAnswerFormat, type Challenge } from '../../services/game/curriculum';
export interface Subskill {id:string;grade:number;topic:string;name:string;variant:number}
// Actual mathematical objectives; these are supported practice skills, not a full curriculum.
const LABELS=[
 ['Count a set of objects','Find the next counting number','Fill a gap in a counting sequence','Add within 10','Find a missing addend within 10','Solve an addition story within 10'],
 ['Add within 20','Find a missing addend within 20','Solve an addition story within 20','Subtract within 20','Find the amount taken away','Solve a subtraction story within 20'],
 ['Add two-digit numbers without regrouping','Add two-digit numbers with regrouping','Find a missing two-digit addend','Subtract without regrouping','Subtract with regrouping','Find a missing subtraction amount'],
 ['Multiply equal groups','Find a missing multiplication factor','Solve a multiplication story','Divide into equal groups','Find an unknown divisor','Solve an equal-sharing story'],
 ['Multiply a two-digit number by one digit','Use partial products','Solve a two-digit multiplication story','Find a missing factor','Count all factors of a number','Find a greatest common factor'],
 ['Add tenths','Subtract tenths','Add hundredths','Find a unit fraction of a quantity','Find a non-unit fraction of a quantity','Find the whole from a fractional part'],
 ['Find a unit rate','Scale an equivalent ratio','Use a unit rate in a story','Add signed integers','Subtract signed integers','Multiply signed integers'],
 ['Find a percentage of a quantity','Find the whole from a percentage','Find the percent represented by a part','Solve an addition equation','Solve a multiplication equation','Solve a division equation'],
 ['Solve a two-step linear equation','Solve an equation with parentheses','Solve a linear equation with x on both sides','Find a hypotenuse','Find a missing leg','Find a diagonal in a rectangle'],
 ['Find a positive square root solution','Solve a shifted-square equation','Find the larger root of a factored quadratic','Find slope from two points','Find a missing y-coordinate using slope','Read slope from an equation'],
 ['Solve a system by elimination','Solve a system by substitution','Solve a two-quantity system story','Find the vertex x-coordinate','Find the vertex y-coordinate','Find the vertex from standard form'],
 ['Evaluate powers','Evaluate a logarithm','Solve an exponential equation','Find a term in an arithmetic sequence','Find the common difference','Find the first term of an arithmetic sequence'],
 ['Differentiate a quadratic at a point','Differentiate a cubic at a point','Find a stationary x-value of a quadratic','Find a simple event probability','Find the probability of independent events','Find a complement probability'],
] as const;
export const skillsForGrade=(grade:number):Subskill[]=> [...(LABELS[grade]??[]).map((name,i)=>({id:`g${grade}-s${i}`,grade,topic:GRADE_TOPICS[grade][i<3?0:1],name,variant:i})), ...middleSkills(grade)];
export const getSkill=(id:string)=>{const match=/^g(\d+)-s(0|[1-9]\d*)$/.exec(id);return match?skillsForGrade(Number(match[1]))[Number(match[2])]:undefined;};
export interface Problem {text:string;answer:number;hint:string;explanation:string}
export function problem(skill:Subskill,challenge:Challenge,random:()=>number):Problem{
 if(middleSkill(skill.id))return middleProblem(skill.id,challenge,'check',0,random);
 const max=challenge==='support'?5:challenge==='stretch'?12:9;
 const int=(lo:number,hi:number)=>lo+Math.floor(random()*(hi-lo+1));
 const v=skill.variant,g=skill.grade,a=int(2,max),b=int(g===5&&v===4?3:2,max),c=int(1,5);
 const p=(text:string,answer:number,hint:string,explanation:string):Problem=>({text:withAnswerFormat(text,answer),answer,hint,explanation});
 const add=(x:number,y:number,kind:number)=>kind===1?p(`${x} + ? = ${x+y}`,y,'Subtract the known addend from the total.',`${x+y} − ${x} = ${y}.`):kind===2?p(`Pip has ${x} seeds and finds ${y} more. How many seeds now?`,x+y,'Combine the two groups.',`${x} + ${y} = ${x+y}.`):p(`${x} + ${y} = ?`,x+y,'Add by place value or count on.',`${x} + ${y} = ${x+y}.`);
 const sub=(x:number,y:number,kind:number)=>kind===1?p(`${x} − ? = ${x-y}`,y,'Find the difference between the start and the result.',`${x} − ${x-y} = ${y}.`):kind===2?p(`Moss has ${x} leaves and gives away ${y}. How many remain?`,x-y,'Take the given amount away from the starting amount.',`${x} − ${y} = ${x-y}.`):p(`${x} − ${y} = ?`,x-y,'Subtract by place value or count back.',`${x} − ${y} = ${x-y}.`);
 if(g===0){if(v===0){const n=int(1,10),symbol=['★','●','◆'][int(0,2)];return p(`How many objects? ${`${symbol} `.repeat(n).trim()}`,n,'Count each object once.',`There are ${n} objects.`);}if(v===1){const n=int(0,9);return p(`${int(0,1)?'Count on one from':'What number comes just after'} ${n}?`,n+1,'Move one counting step forward.',`${n} + 1 = ${n+1}.`);}if(v===2){const n=int(0,7),gap=int(1,2),sequence=[String(n),String(n+1),String(n+2),String(n+3)];sequence[gap]='?';return p(`Fill the gap: ${sequence.join(', ')}`,n+gap,'The numbers increase by one.',`The missing number is ${n+gap}.`);}return add(int(0,5),int(0,5),v-3);}
 if(g===1){const x=int(1,10),y=int(1,10);return v<3?add(x,y,v):sub(x+y,x,v-3);}
 if(g===2){if(v===0)return add(int(1,4)*10+int(0,4),int(1,4)*10+int(0,4),0);if(v===1)return add(int(1,4)*10+int(5,9),int(1,4)*10+int(5,9),0);if(v===2)return add(int(10,49),int(10,49),1);if(v===3){const x=int(4,9)*10+int(5,9),y=int(1,3)*10+int(0,4);return sub(x,y,0);}if(v===4){const x=int(4,9)*10+int(0,4),y=int(1,3)*10+int(5,9);return sub(x,y,0);}return sub(int(50,99),int(10,49),1);}
 if(g===3||g===4){const x=g===4?a+10:a;
 if(v===0)return p(`${x} × ${b} = ?`,x*b,'Use equal groups or split the larger factor.',`${x} × ${b} = ${x*b}.`);
 if(v===1&&g===4)return p(`Complete: ${x} × ${b} = (10 × ${b}) + (? × ${b})`,x-10,'Split the two-digit factor into 10 and its remaining ones.',`${x} = 10 + ${x-10}.`);
 if(v===1||v===3&&g===4)return p(`${b} × ? = ${a*b}`,a,'Divide the product by the known factor.',`${a*b} ÷ ${b} = ${a}.`);
 if(v===2)return p(`${b} baskets each hold ${x} berries. How many berries altogether?`,x*b,'Multiply the number of baskets by berries in each.',`${b} × ${x} = ${x*b}.`);
 if(v===3)return p(`${a*b} ÷ ${b} = ?`,a,'Use the related multiplication fact.',`${a} × ${b} = ${a*b}, so the quotient is ${a}.`);
 if(v===4&&g===4){const n=int(4,40),factors=Array.from({length:n},(_,i)=>i+1).filter(x=>n%x===0);return p(`How many positive factors does ${n} have?`,factors.length,'List the factor pairs. Count each positive factor once.',`Factors: ${factors.join(', ')}.`);}
 if(v===4)return p(`${a*b} ÷ ? = ${a}`,b,'Divide the dividend by the quotient.',`${a*b} ÷ ${a} = ${b}.`);
 if(g===4){const x=a*c,y=b*c,common=Array.from({length:Math.min(x,y)},(_,i)=>i+1).filter(n=>x%n===0&&y%n===0);return p(`Find the greatest common factor of ${x} and ${y}.`,Math.max(...common),'List factors shared by both numbers and choose the largest.',`Common factors: ${common.join(', ')}. The greatest is ${Math.max(...common)}.`);}
 return p(`${a*b} seeds are shared equally among ${b} pots. How many seeds per pot?`,a,'Divide the total by the number of equal groups.',`${a*b} ÷ ${b} = ${a}.`);}
 if(g===5){if(v===0)return p(`${(a/10).toFixed(1)} + ${(b/10).toFixed(1)} = ?`,(a+b)/10,'Add the tenths.',`${a} + ${b} = ${a+b} tenths = ${(a+b)/10}.`);if(v===1)return p(`${((a+b)/10).toFixed(1)} − ${(b/10).toFixed(1)} = ?`,a/10,'Subtract the tenths.',`${a+b} − ${b} = ${a} tenths = ${a/10}.`);if(v===2){const x=int(11,89),y=int(11,89);return p(`${(x/100).toFixed(2)} + ${(y/100).toFixed(2)} = ?`,(x+y)/100,'Align the decimal points and add hundredths.',`${x} + ${y} = ${x+y} hundredths = ${(x+y)/100}.`);}if(v===3)return p(`What is 1/${b} of ${a*b}?`,a,'Divide the quantity by the denominator.',`${a*b} ÷ ${b} = ${a}.`);if(v===4)return p(`What is ${b-1}/${b} of ${a*b}?`,a*(b-1),'Find one share, then multiply by the numerator.',`${a*b} ÷ ${b} × ${b-1} = ${a*(b-1)}.`);return p(`1/${b} of a whole is ${a}. What is the whole?`,a*b,'Multiply one share by the number of shares.',`${a} × ${b} = ${a*b}.`);}
 if(g===6){if(v===0)return p(`${b} packs contain ${a*b} pencils. How many pencils per pack?`,a,'Divide to find one unit.',`${a*b} ÷ ${b} = ${a}.`);if(v===1)return p(`Complete the equivalent ratio: ${a}:${b} = ${a*c}:?`,b*c,'Multiply both parts by the same scale factor.',`The scale factor is ${c}. ${b} × ${c} = ${b*c}.`);if(v===2)return p(`${b} tickets cost ${a*b} coins. How much do ${b+c} tickets cost?`,a*(b+c),'Find the cost of one ticket, then scale up.',`${a*b} ÷ ${b} = ${a} each; ${a} × ${b+c} = ${a*(b+c)}.`);if(v===3)return p(`−${a} + ${b} = ?`,b-a,'Add by moving right from a negative starting point.',`−${a} + ${b} = ${b-a}.`);if(v===4)return p(`${a} − (−${b}) = ?`,a+b,'Subtracting a negative adds its opposite.',`${a} + ${b} = ${a+b}.`);return p(`(−${a}) × ${b} = ?`,-a*b,'One negative factor makes a negative product.',`The magnitude is ${a*b}; the signed product is ${-a*b}.`);}
 if(g===7){if(v===0)return p(`What is ${a*5}% of ${b*20}?`,a*b,'Multiply the whole by percent / 100.',`${a*5}/100 × ${b*20} = ${a*b}.`);if(v===1)return p(`${a*5}% of a number is ${a*b}. What is the number?`,b*20,'Divide the part by the percentage written as a decimal.',`${a*b} ÷ ${a*5/100} = ${b*20}.`);if(v===2)return p(`${a*b} is what percent of ${b*20}? Enter the percent number.`,a*5,'Divide the part by the whole and multiply by 100.',`${a*b} ÷ ${b*20} × 100 = ${a*5}%.`);if(v===3)return p(`Solve: x + ${b} = ${a+b}`,a,'Subtract the same amount from each side.',`x = ${a+b} − ${b} = ${a}.`);if(v===4)return p(`Solve: ${b}x = ${a*b}`,a,'Divide both sides by the coefficient.',`x = ${a*b} ÷ ${b} = ${a}.`);return p(`Solve: x / ${b} = ${a}`,a*b,'Multiply both sides by the divisor.',`x = ${a} × ${b} = ${a*b}.`);}
 if(g===8){if(v===0)return p(`Solve: ${b}x + ${c} = ${a*b+c}`,a,'Undo addition, then multiplication.',`Subtract ${c}, then divide by ${b}: x = ${a}.`);if(v===1)return p(`Solve: ${b}(x + ${c}) = ${b*(a+c)}`,a,'Divide first, then subtract.',`x + ${c} = ${a+c}, so x = ${a}.`);if(v===2)return p(`Solve: ${b+c}x = ${b}x + ${a*c}`,a,'Collect x terms on one side.',`${c}x = ${a*c}, so x = ${a}.`);const triple=[[3,4,5],[5,12,13],[8,15,17],[7,24,25]][int(0,3)],x=triple[0]*a,y=triple[1]*a,z=triple[2]*a;if(v===3)return p(`A right triangle has legs ${x} and ${y}. Find its hypotenuse.`,z,'Square the legs, add, and take a positive square root.',`c² = ${x*x} + ${y*y} = ${z*z}; c = ${z}.`);if(v===4)return p(`A right triangle has hypotenuse ${z} and one leg ${x}. Find the other leg.`,y,'Subtract the known leg squared from the hypotenuse squared.',`b² = ${z*z} − ${x*x} = ${y*y}; b = ${y}.`);return p(`A rectangle is ${x} wide and ${y} long. Find its diagonal.`,z,'The diagonal is the hypotenuse of a right triangle.',`d² = ${x}² + ${y}² = ${z*z}; d = ${z}.`);}
 if(g===9){if(v===0){const n=int(1,max+3);return p(int(0,1)?`Find the positive solution: x² = ${n*n}`:`What is the positive square root of ${n*n}?`,n,'Take the positive square root.',`√${n*n} = ${n}.`);}if(v===1)return p(`Find the larger solution: (x − ${b})² = ${a*a}`,a+b,'The inner expression can be either square root.',`x = ${b} ± ${a}; the larger root is ${a+b}.`);if(v===2)return p(`Find the larger root: (x − ${a})(x − ${a+b}) = 0`,a+b,'A product is zero when either factor is zero.',`The roots are ${a} and ${a+b}. The larger is ${a+b}.`);if(v===3)return p(`Find the slope through (${c}, ${b}) and (${c+a}, ${b+a*b}).`,b,'Slope is change in y divided by change in x.',`(${b+a*b} − ${b}) / (${c+a} − ${c}) = ${b}.`);if(v===4)return p(`A line has slope ${b} and passes through (0, ${c}). What is y when x = ${a}?`,a*b+c,'Use y = mx + the y-intercept.',`y = ${b} × ${a} + ${c} = ${a*b+c}.`);return p(`What is the slope of y = ${a}x + ${b}?`,a,'In y = mx + b, m is the slope.',`The coefficient of x is ${a}, so slope = ${a}.`);}
 if(g===10){if(v===0)return p(`Find x: x + y = ${a+b}; 2x + y = ${2*a+b}.`,a,'Subtract the first equation from the second.',`x = ${2*a+b} − ${a+b} = ${a}.`);if(v===1)return p(`Find x: y = x + ${b}; x + y = ${2*a+b}.`,a,'Substitute the expression for y into the second equation.',`2x + ${b} = ${2*a+b}; x = ${a}.`);if(v===2)return p(`${a+b} tickets cost ${2*a+3*b} coins. Small tickets cost 2 and large tickets cost 3. How many large tickets?`,b,'Use s + l = total tickets and 2s + 3l = cost.',`Subtract twice the ticket count from the cost: ${2*a+3*b} − ${2*(a+b)} = ${b}.`);if(v===3)return p(`Find the vertex x-coordinate: y = (x − ${a})² + ${b}.`,a,'Use vertex form y = (x − h)² + k.',`The vertex is (${a}, ${b}), so x = ${a}.`);if(v===4)return p(`Find the vertex y-coordinate: y = (x − ${a})² − ${b}.`,-b,'The square is smallest when it is zero.',`At x = ${a}, y = −${b}.`);return p(`Find the vertex x-coordinate: y = x² − ${2*a}x + ${b}.`,a,'Use x = −B / (2A) for Ax² + Bx + C.',`x = −(−${2*a}) / 2 = ${a}.`);}
 if(g===11){const exponent=int(2,5);if(v===0)return p(`${b}^${exponent} = ?`,b**exponent,'Multiply the base by itself as many times as the exponent says.',`${b}^${exponent} = ${b**exponent}.`);if(v===1)return p(`log base ${b} of ${b**exponent} = ?`,exponent,'Which power of the base gives the number?',`${b}^${exponent} = ${b**exponent}, so the logarithm is ${exponent}.`);if(v===2)return p(`Solve for x: ${b}^x = ${b**exponent}`,exponent,'Find the exponent producing the number.',`${b}^${exponent} = ${b**exponent}, so x = ${exponent}.`);if(v===3)return p(`An arithmetic sequence starts at ${a} and adds ${b}. Find term ${c+2}.`,a+(c+1)*b,'Use first term + (term number − 1) × difference.',`${a} + ${c+1} × ${b} = ${a+(c+1)*b}.`);if(v===4)return p(`Find the common difference: ${a}, ${a+b}, ${a+2*b}, …`,b,'Subtract consecutive terms.',`${a+b} − ${a} = ${b}.`);return p(`An arithmetic sequence has term ${c+2} = ${a+(c+1)*b} and difference ${b}. Find its first term.`,a,'Undo the additions before that term.',`${a+(c+1)*b} − ${c+1} × ${b} = ${a}.`);}
 if(v===0)return p(`f(x) = ${a}x². Find f′(${b}).`,2*a*b,'Use the power rule, then substitute.',`f′(x) = ${2*a}x; f′(${b}) = ${2*a*b}.`);
 if(v===1)return p(`f(x) = ${a}x³. Find f′(${b}).`,3*a*b*b,'The derivative of x³ is 3x².',`f′(x) = ${3*a}x²; f′(${b}) = ${3*a*b*b}.`);
 if(v===2)return p(`f(x) = x² − ${2*a}x + ${b}. At what x is f′(x) = 0?`,a,'Differentiate and solve the resulting linear equation.',`f′(x) = 2x − ${2*a}; 2x = ${2*a}; x = ${a}.`);
 if(v===3)return p(`A bag has ${a} blue and ${b} red counters. What is P(blue)? Enter a fraction or decimal.`,a/(a+b),'Divide favorable outcomes by all outcomes.',`P(blue) = ${a}/${a+b}.`);
 if(v===4){const gold=int(1,a-1);return p(`A fair ${a}-section spinner has ${gold} gold section(s). A separate fair ${b}-section spinner has one gold section. Spin each independently. What is P(both gold)?`,gold/(a*b),'Multiply the probabilities of independent events.',`${gold}/${a} × 1/${b} = ${gold}/${a*b}.`);}
 return p(`A bag has ${a} green and ${b} red counters. What is P(not green)? Enter a fraction or decimal.`,b/(a+b),'Subtract the probability of green from 1.',`1 − ${a}/${a+b} = ${b}/${a+b}.`);
}
