import { middleSkill } from '../middle-school/catalog';
import { middleProblem, middleLesson } from '../middle-school/content';
import {getSkill,problem,type Problem} from './catalog';
import {deepTransfer} from './transfer';
import {structuralTransfer,type Stakes} from './structural';
import {withAnswerFormat,type Challenge} from '../../services/game/curriculum';
export interface Visual {kind:'table'|'dots'|'coordinate';points?:[number,number][];caption:string;rows:[string,string][];dots?:number[]}
export interface LearningProblem extends Problem {templateId:string;representation:string;visual?:Visual;reasonPrompt:string;hints:string[];outcome:string;guided:boolean;stakes?:Stakes}
interface Case {ask:string;answer:number;rows:[string,string][];strategy:string;work:string;reason:string;step?:{ask:string;answer:number;work:string};dots?:number[]}
const row=(label:string,value:number|string):[string,string]=>[label,String(value)];
export const missionNames=['Counting garden','Supply station','Place-value workshop','Equal-group garden','Packing workshop','Recipe studio','Supply planner','Budget studio','Route planner','Design studio','Community planner','Pattern lab','Change & chance lab'];
export const gradeConcepts=[
 'Count each object once. The last number tells how many. A whole can be made from two parts.',
 'Connect joining and taking away to a part–whole picture. Use the inverse operation to find a missing part.',
 'Keep tens and ones aligned. Regroup one ten as ten ones when needed.',
 'Equal groups connect multiplication and division. Label the total, number of groups, and amount in one group.',
 'Break multiplication into useful parts. Factors divide a number with no remainder.',
 'Equal-sized shares make fractions meaningful. Place value tells the size of each decimal unit.',
 'A unit rate describes one unit. Scale both parts of a ratio together; track direction for signed numbers.',
 'Percent means per hundred. Equations stay balanced when the same operation is applied to both sides.',
 'Model the relationship before solving. Undo operations in reverse order; right triangles satisfy a² + b² = c².',
 'Connect equations to roots and points. Slope compares change in output with change in input.',
 'Two equations constrain the same quantities. A quadratic’s vertex describes its turning point.',
 'Exponents and logarithms are inverse descriptions. Arithmetic sequences change by a constant amount.',
 'A derivative describes instantaneous change. Probability compares favorable outcomes with the full sample space.',
];
/** Context models for the original 78 named subskills; middle-school additions are authored separately. Values remain within the assigned objective. */
function contextCase(id:string,level:Challenge,r:()=>number,plain:boolean):Case {
 const s=getSkill(id);if(!s)throw Error('Unknown skill');const g=s.grade,v=s.variant;
 const int=(lo:number,hi:number)=>lo+Math.floor(r()*(hi-lo+1));
 const max=level==='support'?5:level==='stretch'?12:9,a=int(2,max),b=int(g===5&&v===4?3:2,g===3||g===4?Math.min(max,9):max),c=int(1,5);
 const item=plain?'cards':'seeds',place=plain?'school club':'garden crew';
 const make=(ask:string,answer:number,rows:Case['rows'],strategy:string,work:string,reason:string,step?:Case['step']):Case=>({ask,answer,rows,strategy,work,reason,step});
 const add=(x:number,y:number,missing=false)=>make(missing?`How many ${item} must be added to reach the target?`:`How many ${item} will ${place} have altogether?`,missing?y:x+y,[row('Starting amount',x),row(missing?'Target total':'Added amount',missing?x+y:y)],missing?'Subtract the known part from the whole.':'Combine the two parts, aligning place values.',missing?`${x+y} − ${x} = ${y}. Check: ${x} + ${y} = ${x+y}.`:`${x} + ${y} = ${x+y}.`,missing?'How can addition check your missing part?':'How did you combine the parts?',x<10?{ask:`Start at ${x} and count on one. What number comes next?`,answer:x+1,work:`One more than ${x} is ${x+1}. Keep counting the added objects.`}:{ask:`Split ${x} into tens and ones. How many ones are in ${x}?`,answer:x%10,work:`${x} = ${Math.floor(x/10)} tens and ${x%10} ones.`});
 const sub=(x:number,y:number,missing=false)=>make(missing?'How many were taken away?':`How many ${item} remain?`,missing?y:x-y,[row('Starting amount',x),row(missing?'Remaining amount':'Taken away',missing?x-y:y)],'Relate the starting whole to the two parts.',`${x} − ${y} = ${x-y}. Check: ${x-y} + ${y} = ${x}.`,'How could you check using addition?');
 if(g===0){if(v<3){const n=int(1,8),gap=int(1,2);return v===0?{...make('Count all the objects. How many?',n,[row('Task','Count each dot once')],'Touch or point to each object once.',`The total is ${n}.`,'Show how you counted without missing any.'),dots:[n]}:make(v===1?'What number comes next?':'What number belongs in the empty box?',n+(v===1?1:gap),[row('Counting strip',v===1?`${n-1}, ${n}, ?`:`${n}, ${gap===1?'?':n+1}, ${gap===2?'?':n+2}, ${n+3}`)],'Each next number is one more.',`Count in ones: ${n}, ${n+1}, ${n+2}, ${n+3}.`,'Show one step forward.');}const x=int(1,5),y=int(1,5);return {...add(x,y,v===4),dots:v===4?[x]:[x,y]};}
 if(g===1){const x=int(1,10),y=int(1,10);return v<3?add(x,y,v===1):sub(x+y,x,v===4);}
 if(g===2){if(v<3){const x=int(1,4)*10+int(v===1?5:0,v===1?9:4),y=int(1,4)*10+int(v===1?5:0,v===1?9:4);return add(x,y,v===2);}return sub(int(4,9)*10+int(v===4?0:5,v===4?4:9),int(1,3)*10+int(v===4?5:0,v===4?9:4),v===5);}
 if(g===3||g===4){const x=g===4?10+a:a;
 if(v===0||v===2)return make(`How many ${item} are needed for all the packs?`,x*b,[row('Packs',b),row('In each pack',x)],'Multiply equal groups. Split a larger factor if useful.',`${b} × ${x} = ${b*x}.`,'Why does multiplication fit these quantities?',{ask:`For ${b} packs of ${x}, what is the number in one pack?`,answer:x,work:`Each pack contains ${x}; there are ${b} equal groups.`});
 if(v===1&&g===4)return make('The packing plan splits each pack into 10 and some more. How many more per pack?',a,[row('Per pack',x),row('Number of packs',b),row('First part of each pack',10)],'Decompose the factor before multiplying.',`${x} = 10 + ${a}; ${b} × ${x} = ${b*10} + ${b*a}.`,'Why must both parts be multiplied by the number of packs?');
 if(v===1||v===3&&g===4)return make('How many go in each equal pack?',a,[row('Total',a*b),row('Packs',b)],'Divide the total by the number of packs.',`${a*b} ÷ ${b} = ${a}.`,'How does the related multiplication fact check this?');
 if(g===3)return v===4?make('How many equal packs are needed?',b,[row('Total',a*b),row('Per pack',a)],'Find how many groups fit in the total.',`${a*b} ÷ ${a} = ${b}.`,'Which quantity is the group size?'):make('How many go in each equal group?',a,[row('Total',a*b),row('Groups',b)],'Share the total equally.',`${a*b} ÷ ${b} = ${a}.`,'How can you check every group is equal?');
 if(v===4){const n=int(6,40),fs=Array.from({length:n},(_,i)=>i+1).filter(d=>n%d===0);return make('How many positive pack sizes divide the total exactly?',fs.length,[row('Total items',n),row('Rule','No leftovers; count each size once')],'List divisor pairs and remove repeats.',`Valid sizes: ${fs.join(', ')}. There are ${fs.length}.`,'Why is a repeated factor counted only once?');}
 const x1=a*c,y=b*c,fs=Array.from({length:Math.min(x1,y)},(_,i)=>i+1).filter(d=>x1%d===0&&y%d===0);return make('What is the largest pack size that divides both totals with no leftovers?',Math.max(...fs),[row('First supply',x1),row('Second supply',y)],'Find shared factors; choose the largest.',`Shared sizes: ${fs.join(', ')}. Largest: ${Math.max(...fs)}.`,'Why must your size divide both supplies?');}
 if(g===5){if(v<3){const unit=v===2?100:10,x=v===2?int(11,89):a,y=v===2?int(11,89):b,minus=v===1;return make(minus?'How many liters remain?':'How many liters are there altogether?',(minus?x:x+y)/unit,[row('First amount (liters)',(minus?x+y:x)/unit),row(minus?'Used (liters)':'Added (liters)',y/unit)],'Align decimal places so equal-sized units combine.',minus?`${(x+y)/unit} − ${y/unit} = ${x/unit}.`:`${x/unit} + ${y/unit} = ${(x+y)/unit}.`,'What does the digit after the decimal point represent?');}
 const n=v===4?b-1:1;return v===5?make('What is the whole recipe quantity?',a*b,[row('Fraction of whole',`1/${b}`),row('Amount in that fraction',a)],'One share times the number of equal shares gives the whole.',`${a} × ${b} = ${a*b}.`,'Why do you multiply instead of divide?',{ask:'How much would two equal shares contain?',answer:2*a,work:`Two shares contain 2 × ${a} = ${2*a}. The whole has ${b} equal shares.`}):make('How much of the supply does this recipe use?',a*n,[row('Whole supply',a*b),row('Fraction used',`${n}/${b}`)],'Find one equal share, then take the required number of shares.',`${a*b} ÷ ${b} = ${a} in one share; ${a} × ${n} = ${a*n}.`,'What do the numerator and denominator mean here?',{ask:'How much is in one equal share?',answer:a,work:`${a*b} ÷ ${b} = ${a}.`});}
 if(g===6){if(v===0||v===2)return make(v===0?'What is the cost per kit?':'What will the new order cost?',v===0?a:a*(b+c),[row('Original kits',b),row('Original cost',a*b),...(v===2?[row('New order kits',b+c)]:[])],'Find the cost of one kit, then scale.',`${a*b} ÷ ${b} = ${a} per kit.${v===2?` Then ${a} × ${b+c} = ${a*(b+c)}.`:''}`,'Why is the cost per kit unchanged?',{ask:'What is the cost of one kit?',answer:a,work:`${a*b} ÷ ${b} = ${a}.`});
 if(v===1)return make('How much water is needed for the larger batch?',b*c,[row('Original concentrate',a),row('Original water',b),row('New concentrate',a*c)],'Scale both parts by the same factor.',`Scale = ${a*c}/${a} = ${c}. Water = ${b} × ${c} = ${b*c}.`,'Why must both parts change by the same factor?',{ask:'What is the scale factor?',answer:c,work:`${a*c} ÷ ${a} = ${c}.`});
 if(v===3)return make('What is the new temperature?',b-a,[row('Starting temperature',-a),row('Rise',b)],'Move right for an increase on a number line.',`−${a} + ${b} = ${b-a}.`,'Which direction represents a rise?');if(v===4)return make('What is the balance after removing a debt?',a+b,[row('Balance',a),row('Debt removed',-b)],'Removing a negative adds its opposite.',`${a} − (−${b}) = ${a+b}.`,'Why does removing a debt increase the balance?');return make('What is the total signed change?',-a*b,[row('Change per hour',-a),row('Hours',b)],'Multiply the magnitude and keep the negative direction.',`(−${a}) × ${b} = ${-a*b}.`,'What does the negative result mean?');}
 if(g===7){if(v<3){const whole=b*20,part=a*b,pct=a*5;return make(v===0?'How much is the discount?':v===1?'What was the full price?':'What percent is the discount? Enter the percent number.',v===0?part:v===1?whole:pct,[...(v!==1?[row('Full price',whole)]:[]),...(v!==0?[row('Discount amount',part)]:[]),...(v!==2?[row('Discount percent',pct)]:[])],'Relate part = whole × percent / 100.',`${part} = ${whole} × ${pct}/100.`,'Which amount represents 100%?');}
 if(v===3)return make('What was the starting supply?',a,[row('Added supply',b),row('Final supply',a+b)],'Undo the addition on both sides.',`x + ${b} = ${a+b}; x = ${a}.`,'Why must you subtract from both sides?');if(v===4)return make('How many items are in one equal box?',a,[row('Boxes',b),row('Total items',a*b)],'Divide both sides by the number of boxes.',`${b}x = ${a*b}; x = ${a}.`,'What does x represent?');return make('What was the whole supply before sharing?',a*b,[row('Equal shares',b),row('In one share',a)],'Undo division by multiplying both sides.',`x/${b} = ${a}; x = ${a*b}.`,'Why is multiplication the inverse here?');}
 if(g===8){if(v<3){if(v===0)return make('How many parcels can the budget cover exactly?',a,[row('Fixed fee',c),row('Cost per parcel',b),row('Total budget',a*b+c)],'Remove the fixed fee, then divide by the unit cost.',`${c} + ${b}p = ${a*b+c}; ${b}p = ${a*b}; p = ${a}.`,'Why do you remove the fixed fee before dividing?',{ask:'How much of the budget is left after the fixed fee?',answer:a*b,work:`${a*b+c} − ${c} = ${a*b}.`});if(v===1)return make('How much is the base price of one kit?',a,[row('Kits',b),row('Extra fee per kit',c),row('Total cost',b*(a+c))],'Divide the total across kits, then remove the fee per kit.',`${b}(x + ${c}) = ${b*(a+c)}; x + ${c} = ${a+c}; x = ${a}.`,'Why is the extra fee inside the parentheses?',{ask:'How much does one kit cost including its extra fee?',answer:a+c,work:`${b*(a+c)} ÷ ${b} = ${a+c} per kit. Now separate the extra fee from the base price.`});return make('At how many hours do the two plans cost the same?',a,[row('Plan A hourly cost',b+c),row('Plan B hourly cost',b),row('Plan B fixed fee',a*c)],'Set costs equal and collect the variable terms.',`${b+c}x = ${b}x + ${a*c}; ${c}x = ${a*c}; x = ${a}.`,'What does equality mean for these plans?',{ask:'How much more per hour does Plan A cost than Plan B?',answer:c,work:`${b+c} − ${b} = ${c} extra per hour. Relate that difference to the fixed fee.`});}
 const [u,w,z]=[[3,4,5],[5,12,13],[8,15,17],[7,24,25]][int(0,3)].map(n=>n*a);return make(v===4?'What is the missing perpendicular height?':'What is the straight-line diagonal length?',v===4?w:z,[row(v===4?'Diagonal':'Horizontal side',v===4?z:u),row(v===4?'Horizontal side':'Vertical side',v===4?u:w),row('Angle between sides','90°')],'Identify the hypotenuse before using the sum of squares.',`${u}² + ${w}² = ${z}². ${v===4?`Height = √(${z*z} − ${u*u}) = ${w}.`:`Diagonal = √(${u*u} + ${w*w}) = ${z}.`}`,'Which side is the hypotenuse, and why?');}
 if(g===9){const root=int(1,max+3);if(v<3)return v===0?make('What positive side length makes this square?',root,[row('Square area',root*root)],'Take the positive square root of the area.',`s² = ${root*root}; s = ${root}.`,'Why is the negative root excluded for a length?'):v===1?make('What is the larger possible value of x?',a+b,[row('Rule',`(x − ${b})²`),row('Rule output',a*a)],'Take both square roots, then undo the shift.',`x − ${b} = ±${a}; x = ${b} ± ${a}. Larger: ${a+b}.`,'Why are there two possible square roots?'):make('At which larger time does the height model reach zero?',a+b,[row('Height model',`h(t) = (t − ${a})(t − ${a+b})`)],'A product is zero when at least one factor is zero.',`t = ${a} or ${a+b}; larger time = ${a+b}.`,'Why can you set each factor equal to zero?');
 if(v===3)return make('What is the constant rate of change?',b,[row(`Output at input ${c}`,a),row(`Output at input ${c+2}`,a+2*b)],'Divide change in output by change in input.',`(${a+2*b} − ${a}) / (${c+2} − ${c}) = ${b}.`,'Why must both changes use the same point order?');if(v===4)return make('What is the output at the requested input?',a*b+c,[row('Starting output at input 0',c),row('Change per input unit',b),row('Requested input',a)],'Use output = rate × input + starting output.',`y = ${b} × ${a} + ${c} = ${a*b+c}.`,'Which value is the rate and which is the starting amount?');return make('How much does output increase for each extra input unit?',a,[row('Model',`y = ${a}x + ${b}`)],'Read the coefficient of x as the rate.',`An increase of 1 in x increases y by ${a}.`,'Why does the constant term not change the slope?');}
 if(g===10){if(v<3){if(v===0)return make('How many of the first item are there?',a,[row('Total item count',a+b),row('Weighted total: first costs 2, second costs 1',2*a+b)],'Subtract the count equation from the weighted-total equation.',`x + y = ${a+b}; 2x + y = ${2*a+b}; x = ${a}.`,'Why does subtraction eliminate y?');if(v===1)return make('How many are in the smaller group?',a,[row('Larger group has this many extra',b),row('Total in both groups',2*a+b)],'Replace the larger group by x plus the extra amount.',`x + (x + ${b}) = ${2*a+b}; 2x = ${2*a}; x = ${a}.`,'Why is the extra amount added only once?');return make('How many large tickets were sold?',b,[row('Tickets sold',a+b),row('Small price',2),row('Large price',3),row('Revenue',2*a+3*b)],'Model both ticket count and revenue.',`s + l = ${a+b}; 2s + 3l = ${2*a+3*b}; l = ${b}.`,'Why do we need two equations?');}
 if(v===3)return make('At what input is this cost smallest?',a,[row('Cost model',`C(x) = (x − ${a})² + ${b}`)],'The squared part reaches zero at the vertex.',`x − ${a} = 0, so x = ${a}.`,'Why can the squared part never be negative?');if(v===4)return make('What is the minimum model output?',-b,[row('Model',`y = (x − ${a})² − ${b}`)],'Set the nonnegative square to zero.',`At x = ${a}, y = −${b}.`,'Which coordinate gives the minimum output?');return make('At what input is this quadratic smallest?',a,[row('Model',`y = x² − ${2*a}x + ${b}`)],'For Ax² + Bx + C, the vertex input is −B/(2A).',`x = −(−${2*a})/(2 × 1) = ${a}.`,'How could symmetry check the vertex?');}
 if(g===11){const e=int(2,5);if(v<3)return make(v===0?'How many outcomes are possible?':'Start at 1. How many multiplications by the base reach the final value?',v===0?b**e:e,[row('Base',b),row(v===0?'Independent stages':'Final value',v===0?e:b**e)],v===0?'Multiply the same number of choices at each stage.':'Find the exponent that produces the final value.',`${b}^${e} = ${b**e}${v===1?`; log base ${b} of ${b**e} = ${e}`:''}.`,'How are powers and logarithms related?');if(v===3)return make('How many seats are in the requested row?',a+(c+1)*b,[row('Seats in row 1',a),row('Extra seats per row',b),row('Requested row',c+2)],'There are one fewer increases than the row number.',`${a} + (${c+2} − 1) × ${b} = ${a+(c+1)*b}.`,'Why do you subtract one from the row number?');if(v===4)return make('What constant amount is added at each step?',b,[row('Three consecutive totals',`${a}, ${a+b}, ${a+2*b}`)],'Subtract consecutive terms.',`${a+b} − ${a} = ${b}.`,'How do you check the change is constant?');return make('What was the first-row quantity?',a,[row('Known row number',c+2),row('Quantity in that row',a+(c+1)*b),row('Increase per row',b)],'Undo the increases before the known row.',`${a+(c+1)*b} − (${c+2} − 1) × ${b} = ${a}.`,'How many increases occurred before the known row?');}
 if(v<3)return v===2?make('At what input is the instantaneous change zero?',a,[row('Model',`f(x) = x² − ${2*a}x + ${b}`)],'Differentiate first, then set the derivative equal to zero.',`f′(x) = 2x − ${2*a}; 0 = 2x − ${2*a}; x = ${a}.`,'Why do you solve f′(x) = 0 rather than f(x) = 0?'):make('What is the instantaneous rate at the stated time?',v===0?2*a*b:3*a*b*b,[row('Position model',`s(t) = ${a}t^${v===0?2:3}`),row('Time',b)],'Apply the power rule before substituting the time.',v===0?`s′(t) = ${2*a}t; s′(${b}) = ${2*a*b}.`:`s′(t) = ${3*a}t²; s′(${b}) = ${3*a*b*b}.`,'How is instantaneous rate different from average rate?');
 if(v===3||v===5)return make(v===3?'What is the probability of selecting blue?':'What is the probability of not selecting blue?',v===3?a/(a+b):b/(a+b),[row('Blue tickets',a),row('Other tickets',b),row('Selection','One equally likely ticket')],'Divide favorable outcomes by all outcomes.',`${v===3?a:b}/${a+b}.`,'What makes up the sample space?');
 return make('What is the probability that both independent selections are gold?',1/(a*b),[row('First spinner equal sectors',a),row('Second spinner equal sectors',b),row('Gold sectors on each',1)],'Multiply probabilities only because these events are independent.',`(1/${a}) × (1/${b}) = 1/${a*b}.`,'Why does independence matter?');
}
export function learningProblem(id:string,level:Challenge,stage:string,index:number,r:()=>number):LearningProblem {
 const s=getSkill(id);if(!s)throw Error('Unknown skill');
 // Structural families run before the middle-school generator, whose later checks only re-roll numbers.
 const structural=structuralTransfer(id,level,stage,index,r);if(structural)return structural;
 if(middleSkill(id))return middleProblem(id,level,stage,index,r);
 if(['transfer','follow','retention'].includes(stage)){
  const transfer=deepTransfer(id,level,index+(stage==='follow'?1:0),r);
  if(transfer)return transfer;
 }
 const symbolic=(stage==='baseline'&&index!==1)||(stage==='check'&&index%2===0);
 const data=contextCase(id,level,r,stage==='transfer'||stage==='follow'||stage==='retention');
 const guided=stage==='practice'&&index%3===0&&!!data.step;
 const q=symbolic?problem(s,level,r):{text:guided?data.step!.ask:data.ask,answer:guided?data.step!.answer:data.answer,hint:data.strategy,explanation:guided?data.step!.work:data.work};
 if(s.grade===0&&s.variant===0&&['transfer','follow','retention'].includes(stage))data.rows=[row('Objects', '● '.repeat(data.dots![0]).trim())];
 const representation=symbolic?'symbolic':stage==='transfer'||stage==='retention'?'unfamiliar-context':stage==='follow'?'plain-context':guided?'guided-step':'quantity-model';
 // Each later check uses plain prose instead of the mission table.
 if(!symbolic&&(stage==='follow'||stage==='retention'||stage==='transfer'))q.text=`${data.rows.map(([k,v])=>`${k}: ${v}`).join('. ')}. ${q.text}`;
 if(stage==='transfer'||stage==='retention'){
  const swaps:[string,string][] = s.grade===5?[['recipe','class project'],['Recipe','Class project'],['supply','craft paper'],['liters','meters']]:s.grade===6?[['kits','hours'],['kit','hour'],['cost','distance'],['Cost','Distance'],['order','journey'],['concentrate','red paint'],['water','white paint'],['batch','paint mix']]:s.grade===8&&s.variant===0?[['parcels','tickets'],['parcel','ticket'],['budget','trip fund'],['Fixed fee','Entry fee'],['Total budget','Total trip fund']]:[['garden crew','school club'],['seeds','cards'],['packs','boxes']];
  for(const [from,to] of swaps)q.text=q.text.split(from).join(to);
 }
 q.text=withAnswerFormat(q.text,q.answer);
 return {...q,templateId:`${id}:v2:${representation}`,representation,guided,reasonPrompt:symbolic?`Explain a step you used to solve: ${q.text}`:data.reason,
 visual:symbolic||stage==='follow'||stage==='retention'||stage==='transfer'?undefined:{kind:data.dots?'dots':'table',caption:stage==='transfer'?'Use this new situation':missionNames[s.grade],rows:data.rows,...(data.dots?{dots:data.dots}:{})},
 hints:[`Look at the known quantities. ${data.reason}`,q.hint,`Worked example for this question: ${q.explanation}`],
 outcome:stage==='practice'&&!guided?`Plan checked: ${q.explanation}`:'Explain how the quantities relate; your teacher reviews your reasoning.'};
}
export function lesson(id:string,level:Challenge){if(middleSkill(id))return middleLesson(id,level);let seed=91+Number(id.replace(/\D/g,''));const r=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};const s=getSkill(id)!;const c=contextCase(id,level,r,false);return {title:s.name,mission:missionNames[s.grade],concept:gradeConcepts[s.grade],visual:{kind:c.dots?'dots':'table',caption:'Worked example',rows:c.rows,...(c.dots?{dots:c.dots}:{})} as Visual,question:c.ask,steps:[c.strategy,c.work,`Check your thinking: ${c.reason}`],oralPrompt:c.reason};}
