import {describe,it,expect} from 'vitest';
import {skillsForGrade,problem,getSkill} from './catalog';
import {initial,begin,answer,hint,confirm,replace,status,metrics,publicProgress,candidates,DEFAULT_POLICY,type Progress,type Stage} from './model';
import {normalizeLearning} from '../../services/game/curriculum';
let seed=178;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};let id=0;
const fresh=()=>initial(normalizeLearning({grade:7,topic:'mixed'}),[{id:'g7-s3',reason:'Teacher selected'}]);
function doQuestion(p:Progress,stage:Stage,correct=true,now=10000,support=false){let n=begin(p,'g7-s3',stage,DEFAULT_POLICY,now,random,`q${++id}`);if(support)n=hint(n,n.current!.id);return answer(n,n.current!.id,String(correct?n.current!.answer:n.current!.answer+100),now);}
function practiced(){let p=fresh();for(let i=0;i<3;i++)p=doQuestion(p,'baseline',i!==0,1000+i);for(let i=0;i<3;i++)p=doQuestion(p,'practice',true,2000+i,true);return p;}
function passed(){let p=practiced();for(let i=0;i<5;i++)p=doQuestion(p,'check',i!==0,3000+i);return p;}
describe('skill challenge evidence and fairness',()=>{
 it('has the expected specific skills at every supported grade, with valid finite questions',()=>{for(let g=0;g<=12;g++){const skills=skillsForGrade(g);expect(skills).toHaveLength(g>=6&&g<=8?24:6);expect(new Set(skills.map(s=>s.id)).size).toBe(skills.length);for(const skill of skills)for(const challenge of ['support','standard','stretch'] as const)for(let i=0;i<40;i++){const q=problem(skill,challenge,random);expect(Number.isFinite(q.answer)).toBe(true);expect(q.text.length).toBeGreaterThan(3);expect(q.hint).toBeTruthy();expect(q.explanation).toBeTruthy();}}});
 it('checks independent expected values for representative algebra, factors and probability',()=>{expect(problem(getSkill('g7-s5')!,'standard',()=>0).answer).toBe(4);expect(problem(getSkill('g4-s4')!,'standard',()=>0).answer).toBe(3);expect(problem(getSkill('g4-s5')!,'standard',()=>0).answer).toBe(2);expect(problem(getSkill('g12-s4')!,'standard',()=>0).answer).toBe(.25);expect(problem(getSkill('g9-s1')!,'standard',()=>0).answer).toBe(4);});
 it('does not count skills that were secure at baseline as new mastery',()=>{let p=fresh();for(let i=0;i<3;i++)p=doQuestion(p,'baseline');expect(status(p.targets[0])).toBe('secure');expect(()=>confirm(p,'g7-s3','Already knew it',10000)).toThrow();expect(()=>doQuestion(p,'check')).toThrow();});
 it('requires practice, a 4/5 check, delayed 2/2 check, then teacher confirmation',()=>{let p=fresh();expect(()=>doQuestion(p,'check')).toThrow();p=practiced();expect(metrics(p,p.targets[0]).independentPractice).toBe(0);p=passed();expect(status(p.targets[0])).toBe('follow');expect(()=>confirm(p,'g7-s3','Observed growth',90000)).toThrow();expect(()=>doQuestion(p,'follow',true,3005)).toThrow();p=doQuestion(p,'follow',true,86410000);p=doQuestion(p,'follow',true,86410001);expect(status(p.targets[0])).toBe('ready');p=confirm(p,'g7-s3','Explained the inverse operation independently',86410002);expect(status(p.targets[0])).toBe('confirmed');expect(p.targets[0].teacherNote).toContain('independently');});
 it('records hints in practice but never provides them in checks',()=>{const p=begin(practiced(),'g7-s3','check',DEFAULT_POLICY,10000,random,'secret');expect(()=>hint(p,'secret')).toThrow();expect(publicProgress(p).current).not.toHaveProperty('answer');expect(publicProgress(p).current).not.toHaveProperty('hint');expect(publicProgress(p).current).not.toHaveProperty('explanation');});
 it('requires fresh practice after an unsuccessful independent check',()=>{let p=practiced();for(let i=0;i<5;i++)p=doQuestion(p,'check',i<3,4000+i);expect(p.targets[0].passedAt).toBeNull();expect(()=>doQuestion(p,'check')).toThrow();for(let i=0;i<3;i++)p=doQuestion(p,'practice',true,5000+i);expect(()=>doQuestion(p,'check',true,6000)).not.toThrow();});
 it('returns an unsuccessful follow-up to practice without erasing evidence',()=>{let p=passed();p=doQuestion(p,'follow',true,86410000);p=doQuestion(p,'follow',false,86410001);expect(status(p.targets[0])).toBe('practice');expect(p.events.filter(e=>e.stage==='follow')).toHaveLength(2);expect(()=>confirm(p,'g7-s3','Many attempts',86410002)).toThrow();expect(()=>doQuestion(p,'check',true,86410003)).toThrow();});
 it('cannot gain credit by replaying answers, submitting invalid answers or skipping pending questions',()=>{const p=begin(fresh(),'g7-s3','baseline',DEFAULT_POLICY,10000,random,'one');expect(()=>answer(p,'other','2',10000)).toThrow();expect(()=>answer(p,'one','2abc',10000)).toThrow();expect(()=>begin(p,'g7-s3','baseline',DEFAULT_POLICY,10000,random,'two')).toThrow();const done=answer(p,'one','2',10000);expect(answer(done,'one','100',10001).events).toHaveLength(1);expect(answer(done,'one','100',10001).events[0].answer).toBe('2');});
 it('keeps replaced work and does not transfer credit to a new target',()=>{const p=replace(practiced(),'g7-s3','g7-s4','Teacher wants multiplication next');expect(p.targets[0].baseline).toBeNull();expect(p.archived[0].baseline).toBe(2);expect(p.events).toHaveLength(6);expect(()=>replace(p,'g7-s4','g8-s1','Wrong grade')).toThrow();expect(()=>replace(p,'g7-s4','g7-s3','Already used')).toThrow();});
 it('uses current grade topic history to suggest needs without fabricating subskill mastery',()=>{const list=candidates(7,skillsForGrade(7),[{topic:'One-step equations',questions:10,independent:2}],[]);expect(list[0].topic).toBe('One-step equations');expect(list[0].reason).toContain('subskill needs a starting check');expect(list.every(s=>s.grade===7)).toBe(true);});
 it('requires finishing a short independent set before switching targets',()=>{let p=practiced();p.targets.push({...initial(normalizeLearning({grade:7}),[{id:'g7-s4',reason:'Selected'}]).targets[0]});p=doQuestion(p,'check');expect(()=>begin(p,'g7-s4','baseline',DEFAULT_POLICY,10000,random,'other')).toThrow();expect(()=>doQuestion(p,'practice')).toThrow();});
});

it('every subskill can complete a full support-level learning path with fresh questions',()=>{for(let grade=0;grade<=12;grade++)for(const skill of skillsForGrade(grade)){let p=initial(normalizeLearning({grade,challenge:'support'}),[{id:skill.id,reason:'Selected'}]);let now=10000;for(const stage of ['baseline','practice','check','follow'] as Stage[]){if(stage==='follow')now+=86400000;const count=stage==='check'?5:stage==='follow'?2:3;for(let i=0;i<count;i++){p=begin(p,skill.id,stage,DEFAULT_POLICY,++now,random,`full-${++id}`);p=answer(p,p.current!.id,String(p.current!.answer+(stage==='baseline'&&i===0?1000:0)),now);}}expect(status(p.targets[0]),skill.id).toBe('ready');}});
