import { middleSkill } from '../middle-school/catalog';
import { startPolling } from '../../pilot/polling';
import {lesson} from './lessons';
import {LessonView,QuantityModel} from './LessonView';
import {useStudentChallenge,type StudentData,type Challenge} from './studentContext';
import {useCallback,useEffect,useRef,useState} from 'react';
import {pilotAPI} from '../../pilot/api';
import {gradeLabel,parseMathAnswer,type LearningSettings} from '../../services/game/curriculum';
import {getSkill,skillsForGrade} from './catalog';
import type {Triage,TriageGroup} from './triage';
import {consequence} from './structural';
import {ENHANCED_POLICY,metrics,status,hasOpenCheck,type Candidate,type Policy,type ProgressView,type Target,type Stage} from './model';
import './challenge.css';
type Plan={id:string;alias:string;learning:LearningSettings;settingsVersion:number;candidates:Candidate[]};
type Learner={id:string;alias:string;active:boolean;gradeChanged:boolean;revision:number;updatedAt:number;progress:ProgressView;confirmed:number;summary?:{id:string;autoConfirmed?:boolean;triage?:Triage}[]};
const GROUPS:[TriageGroup,string,string][]=[['needs-you','Needs you','Something in the record doesn’t add up, or this challenge needs your confirmation. Use the 30-second question.'],['ready','Ready — clean record','Finished with no contradictions.'],['auto-confirmed','Auto-confirmed','Perfect independent, different-use, and next-day checks with no hints. Undo if you disagree.'],['confirmed','Confirmed by you','Your confirmations, with your notes.'],['in-progress','Still working','Nothing for you to do yet.']];
const triageOf=(s:Learner,id:string)=>s.summary?.find(x=>x.id===id)?.triage;
type TeacherData={challenge:Challenge|null;learners:Learner[]};
const labels={baseline:'Starting check',practice:'Practice & grow',check:'Independent check',transfer:'Different-use check',retention:'One-week check',follow:'Fresh follow-up check',ready:'Ready for teacher review',confirmed:'Teacher-confirmed',secure:'Already secure · choose a new growth target'};
const skillLabel=(id:string,stage:keyof typeof labels)=>stage==='transfer'&&middleSkill(id)?'Additional fresh check':labels[stage];
const title=(id:string)=>getSkill(id)?.name??id;
const reviewId=new URLSearchParams(window.location.search).get('skillChallenge');
const reviewPath=`skill-challenges${reviewId?`?id=${encodeURIComponent(reviewId)}`:''}`;
const delayLabel=(hours:number)=>hours===24?'at least 24 hours later':'at least 10 minutes later';
function Rules({policy}:{policy:Policy}){return <details className="skill-rules"><summary>What counts as mastery for this challenge?</summary><ol><li>A 3-question starting check identifies your starting point. A 3/3 target is already secure; your teacher can choose a fresh growth target.</li><li>Complete at least 3 practice questions. Hints and mistakes are welcome here.</li><li>Answer at least 4 of 5 fresh check questions correctly, without hints.</li><li>Answer 2 of 2 follow-up questions correctly, {delayLabel(policy.delayHours)}.</li>{policy.version===2&&<li>Answer 2 additional fresh questions, then explain your thinking in writing or to your teacher. The later check uses plain questions; a one-week check is optional evidence.</li>}<li>Your teacher reviews the evidence and confirms each of your {policy.target} targets.</li></ol><p>These are this challenge’s evidence rules, not a permanent claim about everything you know. No speed points. Practice totals show context, not an automatic score.</p></details>;}
function TeacherReviewGuide(){return <section className="skill-review-guide" aria-label="How to check mastery and choose a winner"><p className="skill-eyebrow">Your review checklist</p><h3>How do I check their work?</h3><ol><li><strong>Open a skill marked “Ready for teacher review”.</strong><p>Find the learner below and click the skill name. The app checks for practice, at least 4/5 on the independent check, and 2/2 on the follow-up before showing this status.</p></li><li><strong>Compare their starting point with their new work.</strong><p>Read the evidence boxes, then open “View question-by-question proof” to see answers, hint use, and dates. Look for learning after mistakes and success on fresh questions. Practice hints are allowed.</p></li><li><strong>Add your observation, then click “Confirm mastery”.</strong><p>If you are unsure, ask the student to explain how they solved a problem before confirming. Example note: “Started at 1/3; explained equal groups and passed both fresh checks.” Leave it unconfirmed until you have enough evidence.</p></li><li><strong>Review every target, then choose a qualified winner.</strong><p>All assigned skills need your confirmation. Give everyone the challenge window, click “Close challenge for judging”, and finish any pending reviews. Under “Qualified learner”, select a student, explain their growth and follow-through, and click “Record selected winner”.</p></li></ol><p className="skill-fair">Qualification is automatic after your confirmations; choosing the winner is your decision. Compare growth within each student’s own grade and targets. Speed, higher grades, and more attempts do not earn extra credit.</p></section>;}
const teacherNext:Record<ReturnType<typeof status>,string>={baseline:'Wait for the student to finish the 3-question starting check.',practice:'The student needs practice and successful fresh checks before you can confirm.',transfer:'Review independent work, then ask the learner to try the additional fresh check.',follow:'Wait for the follow-up check: both answers must be correct.',ready:'Review the evidence below, add an observation, then confirm mastery if the work supports it.',confirmed:'Your confirmation is saved. This skill counts toward qualification.',secure:'The student scored 3/3 at the start. Choose “Teacher: replace this target” while submissions are open so they have a new growth goal.'};
function exportChallenge(data:TeacherData){const rows=[['Student','Grade','Skill','Starting correct / 3','Practice correct','Practice attempted','Practice days (UTC)','Check correct / 5','Follow-up correct / 2','Status','Teacher observation','Policy version','Additional check correct / 2','Learner explanation (teacher reviewed)','One-week correct / 2','Supported practice','Independent practice'],...data.learners.flatMap(s=>s.progress.targets.map(t=>{const m=metrics(s.progress,t);return [s.alias,String(s.progress.learning.grade),title(t.id),t.baseline===null?'Not checked':String(t.baseline),String(m.completedPractice),String(m.practice),String(m.practiceDays),String(m.check),String(m.follow),skillLabel(t.id,status(t)),t.teacherNote,String(s.progress.version??1),s.progress.version===2?(t.transferAt?String(m.transfer):'Not completed'):'Not assessed',t.reflection??'Not recorded',t.retentionAt?String(m.retention):'Not assessed',String(m.supported),String(m.independentPractice)];}))];const csv=rows.map(r=>r.map(v=>`"${(/^[=+\-@\t\r]/.test(v)?"'":'')+v.replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='skill-challenge-evidence.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function TeacherSkillChallenge(){
 const [topicFilters,setTopicFilters]=useState<Record<string,string>>({});
 const [data,setData]=useState<TeacherData>({challenge:null,learners:[]}),[plans,setPlans]=useState<Plan[]>([]),[policy,setPolicy]=useState(ENHANCED_POLICY),[draft,setDraft]=useState<Record<string,string[]>>({}),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[planning,setPlanning]=useState(false),[winner,setWinner]=useState(''),[reason,setReason]=useState('');
 const [oral,setOral]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[replacements,setReplacements]=useState<Record<string,string>>({});const lock=useRef(false);
 const refresh=useCallback(async()=>{const next=await pilotAPI<TeacherData>(reviewPath);setData(next);return next;},[]);
 useEffect(()=>{let active=true;const poll=async()=>{try{const next=await pilotAPI<TeacherData>(reviewPath);if(active)setData(next);}catch(e){if(active)setError(e instanceof Error?e.message:'Could not load challenge.');}};const stop=startPolling(poll,15000);return()=>{active=false;stop();};},[]);
 const run=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{lock.current=false;setBusy(false);}};
 const plan=()=>run(async()=>{const next=await pilotAPI<{learners:Plan[]}>('skill-challenges/preview');setPlans(next.learners);setDraft(Object.fromEntries(next.learners.map(s=>[s.id,s.candidates.slice(0,policy.target).map(c=>c.id)])));setSelected(next.learners.filter(s=>s.candidates.length>=policy.target).map(s=>s.id));setPlanning(true);});
 const mutate=(op:string,body:Record<string,unknown>)=>run(async()=>{setData(await pilotAPI<TeacherData>(`skill-challenges/${op}?id=${data.challenge!.id}`,'POST',{challengeId:data.challenge!.id,...body}));});
 const c=data.challenge,eligible=data.learners.filter(s=>s.confirmed>=(c?.policy.target??3));
 return <section className="skill-challenge"><header className="skill-hero"><img src="/assets/woodland-v1/pip-portrait.png" alt="Pip"/><div><p className="skill-eyebrow">Teacher-led growth challenge</p><h2>Different paths. Real progress.</h2><p>Choose the exact skills each learner needs. Recognize the work they put into mastering their own targets.</p></div></header>
 <details className="skill-rules"><summary>How to review evidence and choose a winner</summary><TeacherReviewGuide/></details>
 {error&&<p role="alert" className="skill-error">{error}</p>}
 {!planning&&(!c||c.closedAt)&&<button className="pilot-primary" disabled={busy} onClick={()=>void plan()}>Plan a skill challenge</button>}
 {planning&&<><div className="skill-settings"><label>Learning path<select aria-label="Learning path" value={policy.version??1} onChange={e=>setPolicy({...policy,version:Number(e.target.value) as 1|2})}><option value={2}>Guided learning + different-use checks (K–12)</option><option value={1}>Original challenge rules</option></select></label><label>Challenge name<input value={policy.name} maxLength={80} onChange={e=>setPolicy({...policy,name:e.target.value})}/></label><label>Skills to master<select aria-label="Skills to master" value={policy.target} onChange={e=>{const target=Number(e.target.value);setPolicy({...policy,target});setDraft(old=>Object.fromEntries(plans.map(s=>{const ids=old[s.id]??[];return [s.id,[...ids,...s.candidates.filter(c=>!ids.includes(c.id)).map(c=>c.id)].slice(0,target)];})));}}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>Follow-up check<select aria-label="Follow-up check" value={policy.delayHours} onChange={e=>setPolicy({...policy,delayHours:Number(e.target.value)})}><option value={24}>A later day · after 24 hours</option><option value={1/6}>Same class · after 10 minutes</option></select></label></div><Rules policy={policy}/><p>Coverage: 24 objectives in each of grades 6–8, plus six in each other grade (132 total). Worked examples, practice, and later checks support the selected objectives. This is a practice catalog, not a complete curriculum. Expanded middle-school objectives use fresh-quantity checks; transfer to unfamiliar situations still needs teacher review.</p><p><strong>You choose the targets.</strong> Suggestions use the last 30 days of available work at each student’s current settings. Existing records describe topics; the new starting check measures these specific subskills.</p>
 {plans.map(s=><article className="skill-plan" key={s.id}><label className="skill-check"><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>Include {s.alias} · {gradeLabel(s.learning.grade)}</label><details><summary>Choose exact targets · {draft[s.id]?.length??0} / {policy.target} selected</summary><label>Filter targets by topic<select aria-label={`Filter topics for ${s.alias}`} value={topicFilters[s.id]??''} onChange={e=>setTopicFilters({...topicFilters,[s.id]:e.target.value})}><option value="">All topics</option>{[...new Set(s.candidates.map(c=>c.topic))].map(topic=><option key={topic}>{topic}</option>)}</select></label><div className="skill-options">{s.candidates.filter(c=>!topicFilters[s.id]||c.topic===topicFilters[s.id]).map(option=><label className="skill-option" key={option.id}><input type="checkbox" checked={draft[s.id]?.includes(option.id)??false} disabled={!draft[s.id]?.includes(option.id)&&(draft[s.id]?.length??0)>=policy.target} onChange={e=>setDraft({...draft,[s.id]:e.target.checked?[...(draft[s.id]??[]),option.id]:(draft[s.id]??[]).filter(id=>id!==option.id)})}/><span><strong>{option.name}</strong><small>{option.reason}</small></span></label>)}</div></details><p className="skill-selected">{(draft[s.id]??[]).map(title).join(' · ')}</p></article>)}
 <div className="skill-actions"><button className="pilot-primary" disabled={busy||!selected.length||selected.some(id=>draft[id]?.length!==policy.target)||policy.name.trim().length<3} onClick={()=>void run(async()=>{setData(await pilotAPI<TeacherData>('skill-challenges/issue','POST',{...policy,assignments:selected.map(id=>({studentId:id,settingsVersion:plans.find(s=>s.id===id)!.settingsVersion,skills:draft[id]}))}));setPlanning(false);})}>Issue {policy.target}-skill challenge to {selected.length} learners</button><button disabled={busy} onClick={()=>setPlanning(false)}>Cancel planning</button></div></>}
 {c&&!planning&&<><div className="skill-challenge-heading"><div><p className="skill-eyebrow">{c.closedAt?'Closed challenge':'Active challenge'}</p><h3>{c.policy.name}</h3><p>Each learner must have all {c.policy.target} assigned skills confirmed to qualify. Counts and timing do not choose the winner.</p></div><div className="skill-actions"><button disabled={busy} onClick={()=>void run(async()=>{await refresh();})}>Refresh progress</button><button onClick={()=>exportChallenge(data)}>Download evidence CSV</button><a href={`/?skillChallenge=${encodeURIComponent(c.id)}`}>Saved review link</a>{reviewId&&<a href="/">Return to current classroom</a>}{!c.closedAt&&<button disabled={busy} onClick={()=>{if(confirm('Close student submissions? You can still review and confirm completed checks, then choose a winner.'))void mutate('close',{});}}>Close challenge for judging</button>}</div></div><Rules policy={c.policy}/><p className="skill-review-ready"><strong>{data.learners.flatMap(s=>s.progress.targets).filter(t=>status(t)==='ready').length} skills ready for your review</strong> · Passing the checks opens teacher review; only your confirmation counts toward the goal.</p>
 <section className="skill-review-queue" aria-label="Teacher review queue"><h3>What needs my attention?</h3><div>{GROUPS.map(([group,label,help])=>{const items=data.learners.flatMap(s=>s.progress.targets.map(t=>({s,t,tri:triageOf(s,t.id)})).filter(x=>(x.tri?.group??(x.t.confirmedAt?'confirmed':'in-progress'))===group));return <section key={group}><h4>{label} ({items.length})</h4><p>{help}</p>{group!=='in-progress'&&items.map(({s,t,tri})=><button key={s.id+t.id} onClick={()=>{const el=document.getElementById(`evidence-${s.id}-${t.id}`) as HTMLDetailsElement|null;if(el){el.open=true;el.scrollIntoView({block:'start'});el.querySelector('summary')?.focus();}}}>{s.alias} · {title(t.id)}{group==='needs-you'&&tri?.reasons[0]&&<small> — {tri.reasons[0]}</small>}</button>)}</section>;})}</div><p>Clean runs confirm themselves so your time goes to the records that need a person. Groups guide conversations; they do not rank learners.</p></section>
 <p className="skill-fair">Compare learners with their own starting points. Hints support practice; checks measure independent work. More clicks, harder grades, and faster completion earn no extra rank.</p>
 {data.learners.map(s=><article key={s.id} className="skill-learner"><header><div><h3>{s.alias}</h3><p>{gradeLabel(s.progress.learning.grade)} · {s.progress.learning.challenge}</p></div><strong className="skill-count">{s.confirmed} / {c.policy.target}<small>teacher-confirmed</small></strong></header><progress max={c.policy.target} value={s.confirmed} aria-label={`${s.alias} confirmed skills`}/><p className="skill-qualification"><strong>{s.confirmed>=c.policy.target?'Qualified to be selected as winner':`${c.policy.target-s.confirmed} more teacher confirmations needed to qualify`}</strong> · {s.progress.targets.filter(t=>status(t)==='ready').length} skills ready for review</p>{s.gradeChanged&&<p className="skill-error">Assigned grade changed. This challenge is paused for this learner. Review their new level before the next challenge.</p>}{!s.active&&<p>Account paused.</p>}
 {!c.closedAt&&s.active&&!s.gradeChanged&&<section className="skill-focus-controls"><h4>Focused classroom session</h4><p>One assigned target stays on Home across reloads and devices. Ending the session keeps every answer.</p>{s.progress.focus?<><p>Current focus: {title(s.progress.focus.skillId)} · {s.progress.focus.onBreak?'On an approved break':s.progress.focus.activity}</p><button disabled={busy} onClick={()=>void mutate('focus',{studentId:s.id,revision:s.revision,skillId:''})}>End focused session for {s.alias}</button></>:<form onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget);void mutate('focus',{studentId:s.id,revision:s.revision,skillId:String(values.get('target')),activity:String(values.get('activity')),breakAllowed:values.get('break')==='on'});}}><label>Focus target for {s.alias}<select name="target">{s.progress.targets.map(t=><option key={t.id} value={t.id}>{title(t.id)}</option>)}</select></label><label>Session activity<select name="activity"><option value="lesson">Worked example and guided practice</option><option value="practice">Practice and due checks</option></select></label><label><input name="break" type="checkbox" defaultChecked/> Allow a quiet pet break</label><button disabled={busy}>Start focused session for {s.alias}</button></form>}</section>}
 {s.progress.targets.map(t=>{const key=s.id+t.id,m=metrics(s.progress,t),state=status(t);return <details id={`evidence-${s.id}-${t.id}`} key={t.id} className={`skill-target skill-${state}`}><summary><strong>{title(t.id)}</strong><span>{skillLabel(t.id,state)}</span></summary><p className="skill-review-next"><strong>Your next step:</strong> {c.winnerId?'Judging is complete. This evidence remains available for review.':s.gradeChanged||!s.active?'This learner’s challenge is paused. Review their grade or access before confirming.':c.closedAt&&state!=='ready'&&state!=='confirmed'?'Submissions are closed. This unfinished target cannot count toward qualification.':teacherNext[state]}</p><p>{t.reason}</p>{(()=>{const tri=triageOf(s,t.id);return <>{tri&&tri.reasons.length>0&&<div className="skill-flags"><strong>Why this needs you:</strong><ul>{tri.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>}<p><strong>30-second check:</strong> {tri?.prompt??lesson(t.id,s.progress.learning.challenge).oralPrompt}</p>{t.autoConfirmed&&t.confirmedAt&&!c.winnerId&&<button disabled={busy} onClick={()=>void mutate('unconfirm',{studentId:s.id,skillId:t.id,revision:s.revision})}>Undo auto-confirm</button>}</>;})()}<div className="skill-evidence"><span>Starting check<strong>{t.baseline===null?`${t.baselineIds.length}/3 answered`:`${t.baseline}/3 correct`}</strong></span><span>Practice<strong>{m.completedPractice} correct / {m.practice} attempted</strong></span><span>Practice dates (UTC)<strong>{m.practiceDays}</strong></span><span>Independent check<strong>{m.check}/5</strong></span><span>Follow-up check<strong>{m.follow}/2</strong></span><span>Different-use check<strong>{s.progress.version===2?`${m.transfer}/2`:'Not assessed (original rules)'}</strong></span><span>One-week check<strong>{t.retentionAt?`${m.retention}/2`:"Not assessed"}</strong></span><span>Supported practice<strong>{m.supported}</strong></span></div>{t.passedAt&&!t.followAt&&<p>Follow-up opens {new Date(Math.max(t.passedAt,t.transferAt??0)+c.policy.delayHours*3600000).toLocaleString()}.</p>}{t.teacherNote&&<p><strong>Your observation:</strong> {t.teacherNote}</p>}
 <p><strong>Learner explanation (not automatically scored):</strong> {t.reflection??'Not recorded'}</p><details className="skill-proof"><summary>View question-by-question proof</summary><ol>{s.progress.events.filter(e=>e.skill===t.id).map(e=><li key={e.id}><strong>{skillLabel(e.skill,e.stage)} · {e.correct?'Correct':'Not yet'}{e.supported?e.representation==='guided-step'?' · Guided step':' · Hint used':''}</strong><p>{e.text}</p><QuantityModel visual={e.visual}/><p>{e.representation??'Original question format'}{e.answerRevealed?' · Answer revealed during support':''}</p>{e.reasoning&&<p>Student reasoning (teacher review): {e.reasoning}</p>}<p>Response: {e.answer} · Answer: {e.expected} · {new Date(e.at).toLocaleString()}</p></li>)}</ol></details>
 {!c.winnerId&&!s.gradeChanged&&state==='ready'&&<div className="skill-confirm">{s.progress.version===2&&!t.reflection&&<form onSubmit={e=>{e.preventDefault();void mutate('reflection',{studentId:s.id,skillId:t.id,revision:s.revision,reflection:oral[key]});}}><label>Oral explanation I heard<textarea value={oral[key]??''} maxLength={1000} onChange={e=>setOral({...oral,[key]:e.target.value})} placeholder="Record the student's words, drawing, pointing, or demonstration. Do not judge spelling."/></label><button disabled={busy||!oral[key]?.trim()}>Save observed explanation</button></form>}<p><strong>Before confirming:</strong> review both check results and the question-by-question proof. Your note records what convinced you the student can use this skill independently.</p><label>Teacher observation<input aria-label={`Observation for ${s.alias}: ${title(t.id)}`} value={notes[key]??''} maxLength={500} placeholder="Example: Started at 1/3; explained the method and passed both fresh checks." onChange={e=>setNotes({...notes,[key]:e.target.value})}/></label><p>Write an observation of at least 5 characters to enable confirmation. If unsure, leave this skill awaiting review.</p><button className="pilot-primary" disabled={busy||(notes[key]?.trim().length??0)<5||s.progress.version===2&&!t.reflection} onClick={()=>void mutate('confirm',{studentId:s.id,skillId:t.id,revision:s.revision,note:notes[key]})}>Confirm mastery</button></div>}
 {!c.closedAt&&!t.confirmedAt&&!s.gradeChanged&&<details><summary>Teacher: replace this target</summary><p>The old work stays in the record. The new target starts with its own baseline; it does not inherit credit.</p><label>New skill<select aria-label={`Replacement for ${s.alias}: ${title(t.id)}`} value={replacements[key]??''} onChange={e=>setReplacements({...replacements,[key]:e.target.value})}><option value="">Choose another skill at this grade</option>{skillsForGrade(s.progress.learning.grade).filter(x=>![...s.progress.targets,...s.progress.archived].some(t=>t.id===x.id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Reason<input value={notes[key]??''} maxLength={500} onChange={e=>setNotes({...notes,[key]:e.target.value})}/></label><button disabled={busy||!replacements[key]||(notes[key]?.trim().length??0)<5} onClick={()=>void mutate('replace',{studentId:s.id,skillId:t.id,newSkillId:replacements[key],revision:s.revision,note:notes[key]})}>Assign replacement skill</button></details>}
 </details>;})}{s.progress.archived.length>0&&<details><summary>Replaced targets and prior work</summary>{s.progress.archived.map(t=><p key={t.id}>{title(t.id)} · baseline {t.baseline??'unfinished'}/3 · {s.progress.events.filter(e=>e.skill===t.id).length} recorded questions</p>)}</details>}
 </article>)}
 <section className="skill-judging"><h3>You choose who earned the recognition.</h3><p>Look for improvement, purposeful practice, and a successful return to the skill. Review the starting check and both independent checks. Students are shown only their own progress.</p>{c.winnerId?<p className="skill-recognition"><strong>{data.learners.find(s=>s.id===c.winnerId)?.alias} · Recognized for growth</strong><br/>{c.winnerReason}</p>:c.closedAt?<><label>Qualified learner<select aria-label="Qualified learner" value={winner} onChange={e=>setWinner(e.target.value)}><option value="">Choose after reviewing their work</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.alias} · {s.confirmed}/{c.policy.target} confirmed</option>)}</select></label>{!eligible.length&&<p>No learner has all targets confirmed. No winner is assigned automatically.</p>}<label>Why their work deserves recognition<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder="Describe the growth and follow-through you are recognizing."/></label><button className="pilot-primary" disabled={busy||!winner||reason.trim().length<10} onClick={()=>void mutate('winner',{studentId:winner,reason})}>Record selected winner</button></>:<p>Close submissions when you’re ready to judge. You can finish reviewing completed checks afterward. Learners stay listed alphabetically.</p>}</section>
 </>}
 </section>;
}
function TargetAction({t,p,policy,now,onBegin,busy}:{t:Target;p:ProgressView;policy:Policy;now:number;onBegin:(id:string,stage:Stage)=>void;busy:boolean}){
 const inProgress=p.targets.find(x=>x.checkIds.length>0&&x.checkIds.length<5||x.followIds.length===1||x.transferIds?.length===1||x.retentionIds?.length===1);if(inProgress){return inProgress.id===t.id?<button disabled={busy} onClick={()=>onBegin(t.id,inProgress.retentionIds?.length===1?'retention':inProgress.transferIds?.length===1?'transfer':inProgress.followIds.length===1?'follow':'check')}>Continue your short check</button>:<p>Finish the short check on {title(inProgress.id)} first.</p>;}
 const state=status(t),m=metrics(p,t);if(state==='transfer')return <button disabled={busy} onClick={()=>onBegin(t.id,'transfer')}>Use it differently · {t.transferIds?.length??0}/2</button>;if(p.version===2&&t.baseline!==null&&t.baseline<3&&!t.lessonAt)return <p>Open the worked example above, then mark it reviewed to begin guided practice.</p>;if(['confirmed','ready','secure'].includes(state))return <p className="skill-next-note">{state==='confirmed'?'Your teacher confirmed this skill.':state==='secure'?'You already showed this skill. Your teacher can choose a new growth target.':'Both checks passed. Your teacher will review your work.'}</p>;
 return <div className="skill-actions">{state==='baseline'?<button disabled={busy} onClick={()=>onBegin(t.id,'baseline')}>Starting check · {t.baselineIds.length}/3</button>:<><button disabled={busy} onClick={()=>onBegin(t.id,'practice')}>Practice with hints</button>{!t.passedAt&&<button disabled={busy||!(t.checkIds.length>0&&t.checkIds.length<5)&&m.practiceForNextCheck<3} onClick={()=>onBegin(t.id,'check')}>{t.checkIds.length>0&&t.checkIds.length<5?`Continue check · ${t.checkIds.length}/5`:'Take independent check'}</button>}{t.passedAt&&(now>=Math.max(t.passedAt,t.transferAt??0)+policy.delayHours*3600000?<button disabled={busy} onClick={()=>onBegin(t.id,'follow')}>Fresh follow-up · {t.followIds.length}/2</button>:<p>Follow-up opens {new Date(Math.max(t.passedAt,t.transferAt??0)+policy.delayHours*3600000).toLocaleString()}. You can work on another target.</p>)}{!t.passedAt&&!(t.checkIds.length>0&&t.checkIds.length<5)&&m.practiceForNextCheck<3&&<p>Complete {3-m.practiceForNextCheck} more practice questions to open your check.</p>}</>}</div>;
}
export function StudentSkillChallenge({prepare,blocked}:{prepare:()=>Promise<void>;blocked:boolean}){
 const shared=useStudentChallenge();
 const data=shared?.data??null;
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[answerText,setAnswer]=useState(''),[reasoning,setReasoning]=useState(''),[reflection,setReflection]=useState(''),[open,setOpen]=useState(false),[now,setNow]=useState(Date.now());const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false),opened=useRef(0);
 const accept=shared!.accept,refresh=shared!.refresh;
 const show=useCallback(async()=>{setBusy(true);setError('');try{await prepare();await refresh();setOpen(true);dialog.current?.showModal();}catch(e){setError(e instanceof Error?e.message:'Finish your current activity first.');}finally{setBusy(false);}},[prepare,refresh]);
 useEffect(()=>{if(shared?.openRequest&&shared.openRequest!==opened.current){opened.current=shared.openRequest;void show();}},[shared?.openRequest,show]);
 const command=async(op:string,body:Record<string,unknown>)=>{if(lock.current||!data?.assignment||!data.challenge)return;lock.current=true;setBusy(true);setError('');try{const next=await pilotAPI<StudentData>(`skill-challenges/${op}?id=${data.challenge.id}`,'POST',{...body,revision:data.assignment.revision});accept(next);setNow(next.serverNow);if(op==='begin'){setAnswer('');setReasoning('');}if(op==='begin'||op==='answer')requestAnimationFrame(()=>dialog.current?.querySelector(op==='begin'?'.skill-question':'.skill-feedback')?.scrollIntoView({block:'start'}));}catch(e){setError(e instanceof Error?e.message:'Could not save your work.');try{await refresh();}catch{/* Keep current question until connection returns. */}}finally{setBusy(false);lock.current=false;}};
 if(!data?.assignment||!data.challenge)return null;
 const {progress:p,gradeChanged}=data.assignment,c=data.challenge,q=p.current,confirmed=p.targets.filter(t=>t.confirmedAt).length;
 return <><button className="skill-student-invite" disabled={blocked||busy} onClick={()=>void show()}>My skill challenge · {confirmed}/{c.policy.target}</button>{!open&&error&&<span role="alert">{error}</span>}<dialog ref={dialog} className="skill-dialog" onClose={()=>setOpen(false)}><section className="skill-challenge"><header className="skill-hero"><img src="/assets/woodland-v1/pip-portrait.png" alt="Pip"/><div><p className="skill-eyebrow">Your teacher’s challenge</p><h2>{c.policy.name}</h2><p>Master these {c.policy.target} skills to qualify. Your own progress matters.</p></div><button onClick={()=>dialog.current?.close()}>Back to my pet</button></header>{error&&<p className="skill-error" role="alert">{error}</p>}<progress max={c.policy.target} value={confirmed} aria-label="My confirmed skills"/><p><strong>{confirmed} / {c.policy.target} teacher-confirmed</strong> · {gradeLabel(p.learning.grade)}</p><Rules policy={c.policy}/><p><a href={`/?skillChallenge=${encodeURIComponent(c.id)}`}>Saved link to this challenge and its later checks</a> · Bookmark this link to return after your class starts a new challenge.</p>{gradeChanged&&<p className="skill-error">Your teacher changed your grade. Ask them to review these targets before continuing.</p>}{c.closedAt&&<p className="skill-recognition">This challenge has closed. Your work is saved.{c.winnerId===data.assignment.studentId?` Your teacher recognized your growth: ${c.winnerReason}`:''}</p>}
 {q&&!q.answered&&(!c.closedAt||q.stage==='retention')&&!gradeChanged&&<form className="skill-question" onSubmit={e=>{e.preventDefault();void command('answer',{questionId:q.id,answer:answerText,reasoning});}}><p className="skill-eyebrow">{skillLabel(q.skill,q.stage)} · {title(q.skill)}</p><h3>{q.text}</h3><QuantityModel visual={q.visual}/>{p.version===2&&q.stage==='practice'&&<p>Use the quantities to make your plan. Hints can guide you one step at a time.</p>}<label>Your answer<input value={answerText} required autoComplete="off" maxLength={100} onChange={e=>setAnswer(e.target.value)} placeholder="Number, decimal, or fraction"/></label><label>Explain your thinking (optional; you may explain aloud)<textarea value={reasoning} maxLength={1000} onChange={e=>setReasoning(e.target.value)} placeholder={q.reasonPrompt}/></label><div className="skill-actions"><button className="pilot-primary" disabled={busy||blocked||!!p.focus?.onBreak}>Submit answer</button>{q.stage==='practice'&&(!q.hintUsed||p.version===2&&(q.hintLevel??0)<3)&&<button type="button" disabled={busy||blocked} onClick={()=>void command('hint',{questionId:q.id})}>{q.hintUsed?(q.hintLevel===1?'Strategy hint':'Show worked solution · supported'):'Give me a hint'}</button>}</div>{q.hintUsed&&<p className="skill-hint">{q.hint}</p>}{q.stage!=='practice'&&<p>No hints during this short check. Mistakes simply show us what to practice next.</p>}</form>}
 {q?.answered&&<div className="skill-feedback" role="status">{(()=>{const e=p.events.find(e=>e.id===q.id),miss=e&&!e.correct&&q.stakes?consequence(q.stakes,parseMathAnswer(e.answer),e.expected):'';return <><strong>{e?.correct?'You got it.':'Let’s learn from that one.'}</strong>{miss&&<p className="skill-stakes">{miss}</p>}</>;})()}<p>{q.explanation}</p><p>Answer: {q.answer}</p><p>Your work is saved. Your companion is here with you. This is a good stopping point; leaving never counts as a wrong answer.</p></div>}
 {p.targets.filter(t=>!p.focus||c.closedAt||t.id===p.focus.skillId).map(t=><article className={`skill-target skill-${status(t)}`} key={t.id}><h3>{title(t.id)}</h3><p>{skillLabel(t.id,status(t))}</p>{p.version===2&&t.baseline!==null&&t.baseline<3&&!hasOpenCheck(p)&&(!q||q.answered)&&!t.confirmedAt&&!c.closedAt&&<><details className="skill-example" open={p.focus?.activity==='lesson'?true:undefined}><summary>Learn this skill · example and model</summary><LessonView id={t.id} level={p.learning.challenge}/><button disabled={busy||blocked} onClick={()=>void command('lesson',{skillId:t.id})}>{t.lessonAt?'Example reviewed · review again':'I read the example · ready to practice'}</button></details></>}{p.version===2&&t.transferAt&&!t.confirmedAt&&!c.closedAt&&<form onSubmit={e=>{e.preventDefault();void command('reflect',{skillId:t.id,reflection});}}><label>Explain how you used {title(t.id)}<textarea maxLength={1000} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Write your reasoning, or write: I will explain to my teacher."/></label><button disabled={busy||blocked||!reflection.trim()}>Save my explanation</button>{t.reflection&&<p>Saved for your teacher: {t.reflection}</p>}</form>}{p.version===2&&t.confirmedAt&&!t.retentionAt&&Math.max(now,data.serverNow??0)>=t.confirmedAt+7*86400000&&(!q||q.answered)&&<button disabled={busy||blocked} onClick={()=>void command('begin',{skillId:t.id,stage:'retention'})}>Optional one-week check</button>}{!c.closedAt&&!gradeChanged&&(!q||q.answered)&&<TargetAction t={t} p={p} policy={c.policy} now={Math.max(now,data.serverNow??0)} busy={busy||blocked||!!p.focus?.onBreak} onBegin={(id,stage)=>void command('begin',{skillId:id,stage})}/>}</article>)}
 </section></dialog></>;
}
