import {useEffect,useState} from 'react';
import {pilotAPI} from '../../pilot/api';
import {OFFERED_PRIZES,PRIZE_CATEGORIES,teacherPrize} from './prizeCatalog';
type Learner={id:string;alias:string;active:number};
type Gift={id:string;alias:string;prize_id:string;claimed_at:number|null;used_at:number|null};
type Draft={requestId:string;students:string[];prizeId:string;category:string};
export function TeacherPrizePicker({standings, initialStudentId, initialPrizeId, defaultOpen = false}:{standings:{studentId:string;score:number;rank:number}[]; initialStudentId?:string; initialPrizeId?:string; defaultOpen?:boolean}){
 const [learners,setLearners]=useState<Learner[]>([]),[history,setHistory]=useState<Gift[]>([]),[selected,setSelected]=useState<string[]>(initialStudentId?[initialStudentId]:[]);
 const [category,setCategory]=useState(initialPrizeId?teacherPrize(initialPrizeId)?.category??'':''),[search,setSearch]=useState(''),[choice,setChoice]=useState(initialPrizeId??'random'),[preview,setPreview]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const refresh=async()=>{const data=await pilotAPI<{learners:Learner[];grants:Gift[]}>('clash/gifts');setLearners(data.learners);setHistory(data.grants);};
 useEffect(()=>{void refresh().catch(e=>setMessage((e as Error).message));},[]);
 const options=OFFERED_PRIZES.filter(p=>(!category||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(search.toLowerCase()));
 const award=async()=>{if(!preview||busy)return;setBusy(true);try{const r=await pilotAPI<{grants:{alias:string;name:string}[]}>('clash/award','POST',preview);setMessage(`Prizes ready to collect: ${r.grants.map(g=>`${g.alias}: ${g.name}`).join('; ')}`);setPreview(null);await refresh().catch(()=>setMessage(current=>current+' Award saved; refresh prize history to see the latest status.'));}catch(e){setMessage(`${(e as Error).message} You can retry this same award without drawing again.`);}finally{setBusy(false);}};
 return <details className="teacher-prize-picker" open={defaultOpen}><summary>Gift catalog · {OFFERED_PRIZES.length} items · {PRIZE_CATEGORIES.length} categories</summary>
  <p>1. Choose a student. 2. Choose a gift. 3. Preview and send. Prizes wait in each learner’s private inbox; their current game continues. Random draws prefer unowned collectibles and avoid the same pending item when possible. If collectible choices are exhausted, duplicate collectibles become 15 tokens.</p>
  {initialPrizeId==='gift_early_hatch'&&<section className="teacher-egg-explainer" aria-label="How the early egg pass works"><span className="teacher-kicker">One-Day-Early Egg Pass</span><h3>A head start on their next companion.</h3><p>This gift replaces one of five activity days. It does not hatch the egg immediately. The questionnaire is optional.</p><ol><li>Choose the student below and send the gift.</li><li>They open <strong>Classroom Clash → Your teacher prizes</strong> and collect it.</li><li>In <strong>Egg discovery or Prize Studio</strong>, they use the pass. One pass per egg; it stays saved until they can use it.</li></ol></section>}
  <fieldset disabled={busy}><div className="clash-actions"><button onClick={()=>{setSelected(learners.map(l=>l.id));setPreview(null);}}>Select whole class</button>{standings.length>0&&<><button onClick={()=>{setSelected(standings.filter(s=>s.score>0).map(s=>s.studentId));setPreview(null);}}>Round participants</button><button onClick={()=>{setSelected(standings.filter(s=>s.score>0&&s.rank<=3).map(s=>s.studentId));setPreview(null);}}>Top 3 including ties</button></>}<button onClick={()=>{setSelected([]);setPreview(null);}}>Clear selection</button><strong>{selected.length} selected</strong></div>
  <div className="teacher-prize-learners">{learners.map(l=><label key={l.id}><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>{setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id));setPreview(null);}}/>{l.alias}{!l.active?' · paused login':''}</label>)}</div>
  <div className="clash-actions"><label>Prize category<select aria-label="Prize category" value={category} onChange={e=>{setCategory(e.target.value);setChoice('random');setPreview(null);}}><option value="">All categories</option>{PRIZE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Find a prize<input aria-label="Find a prize" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Egg, crown, racing, garden…"/></label></div>
  <button aria-pressed={choice==='random'} onClick={()=>{setChoice('random');setPreview(null);}}>🎲 Random {category||'any category'} · {OFFERED_PRIZES.filter(p=>!category||p.category===category).length} possible prizes</button><p>Search filters the cards only. Random draws use the selected category. Every eligible item has the same chance.</p>
  <div className="teacher-prize-catalog">{options.map(p=><button key={p.id} aria-pressed={choice===p.id} onClick={()=>{setChoice(p.id);setPreview(null);}}>{p.art&&<img src={p.art} alt="" loading="lazy"/>}<strong>{p.name}</strong><small>{p.category}</small><span>{p.description}</span></button>)}</div>
  <button disabled={!selected.length} onClick={()=>setPreview({requestId:crypto.randomUUID(),students:[...selected],prizeId:choice,category})}>Preview prize award</button>
  {preview&&<div className="teacher-prize-preview"><h3>Ready to award</h3><p>{preview.students.length} learners: {learners.filter(l=>preview.students.includes(l.id)).map(l=>l.alias).join(', ')}</p><p>{preview.prizeId==='random'?`One random prize per learner from ${preview.category||'all categories'}. The draw happens once when you award.`:teacherPrize(preview.prizeId)?.description}</p><button onClick={()=>void award()}>Award prizes now</button><button onClick={()=>setPreview(null)}>Cancel preview</button></div>}</fieldset>
  <p role="status">{message}</p><details><summary>Recent teacher awards</summary><button disabled={busy} onClick={()=>void refresh().catch(e=>setMessage((e as Error).message))}>Refresh prize history</button><ul>{history.map(g=><li key={g.id}>{g.alias}: {teacherPrize(g.prize_id)?.name} · {g.used_at?'Perk used':g.claimed_at?'Collected':'Waiting to collect'}</li>)}</ul></details>
 </details>;
}
