import {describe,it,expect} from 'vitest';
import {initMomentum,buildBoard,selectPiece,beginMove,advanceAfterAnimation,tacticalAction,startNextTurn,skipTurn} from '../MomentumSystem';
import {powerMoves,applyMathPower} from '../MomentumPowers';
import {selectAIAction} from '../MomentumAI';
import type {MomentumPiece,MathPower,ActiveMomentumState} from '../../../types/momentum';
const piece=(id:string,role:MathPower,x:number,y:number,energy=3,team:'player'|'enemy'='player'):MomentumPiece=>({id,mathPower:role,team,rank:2,energy,position:{x,y},isTemporaryRank4:false,rank4TurnsRemaining:0,previousRank:null});
const board=(pieces:MomentumPiece[]):ActiveMomentumState=>({...initMomentum('hard','powers'),pieces,board:buildBoard(pieces,7)});
describe('Power Clash',()=>{
 it('starts hard with four distinct roles each, fair energy and 7×7 board',()=>{const s=initMomentum('easy','powers');expect(s.difficulty).toBe('hard');expect(s.board).toHaveLength(7);expect(s.pieces).toHaveLength(8);expect(s.pieces.filter(p=>p.team==='player').map(p=>p.mathPower)).toEqual(['add','subtract','multiply','divide']);expect(s.pieces.filter(p=>p.team==='player').map(p=>p.energy)).toEqual([3,3,3,3]);expect(startNextTurn(s).pieces.filter(p=>p.team==='enemy').map(p=>p.energy)).toEqual([3,3,3,3]);});
 it('Scout is straight, Shade diagonal and Weaver short; blockers stop rays',()=>{for(const role of ['add','subtract','divide'] as const){const p=piece('p',role,3,3,6);const moves=powerMoves(p,[p]);expect(moves.every(m=>m.energyCost<=(role==='divide'?2:3))).toBe(true);expect(moves.every(m=>role==='add'?m.destination.x===3||m.destination.y===3:role==='subtract'?Math.abs(m.destination.x-3)===Math.abs(m.destination.y-3):true)).toBe(true);}const p=piece('p','add',0,6),a=piece('a','divide',0,5);expect(powerMoves(p,[p,a]).some(m=>m.destination.x===0)).toBe(false);});
 it('Lancer vaults over allies and enemies, charges half distance, never lands on allies',()=>{const p=piece('p','multiply',0,6,2),a=piece('a','add',0,5),b=piece('b','divide',0,4),e=piece('e','subtract',0,2,1,'enemy');const moves=powerMoves(p,[p,a,b,e]);expect(moves.find(m=>m.targetPieceId==='e')).toMatchObject({energyCost:2,destination:{x:0,y:2}});expect(moves.some(m=>m.destination.y===4&&m.destination.x===0)).toBe(false);expect(moves.every(m=>[1,2].includes(m.energyCost))).toBe(true);});
 it('Charge adds exactly two, rejects full/out-of-range targets and switches turns once',()=>{const s=board([piece('p','add',0,6,0),piece('a','divide',2,6,4),piece('far','multiply',6,6),piece('e','subtract',0,0,1,'enemy')]);expect(applyMathPower(s,'p','far')).toBe(s);const next=tacticalAction(s,'p','a');expect(next.activeTeam).toBe('enemy');expect(next.turnCount).toBe(s.turnCount);expect(next.pieces[1].energy).toBe(6);expect(next.pieces[0].energy).toBe(0);expect(applyMathPower({...s,pieces:s.pieces.map(p=>p.id==='a'?{...p,energy:5}:p)},'p','a').pieces[1].energy).toBe(5);});
 it('Drain spends two, cannot go negative, then the enemy recharges normally',()=>{const s=board([piece('p','subtract',2,2,2),piece('e','add',3,3,1,'enemy')]);expect(applyMathPower(s,'p','e').pieces.map(p=>p.energy)).toEqual([0,0]);expect(tacticalAction(s,'p','e').pieces.map(p=>p.energy)).toEqual([0,1]);expect(applyMathPower({...s,pieces:[{...s.pieces[0],energy:1},s.pieces[1]]},'p','e').pieces[0].energy).toBe(1);});
 it('Split conserves energy and rejects odd, zero, distant and overflowing transfers',()=>{const s=board([piece('p','divide',3,3,6),piece('a','multiply',4,3,2),piece('e','add',0,0,1,'enemy')]);expect(applyMathPower(s,'p','a').pieces.slice(0,2).map(p=>p.energy)).toEqual([3,5]);for(const energy of [0,1,3,5]){const bad={...s,pieces:[{...s.pieces[0],energy},...s.pieces.slice(1)]};expect(applyMathPower(bad,'p','a')).toBe(bad);}const full={...s,pieces:s.pieces.map(p=>p.id==='a'?{...p,energy:4}:p)};expect(applyMathPower(full,'p','a')).toBe(full);});
 it('captures do not invoke Flash or change role, and the last capture wins',()=>{let s=selectPiece(board([piece('p','multiply',0,4,2),piece('e','add',0,0,1,'enemy')]),'p');s=beginMove(s,s.validMoves.findIndex(m=>m.targetPieceId==='e'));s=advanceAfterAnimation(s);expect(s.phase).toBe('victory');expect(s.flashPending).toBeNull();expect(s.pieces[0].mathPower).toBe('multiply');expect(s.pieces[0].rank).toBe(2);});
 it('does not enter clutch, and cannot stall beyond turn 60',()=>{const s=board([piece('p','add',0,6),piece('e','add',6,0,1,'enemy')]);expect(startNextTurn(startNextTurn(s)).phase).toBe('player_select');expect(skipTurn({...s,turnCount:60}).phase).toBe('defeat');});
 it('AI returns a legal move or power throughout complete games',()=>{for(let game=0;game<12;game++){let s=initMomentum('hard','powers');for(let turn=0;turn<128&&!['victory','defeat'].includes(s.phase);turn++){const turnState={...s,phase:'ai_turn' as const};const options=s.pieces.filter(p=>p.team===s.activeTeam).flatMap(p=>powerMoves(p,s.pieces).map((m,moveIndex)=>({pieceId:p.id,moveIndex,attack:m.isAttack,tactic:false,targetId:undefined})));const action=s.activeTeam==='enemy'?selectAIAction(turnState):options.find(m=>m.attack)??options[(game+turn)%Math.max(1,options.length)]??null;if(!action){s=skipTurn(s);continue;}if(action.tactic){const next=tacticalAction(turnState,action.pieceId,action.targetId);expect(next).not.toBe(turnState);s=next;}else {const p=s.pieces.find(p=>p.id===action.pieceId)!;expect(p.team).toBe(s.activeTeam);const moves=powerMoves(p,s.pieces);expect(moves[action.moveIndex]).toBeDefined();s=advanceAfterAnimation(beginMove({...s,selectedPieceId:p.id,validMoves:moves},action.moveIndex));}expect(s.pieces.every(p=>p.energy>=0&&p.energy<=6)).toBe(true);expect(new Set(s.pieces.map(p=>`${p.position.x},${p.position.y}`)).size).toBe(s.pieces.length);}expect(['victory','defeat']).toContain(s.phase);}});
});
