#!/usr/bin/env python3
"""Pack art-source/pet-hunt-props/*/*.png into one sprite sheet plus a typed index for the renderer.

Usage: python3 scripts/pack-hunt-props.py
Greenhouse glass walls and long workshop walls are drawn in code (the generator never produced a clean repeating strip for them), so they are skipped.
"""
import json, os
from PIL import Image

SRC, SHEET, INDEX = 'art-source/pet-hunt-props', 'public/assets/pet-hunt-v4/props.png', 'src/features/pet-hunt/propAtlas.ts'
SKIP = {'glass_h', 'glass_v', 'wall_h'}
items = []
for theme in sorted(os.listdir(SRC)):
    for f in sorted(os.listdir(f'{SRC}/{theme}')):
        name = f[:-4]
        if name not in SKIP: items.append((name, Image.open(f'{SRC}/{theme}/{f}').convert('RGBA')))
# Simple shelf packing: tallest first, rows up to 512 px wide, 2 px gutters so neighbours never bleed.
items.sort(key=lambda it: -it[1].height)
W, x, y, row, rects = 512, 0, 0, 0, {}
for name, img in items:
    if x + img.width > W: x, y, row = 0, y + row + 2, 0
    rects[name] = (x, y, img.width, img.height); x += img.width + 2; row = max(row, img.height)
sheet = Image.new('RGBA', (W, y + row), (0, 0, 0, 0))
for name, img in items: sheet.alpha_composite(img, rects[name][:2])
os.makedirs(os.path.dirname(SHEET), exist_ok=True); sheet.save(SHEET, optimize=True)
with open(INDEX, 'w') as out:
    out.write('// Generated by scripts/pack-hunt-props.py from art-source/pet-hunt-props. Do not edit by hand.\n')
    out.write('export const PROP_SHEET = \'/assets/pet-hunt-v4/props.png\';\n')
    out.write('export const PROP_ATLAS = ' + json.dumps({k: {'x': v[0], 'y': v[1], 'w': v[2], 'h': v[3]} for k, v in sorted(rects.items())}) + ' as const;\n')
    out.write('export type PropName = keyof typeof PROP_ATLAS;\n')
print('packed', len(rects), 'pieces into', sheet.size)
