#!/usr/bin/env python3
"""Pack PixMiniMax battle strips (art-source/battle-v2) into game sheets and write the frame manifest.

Each move strip is copied as-is (128px frames, frame 0 is the pet's own idle pose). An idle loop is added per form
from the pet's regular sprite sheet so the stage never swaps renderers between moves.
Usage: python3 scripts/pack-battle-anims.py
"""
import glob, json, os
from PIL import Image

SRC, OUT = 'art-source/battle-v2', 'public/assets/battle-v2'


def idle_strip(form):
    species, _, stage = form.partition('__')
    stage = stage or 'baby'
    if species == 'koala_sprite' and stage == 'baby':
        sheet = Image.open('public/assets/woodland-v1/pip-idle.png').convert('RGBA')
        return sheet.crop((0, 0, sheet.width, 128))
    return Image.open(f'public/assets/companions-v2/{species}-{stage}.png').convert('RGBA').crop((0, 0, 1024, 128))


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    for folder in sorted(glob.glob(f'{SRC}/*/')):
        form = os.path.basename(folder.rstrip('/'))
        if form in ('backgrounds', 'fx'):
            continue
        moves = {}
        for path in sorted(glob.glob(f'{folder}*.png')):
            move = os.path.basename(path)[:-4]
            strip = Image.open(path).convert('RGBA')
            strip.save(f'{OUT}/{form}-{move}.png', optimize=True)
            moves[move] = strip.width // 128
        idle = idle_strip(form)
        idle.save(f'{OUT}/{form}-idle.png', optimize=True)
        moves['idle'] = idle.width // 128
        manifest[form] = moves
    fx = {}
    for path in sorted(glob.glob(f'{SRC}/fx/*.png')):
        strip = Image.open(path).convert('RGBA')
        name = os.path.basename(path)[:-4]
        if name == 'shield':  # the generator drifted the shield to red after its first frame; keep it blue
            px = strip.load()
            for y in range(strip.height):
                for x in range(strip.width):
                    r, g, b, a = px[x, y]
                    if a and r > g + 50 and r > b + 50:
                        px[x, y] = (min(255, b + 80), min(255, g + 140), r, a)
        strip.save(f'{OUT}/fx-{name}.png', optimize=True)
        fx[name] = strip.width // 96
    manifest['_fx'] = fx
    for path in glob.glob(f'{SRC}/backgrounds/*.png'):
        Image.open(path).convert('RGB').save(f'{OUT}/bg-{os.path.basename(path)}', optimize=True)
    with open('src/features/pet-arena/battleArtManifest.ts', 'w') as f:
        f.write('// Generated by scripts/pack-battle-anims.py: frame counts of each 128px battle strip.\n')
        f.write('export default ' + json.dumps(manifest, indent=1) + ' as Record<string, Record<string, number>>;\n')
    print(len(manifest), 'forms packed')


if __name__ == '__main__':
    main()
