#!/usr/bin/env python3
"""
Turn public/assets/generated/new/_manifest.json into a TypeScript file
that assetReviewList.ts can import and spread into the curated list.

Writes:
  src/config/generatedBatchAssets.ts

All entries become `GeneratedAsset` records with isPreviewable: true so
they show up in the Asset Review "★ Curated" view.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "public/assets/generated/new/_manifest.json"
OUT = ROOT / "src/config/generatedBatchAssets.ts"

HEADER = '''/**
 * AUTO-GENERATED by scripts/register_assets.py.
 * Do not hand-edit — regenerate after each batch.
 *
 * These entries are spread into the Asset Review "Curated" view via
 * assetReviewList.ts → CURATED_DIRECTION_ASSETS.
 */
import type { GeneratedAsset } from './generatedAssetManifest';

export const BATCH_GENERATED_ASSETS: GeneratedAsset[] = [
'''

FOOTER = "];\n"


def emit_entry(e: dict) -> str:
    # Escape quotes in the prompt
    prompt = (e.get("prompt") or "").replace('"', '\\"').replace("\n", " ")
    parts = [
        f'id: "{e["id"]}"',
        f'filename: "{Path(e["path"]).name}"',
        f'category: "{e.get("category","icon")}"',
        f'path: "{e["path"]}"',
        f'prompt: "{prompt}"',
        f'width: {e.get("width", 128)}',
        f'height: {e.get("height", 128)}',
        "isPreviewable: true",
    ]
    if "group" in e:    parts.append(f'group: "{e["group"]}"')
    if "direction" in e: parts.append(f'direction: "{e["direction"]}" as const')
    if "state" in e:    parts.append(f'state: "{e["state"]}"')
    return "  { " + ", ".join(parts) + " },"


def main():
    if not MANIFEST.exists():
        print(f"no manifest at {MANIFEST} — run generate_batch.py first")
        return
    data = json.loads(MANIFEST.read_text())
    lines = [HEADER] + [emit_entry(e) for e in data] + [FOOTER]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(data)} entries)")


if __name__ == "__main__":
    main()
