import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.DEMO_URL || 'http://localhost:5018/');
  const menu = page.getByRole('button', { name: 'Demo features', exact: true });
  await menu.waitFor();
  await page.getByText('Loading your activity…', { exact: true }).waitFor({ state: 'hidden' });
  assert.match(await page.locator('body').innerText(), /Pip/i);
  assert.equal(await page.getByRole('button', { name: 'Restart demo', exact: false }).count(), 1);
  for (const screen of ['home_builder', 'play', 'math', 'catch_math', 'momentum', 'number_merge', 'pet_care', 'feeding', 'shop', 'battle', 'woodland', 'growth', 'discovery', 'incubation', 'run_start', 'run_map', 'run_encounter', 'run_reward', 'run_rest', 'run_event', 'run_over', 'class_roster', 'challenger_preview', 'match_result', 'quest_log', 'season_pass', 'gacha', 'power_forge', 'home']) {
    await menu.click();
    await page.locator(`[data-preview-screen="${screen}"]`).click();
    await page.locator(`.dev-launcher[data-game-screen="${screen}"]`).waitFor();
    await page.getByText('Loading your activity…', { exact: true }).waitFor({ state: 'hidden' });
    await page.waitForTimeout(150);
    assert.doesNotMatch(await page.locator('body').innerText(), /Something went wrong|Available after your companion hatches/);
    console.log(`PASS ${screen}`);
  }
  await menu.click();
  await page.getByRole('dialog').getByRole('button', { name: 'Teacher dashboard', exact: true }).click();
  await page.getByRole('button', { name: 'Learners', exact: true }).click();
  await page.getByRole('textbox', { name: 'Learner nickname or class code' }).fill('Demo learner 2');
  await page.getByRole('button', { name: 'Create learner profile' }).click();
  await page.getByLabel('Choose learner').selectOption({ label: 'Demo learner 1' });
  await page.getByLabel('Choose learner').selectOption({ label: 'Demo learner 2' });
  await page.getByRole('button', { name: 'Learning', exact: true }).click();
  await page.getByLabel('Grade level').selectOption('4');
  await page.getByRole('button', { name: 'Save settings', exact: true }).click();
  await page.getByLabel('Choose learner').selectOption({ label: 'Demo learner 1' });
  await page.getByLabel('Choose learner').selectOption({ label: 'Demo learner 2' });
  await page.getByRole('navigation', { name: 'Teacher sections' }).getByRole('button', { name: 'Learning', exact: true }).click();
  assert.equal(await page.getByLabel('Grade level').inputValue(), '4');
  await page.getByRole('navigation', { name: 'Teacher sections' }).getByRole('button', { name: 'Class tools', exact: true }).click();
  const downloadReady = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download roster spreadsheet' }).click();
  assert.equal((await downloadReady).suggestedFilename(), 'private-learner-roster.csv');
  await page.getByLabel('Assigned activity').selectOption('home_builder');
  await page.getByRole('button', { name: 'Play this learner’s activity' }).click();
  await page.locator('.dev-launcher[data-game-screen="home_builder"]').waitFor();
  await page.getByRole('button', { name: 'Build', exact: false }).filter({ hasText: 'Build' }).first().waitFor();
  console.log('PASS teacher creation, switching, settings isolation, roster download, assigned home building');
  await page.getByRole('button', { name: 'Restart demo', exact: false }).click();
  await menu.waitFor();
  await page.getByText('Loading your activity…', { exact: true }).waitFor({ state: 'hidden' });
  assert.match(await page.locator('body').innerText(), /Pip/i);
  const saves = await page.evaluate(() => Object.keys(localStorage).filter(k => /save/i.test(k)));
  assert.deepEqual(saves, []);
  assert.deepEqual(errors, []);
  await page.setViewportSize({ width: 390, height: 844 });
  await menu.click();
  await page.locator('[data-preview-screen="catch_math"]').click();
  await menu.waitFor();
  await page.getByText('Loading your activity…', { exact: true }).waitFor({ state: 'hidden' });
  console.log('PASS restart, no saved game writes, no runtime errors, mobile shortcuts');
} finally { await browser.close(); }
