import {describe,it,expect} from 'vitest';
import {createTestEngineState} from '../../../engine/state/createTestEngineState';
import {createHomeBase,validHomeBase} from '../../home-base/model';
import {engineReducer} from '../../../engine/state/engineReducer';
import {buildWorld,route,key,locate,checkpoint,approach,validResident} from '../world';
import {makeResident,invite,stepResident,cancelInvitation,savedResident} from '../resident';
const setup=()=>{const s=createTestEngineState();s.mode='normal';s.pet!.state='idle';s.homeBase=createHomeBase(s);s.screen='home_builder';return {s,w:buildWorld(s.homeBase),pet:s.pet!};};
describe('living house spatial continuity',()=>{
 it('builds connected real floors and a staircase while preserving every furniture placement',()=>{const {s,w}=setup(),before=JSON.stringify(s.homeBase);const p=locate(w,undefined,s.pet!.id,'den'),target=w.stairs[1],path=route(w,p,target);expect(path.length).toBeGreaterThan(10);expect(path.every(p=>w.open.has(key(p)))).toBe(true);expect(path.some((p,i)=>i>0&&p.floor!==path[i-1].floor)).toBe(true);expect(JSON.stringify(s.homeBase)).toBe(before);});
 it('keeps owned rooms reachable at all three furniture grid sizes',()=>{const {s}=setup();for(const tier of [0,1,2]){for(const r of Object.values(s.homeBase!.rooms))r!.tier=tier;const w=buildWorld(s.homeBase!);expect(route(w,w.stairs[0],w.stairs[1])).toHaveLength(1);for(const r of w.rooms.filter(r=>r.owned))expect(route(w,w.stairs[0],{x:r.x,y:r.y+r.h-1,floor:r.floor}).length).toBeGreaterThan(0);}});
 it('a call starts a route, not a teleport; every same-floor step has bounded speed',()=>{const {s,w,pet}=setup(),r=makeResident(w,undefined,pet,'den'),from={...r.position};invite(r,w,pet,w.stairs[1]);expect(r.position).toEqual(from);let climbed=false;for(let i=0;i<2000;i++){const prev={...r.position};stepResident(r,w,pet,.02);if(prev.floor===r.position.floor)expect(Math.hypot(r.position.x-prev.x,r.position.y-prev.y)).toBeLessThan(.061);else climbed=true;if(!r.invited&&!r.path.length)break;}expect(climbed).toBe(true);expect(r.position.floor).toBe(1);expect(s.pet).toBe(pet);});
 it('investigates from an accessible adjacent tile, never through furniture',()=>{const {w,pet}=setup(),r=makeResident(w,undefined,pet,'den'),o=w.objects.find(o=>o.placement.furnitureId==='house_counter')!;const destination=approach(w,o,r.position)!;expect(w.open.has(key(destination))).toBe(true);invite(r,w,pet,destination,o);for(let i=0;i<2000&&r.invited;i++)stepResident(r,w,pet,.05);expect(r.lastObject).toBe(o.key);expect(r.activity).toBe('Waiting by the kitchen counter');});
 it('repeated invitations and cancellation do not snap the pet backwards',()=>{const {w,pet}=setup(),r=makeResident(w,undefined,pet,'den');invite(r,w,pet,w.stairs[0]);for(let i=0;i<30;i++)stepResident(r,w,pet,.05);const at={...r.position};invite(r,w,pet,w.stairs[1]);expect(r.position).toEqual(at);cancelInvitation(r);expect(r.position).toEqual(at);expect(r.path).toEqual([]);});
 it('saves pet location separately from the viewed room without charging or awarding anything',()=>{const {s,w,pet}=setup();const resident=checkpoint(w,w.stairs[1],pet.id,'Keeping you company'),next=engineReducer(s,{type:'HOME_RESIDENT',resident});expect(next.homeBase!.activeRoom).toBe('den');expect(next.homeBase!.resident!.roomId).toBe('landing');expect(next.player).toEqual(s.player);expect(next.pet).toEqual(s.pet);expect(validHomeBase(next.homeBase)).toBe(true);expect(locate(w,resident,pet.id,'den')).toEqual(w.stairs[1]);});
 it('rejects corrupt state and a checkpoint for the wrong pet',()=>{const {s,w,pet}=setup(),resident=checkpoint(w,w.stairs[0],pet.id,'Resting');expect(validResident({...resident,x:Infinity})).toBe(false);expect(engineReducer(s,{type:'HOME_RESIDENT',resident:{...resident,petId:'not-the-pet'}})).toBe(s);});
 it('a sleeping pet acknowledges a call before moving',()=>{const {w,pet}=setup();pet.state='sleeping';const r=makeResident(w,undefined,pet,'den');const before={...r.position};invite(r,w,pet,w.stairs[0]);stepResident(r,w,pet,1);expect(r.position).toEqual(before);expect(r.activity).toBe('Waking up slowly');});
 it('resumes an unfinished invitation after reloading without moving to the viewed room',()=>{const {w,pet}=setup(),r=makeResident(w,undefined,pet,'den');invite(r,w,pet,w.stairs[1]);for(let i=0;i<80;i++)stepResident(r,w,pet,.02);const saved=savedResident(w,r,pet);expect(saved.destination?.roomId).toBe('landing');expect(validResident(saved)).toBe(true);const restored=makeResident(w,saved,pet,'kitchen');expect(restored.position.floor).toBe(0);expect(restored.invited).toBe(true);for(let i=0;i<2000&&restored.invited;i++)stepResident(restored,w,pet,.02);expect(restored.position.floor).toBe(1);});

});
