import {EvolutionHUD,EvolutionGuide} from './evolution/HUD';
import {chooseEvolution} from './evolution/state';
import type {ReturnProfile} from './evolution/returnMath';
import {PACKAGES} from './evolution/catalog';
import './evolution/evolution.css';
import { useCallback, useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { startPolling } from '../../pilot/polling';
import { pilotAPI, PilotError } from '../../pilot/api';
import { tabSession } from '../../pilot/tabSession';
import { useReducedMotion } from '../../hooks/useReducedMotion';
import { HuntMenu } from './HuntMenu';
import { HuntToast } from './HuntToast';
import { CompanionPortrait } from './CompanionPortrait';
import { HuntGuide } from './HuntGuide';
import { nextObjective } from './objective';
import { currentAction } from './actions';
import { SparkPanel } from './SparkPanel';
/** Solo-only demo/test start (?huntStart=beacon): begin beside a beacon to try spark checks right away. Solo practice is never saved. */
function practiceStart(m:Match){
 if(new URLSearchParams(location.search).get('huntStart')!=='beacon')return;
 // Pick the beacon farthest from any locked door, so the practice spot is never shut inside a building.
 const door=arenaOf(m).door,me=m.players.find(p=>p.id==='you');
 const b=[...m.beacons].sort((x,y)=>door?distance(y,door)-distance(x,door):0)[0];if(me&&me.role==='runner'&&b){me.x=b.x;me.y=b.y+40;}
}
import { BEACONS_NEEDED, arenaOf, newSeed, HUNTER_RECHARGE, ARENAS, KITS, addPlayer, createMatch, idleInput, startMatch, step, viewFor, distance, type Difficulty, type PetStage, type Input, type Kit, type Match, type Mode, type Role, type View } from './model';
import { draw } from './render';
import { arenaViewport, arenaCamera, screenToArena } from './camera';
import { WORLD_ART, loadHuntArt } from './art';
import './pet-hunt.css';
import './hunt-clean.css';
export interface RoomInfo { ruleset?:'classic'|'evolution'; id:string; name:string; mode:Mode; map:string; phase:string; count:number; }
interface Directory { returnProfile?:ReturnProfile;grade?:number; you:string; teacher:boolean; species:string|null; pet:{species:string;name:string;stage?:PetStage}|null; rooms:RoomInfo[]; }
export interface RoomView { type:'state'; match:View; host:boolean; teacher:boolean; mode:Mode; seats:{id:string;name:string;role:Role;connected:boolean;ready:boolean}[]; queue:string[]; }
type Session = {kind:'solo';ruleset:'classic'|'evolution';returnProfile?:ReturnProfile;grade?:number; role:Role; map:string; kit:Kit; species:string; name:string; difficulty:Difficulty; duration:number; relaxed:boolean; stage:PetStage} | {kind:'online';id:string};
export function PetHunt(){
 const [ready,setReady]=useState(false),[failure,setFailure]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;void loadHuntArt().then(()=>{if(active)setReady(true);}).catch(()=>{if(active)setFailure(true);});return()=>{active=false;};},[attempt]);
 if(!ready)return <main className="hunt-app hunt-loading"><p className="hunt-eyebrow">AURALITH ARCADE</p><h1>{failure?'The garden needs another moment.':'Waking up your pixel pets…'}</h1><p role="status">{failure?'The artwork could not load. Check your connection and try again.':'Packing blasters. Lighting lanterns. Finding hiding places.'}</p>{failure&&<button onClick={()=>{setFailure(false);setAttempt(attempt+1);}}>Try again</button>}<a href="/">Back to Auralith</a></main>;
 return <PetHuntReady/>;
}
function PetHuntReady(){
 const [ruleset,setRuleset]=useState<'classic'|'evolution'>(new URLSearchParams(location.search).get('huntRules')==='classic'?'classic':'evolution'),[profile,setProfile]=useState<{returnProfile?:ReturnProfile;grade?:number}>({});
 const [session,setSession]=useState<Session|null>(null),[map,setMap]=useState('garden'),[kit,setKit]=useState<Kit>('scout'),[difficulty,setDifficulty]=useState<Difficulty>('normal'),[relaxed,setRelaxed]=useState(false),[duration,setDuration]=useState(240);
 const [directory,setDirectory]=useState<Directory|null>(null),[mode,setMode]=useState<Mode>('versus'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tutorial,setTutorial]=useState(false);
 const [companion,setCompanion]=useState<Directory['pet']>(null),[petLoading,setPetLoading]=useState(true),[petError,setPetError]=useState(''),[teacherPet,setTeacherPet]=useState(false),[petRetry,setPetRetry]=useState(0),[petFailure,setPetFailure]=useState<'signin'|'connection'|null>(null);
 const species=companion?.species??'';
 useEffect(()=>{let active=true;setPetFailure(null);setPetError('');void pilotAPI<Directory>('pet-hunt').then(d=>{if(active){setCompanion(d.pet);setTeacherPet(d.teacher);setProfile({returnProfile:d.returnProfile,grade:d.grade});setPetError(d.pet?'':'Hatch your earned pet in Auralith before entering Pet Hunt.');}}).catch(e=>{if(active){const signin=e instanceof PilotError&&e.status===401;setPetFailure(signin?'signin':'connection');setPetError(signin?'Sign in in this tab to bring your earned pet into the arena. Already playing Auralith? Open Pet Hunt from Together in that signed-in tab.':'We could not load your saved pet. Check your connection and try again.');}}).finally(()=>{if(active)setPetLoading(false);});return()=>{active=false;};},[petRetry]);
 const reload=async()=>{const d=await pilotAPI<Directory>('pet-hunt');setDirectory(d);setCompanion(d.pet);setTeacherPet(d.teacher);setProfile({returnProfile:d.returnProfile,grade:d.grade});return d;};
 const online=async(next:Mode)=>{setBusy(true);setError('');try{await reload();setMode(next);}catch{setError('Sign in to your classroom to play online. Your earned pet comes with you.');}finally{setBusy(false);}};
 const hasDirectory=directory!==null;
 useEffect(()=>hasDirectory?startPolling(()=>pilotAPI<Directory>('pet-hunt').then(setDirectory).catch(()=>setError('Could not refresh rooms. Check your connection.')),5000,{immediate:false}):undefined,[hasDirectory]);
 if(!companion)return <main className="hunt-app hunt-entry"><header className="hunt-top"><a href="/">← Back to Auralith</a><span>AURALITH ARCADE</span></header><section className="hunt-panel hunt-entry-card"><img src={`${WORLD_ART}/title.webp`} alt="Pixel pets exploring the Pet Hunt garden"/><div><p className="hunt-eyebrow">PET HUNT</p><h1>{petLoading?'Finding your pet…':petFailure==='signin'?'Bring your pet to play.':petFailure==='connection'?'Let’s reconnect.':'Your adventure starts with a pet.'}</h1><p role="status">{petLoading?'Loading your earned companion.':petError}</p>{!petLoading&&<div className="hunt-entry-actions">{petFailure==='signin'?<a className="hunt-primary" href="/?returnTo=petHunt">Sign in & play</a>:petFailure==='connection'?<button className="hunt-primary" onClick={()=>{setPetLoading(true);setPetRetry(n=>n+1);}}>Try again</button>:<a className="hunt-primary" href="/">Go to my pet</a>}</div>}</div></section></main>;
 if(session)return <ArenaSession session={session} onLeave={()=>{setSession(null);if(directory)void reload().catch(()=>{});}}/>;
 return <main className="hunt-app"><header className="hunt-top"><a href="/">← Back to Auralith</a><span>AURALITH ARCADE</span><button onClick={()=>setTutorial(!tutorial)}>How to play</button></header>
 <section className="evo-mode-picker" aria-label="Game rules"><button aria-pressed={ruleset==='evolution'} onClick={()=>setRuleset('evolution')}>MONSTER EVOLUTION <small>Rift Hunt · Rebuilt rules & branching powers</small></button><button aria-pressed={ruleset==='classic'} onClick={()=>setRuleset('classic')}>Classic Hunt <small>The original beacon chase</small></button></section><section className="hunt-hero"><div><p className="hunt-eyebrow">A LITTLE COURAGE. A GREAT ESCAPE.</p><h1>{ruleset==='evolution'?<>Monster <em>Evolution.</em></>:<>Pet <em>Hunt.</em></>}</h1><p className="hunt-lead">Four little friends.<br/>One very determined hunter.</p><p>{ruleset==='evolution'?'Complete rifts. Evolve your attacks. When defeated, earn your return. Escape—or defeat the monster together.':'Disappear into the garden. Light the beacons. Bring everyone home.'}</p><div className="hunt-tags"><span>Hide & seek</span><span>Energy blasters</span><span>{ruleset==='evolution'?'Earned second lives':'Team rescues'}</span></div></div><div className="hunt-hero-art" aria-hidden="true"><img className="hunt-scene-preview" src={`${WORLD_ART}/title.webp`} alt=""/><span className="hunt-art-caption">THE GARDEN IS WAITING</span></div></section>
 {tutorial&&ruleset==='evolution'?<EvolutionGuide onClose={()=>setTutorial(false)}/>:tutorial&&<HuntGuide onClose={()=>setTutorial(false)}/>}
 {error&&<p role="alert" className="hunt-error">{error}</p>}
 <section className="hunt-panel"><div className="hunt-section-heading"><div><span className="hunt-eyebrow">CHOOSE YOUR ADVENTURE</span><h2>Who’s chasing who?</h2></div><span>One arena. Five players.</span></div><div className="hunt-mode-grid">
 <button className="hunt-mode" disabled={petLoading||!companion} onClick={()=>{if(companion)setSession({kind:'solo',ruleset,...profile,role:'runner',map,species,name:companion.name,kit,difficulty,duration,relaxed,stage:companion.stage??'adult'});}}><span>01 / SOLO</span><strong>Make your escape</strong><p>{ruleset==='evolution'?'Complete rift missions, evolve your build, and extract—or defeat the monster.':'Light 5 of 7 beacons. Hide, sneak, rescue. Get 3 pets out the gate.'}</p><b>Play as a runner →</b></button>
 <button className="hunt-mode" disabled={petLoading||!companion} onClick={()=>{if(companion)setSession({kind:'solo',ruleset,...profile,role:'hunter',map,species,name:companion.name,kit,difficulty,duration,relaxed,stage:companion.stage??'adult'});}}><span>02 / SOLO</span><strong>Become the hunter</strong><p>{ruleset==='evolution'?'Become a giant mutation of your pet. Hunt with claws, burrowing, grabs or drones.':'Stop the third escape. Tag twice to capture; patrol while your blaster recharges.'}</p><b>Play as the hunter →</b></button>
 <button className="hunt-mode" disabled={busy||petLoading||!companion} onClick={()=>void online('coop')}><span>03 / COOPERATIVE</span><strong>Friends vs computer</strong><p>Bring classmates. Outsmart one computer hunter.</p><b>Find your team →</b></button>
 <button className="hunt-mode" disabled={busy||petLoading||!companion} onClick={()=>void online('versus')}><span>04 / CLASSROOM</span><strong>Hunt each other</strong><p>Player versus player, or take on your teacher.</p><b>Open classroom rooms →</b></button></div></section>
 <section className="hunt-panel hunt-setup"><div><h2>Pick your playground</h2><div className="hunt-maps">{ARENAS.map(a=><button key={a.id} aria-pressed={map===a.id} onClick={()=>setMap(a.id)}><span className={`hunt-map-swatch ${a.id}`} style={{backgroundImage:`url(${WORLD_ART}/${a.id}-preview.png)`}}/><strong>{a.name}</strong><small>{a.tagline}</small></button>)}</div></div><div className="hunt-loadout"><h2>Make it yours</h2><div className="hunt-companion-preview" data-testid="hunt-owned-pet">{companion&&<CompanionPortrait species={companion.species} stage={companion.stage??'baby'}/>}<div><strong>{petLoading?'Finding your pet…':companion?.name??'Your pet belongs here'}</strong><small>{companion?(teacherPet?'Your assigned classroom sentinel.':'Your earned pet joins you automatically.') : petError}</small></div></div>{ruleset==='classic'&&<><label>Runner gadget<select value={kit} onChange={e=>setKit(e.target.value as Kit)}>{Object.entries(KITS).map(([id,k])=><option key={id} value={id}>{k.name}</option>)}</select></label><p>{KITS[kit].description}</p></>}<label>Computer difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="gentle">Gentle</option><option value="normal">Normal</option><option value="tricky">Tricky</option></select></label>{ruleset==='evolution'?<p>9 minute rounds · Powers reset each round</p>:<label>Round length<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={180}>3 minutes</option><option value={240}>4 minutes</option><option value={300}>5 minutes</option></select></label>}<label className="hunt-relaxed"><input type="checkbox" checked={relaxed} onChange={e=>setRelaxed(e.target.checked)}/> Relaxed math checks <small>(more time, no penalty)</small></label></div></section>
 {directory&&<section className="hunt-panel" aria-label="Classroom Pet Hunt rooms"><h2>Your classroom arena</h2><p>Join a room, or open one for your classmates. Empty seats become bots when everyone is ready.</p><label>Room mode<select value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="versus">Players versus players</option><option value="coop">Team versus computer</option>{directory.teacher&&<option value="teacher">Beat the Teacher</option>}</select></label><button className="hunt-primary" disabled={busy} onClick={()=>{setBusy(true);setError('');void pilotAPI<{id:string}>('pet-hunt/create','POST',{map,mode,difficulty,duration:ruleset==='evolution'?540:duration,kit,relaxed,ruleset}).then(r=>setSession({kind:'online',id:r.id})).catch(e=>setError((e as Error).message)).finally(()=>setBusy(false));}}>Create {mode==='teacher'?'Beat the Teacher':'classroom'} room</button><div className="hunt-rooms">{directory.rooms.map(r=><article key={r.id}><div><strong>{r.name}</strong><p>{r.ruleset==='evolution'?'Rift Hunt':'Classic Hunt'} · {ARENAS.find(a=>a.id===r.map)?.name} · {r.count}/5 players · {r.phase}</p></div><button onClick={()=>setSession({kind:'online',id:r.id})}>Join room</button></article>)}{!directory.rooms.length&&<p>No rooms yet. Yours can be the first.</p>}</div></section>}
 <footer className="hunt-footer">Energy tags, teamwork, and a little woodland mischief.</footer></main>;
}
function ArenaSession({session,onLeave}:{session:Session;onLeave:()=>void}){
 const [screen,setScreen]=useState(()=>({width:window.innerWidth,height:window.innerHeight}));
 const viewport=arenaViewport(screen.width,screen.height),cameraOffset=useRef({x:0,y:0});
 useEffect(()=>{const resize=()=>setScreen({width:window.innerWidth,height:window.innerHeight});window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',resize);return()=>{window.removeEventListener('resize',resize);document.removeEventListener('fullscreenchange',resize);};},[]);
 const reduced=useReducedMotion(),canvas=useRef<HTMLCanvasElement>(null),surface=useRef<HTMLElement>(null),input=useRef<Input>(idleInput()),keys=useRef(new Set<string>()),match=useRef<Match|null>(null),viewRef=useRef<View|null>(null),previous=useRef<{view:View;at:number}|null>(null),socket=useRef<WebSocket|null>(null);
 const [view,setView]=useState<View|null>(null),[room,setRoom]=useState<RoomView|null>(null),[connection,setConnection]=useState('Opening arena…'),[error,setError]=useState(''),[assist,setAssist]=useState(true),[sound,setSound]=useState(false),[compact,setCompact]=useState(()=>window.innerWidth<600||window.matchMedia('(pointer: coarse)').matches),[leaveConfirm,setLeaveConfirm]=useState(false),[guideOpen,setGuideOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[showMap,setShowMap]=useState(session.kind==='solo'&&session.ruleset==='evolution');
 const resumeAfterGuide=useRef(false),resumeAfterMenu=useRef(false);
 const prefs=useRef({reduced,assist,sound,showMap}),audio=useRef<AudioContext|null>(null),lastSound=useRef(0),lastEvent=useRef(''),localRole=session.kind==='solo'?session.role:'runner';
 useEffect(()=>{prefs.current={reduced,assist,sound,showMap};},[reduced,assist,sound,showMap]);
 const command=(action:string,extra:Record<string,unknown>={})=>{setError('');if(match.current&&action==='evolution-choice'){chooseEvolution(match.current,'you',String(extra.choice));accept(viewFor(match.current,'you'));canvas.current?.focus();return;}const ws=socket.current;if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'command',action,...extra}));};
 const accept=(v:View)=>{previous.current=viewRef.current?{view:viewRef.current,at:performance.now()}:null;viewRef.current=v;setView(v);};
 useEffect(()=>{
   let stopped=false,reconnect:ReturnType<typeof setTimeout>|undefined,attempt=0;
   if(session.kind==='solo'){const m=createMatch(session.map,session.difficulty,session.duration,newSeed(),session.relaxed,session.ruleset);addPlayer(m,'you',session.name,session.role,session.species,session.kit).stage=session.stage;Object.assign(m.players[0],{grade:session.grade??2,returnProfile:session.returnProfile});startMatch(m);m.players.filter(p=>p.bot).forEach(p=>{p.stage='baby';});practiceStart(m);match.current=m;accept(viewFor(m,'you'));setConnection('Solo practice');return()=>{match.current=null;};}
   const connect=()=>{
     const url=new URL(`/api/pilot/pet-hunt/${session.id}/socket`,location.origin);url.protocol=location.protocol==='https:'?'wss:':'ws:';url.searchParams.set('tab',tabSession());
     const ws=new WebSocket(url);socket.current=ws;setConnection(attempt?'Reconnecting…':'Connecting…');
     ws.onopen=()=>{attempt=0;setConnection('Connected');setError('');};
     ws.onmessage=e=>{if(stopped)return;try{const packet=JSON.parse(e.data) as RoomView|{type:'error';message:string};if(packet.type==='state'){setRoom(packet);accept(packet.match);}else if(packet.type==='error')setError(packet.message);}catch{setError('The arena sent an unreadable update. Reconnect to try again.');}};
     ws.onclose=e=>{if(stopped)return;input.current=idleInput();keys.current.clear();if(e.code===4001||e.code===4003){setConnection('Session ended');setError('Your room or classroom session ended. Return to Auralith and sign in again.');return;}setConnection('Reconnecting…');attempt++;reconnect=setTimeout(connect,Math.min(5000,500*2**Math.min(attempt,4)));};
     ws.onerror=()=>setError('Connection interrupted. We will try again; a bot can cover your seat.');
   };connect();return()=>{stopped=true;clearTimeout(reconnect);socket.current?.close(1000,'Left arena');socket.current=null;};
 },[session]);
 useEffect(()=>{
   let frame=0,last=performance.now(),accumulator=0,send=0,display=0;
   const loop=(now:number)=>{
     const dt=Math.min(.1,(now-last)/1000);last=now;const current=viewRef.current,me=current?.players.find(p=>p.id===current.you);
     const i=input.current,k=keys.current;
     if(!compact){i.x=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0);i.y=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);}
     i.quiet=k.has('shift')||i.quiet&&compact;
     if(prefs.current.assist&&me&&current){const target=current.players.filter(p=>p.role!==me.role&&!p.captured&&!p.escaped&&!p.out&&!p.evo?.underground).sort((a,b)=>distance(me,a)-distance(me,b))[0];if(target&&distance(me,target)<350)i.aim=Math.atan2(target.y-me.y,target.x-me.x);else if(Math.hypot(i.x,i.y)>.1)i.aim=Math.atan2(i.y,i.x);}
     if(match.current){accumulator+=dt;while(accumulator>=.025){step(match.current,{you:{...i}},.025);accumulator-=.025;}display+=dt;if(display>=.1){accept(viewFor(match.current,'you'));display=0;}}
     else{send+=dt;if(send>=.05&&current?.phase==='playing'&&!current.paused&&socket.current?.readyState===WebSocket.OPEN){socket.current.send(JSON.stringify({type:'input',input:i}));send=0;}}
     const v=match.current?viewFor(match.current,'you'):viewRef.current,c=canvas.current?.getContext('2d');
     if(c&&v){let rendered=v;const prev=previous.current;if(!match.current&&prev&&v.phase==='playing'&&!v.paused){const fraction=Math.min(1,(now-prev.at)/100);rendered={...v,players:v.players.map(p=>{const old=prev.view.players.find(a=>a.id===p.id);return old&&distance(old,p)<80?{...p,x:old.x+(p.x-old.x)*fraction,y:old.y+(p.y-old.y)*fraction}:p;})};}const pixelScale=c.canvas.height/screen.height,top=90*pixelScale,bottom=(compact?150:70)*pixelScale;cameraOffset.current=arenaCamera(rendered.players.find(p=>p.id===rendered.you),c.canvas.width,c.canvas.height,top,bottom,rendered.evolution);draw(c,rendered,now/1000,{reduced:prefs.current.reduced,aimAssist:prefs.current.assist,minimap:prefs.current.showMap,hud:{top,bottom,scale:pixelScale}});
       if(prefs.current.sound&&audio.current&&now-lastSound.current>180){const own=v.players.find(p=>p.id===v.you);const event=own?.shot?`shot-${Math.floor(v.tick/4)}`:v.message;if(event!==lastEvent.current){lastEvent.current=event;lastSound.current=now;const a=audio.current,o=a.createOscillator(),gain=a.createGain();o.type='sine';o.frequency.setValueAtTime(own?.shot?540:740,a.currentTime);o.frequency.exponentialRampToValueAtTime(own?.shot?170:940,a.currentTime+.12);gain.gain.setValueAtTime(.025,a.currentTime);gain.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(gain);gain.connect(a.destination);o.start();o.stop(a.currentTime+.17);}}
     }
     frame=requestAnimationFrame(loop);
   };frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame);
 },[compact,screen.height]);
 useEffect(()=>{
   const clear=()=>{keys.current.clear();input.current=idleInput();if(match.current&&document.hidden){match.current.paused=true;accept(viewFor(match.current,'you'));}};
   const down=(e:KeyboardEvent)=>{if(document.querySelector('dialog[open]')||(e.target as HTMLElement).closest('input,select,textarea,button,dialog'))return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','e','f','shift','q','t','r'].includes(key)){e.preventDefault();keys.current.add(key);if(key==='e')input.current.interact=true;if(key==='t')input.current.trap=true;if(key==='r')input.current.sensor=true;if(key==='f')input.current.fire=true;if(key===' ')input.current.gadget=true;if(key==='q'&&!e.repeat)setAssist(a=>!a);}};
   const up=(e:KeyboardEvent)=>{const key=e.key.toLowerCase();keys.current.delete(key);if(key==='e')input.current.interact=false;if(key==='t')input.current.trap=false;if(key==='r')input.current.sensor=false;if(key==='f')input.current.fire=false;if(key===' ')input.current.gadget=false;};
   window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);
   return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};
 },[]);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 useEffect(()=>{if(view?.phase==='playing'&&!view.paused)canvas.current?.focus({preventScroll:true});},[view?.phase,view?.paused]);
 const me=view?.players.find(p=>p.id===view.you),hunter=me?.role==='hunter',lobby=view?.phase==='lobby',finished=view?.phase==='finished';
 const evo=me?.evo,mutation=evo?PACKAGES[evo.mutation]:null;
 const action=view?currentAction(view):{title:'Help / use',hint:'Light · rescue · escape'};
 const answer=useCallback((choice:number,id:number)=>{input.current.answer=choice;input.current.answerFor=id;},[]);
 const hold=(key:'fire'|'interact'|'gadget'|'trap'|'sensor')=>({onPointerDown:(e:ReactPointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current[key]=true;},onPointerUp:()=>{input.current[key]=false;},onPointerCancel:()=>{input.current[key]=false;},onLostPointerCapture:()=>{input.current[key]=false;}});
 const pause=()=>{if(match.current){match.current.paused=!match.current.paused;accept(viewFor(match.current,'you'));}else command('pause');};
 const openGuide=()=>{keys.current.clear();input.current=idleInput();resumeAfterGuide.current=!!match.current&&!match.current.paused;if(match.current){match.current.paused=true;accept(viewFor(match.current,'you'));}setGuideOpen(true);};
 const closeGuide=()=>{setGuideOpen(false);if(match.current&&resumeAfterGuide.current){match.current.paused=false;accept(viewFor(match.current,'you'));}canvas.current?.focus();};
 const openMenu=()=>{keys.current.clear();input.current=idleInput();resumeAfterMenu.current=!!match.current&&!match.current.paused;if(match.current){match.current.paused=true;accept(viewFor(match.current,'you'));}setMenuOpen(true);};
 const closeMenu=()=>{setMenuOpen(false);if(match.current&&resumeAfterMenu.current){match.current.paused=false;accept(viewFor(match.current,'you'));}canvas.current?.focus();};
 const rematch=()=>{if(session.kind==='solo'){const m=createMatch(session.map,session.difficulty,session.duration,newSeed(),session.relaxed,session.ruleset);addPlayer(m,'you',session.name,session.role,session.species,session.kit).stage=session.stage;Object.assign(m.players[0],{grade:session.grade??2,returnProfile:session.returnProfile});startMatch(m);m.players.filter(p=>p.bot).forEach(p=>{p.stage='baby';});match.current=m;input.current=idleInput();accept(viewFor(m,'you'));}else command('rematch');};
 return <main ref={surface} className={`hunt-app hunt-game hunt-theme-${view?.map??'garden'} ${view&&!lobby?'hunt-immersive':''} ${compact?'hunt-touch-mode':''} ${view?.paused||finished||leaveConfirm?'hunt-modal-open':''}`}><header className="hunt-top hunt-quiet-top"><button onClick={openMenu} aria-label="Open game menu">☰ Menu</button></header>
 {menuOpen&&<HuntMenu onClose={closeMenu} connection={connection} solo={session.kind==='solo'}>
 <div className="hunt-menu-controls"><button onClick={openGuide}>Guide</button><button aria-pressed={sound} onClick={()=>{if(!audio.current)audio.current=new AudioContext();void audio.current.resume();setSound(!sound);}}>Sound {sound?'on':'off'}</button><button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void surface.current?.requestFullscreen?.().catch(()=>setError('Fullscreen is unavailable in this browser.'));}}>Fullscreen</button>
 <label><input type="checkbox" checked={assist} onChange={e=>setAssist(e.target.checked)}/> Aim assist</label><label><input type="checkbox" checked={compact} onChange={e=>{setCompact(e.target.checked);input.current=idleInput();}}/> Touch controls</label><label><input type="checkbox" checked={showMap} onChange={e=>setShowMap(e.target.checked)}/> Show minimap</label>
 {session.kind==='online'&&(room?.teacher||room?.host)&&!finished&&<button onClick={pause}>{view?.paused?'Resume':'Pause'}</button>}{room?.teacher&&!finished&&<button onClick={()=>command('end')}>End round</button>}
 <button onClick={()=>{setMenuOpen(false);setLeaveConfirm(true);}}>Leave arena</button></div></HuntMenu>}
 
 {error&&<p role="alert" className="hunt-error">{error}</p>}
 {guideOpen&&view?.evolution?<EvolutionGuide onClose={closeGuide}/>:guideOpen&&<HuntGuide initialRole={hunter?'hunter':'runner'} online={session.kind==='online'&&view?.phase==='playing'} onClose={closeGuide}/>}
 {leaveConfirm&&<section role="dialog" aria-modal="true" aria-label="Leave Pet Hunt" className="hunt-panel"><h2>Leave this arena?</h2><p>{session.kind==='online'?'A computer pet will cover your place during the round.':'Your practice round will end.'}</p><button onClick={()=>{command('leave');onLeave();}}>Leave arena</button><button onClick={()=>{setLeaveConfirm(false);closeMenu();}}>Keep playing</button></section>}
 {lobby&&<section className="hunt-panel hunt-lobby"><span className="hunt-eyebrow">GET YOUR TEAM TOGETHER</span><h1>{room?.mode==='teacher'?'Beat the Teacher':room?.mode==='coop'?'Pets vs computer':'Your hunting party'}</h1><p>{view?.evolution?'Rift Hunt · Earned second lives':'Classic Hunt · Teammate rescues'} · {ARENAS.find(a=>a.id===view?.map)?.name} · {Math.round((view?.duration??240)/60)} minute round · {view?.difficulty} bots</p><div className="hunt-seat-grid">{room?.seats.map(p=><article key={p.id}><strong>{p.name}{p.id===view?.you?' · You':''}</strong><span>{p.role==='hunter'?'Hunter':'Runner'} · {p.ready?'Ready':'Choosing'}</span><small>{p.connected?'Connected':'Reconnecting'}</small></article>)}</div><p>Unfilled positions become computer pets. Everyone playing must press Ready before the host starts.</p><div className="hunt-actions"><button onClick={()=>command('role',{role:'runner'})}>Be a runner</button>{room?.mode!=='coop'&&(room?.mode!=='teacher'||room.teacher)&&<button onClick={()=>command('role',{role:'hunter'})}>Be the hunter</button>}{room?.teacher&&<button onClick={()=>command('role',{role:'spectator'})}>Spectate</button>}{!view?.evolution&&<label>Gadget<select value={me?.kit??'scout'} onChange={e=>command('kit',{kit:e.target.value})}>{Object.entries(KITS).map(([id,k])=><option key={id} value={id}>{k.name}</option>)}</select></label>}{me&&<button className="hunt-primary" onClick={()=>command('ready')}>{room?.seats.find(s=>s.id===view?.you)?.ready?'Ready ✓':'Ready to play'}</button>}{room?.host&&<button className="hunt-primary" onClick={()=>command('start')}>Start round</button>}</div>{!!room?.queue.length&&<p>Next round: {room.queue.join(', ')}</p>}</section>}
 {view&&!lobby&&<>{!me&&!room?.teacher&&<p className="hunt-announcer">You are in the next-round queue. Your seat opens when the host starts a rematch.</p>}<section className="hunt-hud"><span className="hunt-role-label">{hunter?(view.evolution?'Monster':'Hunter'):me?'Runner':'Watching'}</span><div className="hunt-objectives"><div><span className="hunt-lantern-icon" aria-hidden="true"/><span><b>{Math.min(view.evolution?4:BEACONS_NEEDED,view.beacons.filter(b=>b.progress>=1).length)} / {view.evolution?4:BEACONS_NEEDED}</b> {view.evolution?'rifts':'lanterns'}</span><i className="hunt-objective-pips" aria-hidden="true">{Array.from({length:view.evolution?4:BEACONS_NEEDED},(_,i)=><i key={i} className={i<view.beacons.filter(b=>b.progress>=1).length?'lit':''}/>)}</i></div><div><span className="hunt-portal-icon" aria-hidden="true"/><span><b>{view.players.filter(p=>p.escaped).length} / 3</b> escaped</span></div></div><div className={`hunt-timer ${view.time<60?'urgent':''}`}><small>TIME LEFT</small><strong data-testid="hunt-clock">{Math.floor(Math.ceil(view.time)/60)}:{String(Math.ceil(view.time)%60).padStart(2,'0')}</strong></div></section>
 <p className="hunt-next-objective" data-testid="hunt-next-objective">{nextObjective(view)}</p><div className="hunt-arena-wrap"><canvas ref={canvas} width={viewport.width} height={viewport.height} tabIndex={0} aria-label="Pet Hunt arena. Move with WASD or arrows, E to interact, F to fire, Space for gadget." onContextMenu={e=>e.preventDefault()} onPointerMove={e=>{if(e.pointerType==='touch')return;const p=viewRef.current?.players.find(p=>p.id===viewRef.current?.you);if(!p)return;const point=screenToArena(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect(),{width:e.currentTarget.width,height:e.currentTarget.height},cameraOffset.current);input.current.aim=Math.atan2(point.y-p.y,point.x-p.x);if(prefs.current.assist)setAssist(false);}} onPointerDown={e=>{if(e.pointerType==='touch')return;e.currentTarget.focus();e.currentTarget.setPointerCapture(e.pointerId);input.current.fire=true;}} onPointerUp={()=>{input.current.fire=false;}} onPointerCancel={()=>{input.current.fire=false;}} onLostPointerCapture={()=>{input.current.fire=false;}}/>
 {view.paused&&<div className="hunt-overlay"><h2>Take a breath.</h2><p>The arena is paused.</p>{(session.kind==='solo'||room?.teacher||room?.host)&&<button onClick={pause}>Resume round</button>}</div>}
 {finished&&<div className="hunt-overlay hunt-result"><p className="hunt-eyebrow">ROUND COMPLETE</p><h2>{view.evolution?.reason==='core'?'Monster defeated!':view.winner==='runners'?'The great escape!':view.winner==='hunter'?'Caught in the garden!':'Round ended'}</h2><p>{view.message}</p><div className="hunt-results">{view.players.map(p=><div key={p.id}><strong>{p.name}</strong><span>{p.escaped?'Escaped · ':''}{view.evolution?`${p.beaconScore} rifts · ${p.evo?.powers.length??0} powers · ${p.evo?.returns??0} earned returns`:`${p.beaconScore} beacons · ${p.rescues} rescues · ${p.tags} tags`}</span></div>)}</div>{(session.kind==='solo'||room?.host)&&<button className="hunt-primary" onClick={rematch}>{session.kind==='solo'?'Play again':'Rotate roles & rematch'}</button>}<button onClick={onLeave}>Back to Pet Hunt</button><small>Teamwork counts. Your saved pet is safe.</small></div>}
 </div>{me&&!hunter&&!me.evo?.echoSupport&&view.phase==='playing'&&<SparkPanel me={me} tick={view.tick} answer={answer}/>}{me&&view.evolution&&<EvolutionHUD view={view} choose={choice=>{command('evolution-choice',{choice});canvas.current?.focus();}} hold={hold}/>} {me&&!view.evolution&&<div className="hunt-hotbar"><button className="hunt-charge-card" aria-label="Fire blaster" {...hold('fire')}><kbd>F</kbd><div><strong>{hunter?'Tag blaster':'Stun blaster'}</strong><span className="hunt-charges" aria-label={`${Math.floor(me.ammo)} charges remaining`}>{[0,1,2].map(i=><i key={i} className={i<Math.floor(me.ammo)?'ready':''}/>)}</span></div><small data-testid="hunt-recharge">{hunter&&me.ammo===0?`Cooling ${Math.max(1,Math.ceil(HUNTER_RECHARGE-me.reload))}s · slower`:me.ammo<3?'Recharging…':'3 shots · aim first'}</small></button><button aria-label={action.title} className={action.urgent?'hunt-escape':''} {...hold('interact')}><kbd>E</kbd><div><strong>{action.title}</strong><small>{action.hint}</small></div></button>{hunter&&<><button aria-label="Place trap" disabled={!view.trapsLeft} {...hold('trap')}><kbd>T</kbd><div><strong>Trap · {view.trapsLeft}</strong><small>Sticks a pet in place</small></div></button><button aria-label="Place sensor" {...hold('sensor')}><kbd>R</kbd><div><strong>{view.sensor?'Move sensor':'Sensor'}</strong><small>Pings when pets pass</small></div></button></>}<button aria-label="Use gadget" {...hold('gadget')} className={me.gadgetCooldown>0?'cooling':''}><kbd>SPACE</kbd><div><strong>{hunter?'Pulse dash':KITS[me.kit].name}{me.gadgetCooldown>0?` · ${Math.ceil(me.gadgetCooldown)}s`:''}</strong><small>{me.gadgetCooldown>0?`Ready in ${Math.ceil(me.gadgetCooldown)}s`:'Gadget ready'}</small></div></button></div>}<HuntToast message={view.message}/>
 
 {compact&&<div className="hunt-touch"><Stick label="Move" onMove={(x,y)=>{input.current.x=x;input.current.y=y;}}/><div className="hunt-touch-buttons"><button aria-label="Fire" {...hold('fire')}>{view.evolution?mutation?.primary:hunter&&me?.ammo===0?`Cooling ${Math.max(1,Math.ceil(HUNTER_RECHARGE-me.reload))}s`:`Fire · ${me?.ammo??0}/3`}</button><button className={action.urgent?'hunt-escape':''} {...hold('interact')}>{action.title}</button>{view.evolution?<><button {...hold('trap')}>{mutation?.secondary}</button><button {...hold('sensor')}>{evo?.items[0]??'No item'}</button></>:hunter&&<><button disabled={!view?.trapsLeft} {...hold('trap')}>Trap · {view?.trapsLeft??0}</button><button {...hold('sensor')}>Sensor</button></>}<button {...hold('gadget')}>{mutation?.skill??(hunter?'Pulse dash':'Gadget')}</button><button aria-pressed={input.current.quiet} onClick={()=>{input.current.quiet=!input.current.quiet;}}>Quiet walk</button></div><Stick label="Aim" onMove={(x,y)=>{if(Math.hypot(x,y)>.1){input.current.aim=Math.atan2(y,x);setAssist(false);}}}/></div>}
 <p className="hunt-control-hint">WASD / arrows: move · Mouse: aim · Click / F: fire · E: help / use · Space: {hunter?'pulse dash':'gadget'} · Shift: quiet walk · Q: aim assist</p></>}
 {!view&&<section className="hunt-panel"><h1>Opening the garden…</h1><p>{connection}</p><button onClick={onLeave}>Back to Pet Hunt</button></section>}
 {view&&(lobby||finished)&&room?.host&&<button className="hunt-close-room" onClick={()=>command('close')}>Close room</button>}
 <span className="hunt-sr">{view?.evolution?'Complete four rifts and extract three runners, or destroy the exposed monster core. Defeated runners earn a second life through profile-based math.':localRole==='hunter'?'Stop three escapes before time runs out, or capture everyone still inside.':'Light five of the seven beacons, then get three runners out through the gate. Hide in lockers, crawl through vents, and rescue caged friends.'}</span></main>;
}
function Stick({label,onMove}:{label:string;onMove:(x:number,y:number)=>void}){
 const [point,setPoint]=useState({x:0,y:0});
 const move=(e:ReactPointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width/2),y=(e.clientY-r.top-r.height/2)/(r.height/2),n=Math.max(1,Math.hypot(x,y));const p={x:x/n,y:y/n};setPoint(p);onMove(p.x,p.y);};
 const reset=()=>{setPoint({x:0,y:0});onMove(0,0);};
 return <div className="hunt-stick" role="group" aria-label={`${label} touch pad`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))move(e);}} onPointerUp={reset} onPointerCancel={reset} onLostPointerCapture={reset}><span style={{transform:`translate(${point.x*27}px,${point.y*27}px)`}}/>{label}</div>;
}
