import {arenaOf,distance,inside,lineClear,playArena,type Match,type Player,type Vec} from '../model';
import {damageRift} from './run';
import {advance,freePoint} from './world';
import {award,has,maxHp} from './state';
export function fx(m:Match,kind:Match['effects'][number]['kind'],p:Vec,life=.7){m.effects.push({id:m.nextId++,kind,x:p.x,y:p.y,life});}
export const active=(p:Player)=>!p.out&&!p.escaped&&!p.captured&&!p.evo?.echo;
export function ungrab(m:Match,h:Player){const a=h.evo!;const r=m.players.find(p=>p.id===a.grab);if(r?.evo){r.evo.grabbedBy=null;r.evo.grabImmune=5;r.immune=1;Object.assign(r,freePoint(playArena(m),{x:h.x+Math.cos(h.aim)*70,y:h.y+Math.sin(h.aim)*70}));}a.grab=null;a.grabTime=0;h.carrying=null;}
export function hurt(m:Match,v:Player,amount:number,owner:Player){const a=v.evo!,exposed=v.role==='hunter'&&m.evolution!.core.exposed>0,guardImmune=v.immune>0;if(!active(v)||a.underground||guardImmune&&!exposed||v.shield>0)return;fx(m,'hit',v);owner.tags++;if(!guardImmune)v.immune=.3;
 if(v.role==='hunter'){if(m.evolution!.core.exposed>0){const c=m.evolution!.core,n=Math.min(amount*(has(owner,'focus')?1.15:1),140-c.windowDamage);c.hp=Math.max(0,c.hp-n);c.windowDamage+=n;if(has(owner,'focus')&&owner.role==='runner'){owner.evo!.hp=Math.min(maxHp(owner),owner.evo!.hp+2);owner.hp=owner.evo!.hp;}}if(guardImmune)return;a.guard-=amount*(has(v,'carapace')?.8:1);if(a.guard<=0){a.guard=100;v.stun=1.5;v.immune=4;if(has(v,'shell')){v.shield=2;fx(m,'smoke',v,2);}ungrab(m,v);award(m,'runner',12,`guard:${Math.floor((m.duration-m.time)/20)}`);}}
 else{a.hp=Math.max(0,a.hp-amount);v.hp=a.hp;if(a.hp<=0){eliminate(m,v);award(m,'hunter',35,`down:${v.id}:${a.returns}`);}}
}
export function damageCover(m:Match,at:Vec,radius:number,damage:number,p:Player){const e=m.evolution!,base=arenaOf(m);for(const t of e.terrain){const r=(base.pieces??base.walls)[t.id];if(t.hp<=0||!r)continue;const near={x:Math.max(r.x,Math.min(r.x+r.w,at.x)),y:Math.max(r.y,Math.min(r.y+r.h,at.y))};if(distance(at,near)>radius)continue;t.hp=Math.max(0,t.hp-damage*(has(p,'demolish')?2:1));if(!t.hp){e.revision++;if(has(p,'demolish'))p.evo!.guard=Math.min(100,p.evo!.guard+8);if(has(p,'reach'))p.gadgetCooldown=Math.max(0,p.gadgetCooldown-1);fx(m,'hit',near);award(m,p.role,4,`cover:${t.id}`);}}}
export function strike(m:Match,p:Player,radius:number,damage:number,all=false){all=all||has(p,p.role==='hunter'?'cleave':'cleave-r');damageRift(m,p,p,radius,damage);const a=p.evo!;a.attack=.3;a.attackAim=p.aim;p.shot=.2;p.noise=1.5;for(const v of m.players){const angle=Math.atan2(v.y-p.y,v.x-p.x)-p.aim;if(v.role!==p.role&&distance(v,p)<radius&&(all||Math.cos(angle)>.3)&&lineClear(playArena(m),p,v))hurt(m,v,damage,p);}damageCover(m,{x:p.x+Math.cos(p.aim)*40,y:p.y+Math.sin(p.aim)*40},radius*.55,damage,p);for(const d of m.evolution!.drones)if(d.role!==p.role&&distance(d,p)<radius)d.hp-=damage;}
export function shoot(m:Match,p:Player,charged=false,angle=p.aim,single=false){p.noise=2;p.shot=.25;const speed=charged?760:580;const fan=!single&&has(p,p.role==='hunter'?'fan':'fan-r');for(const offset of fan?[-.22,0,.22]:[0])m.bullets.push({id:m.nextId++,owner:p.id,role:p.role,x:p.x,y:p.y,vx:Math.cos(angle+offset)*speed,vy:Math.sin(angle+offset)*speed,life:charged?1:.8,damage:(charged?50:p.role==='hunter'?26:22)*(fan?.6:1),pierce:has(p,'pierce')?1:0,ricochets:has(p,'bounce-r')?1:0,hitIds:[]});}
export function nova(m:Match,p:Player){for(let n=0;n<8;n++){shoot(m,p,false,n*Math.PI/4,true);m.bullets[m.bullets.length-1].damage=12;}fx(m,'pulse',p);}
export function emp(m:Match,p:Player){fx(m,'pulse',p);const r=180+(has(p,'signal')?60:0);for(const d of m.evolution!.drones)if(d.role!==p.role&&distance(d,p)<r)d.hp=0;for(const v of m.players)if(v.role!==p.role&&active(v)&&distance(v,p)<r&&lineClear(playArena(m),p,v)){if(p.role==='runner')hurt(m,v,40,p);else if(v.shield<=0&&!v.evo!.underground)v.stun=Math.max(v.stun,.8);}}
export function summon(m:Match,p:Player,kind:'bite'|'scout'|'medic'){const e=m.evolution!;if(e.drones.filter(d=>d.owner===p.id).length>=(p.role==='hunter'?(has(p,'command')?4:3):1))return false;e.drones.push({id:m.nextId++,owner:p.id,role:p.role,kind,x:p.x,y:p.y,hp:has(p,'command')?25:35,life:30+(has(p,'command')?12:0),cooldown:0,aim:p.aim,target:null,think:0});fx(m,'pulse',p);return true;}
/** Defeat is immediate. Only the authoritative math-return path restores a runner. */
export function eliminate(m:Match,p:Player){const a=p.evo!;for(const h of m.players)if(h.evo?.grab===p.id)ungrab(m,h);if(a.grab)ungrab(m,p);for(const s of m.evolution!.run?.sites??[])for(const n of s.nodes)if(n.carrier===p.id){n.carrier=null;Object.assign(n,{x:p.x,y:p.y});}p.out=true;p.captured=false;p.caged=0;p.carrying=null;p.captureTime=0;p.rescue=0;p.charging=-1;p.check=null;p.vent=0;p.ventTo=null;p.hidden=false;p.locker=-1;p.shield=0;a.hp=p.hp=0;a.echo=true;a.echoChoice=true;a.echoSupport=false;a.returnMath=undefined;a.stealth=0;a.work='';a.workTime=0;a.grabbedBy=null;if(a.component>=0){const part=m.evolution!.core.parts[a.component];part.carrier=null;Object.assign(part,{x:p.x,y:p.y});a.component=-1;}fx(m,'escape',p);m.message=`${p.name} is eliminated. Earn a return through math or support the team as an Echo.`;}
export function reviveFromMath(m:Match,p:Player){p.captured=false;p.caged=0;p.captureTime=0;p.rescue=0;p.hp=p.evo!.hp=maxHp(p)*.8;p.evo!.echoChoice=false;p.evo!.echoSupport=false;p.immune=6;fx(m,'rescue',p);}
export function projectiles(m:Match,dt:number){for(const b of m.bullets){b.life-=dt;const owner=m.players.find(p=>p.id===b.owner);if(!owner){b.life=0;continue;}for(let n=0;n<4&&b.life>0;n++){const prev={x:b.x,y:b.y};b.x+=b.vx*dt/4;b.y+=b.vy*dt/4;const a=playArena(m);if(b.x<0||b.y<0||b.x>2800||b.y>1800){b.life=0;break;}if(a.walls.some(r=>inside(b,r))){damageCover(m,b,10,owner.role==='hunter'?30:18,owner);if((b.ricochets??0)>0){const xBlocked=a.walls.some(r=>inside({x:b.x,y:prev.y},r));if(xBlocked)b.vx=-b.vx;else b.vy=-b.vy;b.x=prev.x;b.y=prev.y;b.ricochets!--;fx(m,'spark',b,.3);}else b.life=0;break;}const site=m.evolution!.run?.sites.find(s=>s.kind==='breach'&&!s.done&&s.hp>0&&distance(s,b)<30);if(site&&b.role==='runner'){damageRift(m,owner,b,35,b.damage??22);b.life=0;break;}const drone=m.evolution!.drones.find(d=>d.role!==b.role&&distance(d,b)<22);if(drone){drone.hp-=25;b.life=0;break;}const v=m.players.find(p=>p.role!==b.role&&active(p)&&!p.evo!.underground&&p.locker<0&&!b.hitIds?.includes(p.id)&&distance(p,b)<(p.role==='hunter'?32:20));if(v){hurt(m,v,b.damage??(Math.hypot(b.vx,b.vy)>700?50:b.role==='hunter'?26:22),owner);b.hitIds??=[];b.hitIds.push(v.id);if((b.pierce??0)>0)b.pierce!--;else b.life=0;}}}m.bullets=m.bullets.filter(b=>b.life>0);}
export function dash(m:Match,p:Player,dt:number){damageCover(m,p,90,150*dt,p);advance(m,p,{x:p.x+Math.cos(p.aim)*100,y:p.y+Math.sin(p.aim)*100},420,dt);for(const v of m.players)if(v.role!==p.role&&distance(v,p)<65)hurt(m,v,35,p);}
