import {useEffect,useRef,useState,type PointerEvent} from 'react';
import type {View} from '../model';
import {PACKAGES,power,MILESTONES} from './catalog';
type Hold=(key:'fire'|'interact'|'gadget'|'trap'|'sensor')=>{onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>void;onPointerUp:()=>void;onPointerCancel:()=>void;onLostPointerCapture:()=>void};
export function EvolutionHUD({view,choose,hold}:{view:View;choose:(choice:string)=>void;hold:Hold}){
 const [deferred,setDeferred]=useState(false),me=view.players.find(p=>p.id===view.you),e=view.evolution;
 useEffect(()=>setDeferred(false),[me?.evo?.draft,me?.evo?.starting.length]);
 if(!me?.evo||!e)return null;const a=me.evo,k=PACKAGES[a.mutation],playing=view.phase==='playing'&&!view.paused,hasDraft=!!(a.starting.length||a.offers.length),next=MILESTONES[a.draft],completed=e.run?.sites.filter(s=>s.done).length??0;
 return <>
 <aside className="evo-status" aria-label="Evolution status"><small>RIFT HUNT / {a.echo?'ECHO PHASE':`BUILD ${a.draft} / ${MILESTONES.length}`}</small><strong style={{color:k.color}}>{a.echo?'OUT OF THE ARENA':k.name.toUpperCase()}</strong><span>{a.echo?(a.returns?'Return used · support your team':'One earned return available'):me.role==='hunter'?`Guard ${Math.ceil(a.guard)}`:`Vitality ${Math.ceil(a.hp)}`}</span><meter min={0} max={me.role==='hunter'?100:a.powers.includes('vital')?120:100} value={a.echo?0:me.role==='hunter'?a.guard:a.hp}/><span>Team power {Math.floor(e.xp[me.role])}{next!==undefined?` / ${next}`:' · MAX'}</span><span className={e.core.exposed>0?'evo-danger':''}>Core {Math.ceil(e.core.hp)} · Parts {e.core.installed}/3</span><div className="evo-build">{a.powers.map(id=><span key={id} title={`${power(id)?.name}: ${power(id)?.description}`} aria-label={power(id)?.name}>{power(id)?.icon??'◆'}</span>)}</div><small>{view.gate.state==='open'?'EXTRACT · Get three runners out':`${completed}/${e.run?.needed??4} rifts · or expose the core`}</small></aside>
 {a.echo&&playing&&!a.returnMath&&a.echoChoice!==false&&<section className="evo-draft evo-death" aria-label="Eliminated"><p>ELIMINATED · YOUR NEXT MOVE</p><h2>You’re out. Earn your way back.</h2><span>Five quick answers using familiar skills earn one second life. Wrong answers keep your progress.</span><div><button disabled={a.returns>0||!e.returnsOpen} onClick={()=>choose('echo-return')}><b>↻</b><strong>Earn my return</strong><span>{a.returns?'Second life already used':!e.returnsOpen?'New returns have closed':'Start rapid-fire math now'}</span></button><button onClick={()=>choose('echo-support')}><b>⬡</b><strong>Support my team</strong><span>Move as an Echo. Shield nearby living allies with Space.</span></button></div></section>}
 {a.echo&&playing&&a.returnMath&&!a.echoSupport&&<button className="evo-support-toggle" onClick={()=>choose('echo-support')}>Pause math · support team</button>}
 {a.echo&&playing&&a.echoSupport&&<button className="evo-claim" disabled={a.returns>0||!e.returnsOpen&&!a.returnMath} onClick={()=>choose('echo-return')}>{a.returns?'Support phase · return used':a.returnMath?'Resume my return challenge':'Earn my return · five quick answers'}</button>}
 {hasDraft&&playing&&!a.echo&&!me.escaped&&(deferred?<button className="evo-claim" onClick={()=>setDeferred(false)}>✦ Evolution ready · choose your power</button>:<section className="evo-draft" aria-label="Choose your evolution"><div className="evo-draft-heading"><p>{a.starting.length?'NEW RUN · CHOOSE YOUR MUTATION':`EVOLUTION ${a.draft+1} · SHAPE YOUR BUILD`}</p>{!a.starting.length&&<button onClick={()=>setDeferred(true)} aria-label="Choose upgrade later">Later</button>}</div><h2>{a.starting.length?'Become something different.':'Change how you fight.'}</h2><div>{a.starting.length?a.starting.map(id=><button key={id} style={{borderColor:PACKAGES[id].color}} onClick={()=>choose(id)}><b aria-hidden="true">{id==='broodkeeper'?'♛':id==='burrower'?'≋':id==='duelist'?'ϟ':'⬡'}</b><small>ROUND MUTATION</small><strong>{PACKAGES[id].name}</strong><span>{PACKAGES[id].description}</span><em>{PACKAGES[id].skill} / {PACKAGES[id].secondary}</em></button>):a.offers.map(id=>{const p=power(id);return <button key={id} className={p?.requires?'evo-ascended':''} onClick={()=>choose(id)}><b aria-hidden="true">{p?.icon}</b><small>{p?.requires?'✦ BUILD EVOLUTION':p?.tag.toUpperCase()}</small><strong>{p?.name}</strong><span>{p?.description}</span><em>{p?.requires?'Combination complete':'Lasts for this run'}</em></button>;})}</div><small>{a.starting.length?'Choose within 12 seconds. Your default mutation is already active.':'Earn power from rifts, combat and exploration. A trailing team earns 25% more from its next achievements.'}</small></section>)}
 <div className="hunt-hotbar evo-hotbar"><button {...hold('fire')} disabled={a.echo||me.escaped}><kbd>F</kbd><strong>{k.primary}</strong><small>{k.primary.includes('pistol')||k.primary.includes('blaster')?`${me.ammo}/3 charges`:'Aim · strike · recover'}</small></button><button {...hold('interact')} disabled={me.escaped}><kbd>E</kbd><strong>{a.echo?'Earn my return':a.grabbedBy?'Struggle free':'Interact'}</strong><small>{a.echo?'Five quick answers':'Rifts · supplies · hiding'}</small></button><button {...hold('gadget')} disabled={me.escaped}><kbd>SPACE</kbd><strong>{a.echo?'Shield a friend':k.skill}</strong><small>{Math.ceil(a.echo?a.echoCooldown:me.gadgetCooldown)||'Ready'}</small></button><button {...hold('trap')} disabled={a.echo||me.escaped}><kbd>T</kbd><strong>{k.secondary}</strong><small>{Math.ceil(a.secondary)||'Ready'}</small></button><button {...hold('sensor')} disabled={!a.items.length||a.echo||me.escaped}><kbd>R</kbd><strong>{a.items[0]??'Find supplies'}</strong><small>{a.items.length}/2 carried</small></button></div>
 </>;
}
export function EvolutionGuide({onClose}:{onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose();}} className="evo-guide" aria-label="Monster Evolution guide"><h2>A different hunt every run.</h2><p><b>Build:</b> choose a mutation, then draft powers earned through objectives, eliminations, supplies and destruction. Compatible powers unlock special evolutions. Builds reset each round.</p><p><b>Rift route:</b> complete four of seven missions to open both exits. Breach: attack the crystal’s armor. Circuit: connect both distant terminals. Salvage: retrieve both energy cells. Then hold E at the rift to claim it. Get three runners through either exit to win.</p><p><b>Monster:</b> hunt runners, disrupt unfinished rifts, break cover and claim surges. Defeating a runner eliminates them immediately. Grabs are short combat attacks; a teammate can break a grip by breaking your guard.</p><p><b>Second life:</b> eliminated players choose rapid-fire math or Echo support immediately. Five correct answers using demonstrated profile skills earn one return. Mistakes preserve progress. You can pause math to shield nearby friends, then resume. New returns close in the final 30 seconds; started challenges can finish.</p><p><b>Defeat the monster:</b> assemble three purple core parts. Charge both trap pads, lure the monster in, then attack its exposed core together. Repeat at alternating traps. Destroying the core wins immediately.</p><p><b>Controls:</b> WASD to move, mouse to aim, F attack, Space signature, T secondary, R supplies. Hold E to interact or struggle out of a grab. Shift walks quietly; Shift + E hides in a locker.</p><button onClick={onClose}>Back to the hunt</button></dialog>;}
