import {PACKAGES} from './catalog';
import {propSprite} from '../art';
import {arenaOf,type View} from '../model';
export function evolutionScenery(c:CanvasRenderingContext2D,v:View,t:number,layers:{y:number;draw:()=>void}[]){const e=v.evolution;if(!e)return;
 const label=(s:string,x:number,y:number,color='#ede0fc')=>{c.font='bold 12px monospace';c.textAlign='center';c.lineWidth=4;c.strokeStyle='#14202b';c.strokeText(s,x,y);c.fillStyle=color;c.fillText(s,x,y);};
 const ring=(x:number,y:number,r:number,color:string)=>{c.strokeStyle=color;c.lineWidth=3;c.beginPath();c.ellipse(x,y,r,r*.55,0,0,Math.PI*2);c.stroke();};
 const base=arenaOf(v);for(const o of e.terrain){const p=(base.pieces??base.walls)[o.id];if(!p||o.hp===o.max)continue;if(o.hp<=0){c.fillStyle='#4f4c4888';for(let n=0;n<8;n++)c.fillRect(p.x+(n*17)%p.w,p.y+(n*23)%p.h,8+(n%3)*3,6);}else{c.strokeStyle='#170e17';c.lineWidth=3;c.beginPath();c.moveTo(p.x+p.w*.5,p.y);c.lineTo(p.x+p.w*.4,p.y+p.h*.45);c.lineTo(p.x+p.w*.65,p.y+p.h*.6);c.lineTo(p.x+p.w*.5,p.y+p.h);c.stroke();}}
 for(const l of e.loot)layers.push({y:l.y,draw:()=>{if(l.kind==='crate'){c.save();if(l.opened)c.globalAlpha=.45;propSprite(c,'crate',l.x,l.y+8,1);c.restore();}if(!l.opened)label('SUPPLIES · E',l.x,l.y+24,'#f2daa0');}});
 for(const s of e.run?.sites??[]){const color=s.done?'#a7edbd':s.kind==='breach'?'#ffb78c':s.kind==='circuit'?'#92dafa':'#e4c182';ring(s.x,s.y,70,color);c.save();c.globalAlpha=.16;c.fillStyle=color;c.beginPath();c.ellipse(s.x,s.y,65,35,0,0,Math.PI*2);c.fill();c.restore();layers.push({y:s.y,draw:()=>{c.save();c.translate(s.x,s.y-36);c.rotate(Math.PI/4);c.fillStyle='#182735';c.fillRect(-23,-23,46,46);c.strokeStyle=color;c.lineWidth=4;c.strokeRect(-23,-23,46,46);c.fillStyle=color;c.fillRect(-10,-10,20,20);c.restore();label(s.done?'RIFT SECURED':s.kind.toUpperCase()+' RIFT',s.x,s.y-84,color);label(s.done?'POWER CLAIMED':s.kind==='breach'&&s.hp>0?`ATTACK ARMOR · ${Math.ceil(s.hp)}`:s.nodes.some(n=>!n.done)&&s.kind!=='breach'?(s.kind==='salvage'?'RETURN BOTH CELLS':'CONNECT BOTH TERMINALS'):`HOLD E · ${Math.floor(s.work/12*100)}%`,s.x,s.y+35,color);if(!s.done){c.fillStyle='#111d2e';c.fillRect(s.x-32,s.y+45,64,5);c.fillStyle=color;c.fillRect(s.x-32,s.y+45,64*(s.kind==='breach'&&s.hp>0?1-s.hp/160:s.work/12),5);}}});if(!s.done&&s.kind!=='breach')for(const n of s.nodes){if(n.carrier||n.done)continue;c.save();c.strokeStyle=color+'55';c.setLineDash([5,10]);c.beginPath();c.moveTo(s.x,s.y);c.lineTo(n.x,n.y);c.stroke();c.restore();layers.push({y:n.y,draw:()=>{c.fillStyle='#253a46';c.fillRect(n.x-14,n.y-24,28,24);c.fillStyle=color;c.fillRect(n.x-9,n.y-19,18,12);label(s.kind==='salvage'?'CELL · E':`CONNECT · ${Math.floor(n.work/5*100)}%`,n.x,n.y+22,color);}});}}
 e.core.stations.forEach((p,i)=>{const active=e.core.installed===3&&i===e.core.activeStation;ring(p.x,p.y,240,active?'#da95fa77':'#ad8aab22');layers.push({y:p.y,draw:()=>{propSprite(c,'workbench',p.x,p.y+8,1);c.fillStyle='#1e2536';c.fillRect(p.x-22,p.y-58,44,24);c.strokeStyle='#96749b';c.lineWidth=3;c.strokeRect(p.x-22,p.y-58,44,24);c.fillStyle=active?'#e5acff':'#847b9e';for(let n=0;n<3;n++){c.fillRect(p.x-14+n*12,p.y-52,8,e.core.installed>n?13:4);}ring(p.x,p.y-49,31,active?'#e9acff':'#735875');label(i===0?`ASSEMBLY · ${e.core.installed}/3 PARTS`:'CORE TRAP B',p.x,p.y+35);for(let n=0;n<2;n++){const x=p.x+(n?95:-95);ring(x,p.y,30,active&&e.core.plates[n]>=2?'#c7ffbd':'#cda2dc');if(active)label(e.core.cooldown>0?`${Math.ceil(e.core.cooldown)}s`:`HOLD E · ${Math.min(100,Math.floor(e.core.plates[n]/2*100))}%`,x,p.y+55);}}});});
 e.core.parts.forEach(p=>{if(p.installed||p.carrier)return;layers.push({y:p.y,draw:()=>{c.save();c.translate(p.x,p.y-22);c.rotate(Math.PI/4);c.fillStyle='#e2b0ff';c.fillRect(-12,-12,24,24);c.fillStyle='#7c589f';c.fillRect(-5,-5,10,10);c.restore();label('CORE PART · E',p.x,p.y+20);}});});
 if(e.surge.next<=0){ring(e.surge.at.x,e.surge.at.y,65,'#ffdf84');label('POWER SURGE · HOLD E',e.surge.at.x,e.surge.at.y-40,'#ffe4a3');}
 for(const d of e.drones)layers.push({y:d.y,draw:()=>{const y=d.y-24-Math.sin(t*7+d.id)*3;c.save();c.translate(d.x,y);c.rotate(d.aim);c.fillStyle=d.role==='hunter'?'#ae79c3':'#79c8c6';c.fillRect(-13,-9,26,18);c.fillStyle='#202735';c.fillRect(-20,-15,10,8);c.fillRect(-20,7,10,8);c.fillRect(10,-15,10,8);c.fillRect(10,7,10,8);c.fillStyle='#fff0b0';c.fillRect(8,-3,7,6);c.restore();label(d.kind.toUpperCase(),d.x,d.y+13);}});
 for(const exit of e.exits){ring(exit.x,exit.y,52,v.gate.state==='open'?'#acffdb':'#638085');c.fillStyle=v.gate.state==='open'?'#b7f2d4':'#41646d';c.fillRect(exit.x-38,exit.y-70,8,75);c.fillRect(exit.x+30,exit.y-70,8,75);c.fillRect(exit.x-38,exit.y-70,76,8);label(v.gate.state==='open'?'EXTRACT · E':v.gate.state==='opening'?`OPENING · ${Math.ceil(v.gate.left)}s`:'EXTRACT · COMPLETE 4 RIFTS',exit.x,exit.y-85,'#b5dfd2');}
 const h=v.players.find(p=>p.role==='hunter');if(h&&e.core.exposed>0){ring(h.x,h.y,65,'#ff9cef');label(`CORE EXPOSED · ${Math.ceil(e.core.exposed)}s`,h.x,h.y-160,'#ffc9fb');}
 for(const p of v.players){if(!p.evo)continue;const a=p.evo;if(a.component>=0)label('◆',p.x,p.y-95,'#e3baff');if(a.grab){const r=v.players.find(r=>r.id===a.grab);if(r){c.strokeStyle='#f2c194';c.lineWidth=10;c.beginPath();c.moveTo(p.x,p.y-38);c.lineTo(r.x,r.y-12);c.stroke();}}if(a.attack>0){c.strokeStyle=p.role==='hunter'?'#ffc28b':'#9ffff3';c.lineWidth=6;c.beginPath();c.arc(p.x,p.y-15,p.role==='hunter'?75:55,a.attackAim-.8,a.attackAim+.8);c.stroke();}if(a.underground||a.dig||a.emerge){ring(p.x,p.y,35+Math.sin(t*9)*6,'#bd9469');label(a.underground?'UNDERGROUND':a.emerge?'ERUPTING!':'DIGGING',p.x,p.y-22,'#e7c59a');}}

}

export function evolutionContact(c:CanvasRenderingContext2D,v:View){if(!v.evolution)return;for(const p of v.players){if(!p.evo||p.evo.echo||p.escaped||p.evo.underground)continue;const a=p.evo,color=PACKAGES[a.mutation].color;c.save();c.strokeStyle=color;c.lineWidth=2;c.globalAlpha=.75;const y=p.y-20;if(p.role==='hunter'){c.beginPath();c.moveTo(p.x-36,y-45);c.lineTo(p.x-52,y-85);c.lineTo(p.x-16,y-66);c.moveTo(p.x+36,y-45);c.lineTo(p.x+52,y-85);c.lineTo(p.x+16,y-66);c.stroke();}for(let n=0;n<a.powers.length;n++){const angle=n*Math.PI*2/6+v.tick*.012,x=p.x+Math.cos(angle)*45,z=p.y+Math.sin(angle)*19;c.fillStyle=color;c.fillRect(x-3,z-3,6,6);}if(a.powers.some(id=>['nova','cataclysm','queen','prism','tempest'].includes(id))){c.strokeStyle='#ffe3a0';c.beginPath();c.ellipse(p.x,p.y,53,25,0,0,Math.PI*2);c.stroke();}if(v.evolution.run?.sites.some(s=>s.nodes.some(n=>n.carrier===p.id))){c.fillStyle='#ffe3a0';c.fillRect(p.x-7,p.y-100,14,18);}c.restore();}for(const h of v.players){if(!h.evo?.grab)continue;const r=v.players.find(p=>p.id===h.evo!.grab);if(!r)continue;c.strokeStyle='#7b443e';c.lineWidth=12;c.lineCap='round';c.beginPath();c.moveTo(h.x+Math.cos(h.aim)*20,h.y-45);c.lineTo(r.x,r.y-12);c.stroke();c.strokeStyle='#ffdaad';c.lineWidth=3;for(let n=0;n<3;n++){c.beginPath();c.moveTo(r.x-8+n*7,r.y-16);c.lineTo(r.x-10+n*7,r.y-6);c.stroke();}c.lineCap='butt';}}
