import { useState } from 'react';
import type { Learner } from './PilotTeacher';
import { GRADE_TOPICS, gradeLabel, type LearningSettings } from '../services/game/curriculum';
import { pilotAPI } from './api';
type Change = {id:string;version:number;learning:LearningSettings;assignment:string};
export function BulkSettings({ learners, refresh, disabled }: {learners:Learner[];refresh:()=>Promise<unknown>;disabled:boolean}) {
  const [selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState('');
  const [grade,setGrade]=useState(''),[topic,setTopic]=useState(''),[challenge,setChallenge]=useState(''),[help,setHelp]=useState('');
  const [preview,setPreview]=useState<Change[]|null>(null),[undo,setUndo]=useState<Change[]|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const visible=learners.filter(l=>`${l.alias} ${l.id}`.toLowerCase().includes(search.toLowerCase()));
  const run=async(rows:Change[],isUndo=false)=>{setBusy(true);try{await pilotAPI('teacher/settings-batch','POST',{rows,requestId:crypto.randomUUID()});setUndo(isUndo?null:rows.map(r=>{const old=learners.find(l=>l.id===r.id)!;return{id:r.id,version:r.version+1,learning:old.learning,assignment:old.assignment};}));setPreview(null);await refresh();setMessage(`${rows.length} learners updated. Changes apply on their next question.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  return <section className="pilot-card" aria-label="Bulk learning settings"><h2>Change settings for a group</h2><p>Choose learners, then change only the settings you select. Their current questions and games continue.</p><fieldset disabled={disabled||busy}>
    <label>Find learners for group<input value={search} onChange={e=>setSearch(e.target.value)}/></label>
    <div className="pilot-actions"><button onClick={()=>{setSelected(visible.map(l=>l.id));setPreview(null);}}>Select visible results</button><button onClick={()=>{setSelected(learners.map(l=>l.id));setPreview(null);}}>Select entire class</button><button onClick={()=>{setSelected([]);setPreview(null);}}>Clear selection</button><strong>{selected.length} selected</strong></div>
    <div className="bulk-learners">{visible.map(l=><label key={l.id} className="pilot-check"><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>{setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id));setPreview(null);}}/>{l.alias} · {gradeLabel(l.learning.grade)}</label>)}</div>
    <div className="pilot-form-grid"><label>Group grade<select value={grade} onChange={e=>{setGrade(e.target.value);setPreview(null);}}><option value="">Keep each grade</option>{GRADE_TOPICS.map((_,i)=><option key={i} value={i}>{gradeLabel(i)}</option>)}</select></label>
    <label>Group topic<select value={topic} onChange={e=>{setTopic(e.target.value);setPreview(null);}}><option value="">Keep each topic</option><option value="mixed">Mixed practice</option>{(grade===''?Array.from(new Set(GRADE_TOPICS.flat())):GRADE_TOPICS[Number(grade)]).map(t=><option key={t}>{t}</option>)}</select></label>
    <label>Group challenge<select value={challenge} onChange={e=>{setChallenge(e.target.value);setPreview(null);}}><option value="">Keep each challenge</option>{['support','standard','stretch'].map(c=><option key={c}>{c}</option>)}</select></label>
    <label>Group hints<select value={help} onChange={e=>{setHelp(e.target.value);setPreview(null);}}><option value="">Keep each help setting</option><option value="on">On</option><option value="off">Off</option></select></label></div>
    <button disabled={!selected.length||(!grade&&!topic&&!challenge&&!help)} onClick={()=>{setMessage('');const rows=learners.filter(l=>selected.includes(l.id)).map(l=>({id:l.id,version:l.settingsVersion,assignment:l.assignment,learning:{...l.learning,...(grade!==''?{grade:Number(grade)}:{}),...(topic?{topic}:{}),...(challenge?{challenge:challenge as LearningSettings['challenge']}:{}),...(help?{learningHelp:help==='on'}:{})}}));const bad=rows.find(r=>r.learning.topic!=='mixed'&&!(GRADE_TOPICS[r.learning.grade] as readonly string[]).includes(r.learning.topic));if(bad){setMessage('A retained topic does not match the new grade. Choose Mixed practice or a matching topic.');return;}setPreview(rows);}}>Preview group changes</button>
    {preview&&<div><ul>{preview.map(r=><li key={r.id}>{learners.find(l=>l.id===r.id)?.alias}: {gradeLabel(r.learning.grade)} · {r.learning.topic} · {r.learning.challenge} · hints {r.learning.learningHelp?'on':'off'}</li>)}</ul><button className="pilot-primary" onClick={()=>void run(preview)}>Apply to {preview.length} learners</button></div>}
    {undo&&<button onClick={()=>void run(undo,true)}>Undo last group change</button>}</fieldset><p role="status">{message}</p></section>;
}
