import { useEffect, useState } from 'react';
import { startPolling } from './polling';
import type { Learner } from './PilotTeacher';
import { pilotAPI } from './api';
interface RequestRow {student_id:string;request_id:string;proposed:string;alias:string;nickname_version:number}
interface Change {id:number;old_alias:string;new_alias:string;created_at:number}
export function NicknameTools({learners,classCode,refresh,disabled}:{learners:Learner[];classCode:string;refresh:()=>Promise<unknown>;disabled:boolean}) {
  const [requests,setRequests]=useState<RequestRow[]>([]),[changes,setChanges]=useState<Change[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [chosen,setChosen]=useState(''),[name,setName]=useState('');
  const [drafts,setDrafts]=useState<Record<string,string>>({});
  const [imported,setImported]=useState<{id:string;nickname:string;version?:number}[]|null>(null);
  const load=async()=>{const d=await pilotAPI<{requests:RequestRow[];changes:Change[]}>('teacher/nicknames');setRequests(d.requests);setChanges(d.changes);};
  useEffect(()=>{let alive=true;const poll=async()=>{try{const d=await pilotAPI<{requests:RequestRow[];changes:Change[]}>('teacher/nicknames');if(alive){setRequests(d.requests);setChanges(d.changes);}}catch{/* Keep the current inbox while reconnecting. */}};const stop=startPolling(poll,15000);return()=>{alive=false;stop();};},[]);
  const run=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();await load();await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const approve=async(id:string,nickname:string,version:number,requestId?:string)=>{await pilotAPI(`teacher/students/${id}/nickname`,'POST',{nickname,version,requestId});setMessage(`Nickname approved: ${nickname}. Download a fresh roster and update your private copy on your computer.`);};
  return <section className="pilot-card" aria-label="Nicknames and roster"><h2>Nicknames & roster · {requests.length} awaiting approval</h2><p>Edit the Approved nickname column in a fresh download, or Learner account in a legacy sheet. Use nicknames only. Real names belong in your offline spreadsheet. Requested names stay private until you approve them.</p>
    <fieldset disabled={busy||disabled}>{requests.map(r=><div className="nickname-request" key={r.request_id}><strong>{r.alias} → requested: {r.proposed}</strong><label>Approved nickname for {r.alias}<input maxLength={24} value={drafts[r.request_id]??r.proposed} onChange={e=>setDrafts({...drafts,[r.request_id]:e.target.value})}/></label><button onClick={()=>void run(()=>approve(r.student_id,drafts[r.request_id]??r.proposed,r.nickname_version,r.request_id))}>Approve nickname for {r.alias}</button><button onClick={()=>void run(async()=>{await pilotAPI(`teacher/students/${r.student_id}/nickname`,'POST',{version:r.nickname_version,requestId:r.request_id,decision:'decline'});setMessage('Request declined. The current nickname stays.');})}>Decline nickname for {r.alias}</button></div>)}
    <h3>Assign or replace a nickname</h3><div className="pilot-form-grid"><label>Nickname learner<select value={chosen} onChange={e=>{setChosen(e.target.value);setName(learners.find(l=>l.id===e.target.value)?.alias??'');}}><option value="">Choose learner</option>{learners.map(l=><option key={l.id} value={l.id}>{l.alias}</option>)}</select></label><label>Teacher-approved nickname<input maxLength={24} value={name} onChange={e=>setName(e.target.value)}/></label></div><button disabled={!chosen||!name} onClick={()=>void run(()=>approve(chosen,name,learners.find(l=>l.id===chosen)!.nicknameVersion))}>Save approved nickname</button>
    <h3>Fresh Excel roster</h3><p>Downloads contain approved nicknames and account IDs, with a blank real-name column. Add real names only to your private copy on your computer. Never upload that copy. Existing secret codes are not included or changed.</p>
    <button className="pilot-primary" disabled={!learners.length} onClick={()=>void run(async()=>{const {freshNicknameRoster,downloadWorkbook}=await import('./rosterWorkbook');await downloadWorkbook(await freshNicknameRoster(learners,classCode),`vpet-nickname-roster-${new Date().toISOString().slice(0,10)}.xlsx`);setMessage('Fresh roster download prepared. Match Account IDs when updating your private offline copy. Keep a separate upload copy with the real-name column blank.');})}>Download fresh Excel roster</button>
    <label>Import teacher nicknames from Excel<input type="file" accept=".xlsx" onChange={e=>{const file=e.target.files?.[0];e.target.value='';setImported(null);if(!file)return;void run(async()=>{if(file.size>2*1024*1024)throw new Error('Choose a roster smaller than 2 MB.');const {readNicknameRoster}=await import('./rosterWorkbook');const rows=await readNicknameRoster(await file.arrayBuffer(),classCode);for(const row of rows){const l=learners.find(l=>l.id===row.id);if(!l)throw new Error('An account is not in this class. No nicknames changed.');if(row.version!==undefined&&row.version!==l.nicknameVersion)throw new Error('This roster has older nickname versions. Download a fresh roster before editing.');}setImported(rows.map(r=>({...r,version:learners.find(l=>l.id===r.id)!.nicknameVersion})));setMessage('Review these as nicknames, never real names. Approve each change below.');});}}/></label>
    {imported&&<div>{imported.map(r=><div key={r.id} className="pilot-actions"><span>{learners.find(l=>l.id===r.id)?.alias} → {r.nickname}</span><button onClick={()=>void run(async()=>{await approve(r.id,r.nickname,r.version!);setImported(current=>current?.filter(x=>x.id!==r.id)??null);})}>Approve {r.nickname}</button></div>)}<button onClick={()=>setImported(null)}>Close import preview</button></div>}</fieldset>
    <p role="status" className="pilot-message">{message}</p>
    {changes.length>0&&<details><summary>{changes.length} recent nickname changes · update your offline roster</summary><ul>{changes.map(c=><li key={c.id}>{c.old_alias} → {c.new_alias} · {new Date(c.created_at).toLocaleString()}</li>)}</ul></details>}
  </section>;
}
