import {describe,it,expect} from 'vitest';
import {createMatch,addPlayer,startMatch,step,idleInput,viewFor,type Match} from '../../model';
import {eliminate,hurt,shoot,projectiles,strike} from '../combat';
import {chooseEvolution,award,drafts} from '../state';
import {eligiblePowers} from '../catalog';
import {ensureRun,interactRift,damageRift} from '../run';
const setup=()=>{const m=createMatch('garden','normal',540,94,false,'evolution');addPlayer(m,'h','Monster','hunter');addPlayer(m,'r','Runner','runner');startMatch(m);for(const p of m.players){p.bot=false;p.evo!.starting=[];}m.time=520;ensureRun(m);return m;};
const ticks=(m:Match,n:number,id='r',extra={})=>{for(let k=0;k<n;k++)step(m,{[id]:{...idleInput(),...extra}},.05);};
describe('rebuilt Hunt lifecycle',()=>{
 it('lethal hits immediately eliminate; teammates cannot revive with interaction or healing',()=>{const m=setup(),r=m.players[1],h=m.players[0],friend=m.players[2];Object.assign(r,m.beacons[0]);Object.assign(friend,r,{id:friend.id,evo:friend.evo,role:'runner'});friend.evo!.mutation='medic';hurt(m,r,100,h);expect(r.out).toBe(true);expect(r.captured).toBe(false);expect(r.evo!.echo).toBe(true);expect(r.evo!.echoChoice).toBe(true);expect(r.check).toBeNull();ticks(m,100,friend.id,{interact:true,trap:true,gadget:true});expect(r.out).toBe(true);expect(r.evo!.hp).toBe(0);expect(r.caged).toBe(0);expect(m.message).not.toMatch(/rescue|caged/i);});
 it('defeat releases a physical grab, drops carried objectives and hides the Echo from the monster',()=>{const m=setup(),h=m.players[0],r=m.players[1],a=r.evo!;h.evo!.grab=r.id;a.grabbedBy=h.id;a.component=0;m.evolution!.core.parts[0].carrier=r.id;const node=m.evolution!.run!.sites[0].nodes[0];node.carrier=r.id;eliminate(m,r);expect(h.evo!.grab).toBeNull();expect(a.component).toBe(-1);expect(node.carrier).toBeNull();expect(viewFor(m,h.id).players.some(p=>p.id===r.id)).toBe(false);});
 it('can begin math anywhere, pause for support, retain progress and resume during closing time',()=>{const m=setup(),r=m.players[1];eliminate(m,r);expect(chooseEvolution(m,r.id,'echo-return')).toBe(true);ticks(m,1);let c=r.check!;ticks(m,1,'r',{answer:c.answer,answerFor:c.id});expect(r.evo!.returnMath!.correct).toBe(1);expect(chooseEvolution(m,r.id,'echo-support')).toBe(true);ticks(m,40);expect(r.check).toBeNull();expect(r.evo!.returnMath!.correct).toBe(1);m.time=29;m.evolution!.returnsOpen=false;expect(chooseEvolution(m,r.id,'echo-return')).toBe(true);for(let n=0;n<4;n++){ticks(m,8);c=r.check!;ticks(m,1,'r',{answer:c.answer,answerFor:c.id});}expect(r.out).toBe(false);expect(r.evo!.returns).toBe(1);eliminate(m,r);expect(chooseEvolution(m,r.id,'echo-return')).toBe(false);});
 it('does not let Echoes damage, claim rifts, or be healed back into the match',()=>{const m=setup(),r=m.players[1],s=m.evolution!.run!.sites.find(s=>s.kind==='breach')!;eliminate(m,r);Object.assign(r,{x:s.x,y:s.y});damageRift(m,r,s,100,999);expect(s.hp).toBe(160);expect(interactRift(m,r,99)).toBe(false);ticks(m,1,'r',{fire:true,trap:true,sensor:true});expect(m.bullets).toHaveLength(0);expect(r.out).toBe(true);});
});
describe('rift missions and build paths',()=>{
 it('replaces automatic beacon charging and creates deterministic varied objectives',()=>{const m=setup();expect(m.evolution!.run).toEqual(setup().evolution!.run);expect(new Set(m.evolution!.run!.sites.map(s=>s.kind)).size).toBe(3);const r=m.players[1];Object.assign(r,m.beacons[0]);r.charging=0;ticks(m,50);expect(m.beacons[0].progress).toBe(0);expect(r.check).toBeNull();});
 it('requires assault armor to break before a rift can be claimed',()=>{const m=setup(),r=m.players[1],s=m.evolution!.run!.sites.find(s=>s.kind==='breach')!;Object.assign(r,{x:s.x,y:s.y});interactRift(m,r,20);expect(s.done).toBe(false);damageRift(m,r,s,100,160);interactRift(m,r,12);expect(s.done).toBe(true);expect(m.beacons[s.id].progress).toBe(1);});
 it('salvage requires carrying both cells back, rather than holding a beacon',()=>{const m=setup(),r=m.players[1],s=m.evolution!.run!.sites.find(s=>s.kind==='salvage')!;for(const node of s.nodes){Object.assign(r,node);interactRift(m,r,.05);expect(node.carrier).toBe(r.id);expect(node.done).toBe(false);Object.assign(r,{x:s.x,y:s.y});interactRift(m,r,.05);expect(node.carrier).toBeNull();expect(node.done).toBe(true);}m.tick++;interactRift(m,r,12);expect(s.done).toBe(true);});
 it('monster sabotage is bounded and cannot undo completed rifts',()=>{const m=setup(),h=m.players[0],s=m.evolution!.run!.sites[0];s.work=10;Object.assign(h,{x:s.x,y:s.y});interactRift(m,h,3);expect(s.work).toBe(6);interactRift(m,h,30);expect(s.work).toBe(6);s.done=true;interactRift(m,h,30);expect(s.done).toBe(true);});
 it('offers only compatible powers and gates build evolutions behind their ingredients',()=>{const m=setup(),r=m.players[1];r.evo!.mutation='duelist';expect(eligiblePowers(r).some(p=>p.id==='fan-r')).toBe(false);expect(eligiblePowers(r).some(p=>p.id==='tempest')).toBe(false);r.evo!.powers=['cleave-r','wave-r'];expect(eligiblePowers(r).some(p=>p.id==='tempest')).toBe(true);drafts(m);expect(r.evo!.offers).toContain('tempest');expect(chooseEvolution(m,r.id,'tempest')).toBe(true);expect(chooseEvolution(m,r.id,'tempest')).toBe(false);});
 it('awards a bounded catch-up bonus without repeated event farming',()=>{const m=setup();m.evolution!.xp.hunter=100;award(m,'runner',20,'objective');award(m,'runner',20,'objective');expect(m.evolution!.xp.runner).toBe(25);});
 it('spread power creates a real volley and piercing/bounce state remains bounded',()=>{const m=setup(),r=m.players[1];r.evo!.powers=['fan-r','bounce-r'];shoot(m,r);expect(m.bullets).toHaveLength(3);expect(new Set(m.bullets.map(b=>`${b.vx},${b.vy}`)).size).toBe(3);expect(m.bullets.every(b=>b.ricochets===1)).toBe(true);for(let n=0;n<30;n++)projectiles(m,.05);expect(m.bullets).toHaveLength(0);});
 it('cyclone claws change a frontal swipe into an actual circular attack',()=>{const m=setup(),h=m.players[0],r=m.players[1];Object.assign(h,m.beacons[0]);Object.assign(r,{x:h.x-40,y:h.y});h.aim=0;strike(m,h,95,35);expect(r.evo!.hp).toBe(100);h.evo!.powers=['cleave'];strike(m,h,95,35);expect(r.evo!.hp).toBe(65);});
});
