import { useEffect, useState } from 'react';
import { pilotAPI } from '../../pilot/api';
import { csvValue, independent, reportCSV, type Alert, type EvidenceRecord, type InsightsData, type Intervention, type SkillSummary } from './model';
import './insights.css';
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const time=(n:number|null)=>n?new Date(n).toLocaleString():'No data yet';
const total=(rows:SkillSummary[],field:keyof Pick<SkillSummary,'attempted'|'independent'|'supported'|'laterChecks'>)=>rows.reduce((n,r)=>n+(r[field]??0),0);
const setting=(s:{grade:number;topic:string;challenge:string})=>`Grade ${s.grade} · ${s.topic==='mixed'?'Mixed practice':s.topic} · ${s.challenge}`;
export function TeacherInsights({mode,data,error,updating,days,onDays,refresh,onStudent,focusStudent='',disabled,onApplied}:{mode:'overview'|'alerts'|'reports';data:InsightsData|null;error:string;updating:boolean;days:number;onDays:(n:number)=>void;refresh:()=>Promise<InsightsData>;onStudent:(id:string)=>void;focusStudent?:string;disabled:boolean;onApplied:()=>Promise<unknown>}){
 const [filter,setFilter]=useState(focusStudent||'all'),[topic,setTopic]=useState('all'),[activity,setActivity]=useState('all'),[alertFilter,setAlertFilter]=useState('attention');
 const [eraseConfirmation,setEraseConfirmation]=useState('');
 const [pending,setPending]=useState<{alert?:Alert;change?:Intervention;requestId:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!pending)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.insights-modal');const first=dialog?.querySelector<HTMLElement>('button:not(:disabled)');first?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){e.preventDefault();setPending(null);}if(e.key==='Tab'&&dialog){const items=[...dialog.querySelectorAll<HTMLElement>('button:not(:disabled),a,input,select')].filter(e=>e.getClientRects().length);const a=items[0],z=items.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();z?.focus();}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[pending,busy]);
 const [evidence,setEvidence]=useState<EvidenceRecord[]>([]),[evidenceError,setEvidenceError]=useState('');
 useEffect(()=>{setFilter(focusStudent||'all');},[focusStudent]);
 useEffect(()=>{let active=true;setEvidence([]);setEvidenceError('');if(mode==='reports'&&filter!=='all')void pilotAPI<{rows:EvidenceRecord[]}>(`teacher/insights/evidence?student=${encodeURIComponent(filter)}&days=${days}`).then(r=>{if(active)setEvidence(r.rows);}).catch(e=>{if(active)setEvidenceError((e as Error).message);});return()=>{active=false;};},[filter,days,mode,data?.serverTime]);
 const run=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setMessage('');try{await work();await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not finish.');}finally{setBusy(false);}};
 if(!data)return <section className="pilot-card"><h2>Classroom insights</h2><p role="status">{error||'Gathering your classroom’s practice evidence…'}</p>{error&&<button onClick={()=>void refresh().catch(()=>undefined)}>Try again</button>}</section>;
 const student=data.students.find(s=>s.id===filter),skills=data.skills.filter(s=>(filter==='all'||s.studentId===filter)&&(topic==='all'||s.topic===topic));
 const attention=data.enabled?data.alerts.filter(a=>a.active&&a.status==='new'):[];
 const alerts=data.alerts.filter(a=>(filter==='all'||a.studentId===filter)&&(topic==='all'||a.topic===topic)&&(alertFilter==='all'||alertFilter==='attention'&&attention.includes(a)||a.rule===alertFilter));
 const now=data.serverTime,recent=data.students.filter(s=>s.lastSeen&&now-s.lastSeen<90000);
 const act=async()=>{if(!pending)return;await run(async()=>{if(pending.alert){const a=pending.alert;await pilotAPI('teacher/insights/apply','POST',{requestId:pending.requestId,alertId:a.id,settingsVersion:a.settingsVersion,evidenceAt:a.lastEvidenceAt,evidenceToken:a.evidenceToken});}else if(pending.change){await pilotAPI('teacher/insights/revert','POST',{requestId:pending.requestId,id:pending.change.id});}setPending(null);await onApplied();setMessage('Saved. The student receives the setting at the next question. Follow-up results will appear below.');});};
 return <section className="teacher-insights" aria-label="Teacher learning insights">
  <header className="insights-heading"><div><p className="teacher-kicker">Evidence. Support. A next step.</p><h2>{mode==='overview'?'See who needs you today.':mode==='alerts'?'A little help, at the right time.':'See learning take shape.'}</h2><p>Practice evidence guides a conversation. It is not a mastery grade.</p></div><label>Report period<select aria-label="Report period" value={days} onChange={e=>onDays(Number(e.target.value))}>{[1,7,30,90,180].map(n=><option key={n} value={n}>{n===1?'Last 24 hours':`Last ${n} days`}</option>)}</select></label></header>
  <div className="insights-live"><span className={error?'insights-stale':''}>{error?'Updates paused · showing last received data':updating?'Updating…':'Updates about every 15 seconds while this page is visible'} · Last received {time(data.serverTime)}</span><button disabled={updating} onClick={()=>void refresh().catch(()=>undefined)}>Refresh insights</button></div>
  {error&&<p role="alert">{error}</p>}{disabled&&<p className="insights-note">Save or reset your open learning edits before applying an insight.</p>}<p role="status" className="insights-message">{message}</p>
  {!data.enabled&&<p className="insights-note">Learning alerts are paused for this class. Reports still update.</p>}
  {mode==='overview'&&<>
   <div className="insights-stats"><article><span>Needs attention</span><strong>{data.enabled?attention.filter(a=>a.rule!=='stretch'&&a.rule!=='review').length:0}</strong><small>Recommendations to review</small></article><article><span>Ready for a next step</span><strong>{attention.filter(a=>['stretch','review','fresh-check'].includes(a.rule)).length}</strong><small>Challenge or independent review</small></article><article><span>Recently active</span><strong>{recent.length} / {data.students.length}</strong><small>Reported within 90 seconds</small></article><article><span>First try, without help</span><strong>{total(skills,'independent')} / {total(skills,'attempted')}</strong><small>Distinct questions attempted</small></article></div>
   <section className="pilot-card"><h3>Your next teaching steps</h3>{attention.length?attention.slice(0,5).map(a=><div className="insights-next" key={a.id}><div><strong>{a.alias} · {a.title}</strong><p>{a.explanation}</p></div><button onClick={()=>onStudent(a.studentId)}>View data for {a.alias}</button></div>):<p>{data.skills.length?'No new recommendations. Keep gathering varied practice and later independent checks.':'No recorded practice yet. Students can start with their assigned activity; older missing answers cannot be reconstructed.'}</p>}</section>
   <section className="pilot-card"><div className="insights-toolbar"><h3>Your classroom, at a glance</h3><label>Activity filter<select aria-label="Activity filter" value={activity} onChange={e=>setActivity(e.target.value)}><option value="all">All activities</option>{[...new Set(data.students.map(s=>s.activity).filter(Boolean))].map(a=><option key={a!} value={a!}>{a!.replaceAll('_',' ')}</option>)}</select></label></div><div className="insights-table"><table><caption>Recent activity and practice in the selected report period</caption><thead><tr><th>Student</th><th>Practice</th><th>First try, no help</th><th>Activity & connection</th><th>Next step</th></tr></thead><tbody>{data.students.filter(s=>activity==='all'||s.activity===activity).map(s=>{const rows=data.skills.filter(r=>r.studentId===s.id),a=attention.find(a=>a.studentId===s.id);return <tr key={s.id}><th><button onClick={()=>onStudent(s.id)}>{s.alias}</button>{!s.active&&<small>Login paused</small>}</th><td>{setting(s.learning)}</td><td>{total(rows,'independent')} / {total(rows,'attempted')}<small>{total(rows,'supported')} questions used support</small></td><td>{s.lastSeen&&now-s.lastSeen<90000?'Recently active':'Not recently reporting'}<small>{s.activity?.replaceAll('_',' ')??'No activity reported'} · Last seen {time(s.lastSeen)}</small><small>Last save {time(s.lastSaved)}</small></td><td>{a?.title??(rows.length?'Continue practice':'Gather evidence')}</td></tr>;})}</tbody></table></div></section>
  </>}
  {mode!=='overview'&&<div className="insights-toolbar"><label>Student filter<select aria-label="Student filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All students</option>{data.students.map(s=><option key={s.id} value={s.id}>{s.alias}</option>)}</select></label><label>Skill filter<select aria-label="Skill filter" value={topic} onChange={e=>setTopic(e.target.value)}><option value="all">All skills</option>{[...new Set(data.skills.map(s=>s.topic))].sort().map(t=><option key={t}>{t}</option>)}</select></label>{mode==='alerts'&&<label>Alert filter<select aria-label="Alert filter" value={alertFilter} onChange={e=>setAlertFilter(e.target.value)}><option value="attention">Needs review</option><option value="all">All alerts & history</option><option value="support">May need support</option><option value="stretch">More challenge</option><option value="check-in">Check-in</option><option value="fresh-check">Fresh check</option><option value="review">Later review</option><option value="save-help">Saving & connection</option></select></label>}</div>}
  {(mode==='alerts'||mode==='reports'&&filter!=='all')&&<section aria-label="Learning recommendations"><h3>{mode==='reports'?`Next steps for ${student?.alias??'this student'}`:'Recommendations'}</h3>{!alerts.length&&<p className="pilot-card">No alerts match this view. Small samples and older settings are not enough to recommend a difficulty change.</p>}{alerts.map(a=><article className="pilot-card insight-alert" key={a.id}><div className="insights-toolbar"><span className="insight-badge">{a.rule==='save-help'?'Connection':a.topic}</span><small>{a.active?a.status:'Resolved'} · {time(a.updatedAt)}</small></div><h3>{a.alias} · {a.title}</h3><p>{a.explanation}</p><p><strong>Suggested next step:</strong> {a.suggestion}</p><details><summary>Why this recommendation?</summary><p>{a.count} distinct attempted questions · {a.independent} first try without help · {a.support} with support. Current settings version {a.settingsVersion}. Rule {a.ruleVersion} uses pilot thresholds, not a diagnosis or mastery score.</p><p>Recent comparable practice only. Unknown settings, old settings, delayed records, and help-only records are excluded from difficulty recommendations.</p><button onClick={()=>onStudent(a.studentId)}>View data for {a.alias}</button></details><div className="pilot-actions">{a.patch&&a.active&&!['applied','dismissed','snoozed'].includes(a.status)&&<button className="pilot-primary" disabled={busy||disabled||!data.enabled} onClick={()=>setPending({alert:a,requestId:crypto.randomUUID()})}>Preview change for {a.alias}</button>}{a.active&&!['applied','dismissed'].includes(a.status)&&<>{(['reviewed','snoozed','dismissed'] as const).map((decision,i)=><button key={decision} disabled={busy} onClick={()=>void run(async()=>{await pilotAPI('teacher/insights/decision','POST',{requestId:crypto.randomUUID(),alertId:a.id,decision});setMessage(['Reviewed; settings kept.','Snoozed for one day.','Dismissed for these settings.'][i]);})}>{['Keep settings','Snooze 1 day','Dismiss'][i]}</button>)}</>}</div></article>)}</section>}
  {mode==='reports'&&<>
   <section className="pilot-card"><div className="insights-toolbar"><h3>{student?`${student.alias}’s skill evidence`:'Class skill evidence'}</h3><button disabled={!skills.length} onClick={()=>download('classroom-learning-summary.csv',reportCSV({...data,skills}))}>Export learning summary</button><button onClick={()=>window.print()}>Print report</button></div><p>Independent success: correct on the first attempt without a hint or revealed answer. Support is counted separately and can include an unfinished question. Conditions are separated by grade and challenge.</p><div className="insights-table"><table><caption>{days}-day skill report · {skills.length} skill/setting groups</caption><thead><tr>{['Student / skill','Grade / challenge','Attempted','First try, no help','Used support','Completed','Unfinished','Later checks'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{skills.map(s=><tr key={`${s.studentId}-${s.skillId}-${s.grade}-${s.challenge}`}><th>{data.students.find(p=>p.id===s.studentId)?.alias}<small>{s.topic}</small></th><td>{s.grade} / {s.challenge}{s.imported>0&&<small>{s.imported} imported records</small>}</td><td>{s.attempted}</td><td>{s.independent} / {s.attempted}</td><td>{s.supported}</td><td>{s.completed}</td><td>{s.unfinished}</td><td>{s.laterChecks??0}</td></tr>)}</tbody></table></div>{!skills.length&&<p>No evidence in this period. This is not a zero score.</p>}</section>
   {filter==='all'&&<section className="pilot-card"><h3>Class practice over time</h3><p>Independent first-try results out of attempted questions. Questions are grouped by their latest recorded update, using UTC dates. Changes in skills or challenge affect these totals.</p><div className="insights-trend">{data.trend.slice(-30).map(d=><div key={d.day}><span>{d.day}</span><meter min="0" max={Math.max(1,d.attempted)} value={d.independent} aria-label={`${d.day}: ${d.independent} independent of ${d.attempted} attempted`}/><strong>{d.independent} / {d.attempted}</strong></div>)}</div></section>}
   {filter!=='all'&&<section className="pilot-card"><h3>Question evidence</h3><p>Latest 500 question records in this period. The summary above includes all retained records, even when this list is longer than 500.</p>{evidenceError&&<p role="alert">{evidenceError}</p>}<button disabled={!evidence.length} onClick={()=>download('student-question-evidence.csv',[['Skill','Grade','Challenge','Activity','Attempts','Support','Completed','Independent','Recorded','Received','Imported'],...evidence.map(r=>[r.topic,r.grade,r.practiceSettings?.challenge??'unknown',r.source,r.attempts,r.support,r.correct,independent(r),new Date(r.eventAt).toISOString(),new Date(r.receivedAt).toISOString(),r.imported])].map(r=>r.map(csvValue).join(',')).join('\r\n'))}>Export these question records</button><div className="insights-table insights-evidence"><table><thead><tr><th>When / skill</th><th>Activity</th><th>Attempts</th><th>Support</th><th>Outcome</th></tr></thead><tbody>{evidence.map(r=><tr key={r.questionId}><th>{r.topic}<small>{time(r.eventAt)} · {r.imported?'Imported history':r.receivedAt-r.eventAt>300000?'Delayed record':'Received promptly'}</small></th><td>{r.source}</td><td>{r.attempts}</td><td>{r.answerRevealed?'Answer explained':r.support}</td><td>{independent(r)?'First try without help':r.correct?'Completed with practice':r.attempts?'Unfinished':'Help only'}</td></tr>)}</tbody></table></div></section>}
  </>}
  {mode!=='overview'&&<section className="pilot-card"><h3>Changes and follow-up</h3><p>New practice after a change appears here. Different challenge settings are different conditions; this does not establish what caused a result.</p>{data.interventions.filter(c=>filter==='all'||c.studentId===filter).map(c=><article className="insights-change" key={c.id}><strong>{c.alias} · {c.kind==='revert'?'Setting restored':'Teacher-approved change'}</strong><small>{time(c.createdAt)}</small><p>{setting(c.before)} → {setting(c.after)}</p>{c.recommendation&&<p>Before: {c.recommendation.independent} / {c.recommendation.count} independent. Reason: {c.recommendation.title}.</p>}<p>After: {c.followup.independent} / {c.followup.attempted} first try without help · {c.followup.supported} used support. {c.followup.attempted<8?'Gather more evidence before judging this change.':'Review the student’s new work before another adjustment.'}</p>{c.kind==='apply'&&!c.revertedBy&&<button disabled={busy||disabled||data.students.find(s=>s.id===c.studentId)?.settingsVersion!==c.appliedVersion} onClick={()=>setPending({change:c,requestId:crypto.randomUUID()})}>Preview undo for {c.alias}</button>}{c.revertedBy&&<small>Reverted</small>}</article>)}{!data.interventions.length&&<p>No recommendation changes yet.</p>}</section>}
  {mode==='reports'&&<details className="pilot-card"><summary>All saved setting changes</summary><p>Includes direct teacher edits as well as recommendations. The first entry for a student may be an imported baseline. Latest 200 class changes.</p>{data.settingsChanges.filter(c=>filter==='all'||c.studentId===filter).map(c=><div className="insights-change" key={`${c.studentId}-${c.version}`}><strong>{c.alias} · version {c.version}</strong><small>{time(c.changedAt)}</small><p>{setting(c.learning)} · Activity: {c.assignment}</p></div>)}</details>}
  <details className="pilot-card"><summary>Data coverage, retention & alert settings</summary><p>Extended history began {time(data.historySince)}. Only existing question records could be imported; missing older answers cannot be reconstructed. Extended question snapshots are retained for {data.retentionDays} days; existing game saves keep up to 200 recent question records; teacher decisions and changes for one year. Activity coverage depends on recorded questions, not time spent playing.</p><p>Practice is student-app reported, not a proctored assessment. Presence means the app reported recently; it does not measure attention. We do not infer ability, emotions, or diagnoses from speed or pauses.</p><p>Difficulty suggestions need at least 8 attempted questions for support, or 12 with at least 90% independent success across two practice periods and two templates for more challenge. Three unresolved questions after retries can prompt a check-in. Changes remain teacher-approved.</p><button disabled={busy} onClick={()=>void run(()=>pilotAPI('teacher/insights/policy','POST',{enabled:!data.enabled}))}>{data.enabled?'Pause learning alerts':'Resume learning alerts'}</button>{filter!=='all'&&<details><summary>Delete this student’s stored practice history</summary><p>Removes insight question history, alerts, and intervention records for {student?.alias}. The game, pet, login, and current learning settings stay in place. Recent practice can still exist in the game save and its recovery copies, but it will not be imported into insights again. New practice starts a fresh insight history.</p><label>Type DELETE to confirm<input value={eraseConfirmation} onChange={e=>setEraseConfirmation(e.target.value)}/></label><button disabled={busy||eraseConfirmation!=='DELETE'} onClick={()=>void run(async()=>{await pilotAPI('teacher/insights/erase','POST',{studentId:filter,confirm:'DELETE_PRACTICE_HISTORY'});setEraseConfirmation('');setMessage('Stored insight history deleted. New practice will create new records.');})}>Delete insight history</button></details>}</details>
  {pending&&<div className="insights-modal" role="dialog" aria-modal="true" aria-label="Preview learning adjustment"><section className="pilot-card"><h2>Review this teaching step</h2>{pending.alert?(()=>{const a=pending.alert!,s=data.students.find(s=>s.id===a.studentId);return <><p><strong>{a.alias}</strong> · {a.explanation}</p><p>Before: {s?setting(s.learning):'Unavailable'}</p><p>After: {s?setting({...s.learning,...a.patch}):'Unavailable'}</p><p>{a.suggestion}</p></>;})():<><p>Restore {pending.change?.alias}’s earlier setting:</p><p>{pending.change&&setting(pending.change.before)}</p></>}<p>This applies at the next question. The student’s pet and saved progress stay in place. New evidence or settings changes require a new preview.</p><p role="status">{message}</p><div className="pilot-actions"><button className="pilot-primary" disabled={busy||disabled} onClick={()=>void act()}>{busy?'Saving…':'Apply this change'}</button><button disabled={busy} onClick={()=>setPending(null)}>Cancel</button></div></section></div>}
 </section>;
}
