import {MathPowerPanel} from './MathPowerPanel';
import type {MathPowerCommand} from './mathPower';
import {useRef,useState} from 'react';
import type {EngineState} from '../../types/engine';
import type {GameEngineAction} from '../../engine/core/ActionTypes';
import {PetSprite} from '../../components/pet/PetSprite';
import {getXPForLevel} from '../../services/game/evolutionEngine';
import {GEAR,gear,BRANCHES,TALENTS,MILESTONES,pointsAt,slotsAt,AREAS,ENCOUNTERS,PERKS,type Branch,type Move} from './catalog';
import {arenaOf,buildOf,command,type ArenaCommand} from './model';
import {signatureCost,canMove,TRAITS,traitFor,type Fight} from './combat';
import {ArenaClassroom} from './ArenaClassroom';
import {BattleStage} from './BattleStage';
import {useReducedMotion} from '../../hooks/useReducedMotion';
import './arena.css';
export interface ArenaProps{state:EngineState;dispatch:(a:GameEngineAction)=>void;execute?:(c:ArenaCommand)=>Promise<void>}
const titles:Record<Move,string>={strike:'Strike',guard:'Guard',focus:'Focus',signature:'Signature',item:'Item'};
const intentText:Record<Move,string>={strike:'Strike · incoming attack',guard:'Guard · blocks half a hit',focus:'Focus · prepares energy',signature:'Big attack · guard or shield!',item:'Healing · time to attack'};
export function Arena({state,dispatch,execute}:ArenaProps){
 const [tab,setTab]=useState('adventure'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[practice,setPractice]=useState<Branch>('guardian');
 const lock=useRef(false),pet=state.pet,a=arenaOf(state),build=buildOf(state);
 const executeCommand=async(c:ArenaCommand)=>{if(execute)await execute(c);else{command(state,c);dispatch({type:'ARENA_COMMAND',command:c});}};
 const run=async(c:ArenaCommand)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await executeCommand(c);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 if(!pet)return <main className="arena"><h1>Your companion’s adventure</h1><p>Hatch your earned pet to begin.</p><button onClick={()=>dispatch({type:'SET_SCREEN',screen:'incubation'})}>Visit my egg</button></main>;
 const points=pointsAt(pet.progression.level),spent=Object.values(build.talents).reduce((n,v)=>n+v,0),nextPoint=MILESTONES.find(n=>n>pet.progression.level),levelUp=pet.progression.level>(a.seenLevel[pet.id]??1);
 return <main className="arena" aria-busy={busy}>
 <header className="arena-header"><div><span className="arena-kicker">COMPANION CHRONICLES</span><h1>Pet Battle</h1><p>Your pet. Your build. Your next adventure.</p></div><button onClick={()=>dispatch({type:'SET_SCREEN',screen:'play'})}>← Games</button></header>
 {error&&<p role="alert" className="arena-error">{error}</p>}
 {levelUp&&!a.fight&&<section className="arena-level" role="status"><strong>✦ Level {pet.progression.level}, {pet.name}!</strong><span>{points-spent} talent points ready · {pet.progression.level>=5?'All gear slots unlocked':pet.progression.level>=3?'Battle item slot unlocked':pet.progression.level>=2?'Charm slot unlocked':'Starter kit ready'}</span><button disabled={busy} onClick={()=>{void run({kind:'acknowledge'});setTab('talents');}}>See my upgrades</button></section>}
 {a.fight?<CombatView key={a.fight.id} onMath={async c=>{if(lock.current)throw Error('Wait for your current move.');lock.current=true;setBusy(true);try{await executeCommand(c);}finally{lock.current=false;setBusy(false);}}} fight={a.fight} busy={busy} onMove={move=>void run({kind:'move',move,fightId:a.fight!.id,round:a.fight!.round})} onLeave={()=>void run({kind:'retreat'})} onClose={()=>void run({kind:'close'})} expedition={!!a.expedition?.choosing} onPerk={(perk,route)=>void run({kind:'perk',perk,route})}/>:<>
 <section className="arena-profile"><div className="arena-pet"><PetSprite speciesId={pet.speciesId} stage={pet.stage} animationName="happy" scale={1.1}/></div><div><span className="arena-kicker">YOUR EARNED COMPANION</span><h2>{pet.name} <small>Lv. {pet.progression.level}</small></h2><p>{TRAITS[traitFor(pet.speciesId)]}</p>{a.expeditions>0&&<span className="arena-achievement">✦ Trailblazer</span>}{a.challenges.length===3&&<span className="arena-achievement">♛ Crown Champion</span>}<progress aria-label="Pet experience" max={getXPForLevel(pet.progression.level)} value={pet.progression.xp}/><p>{pet.progression.xp} / {getXPForLevel(pet.progression.level)} XP · {nextPoint?`Next talent at level ${nextPoint}`:'All 6 talent points unlocked'}</p></div><div className="arena-loadout">{(['charm','badge','tool'] as const).map(slot=><div key={slot}><span>{gear(build[slot])?.icon??'◇'}</span><strong>{gear(build[slot])?.name??`Empty ${slot}`}</strong><small>{slot==='charm'&&pet.progression.level<2?'Unlocks at level 2':slot==='badge'&&pet.progression.level<5?'Unlocks at level 5':slot==='tool'&&pet.progression.level<3?'Starter snack · more tools at level 3':slot}</small></div>)}</div></section>
 <nav className="arena-tabs" aria-label="Battle preparation">{[['adventure','Adventure'],['talents',`Talents · ${points-spent}`],['equipment','Equipment'],['practice','Training'],...(execute?[['classroom','Class battles']]:[]),['guide','How to play']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <p className="arena-notice" role="status">{a.notice}</p>
 {tab==='adventure'&&<><div className="arena-areas">{AREAS.map((area,i)=><section key={area.name} className={`arena-area arena-area-${i}`}><span className="arena-kicker">CHAPTER {i+1}</span><h2>{area.name}</h2><p>{area.text}</p><div>{ENCOUNTERS.filter(e=>e.area===i).map(e=>{const unlocked=e.id===0||a.cleared.includes(e.id-1);return <button disabled={busy||!unlocked} key={e.id} onClick={()=>void run({kind:'start',mode:'campaign',encounter:e.id})}><span>{a.cleared.includes(e.id)?'✓':e.boss?'♛':'⚔'}</span><span><strong>{e.name}</strong><small>{unlocked?`Level ${e.level} · ${e.boss?'Boss':e.style}`:'Win the previous encounter'}</small></span><b>→</b></button>;})}</div></section>)}</div><div className="arena-grid"><section className="arena-card"><h2>Five-fight expedition</h2><p>Choose routes and perks between fights. Your pet and equipment stay yours.</p><p>{a.expeditions} expeditions completed</p><button disabled={busy||!a.cleared.includes(4)} onClick={()=>void run({kind:'start',mode:'expedition',encounter:0})}>{a.cleared.includes(4)?'Begin expedition':'Defeat the Old Oak to unlock'}</button></section><section className="arena-card"><h2>Champion challenges</h2><p>Three permanent challenges. Level 20 opponents, changing boss phases, mastery titles.</p>{['Iron Guard','Burning Rhythm','Deep Focus'].map((name,i)=><button key={name} disabled={busy||!a.cleared.includes(14)} onClick={()=>void run({kind:'start',mode:'challenge',encounter:i})}>{name}</button>)}{a.challenges.length>0&&<p>✦ Champion · {a.challenges.length}/3 challenges mastered</p>}</section></div></>}
 {tab==='talents'&&<><div className="arena-section-head"><div><h2>Choose how your pet fights</h2><p>{spent} / {points} points used. Mix branches; reset for free.</p></div><button disabled={busy||!spent} onClick={()=>void run({kind:'reset'})}>Reset talents</button></div><div className="arena-trees">{BRANCHES.map(branch=><section className={`arena-tree ${branch}`} key={branch}><h2>{TALENTS[branch].name}</h2><button disabled={busy} onClick={()=>void run({kind:'preset',branch})}>Use recommended build</button>{TALENTS[branch].nodes.map((n,i)=><button className="arena-node" key={n.name} disabled={busy||i!==build.talents[branch]||spent>=points} data-learned={i<build.talents[branch]} onClick={()=>void run({kind:'talent',branch})}><span>{i<build.talents[branch]?'✓':i+1}</span><strong>{n.name}</strong><small>{n.text}</small></button>)}</section>)}</div><div className="arena-card"><h3>Saved builds</h3>{Array.from({length:slotsAt(pet.progression.level)},(_,slot)=><span className="arena-preset" key={slot}><button disabled={busy} onClick={()=>void run({kind:'saveBuild',slot})}>Save build {slot+1}</button><button disabled={busy||!a.pets[pet.id]?.presets[slot]} onClick={()=>void run({kind:'loadBuild',slot})}>Load {slot+1}</button></span>)}<p>Second slot at level 12 · third at level 16</p></div></>}
 {tab==='equipment'&&<><div className="arena-section-head"><div><h2>Math makes your kit grow</h2><p><strong>{state.player.currencies.mp} MP</strong> · Permanent unlocks · tools recharge each battle</p></div><button onClick={()=>dispatch({type:'SET_SCREEN',screen:'math'})}>Earn MP in math →</button></div>{(['charm','badge','tool'] as const).map(slot=><section key={slot}><h3>{slot==='charm'?'Charms · level 2':slot==='badge'?'Badges · level 5':'Battle tools · level 3'}</h3><div className="arena-gear">{GEAR.filter(g=>g.slot===slot).map(g=>{const owned=a.owned.includes(g.id),equipped=build[slot]===g.id,locked=pet.progression.level<(slot==='charm'?2:slot==='badge'?5:3);return <article className="arena-card" key={g.id}><span className="arena-item-icon">{g.icon}</span><h3>{g.name}</h3><p>{g.text}</p>{!owned&&<small>{Math.max(0,g.price-state.player.currencies.mp)} MP to go · about {Math.ceil(Math.max(0,g.price-state.player.currencies.mp)/2)} completed questions</small>}<button disabled={busy||equipped||owned&&locked||!owned&&state.player.currencies.mp<g.price} onClick={()=>void run({kind:owned?'equip':'buy',id:g.id})}>{equipped?'Equipped':owned?locked?'Slot locked':'Equip':`Unlock · ${g.price} MP`}</button></article>;})}</div></section>)}<p>Existing Forge upgrades remain available for classic battles. Here, attack and defence training contribute at most +3 attack total; math-prep and prize boosts stay saved for classic battles.</p></>}
 {tab==='practice'&&<section className="arena-card"><h2>Try every build</h2><p>Loan equipment and all six talent points. Level 10 training, no rewards or item costs. Your earned pet stays the star.</p><button onClick={()=>dispatch({type:'START_BATTLE'})}>Classic battle & tracing</button><label>Build <select aria-label="Practice build" value={practice} onChange={e=>setPractice(e.target.value as Branch)}>{BRANCHES.map(b=><option key={b} value={b}>{TALENTS[b].name}</option>)}</select></label><div className="arena-grid">{ENCOUNTERS.slice(0,5).map(e=><button key={e.id} disabled={busy} onClick={()=>void run({kind:'start',mode:'practice',encounter:e.id,branch:practice})}>{e.name}<small>{e.hint}</small></button>)}</div></section>}
 {tab==='classroom'&&execute&&<ArenaClassroom prepare={async()=>{await execute({kind:'init'});}}/>}
 {tab==='guide'&&<Guide/>}
 </>}
 </main>;
}
export function CombatView({fight:f,busy,onMove,onLeave,onClose,expedition,onPerk,opponentLabel,onMath}:{fight:Fight;busy:boolean;onMove:(m:Move)=>void;onLeave:()=>void;onClose:()=>void;expedition?:boolean;onPerk?:(p:typeof PERKS[number]['id'],route:number)=>void;opponentLabel?:string;onMath?:(c:MathPowerCommand)=>Promise<void>}){
 const [route,setRoute]=useState(0),[playing,setPlaying]=useState(false),[mathOpen,setMathOpen]=useState(false),[traceMissed,setTraceMissed]=useState(false),done=f.phase!=='active';
 // The stage replays a turn from the fight state it was showing before, so HP drains hit by hit.
 const [frames,setFrames]=useState<{current:Fight;previous:Fight|null}>({current:f,previous:null});
 if(frames.current!==f)setFrames({current:f,previous:frames.current.id===f.id?frames.current:null});
 const previous=frames.previous;
 const reduced=useReducedMotion();
 const said=f.events.map(e=>e.text).join(' · ');
 return <section className={`arena-combat arena-area-${Math.floor(f.encounter/5)}`}><div className="arena-combat-top"><span>{f.mode.toUpperCase()} · Turn {f.round}/20{f.boss?' · BOSS':''}</span><button disabled={busy} onClick={onLeave}>Leave battle</button></div>
 <div className="arena-battlefield"><BattleStage fight={f} previous={previous} reduced={reduced} onPlaying={setPlaying} turnReady={!busy&&!playing&&!mathOpen} intent={done?undefined:{text:opponentLabel??`Next: ${intentText[f.intent]}`,big:f.intent==='signature'}}/>
 {mathOpen&&!done&&onMath&&<MathPowerPanel key={`${f.id}:${f.mathPower?.used}`} fight={f} busy={busy} execute={onMath} close={(expired=false)=>{setMathOpen(false);setTraceMissed(expired);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('.arena-math-bar button')?.focus({preventScroll:true}));}}/>}</div>
 <p className="arena-event" aria-live="polite">{done?(f.phase==='won'?'Victory! Your progress is saved.':f.phase==='lost'?'Your pet needs a breather. Your progress is saved.':'Battle drawn. Your progress is saved.'):said||ENCOUNTERS[f.encounter]?.hint}</p>
 {!done&&<div className="arena-actions">{(['strike','guard','focus','signature','item'] as Move[]).map(m=><button key={m} disabled={busy||playing||(mathOpen&&!!f.mathPower?.challenge?.solved)||!canMove(f.fighters[0],m)} onClick={()=>{setMathOpen(false);onMove(m);}}><strong>{m==='item'?gear(f.fighters[0].build.tool)?.name:titles[m]}</strong><small>{m==='strike'?'+7 energy':m==='guard'?'Block 50% · +4 energy':m==='focus'?'+18 energy':m==='signature'?`${signatureCost(f.fighters[0])} energy`:f.fighters[0].used.includes('tool')?'Used this battle':'One use · spends turn'}</small></button>)}</div>}
 {!done&&onMath&&f.mathPower&&<div className="arena-math-bar"><button disabled={busy||playing||f.mathPower.used>=2||f.mathPower.lastRound===f.round} onClick={()=>{setTraceMissed(false);document.querySelector('.arena-battlefield')?.scrollIntoView({block:'center',behavior:'instant'});setMathOpen(true);}}>✦ {f.mathPower.challenge?'Resume Math Power':'Math Power'} · {2-f.mathPower.used} uses</button><p>{f.fighters[0].mathStrike?<span className="arena-math-ready">Power Strike ready for your next attack.</span>:f.mathPower.lastRound===f.round?'Power activated! Choose your battle move.':traceMissed?'Trace window closed. Answer saved — resume anytime; no use spent.':'Quick math → 6-second trace → power up. Two boosts per battle; no turn spent.'}</p></div>}
 {done&&<section className="arena-results"><h2>{f.phase==='won'?'A well-earned victory':f.phase==='lost'?'Try a different approach':'Evenly matched'}</h2><p>{f.fighters[0].blocked} damage blocked · {f.fighters[0].dealt} dealt · {f.fighters[0].healed} HP restored</p>{!!f.mathPower?.used&&<p>✦ {f.mathPower.used} Math Powers activated: {f.mathPower.activations.map(a=>a.power==='strike'?'Power Strike':a.power==='shield'?'Number Shield':'Energy Spark').join(', ')}. See the battle log for their effects.</p>}{f.result&&<><strong>+{f.result.xp} pet XP{f.result.first?' · First-clear bonus included':''}</strong>{f.result.levelAfter>f.result.levelBefore&&<p className="arena-level">✦ Level {f.result.levelBefore} → {f.result.levelAfter}! Max HP +{Math.max(0,Math.min(20,f.result.levelAfter)-Math.min(20,f.result.levelBefore))*5}. New talent milestones are ready.</p>}</>}{expedition?<><h3>Choose the next route</h3><button aria-pressed={route===0} onClick={()=>setRoute(0)}>Woodland route · steady challenge</button><button aria-pressed={route===1} onClick={()=>setRoute(1)}>High road · stronger opponent</button><h3>Choose one perk for this expedition</h3>{PERKS.map(p=><button key={p.id} disabled={busy} onClick={()=>onPerk?.(p.id,route)}><strong>{p.name}</strong><small>{p.text}</small></button>)}</>:<button disabled={busy} onClick={onClose}>Back to my build</button>}</section>}
 <details className="arena-log"><summary>Battle log · what happened</summary><ol>{f.history.map((e,i)=><li key={i}>{e.text}</li>)}</ol></details></section>;
}
export function Guide(){return <section className="arena-guide"><h2>Make your pet’s powers work together</h2><p><strong>Math Power:</strong> twice per solo battle, solve an assigned question and trace one digit in a six-second battlefield pop-up for extra damage, shield or energy. Activate without drawing for the same benefit. Tracing activates automatically. Untimed tracing, help and retries are available; a missed trace spends no use. One power per turn; your normal move stays ready.</p><p>Defeat the opponent before your pet runs out of HP. Read its next move, protect yourself from big attacks, and choose when to spend energy. A draw happens after 20 turns. Your pet, levels and equipment are always kept.</p><div className="arena-grid">{BRANCHES.map(branch=><article className="arena-card" key={branch}><h3>{TALENTS[branch].name}</h3><video controls preload="none" poster={`/assets/pet-arena-guide/${branch}.jpg`}><source src={`/assets/pet-arena-guide/${branch}.webm`} type="video/webm"/><track kind="captions" src={`/assets/pet-arena-guide/${branch}.vtt`} srcLang="en" label="English" default/></video><p>{branch==='guardian'?'Watch for a big attack. Guard it, then Strike with Counter Ready.':branch==='striker'?'Alternate Strike and Signature. At three Combo, use Signature to break through Guard.':'Focus to gain energy and a shield. Follow with Signature to Weaken the enemy.'}</p><details><summary>Read the guide</summary><p>{TALENTS[branch].nodes.map(n=>`${n.name}: ${n.text}`).join(' ')}</p><p>Unlock equipment using MP earned in math practice. Equip one charm, one badge and one tool. Tools recharge between battles. Try all three builds free in Training.</p></details></article>)}</div><p>Reset talents freely between battles. Equipment and the pet you earned stay yours. Use Aa to enlarge text, buttons and panels.</p></section>;}
