import {useCallback,useEffect,useState} from 'react';
import {pilotAPI} from '../../pilot/api';
import {startPolling} from '../../pilot/polling';
import {BattlePetSprite} from '../../components/battle/BattleEffects';
import {BRANCHES,TALENTS,GEAR,ACTIONS,type Move} from './catalog';
import {preset,canMove,type Build} from './combat';
import type {ClassroomArenaData} from './multiplayer';
import './arena.css';
export function ArenaClassroom({prepare,teacher=false}:{prepare?:()=>Promise<void>;teacher?:boolean}){
 const [data,setData]=useState<ClassroomArenaData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[build,setBuild]=useState<Build>(()=>preset('guardian'));
 const refresh=useCallback(async()=>{setData(await pilotAPI<ClassroomArenaData>('arena-rooms'));},[]);
 useEffect(()=>startPolling(()=>refresh().catch(e=>setError((e as Error).message)),3000),[refresh]);
 const act=async(body:Record<string,unknown>)=>{if(busy)return;setBusy(true);setError('');try{if(['create','join','ready'].includes(String(body.kind)))await prepare?.();await pilotAPI('arena-rooms','POST',body);await refresh();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setBusy(false);}};
 if(!data)return <section className="arena arena-card"><h2>Class Battle Arena</h2><p role="status">{error||'Opening your classroom…'}</p><button onClick={()=>void refresh().catch(e=>setError(e.message))}>Retry</button></section>;
 const rooms=data.rooms.filter(r=>r.phase!=='finished'),recent=data.rooms.filter(r=>r.phase==='finished').slice(0,3);
 return <section className="arena arena-classroom"><div className="arena-section-head"><div><span className="arena-kicker">PLAY TOGETHER</span><h2>Class Battle Arena</h2><p>Fair level 10 battles · six talents · all gear available on loan · no stakes</p></div>{teacher&&<button disabled={busy} onClick={()=>void act({kind:'create',mode:'raid'})}>Start a teacher team challenge</button>}</div>
 {error&&<p role="alert" className="arena-error">{error}</p>}
 {!teacher&&!rooms.some(r=>r.members.some(m=>m.id===data.you))&&<div className="arena-grid">{data.learners.filter(l=>l.id!==data.you).map(l=><button key={l.id} disabled={busy} onClick={()=>void act({kind:'create',mode:'duel',opponent:l.id})}>Invite {l.alias}<small>{l.pet}</small></button>)}{data.learners.length<2&&<p>A classmate needs an earned pet before you can invite them.</p>}</div>}
 {rooms.map(r=>{const mine=r.members.find(m=>m.id===data.you),host=teacher&&r.host===data.you,canAct=!!mine||host,f=mine?.fighter??r.boss,send=(kind:string,extra:Record<string,unknown>={})=>void act({id:r.id,revision:r.revision,kind,...extra});return <article className="arena-card" key={r.id}><div className="arena-section-head"><h3>{r.mode==='raid'?'Class vs Teacher Guardian':'Pet duel'} · {r.phase==='lobby'?'Build preparation':`Turn ${r.round}/20`}</h3><span>{r.paused?'Paused by teacher':''}</span></div>
 {r.phase==='lobby'&&<><p>{r.message}</p>{!mine&&!teacher&&r.mode==='raid'&&<button disabled={busy} onClick={()=>send('join')}>Join with my pet</button>}{mine&&<><div className="arena-grid">{BRANCHES.map(b=><button key={b} onClick={()=>setBuild(preset(b))}>{TALENTS[b].name} build</button>)}</div><p>Customise your loan build · {6-Object.values(build.talents).reduce((n,v)=>n+v,0)} points left</p><div className="arena-grid">{BRANCHES.map(branch=><label key={branch}>{TALENTS[branch].name}<select value={build.talents[branch]} onChange={e=>{const value=Number(e.target.value);if(Object.entries(build.talents).reduce((n,[k,v])=>n+(k===branch?value:v),0)<=6)setBuild({...build,talents:{...build.talents,[branch]:value}});}}>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n} talents</option>)}</select><small>{TALENTS[branch].nodes.slice(0,build.talents[branch]).map(n=>n.name).join(' · ')}</small></label>)}</div><div className="arena-grid">{(['charm','badge','tool'] as const).map(slot=><label key={slot}>{slot}<select value={build[slot]??''} onChange={e=>setBuild({...build,[slot]:e.target.value||null})}>{slot!=='tool'&&<option value="">None</option>}{GEAR.filter(g=>g.slot===slot).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><small>{GEAR.find(g=>g.id===build[slot])?.text}</small></label>)}</div><button disabled={busy} onClick={()=>send('ready',{build})}>{mine.ready?'Update ready build':'Ready with this build'}</button></>}
 <p>{r.members.map(m=>`${m.alias}: ${m.ready?'ready':'choosing'}`).join(' · ')||'Waiting for students to join.'}</p>{canAct&&(r.mode==='duel'||host)&&<button disabled={busy||!r.members.length||r.members.some(m=>!m.ready)} onClick={()=>send('start')}>Start battle</button>}</>}
 {r.phase==='active'&&<><div className="arena-grid">{r.members.map(m=><div className="arena-fighter" key={m.id}><strong>{m.alias} · {m.fighter.name}</strong><BattlePetSprite speciesId={m.fighter.species}/><progress aria-label={`${m.alias} HP`} value={m.fighter.hp} max={m.fighter.maxHP}/><small>{m.fighter.hp}/{m.fighter.maxHP} HP · {m.fighter.energy} energy · {m.fighter.shield} shield</small><p>{r.choices[m.id]?'Move locked in':m.fighter.hp<=0?'Cheering the team':'Choosing a move'}</p></div>)}{r.boss&&<div className="arena-fighter"><strong>{r.boss.name}</strong><BattlePetSprite speciesId={r.boss.species}/><progress aria-label="Guardian HP" value={r.boss.hp} max={r.boss.maxHP}/><p>{r.boss.hp}/{r.boss.maxHP} HP · {r.boss.energy} energy</p></div>}</div>
 {canAct&&f&&f.hp>0&&<><p>{r.choices[data.you]?`Your ${r.choices[data.you]} is locked. Waiting for the round.`:'Choose one action. Your opponent cannot see it until the round resolves.'}</p><div className="arena-actions">{ACTIONS.map(move=><button key={move} disabled={busy||r.paused||!!r.choices[data.you]||!canMove(f,move)} onClick={()=>send('move',{move:move as Move,round:r.round})}>{move==='item'?GEAR.find(g=>g.id===f.build.tool)?.name:move}<small>{move==='signature'?'20 energy · 15 after trained Focus':move==='item'?'Once this battle':'Takes one turn'}</small></button>)}</div></>}
 {host&&<button disabled={busy||r.paused} onClick={()=>send('resolve')}>Resolve team turn · unanswered pets Guard</button>}
 <details><summary>Round results</summary><ul>{r.events.map((e,i)=><li key={i}>{e.text}</li>)}</ul></details></>}
 {teacher&&<button disabled={busy} onClick={()=>send('pause')}>{r.paused?'Resume':'Pause'}</button>}{(canAct||teacher)&&<button disabled={busy} onClick={()=>send('end')}>{teacher?'End match':'Leave match'}</button>}</article>;})}
 {recent.map(r=><p className="arena-notice" key={r.id}>{r.message} {r.winner==='class'?'The class won!':r.winner===data.you?'You won!':r.winner?r.members.find(m=>m.id===r.winner)?.alias??'The guardian won.':'Draw or match ended.'}</p>)}
 </section>;
}
