import {describe,it,expect} from 'vitest';
import {createInitialEngineState} from '../../engine/state/createInitialEngineState';
const freshGame=(_id:string,_alias:string)=>createInitialEngineState();
import {hatchEgg} from '../../services/game/evolutionEngine';
import {command,buildOf,validArena,arenaOf} from './model';
import {createFight,preset,turn,perform,fighter,emptyBuild,type Fight} from './combat';
import {GEAR,ENCOUNTERS,pointsAt,BRANCHES} from './catalog';
import {roomAction,roomView,resolveRoom,type ArenaRoom} from './multiplayer';
function state(level=16){const s=freshGame('p','Learner');s.pet=hatchEgg({id:'egg',type:'koala',state:'ready',progress:100,createdAt:new Date().toISOString()})!;s.pet.id='test-pet';s.pet.progression.level=level;s.player.currencies.mp=500;return s;}
function policy(f:Fight):'strike'|'signature'|'guard'|'focus'|'item'{const p=f.fighters[0],b=p.build.talents;if(p.hp<p.maxHP*.4&&!p.used.includes('tool'))return 'item';if(b.guardian===4&&f.intent==='signature')return 'guard';if(p.counter)return 'strike';if(b.tactician>=3&&!p.focused)return 'focus';if(p.energy>=20&&(b.striker===0||p.lastAttack==='strike'))return 'signature';if(p.energy<15)return 'focus';return 'strike';}
describe('Pet Battle progression and possessions',()=>{
 it('uses the earned pet and never mutates source saves',()=>{const s=state(),raw=JSON.stringify(s),n=command(s,{kind:'init'});expect(n.pet?.id).toBe(s.pet?.id);expect(JSON.stringify(s)).toBe(raw);expect(validArena(n.petArena)).toBe(true);});
 it('charges MP once and enforces ownership and levels',()=>{let s=state(1);expect(()=>command(s,{kind:'equip',id:'mirror'})).toThrow();s=command(s,{kind:'buy',id:'mirror'});expect(s.player.currencies.mp).toBe(490);expect(()=>command(s,{kind:'buy',id:'mirror'})).toThrow();expect(()=>command(s,{kind:'equip',id:'mirror'})).toThrow();s.pet!.progression.level=2;s=command(s,{kind:'equip',id:'mirror'});expect(buildOf(s).charm).toBe('mirror');});
 it('limits points, refunds freely and saves independent loadouts',()=>{let s=state();for(let i=0;i<4;i++)s=command(s,{kind:'talent',branch:'guardian'});for(let i=0;i<2;i++)s=command(s,{kind:'talent',branch:'striker'});expect(()=>command(s,{kind:'talent',branch:'tactician'})).toThrow();s=command(s,{kind:'saveBuild',slot:2});s=command(s,{kind:'reset'});expect(buildOf(s).talents.guardian).toBe(0);s=command(s,{kind:'loadBuild',slot:2});expect(buildOf(s).talents.guardian).toBe(4);expect(pointsAt(100)).toBe(6);});
 it('locks loadouts during combat and guards against replayed turns',()=>{let s=command(state(),{kind:'start',mode:'campaign',encounter:0});const f=s.petArena!.fight!;expect(()=>command(s,{kind:'buy',id:'mirror'})).toThrow();s=command(s,{kind:'move',move:'strike',fightId:f.id,round:1});expect(()=>command(s,{kind:'move',move:'strike',fightId:f.id,round:1})).toThrow();});
 it('awards real XP exactly once and unlocks campaign in order',()=>{let s=command(state(),{kind:'start',mode:'campaign',encounter:0});expect(()=>command(state(),{kind:'start',mode:'campaign',encounter:3})).toThrow();while(s.petArena!.fight!.phase==='active'){const f=s.petArena!.fight!;s=command(s,{kind:'move',move:policy(f),fightId:f.id,round:f.round});}expect(s.petArena!.fight!.phase).toBe('won');const xp=s.pet!.progression.xp;expect(xp).toBeGreaterThan(0);expect(s.petArena!.cleared).toContain(0);s=command(s,{kind:'close'});s=command(s,{kind:'close'});expect(s.pet!.progression.xp).toBe(xp);});
 it('practice lends a complete build without granting gear or XP',()=>{let s=state(1);s=command(s,{kind:'start',mode:'practice',encounter:0,branch:'striker'});expect(s.petArena!.fight!.fighters[0].level).toBe(10);while(s.petArena!.fight!.phase==='active'){const f=s.petArena!.fight!;s=command(s,{kind:'move',move:policy(f),fightId:f.id,round:f.round});}expect(s.pet!.progression.xp).toBe(0);expect(s.petArena!.owned).toEqual(['snack']);});
 it('all four tools have real effects, consume a turn and cannot repeat',()=>{for(const id of ['snack','bubble','berry','leaf']){const b=preset('guardian');b.tool=id;const p=fighter(state().pet!,b),e=fighter(state().pet!,emptyBuild());p.hp=50;p.energy=5;p.weaken=true;const fs:[typeof p,typeof e]=[p,e];perform(fs,0,'item',[]);expect(p.used).toContain('tool');if(id==='snack')expect(p.hp).toBeGreaterThan(50);if(id==='bubble')expect(p.shield).toBeGreaterThan(20);if(id==='berry')expect(p.energy).toBe(30);if(id==='leaf')expect(p.weaken).toBe(false);expect(()=>perform(fs,0,'item',[])).toThrow();}});
 it('counter/retaliation cannot loop and shields are capped',()=>{const p=fighter(state().pet!,preset('guardian')),e=fighter(state().pet!,preset('guardian'));for(let i=0;i<20;i++)perform([p,e],0,'guard',[]);expect(p.shield).toBeLessThanOrEqual(p.maxHP*.4);perform([p,e],1,'strike',[]);expect(p.counter).toBe(true);const hp=e.hp;perform([p,e],0,'strike',[]);expect(e.hp).toBeLessThan(hp);expect(p.counter).toBe(false);});
 it('all builds and species produce bounded terminating fights',()=>{for(const species of ['koala_sprite','slime_baby','mech_bot','subtrak','moss_turtle'])for(const branch of BRANCHES)for(const encounter of ENCOUNTERS){const s=state(encounter.level);s.pet!.speciesId=species;let f=createFight(s.pet!,preset(branch),encounter,`${species}:${branch}:${encounter.id}`,'campaign');for(let n=0;f.phase==='active'&&n<22;n++)f=turn(f,policy(f));expect(f.phase).not.toBe('active');expect(f.round).toBeLessThanOrEqual(20);expect(f.fighters.every(p=>p.hp>=0&&p.hp<=p.maxHP&&p.energy>=0&&p.energy<=60)).toBe(true);}});
 it('guard and focus only cannot create an endless battle',()=>{for(const move of ['guard','focus'] as const){let f=createFight(state().pet!,preset('guardian'),ENCOUNTERS[0],'stall','campaign');while(f.phase==='active')f=turn(f,move);expect(f.round).toBeLessThanOrEqual(20);expect(f.phase).not.toBe('won');}});
 it('all gear definitions are unique and owned gear survives JSON reload',()=>{expect(new Set(GEAR.map(g=>g.id)).size).toBe(16);let s=state();for(const g of GEAR.filter(g=>g.price))s=command(s,{kind:'buy',id:g.id});expect(validArena(JSON.parse(JSON.stringify(s.petArena)))).toBe(true);expect(arenaOf(s).owned).toHaveLength(16);});
});
function room(mode:'duel'|'raid'='duel'):ArenaRoom{const pet=state().pet!;return {id:'r',mode,host:mode==='raid'?'teacher':'a',members:['a','b'].map((id,i)=>({id,alias:id,fighter:fighter({...pet,id},preset(i?'striker':'guardian'),{fair:true}),ready:true})),boss:mode==='raid'?fighter({...pet,id:'boss'},preset('tactician'),{fair:true}):null,phase:'active',round:1,paused:false,choices:{},events:[],winner:null,revision:0,message:''};}
describe('Fair classroom combat',()=>{
 it('hides a locked move from the opponent and resolves once both commit',()=>{let r=room();r=roomAction(r,{kind:'move',move:'guard',round:1},'a',false);expect(roomView(r,'b').choices.a).toBe('locked');r=roomAction(r,{kind:'move',move:'strike',round:1},'b',false);expect(r.round).toBe(2);expect(r.choices).toEqual({});expect(()=>roomAction(r,{kind:'move',move:'strike',round:1},'a',false)).toThrow();});
 it('enforces teacher controls and participants',()=>{const r=room('raid');expect(()=>roomAction(r,{kind:'pause'},'a',false)).toThrow();expect(()=>roomAction(r,{kind:'move',move:'strike',round:1},'intruder',false)).toThrow();const paused=roomAction(r,{kind:'pause'},'teacher',true);expect(()=>roomAction(paused,{kind:'move',move:'strike',round:1},'a',false)).toThrow();});
 it('teacher-team damage does not grow with duplicated class size',()=>{const a=room('raid');a.members=[a.members[0]];a.choices={a:'strike',teacher:'focus'};const b=structuredClone(a);b.members=Array.from({length:20},(_,i)=>({...structuredClone(a.members[0]),id:String(i)}));b.choices=Object.fromEntries(b.members.map(m=>[m.id,'strike']));b.choices.teacher='focus';expect(resolveRoom(a).boss!.hp).toBe(resolveRoom(b).boss!.hp);});
});
it('expedition rewards and route choices survive reload and complete after five fights',()=>{let s=command(state(20),{kind:'init'});s.petArena!.cleared=[0,1,2,3,4];for(const id of ['mirror','thorn','bubble'])s=command(s,{kind:'buy',id});s=command(s,{kind:'preset',branch:'guardian'});s=command(s,{kind:'start',mode:'expedition',encounter:0});for(let stage=0;stage<5;stage++){while(s.petArena!.fight!.phase==='active'){const f=s.petArena!.fight!;s=command(s,{kind:'move',move:policy(f),fightId:f.id,round:f.round});}expect(s.petArena!.fight!.phase,JSON.stringify({stage,fighters:s.petArena!.fight!.fighters,events:s.petArena!.fight!.history.slice(-8)})).toBe('won');s=JSON.parse(JSON.stringify(s));expect(validArena(s.petArena)).toBe(true);if(stage<4){expect(()=>command(s,{kind:'close'})).toThrow();s=command(s,{kind:'perk',perk:'edge',route:0});}}expect(s.petArena!.expeditions).toBe(1);expect(s.petArena!.expedition).toBeNull();s=command(s,{kind:'close'});expect(s.petArena!.expeditions).toBe(1);});
it('a different companion cannot finish another pet’s battle for XP',()=>{let s=command(state(),{kind:'start',mode:'campaign',encounter:0});s={...s,pet:{...s.pet!,id:'other-pet'}};expect(()=>command(s,{kind:'move',move:'strike',fightId:s.petArena!.fight!.id,round:1})).toThrow(/Return to the pet/);expect(command(s,{kind:'retreat'}).petArena!.fight).toBeNull();});
it('new battles pay existing prizes and First Adventure once even through the engine observers',async()=>{const {engineReducer}=await import('../../engine/state/engineReducer');let s=state();s.firstAdventure={phase:'battle',solved:3};s=engineReducer(s,{type:'ARENA_COMMAND',command:{kind:'start',mode:'campaign',encounter:0}});while(s.petArena!.fight!.phase==='active'){const f=s.petArena!.fight!;s=engineReducer(s,{type:'ARENA_COMMAND',command:{kind:'move',move:policy(f),fightId:f.id,round:f.round}});}expect(s.firstAdventure!.phase).toBe('complete');expect(s.prizes!.wins).toBe(1);expect(s.prizes!.arenaWinClaims).toHaveLength(1);const tokens=s.player.currencies.tokens;s=engineReducer(s,{type:'ARENA_COMMAND',command:{kind:'close'}});expect(s.player.currencies.tokens).toBe(tokens);});
