import{it,expect}from'vitest';
import{hatchEgg}from'../../services/game/evolutionEngine';
import{createFight,preset,turn}from'./combat';
import{BRANCHES,ENCOUNTERS,type Move}from'./catalog';
it('reports equal-level build performance against the campaign',()=>{
 const report:Record<string,{wins:number;turns:number;fights:number}>={};
 for(const branch of [...BRANCHES,'strike-only'] as const){let wins=0,turns=0,fights=0;for(const species of ['koala_sprite','slime_baby','mech_bot','subtrak','moss_turtle'])for(const e of ENCOUNTERS){const p=hatchEgg({id:'e',type:'koala',state:'ready',progress:100,createdAt:new Date().toISOString()})!;p.speciesId=species;p.progression.level=e.level;let f=createFight(p,preset(branch==='strike-only'?'striker':branch),e,`${species}:${e.id}`,'campaign');while(f.phase==='active'){const a=f.fighters[0];let move:Move='strike';if(branch!=='strike-only'){if(a.hp<a.maxHP*.45&&!a.used.includes('tool'))move='item';else if(branch==='guardian'&&f.intent==='signature')move='guard';else if(a.counter)move='strike';else if(branch==='tactician'&&!a.focused)move='focus';else if(a.energy>=20&&(branch!=='striker'||a.lastAttack==='strike'))move='signature';else if(a.energy<15)move='focus';}f=turn(f,move);}wins+=Number(f.phase==='won');turns+=f.round;fights++;}report[branch]={wins,turns,fights};}
 console.log('Arena balance sample',JSON.stringify(report));expect(report.guardian.wins).toBeGreaterThan(0);expect(report.striker.wins).toBeGreaterThan(0);expect(report.tactician.wins).toBeGreaterThan(0);
});
it('compares fair classroom builds with both starting seats',async()=>{const {roomAction}=await import('./multiplayer');const {fighter,signatureCost}=await import('./combat');const matrix:Record<string,{wins:number;losses:number;draws:number}>={};for(const left of BRANCHES)for(const right of BRANCHES){const entry=matrix[`${left}/${right}`]={wins:0,losses:0,draws:0};for(let seat=0;seat<2;seat++)for(const species of ['koala_sprite','slime_baby','mech_bot','subtrak']){const pet=hatchEgg({id:'e',type:'koala',state:'ready',progress:100,createdAt:new Date().toISOString()})!;pet.speciesId=species;let r:import('./multiplayer').ArenaRoom={id:'m',mode:'duel',host:'a',members:[{id:'a',alias:'a',fighter:fighter({...pet,id:'a'},preset(left),{fair:true}),ready:true},{id:'b',alias:'b',fighter:fighter({...pet,id:'b'},preset(right),{fair:true}),ready:true}],boss:null,phase:'active',round:1,paused:false,choices:{},events:[],winner:null,revision:0,message:''};if(seat)r.members.reverse();while(r.phase==='active'){const moves=r.members.map(m=>{const p=m.fighter,enemy=r.members.find(e=>e.id!==m.id)!.fighter;let move:Move='strike';if(p.hp<p.maxHP*.4&&!p.used.includes('tool'))move='item';else if(p.counter)move='strike';else if(p.build.talents.guardian===4&&enemy.energy>=20&&(enemy.focused||enemy.lastAttack==='strike'))move='guard';else if(p.build.talents.tactician===4&&!p.focused)move='focus';else if(p.energy>=signatureCost(p)&&(p.build.talents.striker===0||p.lastAttack==='strike'))move='signature';else if(p.energy<15)move='focus';return {id:m.id,move};});for(const m of moves)r=roomAction(r,{kind:'move',move:m.move,round:r.round},m.id,false);}if(r.winner==='a')entry.wins++;else if(r.winner==='b')entry.losses++;else entry.draws++;}}console.log('Fair duel sample',JSON.stringify(matrix));for(const b of BRANCHES)expect(matrix[`${b}/${b}`].wins).toBe(matrix[`${b}/${b}`].losses);});
