// Generated by scripts/pack-battle-anims.py: frame counts of each 128px battle strip.
export default {
 "ember_fox": {
  "defend": 13,
  "idle": 8
 },
 "koala_sprite": {
  "attack": 13,
  "defend": 13,
  "focus": 13,
  "heal": 13,
  "hurt": 9,
  "ko": 9,
  "special": 17,
  "victory": 13,
  "idle": 4
 },
 "koala_sprite__adult": {
  "attack": 13,
  "defend": 13,
  "focus": 13,
  "heal": 13,
  "hurt": 9,
  "ko": 9,
  "victory": 13,
  "idle": 8
 },
 "koala_sprite__juvenile": {
  "ko": 9,
  "idle": 8
 },
 "slime_baby": {
  "attack": 13,
  "defend": 13,
  "focus": 13,
  "heal": 13,
  "hurt": 9,
  "ko": 9,
  "special": 17,
  "victory": 13,
  "idle": 8
 },
 "_fx": {
  "charge": 13,
  "heal": 13,
  "heavy": 13,
  "hit": 9,
  "shield": 9,
  "weaken": 9
 }
} as Record<string, Record<string, number>>;
